/* ============================================================
   📁 dataries/country/african-utara.js
   📌 DATA NEGARA AFRIKA UTARA
   🔥 7 NEGARA — Mesir, Maroko, Aljazair, Tunisia, Libya, Sudan, Mauritania
   🔥 DATA SUPER LENGKAP — 100+ FIELD PER NEGARA!
   ============================================================ */

(function() {
    'use strict';
    
    if (window.__CountryAfricanUtaraLoaded) return;
    window.__CountryAfricanUtaraLoaded = true;
    
    window.__DATA_REGISTER = window.__DATA_REGISTER || [];
    
    const data = [
        // ==========================================================
        // 🇪🇬 MESIR
        // ==========================================================
        {
            text: 'Mesir - Negara di Afrika Utara dengan peradaban kuno dan Suez. Ibu kota: Kairo. Populasi: 110 juta jiwa. Mata uang: Pound (EGP). Bahasa: Arab. Sistem pemerintahan: Republik Semi-Presidensial. Anggota PBB, AU, dan Liga Arab. Rumah bagi piramida Giza, Sphinx, dan Sungai Nil. Pusat peradaban kuno dan pariwisata dunia.',
            metadata: {
                category: 'country',
                region: 'african-utara',
                name: 'Mesir',
                officialName: 'Republik Arab Mesir',
                shortName: 'EGY',
                capital: 'Kairo',
                capitalCoordinates: { lat: 30.0444, lng: 31.2357 },
                largestCity: 'Kairo',
                demonym: 'Mesir',
                subregion: 'North Africa',
                area: 1001450,
                areaRank: 29,
                coastline: 2450,
                highestPoint: 'Gunung Catherine',
                highestElevation: 2629,
                lowestPoint: 'Danau Qattara',
                lowestElevation: -133,
                landBorders: ['Libya', 'Sudan', 'Israel'],
                coordinates: { lat: 26.0, lng: 30.0 },
                timezone: ['Waktu Mesir'],
                utcOffset: ['+2'],
                population: 110000000,
                populationRank: 14,
                populationDensity: 109,
                populationGrowth: 1.5,
                medianAge: 25.0,
                lifeExpectancy: 74.0,
                fertilityRate: 2.5,
                urbanization: 43,
                ethnicGroups: [
                    { name: 'Arab', percentage: 90.0 },
                    { name: 'Berber', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 5.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 90.0 },
                    { name: 'Kristen', percentage: 10.0 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 20 },
                    { name: 'Prancis', percentage: 10 }
                ],
                literacyRate: 75,
                governmentType: 'Republik Semi-Presidensial',
                independenceDay: '1922-02-28',
                nationalHoliday: '23 Juli',
                legalSystem: 'Civil Law',
                constitution: '2014',
                administrativeDivisions: 27,
                memberships: ['PBB', 'AU', 'Liga Arab', 'WTO'],
                giniCoefficient: 31.5,
                hdi: 0.707,
                hdiRank: 116,
                corruptionIndex: 35,
                currency: 'Pound',
                currencyCode: 'EGP',
                gdp: 500000000000,
                gdpPerCapita: 4540,
                gdpPpp: 1600000000000,
                gdpGrowth: 4.5,
                inflation: 8.0,
                unemployment: 7.0,
                povertyRate: 30.0,
                mainIndustries: ['Pariwisata', 'Pertanian', 'Tekstil', 'Manufaktur', 'Energi'],
                exports: [
                    { item: 'Minyak', value: 15000000000 },
                    { item: 'Gas', value: 10000000000 },
                    { item: 'Tekstil', value: 8000000000 },
                    { item: 'Pariwisata', value: 5000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 20000000000 },
                    { item: 'Elektronik', value: 15000000000 },
                    { item: 'Minyak', value: 10000000000 },
                    { item: 'Makanan', value: 8000000000 }
                ],
                tradeBalance: -10000000000,
                naturalResources: ['Minyak', 'Gas', 'Fosfat', 'Besi', 'Emas'],
                economicRanking: 35,
                internetPenetration: 60,
                mobilePenetration: 80,
                electricityAccess: 100,
                roadLength: 100000,
                railwayLength: 5000,
                airports: 100,
                seaports: 20,
                healthcareAccess: 70,
                educationIndex: 0.58,
                nationalMotto: 'Kebebasan, Kemakmuran, Persatuan',
                nationalAnthem: 'Bilady, Bilady, Bilady',
                nationalAnimal: 'Elang',
                nationalFlower: 'Bunga Lotus',
                nationalCuisine: ['Koshari', 'Ful Medames', 'Shawarma', 'Baklava', 'Molokhiya'],
                culturalHeritage: ['Pyramids of Giza', 'Sphinx', 'Luxor', 'Abu Simbel'],
                publicHolidays: ['Hari Kemerdekaan', 'Idul Fitri', 'Idul Adha', 'Christmas'],
                socialRanking: 50,
                climate: 'Gurun',
                averageTemperature: 25,
                averageRainfall: 50,
                forestArea: 0.1,
                protectedAreas: 5,
                biodiversityRank: 30,
                carbonEmissions: 2.5,
                environmentalIndex: 40,
                riskScore: 45,
                politicalStability: 50,
                crimeIndex: 35,
                militarySpending: 2.5,
                peaceIndex: 50,
                terrorismIndex: 30,
                refugeePopulation: 200000,
                opportunityScore: 55,
                easeOfDoingBusiness: 50,
                innovationIndex: 45,
                startupEcosystem: 50,
                investmentScore: 50,
                talentPool: 70,
                marketSize: 85,
                infrastructureQuality: 50,
                internetSpeed: 25,
                digitalAdoption: 55,
                techEcosystem: 50,
                aiReadiness: 40,
                startups: 200,
                phoneCode: '+20',
                tld: '.eg',
                isoCode: 'EGY',
                isoCode2: 'EG',
                drivingSide: 'right',
                tags: ['negara', 'african-utara', 'piramida', 'suez', 'sejarah']
            }
        },
        // ==========================================================
        // 🇲🇦 MAROKO
        // ==========================================================
        {
            text: 'Maroko - Negara di Afrika Utara dengan ekonomi dan pariwisata. Ibu kota: Rabat. Populasi: 37 juta jiwa. Mata uang: Dirham (MAD). Bahasa: Arab, Berber. Sistem pemerintahan: Monarki Konstitusional. Anggota PBB, AU, dan Liga Arab. Negara dengan pasar tradisional, Arsitektur Islam, dan pantai Atlantik yang indah.',
            metadata: {
                category: 'country',
                region: 'african-utara',
                name: 'Maroko',
                officialName: 'Kerajaan Maroko',
                shortName: 'MAR',
                capital: 'Rabat',
                capitalCoordinates: { lat: 34.0209, lng: -6.8416 },
                largestCity: 'Casablanca',
                demonym: 'Maroko',
                subregion: 'North Africa',
                area: 446550,
                areaRank: 57,
                coastline: 1835,
                highestPoint: 'Toubkal',
                highestElevation: 4167,
                lowestPoint: 'Laut Atlantik',
                lowestElevation: 0,
                landBorders: ['Aljazair', 'Mauritania'],
                coordinates: { lat: 31.0, lng: -7.0 },
                timezone: ['Waktu Maroko'],
                utcOffset: ['+1'],
                population: 37000000,
                populationRank: 39,
                populationDensity: 82,
                populationGrowth: 1.0,
                medianAge: 29.0,
                lifeExpectancy: 76.0,
                fertilityRate: 2.2,
                urbanization: 64,
                ethnicGroups: [
                    { name: 'Arab', percentage: 67.0 },
                    { name: 'Berber', percentage: 31.0 },
                    { name: 'Lainnya', percentage: 2.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 99.0 },
                    { name: 'Kristen', percentage: 0.5 },
                    { name: 'Lainnya', percentage: 0.5 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Berber', percentage: 30, official: true },
                    { name: 'Prancis', percentage: 50 },
                    { name: 'Inggris', percentage: 10 }
                ],
                literacyRate: 75,
                governmentType: 'Monarki Konstitusional',
                independenceDay: '1956-03-02',
                nationalHoliday: '30 Juli',
                legalSystem: 'Civil Law',
                constitution: '2011',
                administrativeDivisions: 12,
                memberships: ['PBB', 'AU', 'Liga Arab', 'WTO'],
                giniCoefficient: 39.5,
                hdi: 0.686,
                hdiRank: 121,
                corruptionIndex: 40,
                currency: 'Dirham',
                currencyCode: 'MAD',
                gdp: 140000000000,
                gdpPerCapita: 3780,
                gdpPpp: 350000000000,
                gdpGrowth: 3.5,
                inflation: 3.0,
                unemployment: 9.0,
                povertyRate: 15.0,
                mainIndustries: ['Pariwisata', 'Pertanian', 'Manufaktur', 'Energi', 'Tekstil'],
                exports: [
                    { item: 'Fosfat', value: 8000000000 },
                    { item: 'Pariwisata', value: 6000000000 },
                    { item: 'Tekstil', value: 5000000000 },
                    { item: 'Pertanian', value: 4000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 15000000000 },
                    { item: 'Elektronik', value: 10000000000 },
                    { item: 'Minyak', value: 8000000000 },
                    { item: 'Makanan', value: 6000000000 }
                ],
                tradeBalance: -10000000000,
                naturalResources: ['Fosfat', 'Emas', 'Kayu', 'Perikanan'],
                economicRanking: 55,
                internetPenetration: 75,
                mobilePenetration: 90,
                electricityAccess: 100,
                roadLength: 60000,
                railwayLength: 2000,
                airports: 50,
                seaports: 20,
                healthcareAccess: 75,
                educationIndex: 0.62,
                nationalMotto: 'Allah, Tanah Air, Raja',
                nationalAnthem: 'Hymne Chérifien',
                nationalAnimal: 'Singa',
                nationalFlower: 'Mawar',
                nationalCuisine: ['Couscous', 'Tagine', 'Harira', 'Pastilla', 'Mint Tea'],
                culturalHeritage: ['Marrakech', 'Fes', 'Casablanca', 'Chefchaouen'],
                publicHolidays: ['Idul Fitri', 'Idul Adha', 'Hari Kemerdekaan', 'Tahun Baru'],
                socialRanking: 60,
                climate: 'Beragam',
                averageTemperature: 20,
                averageRainfall: 300,
                forestArea: 12,
                protectedAreas: 10,
                biodiversityRank: 20,
                carbonEmissions: 2.0,
                environmentalIndex: 50,
                riskScore: 35,
                politicalStability: 65,
                crimeIndex: 30,
                militarySpending: 1.5,
                peaceIndex: 40,
                terrorismIndex: 20,
                refugeePopulation: 5000,
                opportunityScore: 60,
                easeOfDoingBusiness: 55,
                innovationIndex: 40,
                startupEcosystem: 45,
                investmentScore: 55,
                talentPool: 65,
                marketSize: 75,
                infrastructureQuality: 60,
                internetSpeed: 30,
                digitalAdoption: 60,
                techEcosystem: 50,
                aiReadiness: 40,
                startups: 150,
                phoneCode: '+212',
                tld: '.ma',
                isoCode: 'MAR',
                isoCode2: 'MA',
                drivingSide: 'right',
                tags: ['negara', 'african-utara', 'energi', 'pariwisata', 'ligar']
            }
        },
        // ==========================================================
        // 🇩🇿 ALJAZAIR
        // ==========================================================
        {
            text: 'Aljazair - Negara terbesar di Afrika dengan cadangan gas alam. Ibu kota: Aljir. Populasi: 44 juta jiwa. Mata uang: Dinar (DZD). Bahasa: Arab, Berber. Sistem pemerintahan: Republik Semi-Presidensial. Anggota PBB, AU, dan OPEC. Negara dengan gurun Sahara dan cadangan minyak dan gas terbesar di Afrika.',
            metadata: {
                category: 'country',
                region: 'african-utara',
                name: 'Aljazair',
                officialName: 'Republik Demokratik Rakyat Aljazair',
                shortName: 'DZA',
                capital: 'Aljir',
                capitalCoordinates: { lat: 36.7538, lng: 3.0588 },
                largestCity: 'Aljir',
                demonym: 'Aljazair',
                subregion: 'North Africa',
                area: 2381741,
                areaRank: 10,
                coastline: 998,
                highestPoint: 'Mount Tahat',
                highestElevation: 3003,
                lowestPoint: 'Laut Mediterania',
                lowestElevation: 0,
                landBorders: ['Maroko', 'Mauritania', 'Mali', 'Niger', 'Libya', 'Tunisia'],
                coordinates: { lat: 28.0, lng: 3.0 },
                timezone: ['Waktu Aljazair'],
                utcOffset: ['+1'],
                population: 44000000,
                populationRank: 34,
                populationDensity: 18,
                populationGrowth: 1.5,
                medianAge: 28.0,
                lifeExpectancy: 76.0,
                fertilityRate: 2.5,
                urbanization: 73,
                ethnicGroups: [
                    { name: 'Arab', percentage: 80.0 },
                    { name: 'Berber', percentage: 18.0 },
                    { name: 'Lainnya', percentage: 2.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 99.0 },
                    { name: 'Kristen', percentage: 0.5 },
                    { name: 'Lainnya', percentage: 0.5 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Berber', percentage: 20, official: true },
                    { name: 'Prancis', percentage: 40 },
                    { name: 'Inggris', percentage: 10 }
                ],
                literacyRate: 80,
                governmentType: 'Republik Semi-Presidensial',
                independenceDay: '1962-07-05',
                nationalHoliday: '5 Juli',
                legalSystem: 'Civil Law',
                constitution: '2020',
                administrativeDivisions: 48,
                memberships: ['PBB', 'AU', 'OPEC', 'Liga Arab', 'WTO'],
                giniCoefficient: 27.6,
                hdi: 0.748,
                hdiRank: 91,
                corruptionIndex: 36,
                currency: 'Dinar',
                currencyCode: 'DZD',
                gdp: 200000000000,
                gdpPerCapita: 4540,
                gdpPpp: 600000000000,
                gdpGrowth: 3.0,
                inflation: 5.0,
                unemployment: 12.0,
                povertyRate: 10.0,
                mainIndustries: ['Minyak', 'Gas', 'Petrokimia', 'Manufaktur', 'Pertanian'],
                exports: [
                    { item: 'Minyak', value: 30000000000 },
                    { item: 'Gas', value: 20000000000 },
                    { item: 'Petrokimia', value: 10000000000 },
                    { item: 'Fosfat', value: 5000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 15000000000 },
                    { item: 'Elektronik', value: 10000000000 },
                    { item: 'Makanan', value: 8000000000 },
                    { item: 'Bahan kimia', value: 6000000000 }
                ],
                tradeBalance: 20000000000,
                naturalResources: ['Minyak', 'Gas', 'Fosfat', 'Emas', 'Besi', 'Seng'],
                economicRanking: 50,
                internetPenetration: 60,
                mobilePenetration: 80,
                electricityAccess: 100,
                roadLength: 100000,
                railwayLength: 4000,
                airports: 100,
                seaports: 20,
                healthcareAccess: 75,
                educationIndex: 0.62,
                nationalMotto: 'Dari rakyat, untuk rakyat',
                nationalAnthem: 'Kassaman',
                nationalAnimal: 'Fenec Fox',
                nationalFlower: 'Iris',
                nationalCuisine: ['Couscous', 'Tajine', 'Merguez', 'Harira', 'Makroud'],
                culturalHeritage: ['Algiers', 'Timgad', 'Djemila', 'Tipasa'],
                publicHolidays: ['Hari Kemerdekaan', 'Idul Fitri', 'Idul Adha', 'Tahun Baru'],
                socialRanking: 55,
                climate: 'Beragam',
                averageTemperature: 20,
                averageRainfall: 300,
                forestArea: 1,
                protectedAreas: 8,
                biodiversityRank: 25,
                carbonEmissions: 4.0,
                environmentalIndex: 45,
                riskScore: 40,
                politicalStability: 55,
                crimeIndex: 30,
                militarySpending: 5.0,
                peaceIndex: 50,
                terrorismIndex: 35,
                refugeePopulation: 5000,
                opportunityScore: 50,
                easeOfDoingBusiness: 45,
                innovationIndex: 35,
                startupEcosystem: 35,
                investmentScore: 45,
                talentPool: 65,
                marketSize: 75,
                infrastructureQuality: 50,
                internetSpeed: 20,
                digitalAdoption: 45,
                techEcosystem: 40,
                aiReadiness: 30,
                startups: 80,
                phoneCode: '+213',
                tld: '.dz',
                isoCode: 'DZA',
                isoCode2: 'DZ',
                drivingSide: 'right',
                tags: ['negara', 'african-utara', 'gas', 'minyak', 'opec']
            }
        },
        // ==========================================================
        // 🇹🇳 TUNISIA
        // ==========================================================
        {
            text: 'Tunisia - Negara di Afrika Utara dengan sejarah dan pantai Mediterania. Ibu kota: Tunis. Populasi: 12 juta jiwa. Mata uang: Dinar (TND). Bahasa: Arab. Sistem pemerintahan: Republik Parlementer. Anggota PBB, AU, dan Liga Arab. Rumah bagi Kartago kuno dan pantai-pantai indah Mediterania.',
            metadata: {
                category: 'country',
                region: 'african-utara',
                name: 'Tunisia',
                officialName: 'Republik Tunisia',
                shortName: 'TUN',
                capital: 'Tunis',
                capitalCoordinates: { lat: 36.8065, lng: 10.1815 },
                largestCity: 'Tunis',
                demonym: 'Tunisia',
                subregion: 'North Africa',
                area: 163610,
                areaRank: 91,
                coastline: 1148,
                highestPoint: 'Jebel ech Chambi',
                highestElevation: 1544,
                lowestPoint: 'Laut Mediterania',
                lowestElevation: 0,
                landBorders: ['Aljazair', 'Libya'],
                coordinates: { lat: 34.0, lng: 9.0 },
                timezone: ['Waktu Tunisia'],
                utcOffset: ['+1'],
                population: 12000000,
                populationRank: 77,
                populationDensity: 73,
                populationGrowth: 0.7,
                medianAge: 32.0,
                lifeExpectancy: 77.0,
                fertilityRate: 2.0,
                urbanization: 69,
                ethnicGroups: [
                    { name: 'Arab', percentage: 98.0 },
                    { name: 'Berber', percentage: 1.0 },
                    { name: 'Lainnya', percentage: 1.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 99.0 },
                    { name: 'Kristen', percentage: 0.5 },
                    { name: 'Lainnya', percentage: 0.5 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Prancis', percentage: 40 },
                    { name: 'Inggris', percentage: 10 }
                ],
                literacyRate: 82,
                governmentType: 'Republik Parlementer',
                independenceDay: '1956-03-20',
                nationalHoliday: '20 Maret',
                legalSystem: 'Civil Law',
                constitution: '2014',
                administrativeDivisions: 24,
                memberships: ['PBB', 'AU', 'Liga Arab', 'WTO'],
                giniCoefficient: 35.8,
                hdi: 0.740,
                hdiRank: 94,
                corruptionIndex: 44,
                currency: 'Dinar',
                currencyCode: 'TND',
                gdp: 50000000000,
                gdpPerCapita: 4160,
                gdpPpp: 140000000000,
                gdpGrowth: 2.5,
                inflation: 5.0,
                unemployment: 15.0,
                povertyRate: 15.0,
                mainIndustries: ['Pariwisata', 'Tekstil', 'Pertanian', 'Manufaktur', 'Fosfat'],
                exports: [
                    { item: 'Tekstil', value: 8000000000 },
                    { item: 'Pariwisata', value: 5000000000 },
                    { item: 'Fosfat', value: 3000000000 },
                    { item: 'Pertanian', value: 2000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 8000000000 },
                    { item: 'Elektronik', value: 6000000000 },
                    { item: 'Minyak', value: 4000000000 },
                    { item: 'Makanan', value: 3000000000 }
                ],
                tradeBalance: -4000000000,
                naturalResources: ['Fosfat', 'Minyak', 'Gas', 'Emas', 'Perikanan'],
                economicRanking: 70,
                internetPenetration: 70,
                mobilePenetration: 85,
                electricityAccess: 100,
                roadLength: 20000,
                railwayLength: 2000,
                airports: 30,
                seaports: 10,
                healthcareAccess: 80,
                educationIndex: 0.68,
                nationalMotto: 'Kebebasan, Keadilan, Kemakmuran',
                nationalAnthem: 'Humat al-Hima',
                nationalAnimal: 'Elang',
                nationalFlower: 'Jasmine',
                nationalCuisine: ['Couscous', 'Brik', 'Harissa', 'Merguez', 'Makroud'],
                culturalHeritage: ['Carthage', 'Tunis', 'Sidi Bou Said', 'Dougga'],
                publicHolidays: ['Hari Kemerdekaan', 'Idul Fitri', 'Idul Adha', 'Tahun Baru'],
                socialRanking: 60,
                climate: 'Mediterania',
                averageTemperature: 20,
                averageRainfall: 400,
                forestArea: 5,
                protectedAreas: 8,
                biodiversityRank: 30,
                carbonEmissions: 2.0,
                environmentalIndex: 50,
                riskScore: 40,
                politicalStability: 60,
                crimeIndex: 25,
                militarySpending: 1.5,
                peaceIndex: 45,
                terrorismIndex: 25,
                refugeePopulation: 1000,
                opportunityScore: 55,
                easeOfDoingBusiness: 55,
                innovationIndex: 40,
                startupEcosystem: 45,
                investmentScore: 50,
                talentPool: 60,
                marketSize: 65,
                infrastructureQuality: 55,
                internetSpeed: 25,
                digitalAdoption: 55,
                techEcosystem: 45,
                aiReadiness: 35,
                startups: 80,
                phoneCode: '+216',
                tld: '.tn',
                isoCode: 'TUN',
                isoCode2: 'TN',
                drivingSide: 'right',
                tags: ['negara', 'african-utara', 'mediterania', 'sejarah', 'pariwisata']
            }
        },
        // ==========================================================
        // 🇱🇾 LIBYA
        // ==========================================================
        {
            text: 'Libya - Negara di Afrika Utara dengan cadangan minyak besar. Ibu kota: Tripoli. Populasi: 7 juta jiwa. Mata uang: Dinar (LYD). Bahasa: Arab. Sistem pemerintahan: Republik. Anggota PBB, AU, dan OPEC. Negara dengan cadangan minyak terbesar di Afrika dan gurun Sahara yang luas.',
            metadata: {
                category: 'country',
                region: 'african-utara',
                name: 'Libya',
                officialName: 'Negara Libya',
                shortName: 'LBY',
                capital: 'Tripoli',
                capitalCoordinates: { lat: 32.8872, lng: 13.1913 },
                largestCity: 'Tripoli',
                demonym: 'Libya',
                subregion: 'North Africa',
                area: 1759540,
                areaRank: 16,
                coastline: 1770,
                highestPoint: 'Bikku Bitti',
                highestElevation: 2267,
                lowestPoint: 'Laut Mediterania',
                lowestElevation: 0,
                landBorders: ['Mesir', 'Sudan', 'Chad', 'Niger', 'Aljazair', 'Tunisia'],
                coordinates: { lat: 25.0, lng: 17.0 },
                timezone: ['Waktu Libya'],
                utcOffset: ['+2'],
                population: 7000000,
                populationRank: 104,
                populationDensity: 4,
                populationGrowth: 1.0,
                medianAge: 29.0,
                lifeExpectancy: 72.0,
                fertilityRate: 2.2,
                urbanization: 80,
                ethnicGroups: [
                    { name: 'Arab', percentage: 85.0 },
                    { name: 'Berber', percentage: 10.0 },
                    { name: 'Lainnya', percentage: 5.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 97.0 },
                    { name: 'Kristen', percentage: 2.0 },
                    { name: 'Lainnya', percentage: 1.0 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 15 },
                    { name: 'Italia', percentage: 10 }
                ],
                literacyRate: 91,
                governmentType: 'Republik',
                independenceDay: '1951-12-24',
                nationalHoliday: '17 Februari',
                legalSystem: 'Civil Law',
                constitution: '2011',
                administrativeDivisions: 22,
                memberships: ['PBB', 'AU', 'OPEC', 'Liga Arab'],
                giniCoefficient: 40.0,
                hdi: 0.724,
                hdiRank: 100,
                corruptionIndex: 18,
                currency: 'Dinar',
                currencyCode: 'LYD',
                gdp: 50000000000,
                gdpPerCapita: 7140,
                gdpPpp: 150000000000,
                gdpGrowth: -5.0,
                inflation: 10.0,
                unemployment: 30.0,
                povertyRate: 20.0,
                mainIndustries: ['Minyak', 'Gas', 'Petrokimia', 'Manufaktur', 'Pertanian'],
                exports: [
                    { item: 'Minyak', value: 30000000000 },
                    { item: 'Gas', value: 10000000000 },
                    { item: 'Petrokimia', value: 5000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 10000000000 },
                    { item: 'Elektronik', value: 8000000000 },
                    { item: 'Makanan', value: 6000000000 },
                    { item: 'Bahan kimia', value: 4000000000 }
                ],
                tradeBalance: 20000000000,
                naturalResources: ['Minyak', 'Gas', 'Emas', 'Garam', 'Fosfat'],
                economicRanking: 80,
                internetPenetration: 50,
                mobilePenetration: 70,
                electricityAccess: 90,
                roadLength: 50000,
                railwayLength: 0,
                airports: 50,
                seaports: 10,
                healthcareAccess: 65,
                educationIndex: 0.62,
                nationalMotto: 'Kebebasan, Kemakmuran, Persatuan',
                nationalAnthem: 'Libya, Libya, Libya',
                nationalAnimal: 'Elang',
                nationalFlower: 'Bunga Gurun',
                nationalCuisine: ['Couscous', 'Bazeen', 'Shawarma', 'Harissa', 'Makroud'],
                culturalHeritage: ['Tripoli', 'Leptis Magna', 'Sabratha', 'Ghadames'],
                publicHolidays: ['Hari Kemerdekaan', 'Idul Fitri', 'Idul Adha', 'Tahun Baru'],
                socialRanking: 35,
                climate: 'Gurun',
                averageTemperature: 25,
                averageRainfall: 50,
                forestArea: 0.1,
                protectedAreas: 5,
                biodiversityRank: 35,
                carbonEmissions: 10.0,
                environmentalIndex: 30,
                riskScore: 80,
                politicalStability: 20,
                crimeIndex: 50,
                militarySpending: 3.0,
                peaceIndex: 75,
                terrorismIndex: 60,
                refugeePopulation: 5000,
                opportunityScore: 35,
                easeOfDoingBusiness: 30,
                innovationIndex: 25,
                startupEcosystem: 20,
                investmentScore: 30,
                talentPool: 55,
                marketSize: 60,
                infrastructureQuality: 30,
                internetSpeed: 15,
                digitalAdoption: 35,
                techEcosystem: 25,
                aiReadiness: 20,
                startups: 20,
                phoneCode: '+218',
                tld: '.ly',
                isoCode: 'LBY',
                isoCode2: 'LY',
                drivingSide: 'right',
                tags: ['negara', 'african-utara', 'minyak', 'opec', 'sejarah']
            }
        },
        // ==========================================================
        // 🇸🇩 SUDAN
        // ==========================================================
        {
            text: 'Sudan - Negara di Afrika Utara dengan sungai Nil dan pertanian. Ibu kota: Khartoum. Populasi: 46 juta jiwa. Mata uang: Pound (SDG). Bahasa: Arab, Inggris. Sistem pemerintahan: Republik. Anggota PBB dan AU. Negara dengan sungai Nil dan pertanian subur.',
            metadata: {
                category: 'country',
                region: 'african-utara',
                name: 'Sudan',
                officialName: 'Republik Sudan',
                shortName: 'SDN',
                capital: 'Khartoum',
                capitalCoordinates: { lat: 15.5007, lng: 32.5599 },
                largestCity: 'Khartoum',
                demonym: 'Sudan',
                subregion: 'North Africa',
                area: 1886068,
                areaRank: 15,
                coastline: 853,
                highestPoint: 'Deriba Caldera',
                highestElevation: 3042,
                lowestPoint: 'Laut Merah',
                lowestElevation: 0,
                landBorders: ['Mesir', 'Libya', 'Chad', 'Republik Afrika Tengah', 'Sudan Selatan', 'Eritrea', 'Etiopia'],
                coordinates: { lat: 15.0, lng: 30.0 },
                timezone: ['Waktu Sudan'],
                utcOffset: ['+2'],
                population: 46000000,
                populationRank: 33,
                populationDensity: 24,
                populationGrowth: 2.0,
                medianAge: 20.0,
                lifeExpectancy: 65.0,
                fertilityRate: 4.0,
                urbanization: 35,
                ethnicGroups: [
                    { name: 'Arab', percentage: 70.0 },
                    { name: 'Afrika', percentage: 30.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 90.0 },
                    { name: 'Kristen', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 5.0 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 20, official: true }
                ],
                literacyRate: 60,
                governmentType: 'Republik',
                independenceDay: '1956-01-01',
                nationalHoliday: '1 Januari',
                legalSystem: 'Civil Law',
                constitution: '2019',
                administrativeDivisions: 18,
                memberships: ['PBB', 'AU', 'Liga Arab'],
                giniCoefficient: 35.0,
                hdi: 0.510,
                hdiRank: 170,
                corruptionIndex: 16,
                currency: 'Pound',
                currencyCode: 'SDG',
                gdp: 30000000000,
                gdpPerCapita: 650,
                gdpPpp: 150000000000,
                gdpGrowth: 2.0,
                inflation: 50.0,
                unemployment: 20.0,
                povertyRate: 50.0,
                mainIndustries: ['Pertanian', 'Minyak', 'Tekstil', 'Tambang'],
                exports: [
                    { item: 'Minyak', value: 5000000000 },
                    { item: 'Emas', value: 3000000000 },
                    { item: 'Pertanian', value: 2000000000 },
                    { item: 'Tekstil', value: 1000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 5000000000 },
                    { item: 'Elektronik', value: 4000000000 },
                    { item: 'Makanan', value: 3000000000 },
                    { item: 'Minyak', value: 2000000000 }
                ],
                tradeBalance: -2000000000,
                naturalResources: ['Minyak', 'Emas', 'Besi', 'Perak', 'Kayu'],
                economicRanking: 90,
                internetPenetration: 30,
                mobilePenetration: 50,
                electricityAccess: 60,
                roadLength: 30000,
                railwayLength: 5000,
                airports: 30,
                seaports: 5,
                healthcareAccess: 40,
                educationIndex: 0.42,
                nationalMotto: 'Kemenangan adalah milik kita',
                nationalAnthem: 'Nahnu Jund Allah Jund Al-watan',
                nationalAnimal: 'Elang',
                nationalFlower: 'Bunga Gurun',
                nationalCuisine: ['Ful Medames', 'Kisra', 'Shawarma', 'Tamaya', 'Bamia'],
                culturalHeritage: ['Khartoum', 'Meroe', 'Kerma', 'Nubia'],
                publicHolidays: ['Hari Kemerdekaan', 'Idul Fitri', 'Idul Adha', 'Christmas'],
                socialRanking: 30,
                climate: 'Gurun',
                averageTemperature: 30,
                averageRainfall: 100,
                forestArea: 5,
                protectedAreas: 5,
                biodiversityRank: 30,
                carbonEmissions: 0.5,
                environmentalIndex: 35,
                riskScore: 75,
                politicalStability: 25,
                crimeIndex: 45,
                militarySpending: 2.0,
                peaceIndex: 70,
                terrorismIndex: 50,
                refugeePopulation: 100000,
                opportunityScore: 30,
                easeOfDoingBusiness: 30,
                innovationIndex: 20,
                startupEcosystem: 15,
                investmentScore: 25,
                talentPool: 45,
                marketSize: 65,
                infrastructureQuality: 25,
                internetSpeed: 8,
                digitalAdoption: 25,
                techEcosystem: 15,
                aiReadiness: 15,
                startups: 20,
                phoneCode: '+249',
                tld: '.sd',
                isoCode: 'SDN',
                isoCode2: 'SD',
                drivingSide: 'right',
                tags: ['negara', 'african-utara', 'nil', 'pertanian', 'sejarah']
            }
        },
        // ==========================================================
        // 🇲🇷 MAURITANIA (NEW!)
        // ==========================================================
        {
            text: 'Mauritania - Negara di Afrika Utara dengan gurun Sahara dan pesisir Atlantik. Ibu kota: Nouakchott. Populasi: 4.7 juta jiwa. Mata uang: Ouguiya (MRU). Bahasa: Arab. Sistem pemerintahan: Republik Presidensial. Negara dengan perbatasan terpanjang di Afrika. Potensi minyak dan gas. Budaya Arab-Berber yang kaya.',
            metadata: {
                category: 'country',
                region: 'african-utara',
                name: 'Mauritania',
                officialName: 'Republik Islam Mauritania',
                shortName: 'MRT',
                capital: 'Nouakchott',
                capitalCoordinates: { lat: 18.0735, lng: -15.9582 },
                largestCity: 'Nouakchott',
                demonym: 'Mauritania',
                subregion: 'North Africa',
                area: 1030700,
                areaRank: 28,
                coastline: 754,
                highestPoint: 'Kediet ej Jill',
                highestElevation: 915,
                lowestPoint: 'Laut Atlantik',
                lowestElevation: 0,
                landBorders: ['Aljazair', 'Mali', 'Senegal', 'Sahara Barat'],
                coordinates: { lat: 20.0, lng: -12.0 },
                timezone: ['Waktu Mauritania'],
                utcOffset: ['+0'],
                population: 4700000,
                populationRank: 123,
                populationDensity: 4,
                populationGrowth: 2.5,
                medianAge: 20.0,
                lifeExpectancy: 65.0,
                fertilityRate: 4.5,
                urbanization: 55,
                ethnicGroups: [
                    { name: 'Arab', percentage: 40.0 },
                    { name: 'Berber', percentage: 30.0 },
                    { name: 'Afrika', percentage: 30.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 100.0 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Prancis', percentage: 20 },
                    { name: 'Berber', percentage: 10 }
                ],
                literacyRate: 50,
                governmentType: 'Republik Presidensial',
                independenceDay: '1960-11-28',
                nationalHoliday: '28 November',
                legalSystem: 'Civil Law',
                constitution: '1991',
                administrativeDivisions: 15,
                memberships: ['PBB', 'AU', 'Liga Arab', 'WTO'],
                giniCoefficient: 32.0,
                hdi: 0.556,
                hdiRank: 157,
                corruptionIndex: 28,
                currency: 'Ouguiya',
                currencyCode: 'MRU',
                gdp: 10000000000,
                gdpPerCapita: 2120,
                gdpPpp: 25000000000,
                gdpGrowth: 3.5,
                inflation: 4.0,
                unemployment: 10.0,
                povertyRate: 30.0,
                mainIndustries: ['Tambang', 'Perikanan', 'Pertanian', 'Energi'],
                exports: [
                    { item: 'Besi', value: 3000000000 },
                    { item: 'Emas', value: 2000000000 },
                    { item: 'Perikanan', value: 1000000000 },
                    { item: 'Minyak', value: 500000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 2000000000 },
                    { item: 'Elektronik', value: 1500000000 },
                    { item: 'Makanan', value: 1000000000 },
                    { item: 'Minyak', value: 800000000 }
                ],
                tradeBalance: 1000000000,
                naturalResources: ['Besi', 'Emas', 'Minyak', 'Gas', 'Perikanan'],
                economicRanking: 100,
                internetPenetration: 35,
                mobilePenetration: 55,
                electricityAccess: 50,
                roadLength: 10000,
                railwayLength: 700,
                airports: 20,
                seaports: 5,
                healthcareAccess: 40,
                educationIndex: 0.42,
                nationalMotto: 'Kehormatan, Persaudaraan, Keadilan',
                nationalAnthem: 'Hymne National de Mauritanie',
                nationalAnimal: 'Unta',
                nationalFlower: 'Bunga Gurun',
                nationalCuisine: ['Couscous', 'Mafe', 'Yassa', 'Thiebou Djeun', 'Mechoui'],
                culturalHeritage: ['Nouakchott', 'Chinguetti', 'Ouadane', 'Tichitt'],
                publicHolidays: ['Hari Kemerdekaan', 'Idul Fitri', 'Idul Adha', 'Tahun Baru'],
                socialRanking: 35,
                climate: 'Gurun',
                averageTemperature: 30,
                averageRainfall: 100,
                forestArea: 0.5,
                protectedAreas: 5,
                biodiversityRank: 40,
                carbonEmissions: 0.5,
                environmentalIndex: 38,
                riskScore: 55,
                politicalStability: 50,
                crimeIndex: 35,
                militarySpending: 2.0,
                peaceIndex: 55,
                terrorismIndex: 30,
                refugeePopulation: 1000,
                opportunityScore: 40,
                easeOfDoingBusiness: 40,
                innovationIndex: 25,
                startupEcosystem: 20,
                investmentScore: 35,
                talentPool: 40,
                marketSize: 45,
                infrastructureQuality: 30,
                internetSpeed: 10,
                digitalAdoption: 25,
                techEcosystem: 20,
                aiReadiness: 15,
                startups: 10,
                phoneCode: '+222',
                tld: '.mr',
                isoCode: 'MRT',
                isoCode2: 'MR',
                drivingSide: 'right',
                tags: ['negara', 'african-utara', 'sahara', 'minyak', 'pesisir']
            }
        }
    ];

    // ============================================================
    // PROSES DATA KE REGISTER
    // ============================================================
    for (let i = 0; i < data.length; i++) {
        window.__DATA_REGISTER.push(data[i]);
    }

    // ============================================================
    // LOGGER
    // ============================================================
    if (window.InternalLogger) {
        window.InternalLogger.info('CountryAfricanUtara', '✅ Loaded ' + data.length + ' countries (SUPER LENGKAP - 7 NEGARA!)');
    }

})();