/* ============================================================
   📁 dataries/country/asian-timur.js
   📌 DATA NEGARA ASIA TIMUR
   🔥 8 NEGARA/WILAYAH — China, Jepang, Korea Selatan, Taiwan, Mongolia, Hong Kong, Makau, Tibet
   🔥 DATA SUPER LENGKAP — 100+ FIELD PER NEGARA!
   ============================================================ */

(function() {
    'use strict';
    
    if (window.__CountryAsianTimurLoaded) return;
    window.__CountryAsianTimurLoaded = true;
    
    window.__DATA_REGISTER = window.__DATA_REGISTER || [];
    
    const data = [
        // ==========================================================
        // 🇨🇳 CHINA
        // ==========================================================
        {
            text: 'China - Negara terbesar di Asia Timur dan terpadat di dunia dengan populasi 1.4 miliar jiwa. Ibu kota: Beijing. Mata uang: Yuan (CNY). Bahasa: Mandarin. Sistem pemerintahan: Republik Sosialis Satu Partai. Negara dengan ekonomi terbesar kedua di dunia dan kekuatan adidaya global. Anggota tetap Dewan Keamanan PBB. Pemimpin dalam AI, 5G, dan manufaktur. Rumah bagi Tembok Besar, Kota Terlarang, dan Terakota. Negara dengan sejarah peradaban 5000 tahun.',
            metadata: {
                category: 'country',
                region: 'asian-timur',
                name: 'China',
                officialName: 'Republik Rakyat China',
                shortName: 'PRC',
                capital: 'Beijing',
                capitalCoordinates: { lat: 39.9042, lng: 116.4074 },
                largestCity: 'Shanghai',
                demonym: 'China',
                subregion: 'Eastern Asia',
                area: 9596961,
                areaRank: 4,
                coastline: 14500,
                highestPoint: 'Gunung Everest',
                highestElevation: 8848,
                lowestPoint: 'Turpan Depression',
                lowestElevation: -154,
                landBorders: ['Afghanistan', 'Bhutan', 'India', 'Kazakhstan', 'Kyrgyzstan', 'Laos', 'Mongolia', 'Myanmar', 'Nepal', 'Pakistan', 'Rusia', 'Tajikistan', 'Vietnam'],
                coordinates: { lat: 35.0, lng: 105.0 },
                timezone: ['Waktu China'],
                utcOffset: ['+8'],
                population: 1400000000,
                populationRank: 1,
                populationDensity: 146,
                populationGrowth: 0.3,
                medianAge: 38.4,
                lifeExpectancy: 77.3,
                fertilityRate: 1.3,
                urbanization: 64,
                ethnicGroups: [
                    { name: 'Han', percentage: 91.6 },
                    { name: 'Zhuang', percentage: 1.3 },
                    { name: 'Hui', percentage: 0.9 },
                    { name: 'Manchu', percentage: 0.8 }
                ],
                religions: [
                    { name: 'Atheis', percentage: 50.0 },
                    { name: 'Buddha', percentage: 20.0 },
                    { name: 'Tao', percentage: 15.0 },
                    { name: 'Kristen', percentage: 5.0 }
                ],
                languages: [
                    { name: 'Mandarin', percentage: 100, official: true },
                    { name: 'Kanton', percentage: 10 },
                    { name: 'Shanghainese', percentage: 5 }
                ],
                literacyRate: 96,
                governmentType: 'Republik Sosialis Satu Partai',
                independenceDay: '1949-10-01',
                nationalHoliday: '1 Oktober',
                legalSystem: 'Civil Law',
                constitution: '1982',
                administrativeDivisions: 33,
                memberships: ['PBB', 'WTO', 'APEC', 'SCO', 'BRICS', 'G20'],
                giniCoefficient: 38.2,
                hdi: 0.768,
                hdiRank: 85,
                corruptionIndex: 42,
                currency: 'Yuan',
                currencyCode: 'CNY',
                gdp: 17700000000000,
                gdpPerCapita: 12640,
                gdpPpp: 30500000000000,
                gdpGrowth: 5.2,
                inflation: 2.0,
                unemployment: 5.0,
                povertyRate: 0.5,
                mainIndustries: ['Manufaktur', 'Teknologi', 'Elektronik', 'Otomotif', 'Pertanian'],
                exports: [
                    { item: 'Elektronik', value: 1000000000000 },
                    { item: 'Mesin', value: 800000000000 },
                    { item: 'Tekstil', value: 500000000000 },
                    { item: 'Otomotif', value: 300000000000 }
                ],
                imports: [
                    { item: 'Elektronik', value: 800000000000 },
                    { item: 'Mesin', value: 600000000000 },
                    { item: 'Minyak', value: 400000000000 },
                    { item: 'Bahan kimia', value: 300000000000 }
                ],
                tradeBalance: 600000000000,
                naturalResources: ['Batu bara', 'Besi', 'Gas', 'Minyak', 'Emas', 'Rare earth'],
                economicRanking: 2,
                internetPenetration: 80,
                mobilePenetration: 95,
                electricityAccess: 100,
                roadLength: 5000000,
                railwayLength: 150000,
                airports: 500,
                seaports: 200,
                healthcareAccess: 85,
                educationIndex: 0.75,
                nationalMotto: 'Kemakmuran, Kekuatan, Peradaban, Harmoni, Keindahan',
                nationalAnthem: 'March of the Volunteers',
                nationalAnimal: 'Panda Giant',
                nationalFlower: 'Plum Blossom',
                nationalCuisine: ['Peking Duck', 'Dim Sum', 'Hot Pot', 'Noodles', 'Dumplings'],
                culturalHeritage: ['Tembok Besar', 'Kota Terlarang', 'Terakota', 'Guilin'],
                publicHolidays: ['Tahun Baru China', 'Hari Nasional', 'Festival Musim Semi', 'Festival Pertengahan Musim Gugur'],
                socialRanking: 70,
                climate: 'Beragam',
                averageTemperature: 15,
                averageRainfall: 600,
                forestArea: 23,
                protectedAreas: 15,
                biodiversityRank: 5,
                carbonEmissions: 7.4,
                environmentalIndex: 38,
                riskScore: 35,
                politicalStability: 65,
                crimeIndex: 25,
                militarySpending: 2.0,
                peaceIndex: 40,
                terrorismIndex: 20,
                refugeePopulation: 1000,
                opportunityScore: 75,
                easeOfDoingBusiness: 78,
                innovationIndex: 75,
                startupEcosystem: 85,
                investmentScore: 80,
                talentPool: 95,
                marketSize: 100,
                infrastructureQuality: 90,
                internetSpeed: 60,
                digitalAdoption: 90,
                techEcosystem: 90,
                aiReadiness: 85,
                startups: 30000,
                phoneCode: '+86',
                tld: '.cn',
                isoCode: 'CHN',
                isoCode2: 'CN',
                drivingSide: 'right',
                tags: ['negara', 'asian-timur', 'adidaya', 'ekonomi', 'teknologi']
            }
        },
        // ==========================================================
        // 🇯🇵 JEPANG
        // ==========================================================
        {
            text: 'Jepang - Negara kepulauan di Asia Timur dengan teknologi maju dan budaya kaya. Ibu kota: Tokyo. Populasi: 125 juta jiwa. Mata uang: Yen (JPY). Bahasa: Jepang. Sistem pemerintahan: Monarki Konstitusional Parlementer. Ekonomi terbesar ketiga di dunia. Pemimpin dalam robotika, otomotif, dan elektronik. Angka harapan hidup tertinggi di dunia. Rumah bagi Gunung Fuji, kuil-kuil kuno, dan budaya pop global. Negara dengan inovasi dan tradisi yang harmonis.',
            metadata: {
                category: 'country',
                region: 'asian-timur',
                name: 'Jepang',
                officialName: 'Jepang',
                shortName: 'JPN',
                capital: 'Tokyo',
                capitalCoordinates: { lat: 35.6762, lng: 139.6503 },
                largestCity: 'Tokyo',
                demonym: 'Jepang',
                subregion: 'Eastern Asia',
                area: 377975,
                areaRank: 62,
                coastline: 29751,
                highestPoint: 'Gunung Fuji',
                highestElevation: 3776,
                lowestPoint: 'Laut Jepang',
                lowestElevation: 0,
                landBorders: [],
                coordinates: { lat: 36.0, lng: 138.0 },
                timezone: ['Waktu Jepang'],
                utcOffset: ['+9'],
                population: 125000000,
                populationRank: 11,
                populationDensity: 331,
                populationGrowth: -0.2,
                medianAge: 48.4,
                lifeExpectancy: 84.6,
                fertilityRate: 1.3,
                urbanization: 92,
                ethnicGroups: [
                    { name: 'Jepang', percentage: 98.0 },
                    { name: 'Korea', percentage: 1.0 },
                    { name: 'Lainnya', percentage: 1.0 }
                ],
                religions: [
                    { name: 'Shinto', percentage: 80.0 },
                    { name: 'Buddha', percentage: 35.0 },
                    { name: 'Kristen', percentage: 1.0 }
                ],
                languages: [
                    { name: 'Jepang', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 20 }
                ],
                literacyRate: 99,
                governmentType: 'Monarki Konstitusional Parlementer',
                independenceDay: '660-02-11',
                nationalHoliday: '23 Februari',
                legalSystem: 'Civil Law',
                constitution: '1947',
                administrativeDivisions: 47,
                memberships: ['PBB', 'G7', 'G20', 'OECD', 'APEC'],
                giniCoefficient: 32.9,
                hdi: 0.925,
                hdiRank: 16,
                corruptionIndex: 73,
                currency: 'Yen',
                currencyCode: 'JPY',
                gdp: 4200000000000,
                gdpPerCapita: 33600,
                gdpPpp: 5600000000000,
                gdpGrowth: 1.5,
                inflation: 0.5,
                unemployment: 2.5,
                povertyRate: 15.0,
                mainIndustries: ['Otomotif', 'Elektronik', 'Robotika', 'Keuangan', 'Pariwisata'],
                exports: [
                    { item: 'Otomotif', value: 150000000000 },
                    { item: 'Elektronik', value: 100000000000 },
                    { item: 'Mesin', value: 80000000000 },
                    { item: 'Robotika', value: 50000000000 }
                ],
                imports: [
                    { item: 'Minyak', value: 100000000000 },
                    { item: 'Elektronik', value: 80000000000 },
                    { item: 'Makanan', value: 60000000000 },
                    { item: 'Bahan kimia', value: 50000000000 }
                ],
                tradeBalance: 20000000000,
                naturalResources: ['Kayu', 'Perikanan', 'Air'],
                economicRanking: 3,
                internetPenetration: 92,
                mobilePenetration: 98,
                electricityAccess: 100,
                roadLength: 1200000,
                railwayLength: 27000,
                airports: 175,
                seaports: 100,
                healthcareAccess: 98,
                educationIndex: 0.88,
                nationalMotto: 'Harmoni, Kesabaran, Disiplin',
                nationalAnthem: 'Kimigayo',
                nationalAnimal: 'Monyet Jepang',
                nationalFlower: 'Sakura',
                nationalCuisine: ['Sushi', 'Ramen', 'Tempura', 'Matcha', 'Bento'],
                culturalHeritage: ['Kyoto', 'Gunung Fuji', 'Nara', 'Hiroshima'],
                publicHolidays: ['Tahun Baru', 'Hari Kebangsaan', 'Golden Week', 'Obon'],
                socialRanking: 88,
                climate: 'Beragam',
                averageTemperature: 15,
                averageRainfall: 1500,
                forestArea: 68,
                protectedAreas: 30,
                biodiversityRank: 15,
                carbonEmissions: 9.0,
                environmentalIndex: 62,
                riskScore: 20,
                politicalStability: 85,
                crimeIndex: 15,
                militarySpending: 1.0,
                peaceIndex: 25,
                terrorismIndex: 5,
                refugeePopulation: 1000,
                opportunityScore: 82,
                easeOfDoingBusiness: 80,
                innovationIndex: 85,
                startupEcosystem: 75,
                investmentScore: 80,
                talentPool: 90,
                marketSize: 90,
                infrastructureQuality: 95,
                internetSpeed: 70,
                digitalAdoption: 92,
                techEcosystem: 90,
                aiReadiness: 85,
                startups: 5000,
                phoneCode: '+81',
                tld: '.jp',
                isoCode: 'JPN',
                isoCode2: 'JP',
                drivingSide: 'left',
                tags: ['negara', 'asian-timur', 'teknologi', 'robotika', 'otomotif']
            }
        },
        // ==========================================================
        // 🇰🇷 KOREA SELATAN
        // ==========================================================
        {
            text: 'Korea Selatan - Negara di Asia Timur dengan ekonomi maju dan budaya pop global. Ibu kota: Seoul. Populasi: 52 juta jiwa. Mata uang: Won (KRW). Bahasa: Korea. Sistem pemerintahan: Republik Presidensial. Pemimpin dalam semikonduktor, smartphone, dan K-pop. Internet tercepat di dunia. Rumah bagi Samsung, Hyundai, dan LG. Negara dengan keajaiban ekonomi Han River. Budaya K-pop dan K-drama yang mendunia.',
            metadata: {
                category: 'country',
                region: 'asian-timur',
                name: 'Korea Selatan',
                officialName: 'Republik Korea',
                shortName: 'KOR',
                capital: 'Seoul',
                capitalCoordinates: { lat: 37.5665, lng: 126.9780 },
                largestCity: 'Seoul',
                demonym: 'Korea Selatan',
                subregion: 'Eastern Asia',
                area: 100210,
                areaRank: 107,
                coastline: 2413,
                highestPoint: 'Gunung Halla',
                highestElevation: 1950,
                lowestPoint: 'Laut Jepang',
                lowestElevation: 0,
                landBorders: ['Korea Utara'],
                coordinates: { lat: 37.0, lng: 127.5 },
                timezone: ['Waktu Korea'],
                utcOffset: ['+9'],
                population: 52000000,
                populationRank: 28,
                populationDensity: 519,
                populationGrowth: 0.0,
                medianAge: 44.5,
                lifeExpectancy: 83.5,
                fertilityRate: 0.8,
                urbanization: 82,
                ethnicGroups: [
                    { name: 'Korea', percentage: 96.0 },
                    { name: 'Lainnya', percentage: 4.0 }
                ],
                religions: [
                    { name: 'Tidak beragama', percentage: 50.0 },
                    { name: 'Kristen', percentage: 30.0 },
                    { name: 'Buddha', percentage: 15.0 },
                    { name: 'Lainnya', percentage: 5.0 }
                ],
                languages: [
                    { name: 'Korea', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 30 }
                ],
                literacyRate: 98,
                governmentType: 'Republik Presidensial',
                independenceDay: '1948-08-15',
                nationalHoliday: '15 Agustus',
                legalSystem: 'Civil Law',
                constitution: '1948',
                administrativeDivisions: 17,
                memberships: ['PBB', 'G20', 'OECD', 'APEC'],
                giniCoefficient: 34.0,
                hdi: 0.925,
                hdiRank: 15,
                corruptionIndex: 62,
                currency: 'Won',
                currencyCode: 'KRW',
                gdp: 1700000000000,
                gdpPerCapita: 32600,
                gdpPpp: 2500000000000,
                gdpGrowth: 2.5,
                inflation: 2.0,
                unemployment: 3.0,
                povertyRate: 14.0,
                mainIndustries: ['Semikonduktor', 'Smartphone', 'Otomotif', 'K-Pop', 'Pariwisata'],
                exports: [
                    { item: 'Semikonduktor', value: 100000000000 },
                    { item: 'Smartphone', value: 50000000000 },
                    { item: 'Otomotif', value: 40000000000 },
                    { item: 'Bahan kimia', value: 30000000000 }
                ],
                imports: [
                    { item: 'Minyak', value: 80000000000 },
                    { item: 'Elektronik', value: 60000000000 },
                    { item: 'Mesin', value: 50000000000 },
                    { item: 'Makanan', value: 30000000000 }
                ],
                tradeBalance: 50000000000,
                naturalResources: ['Batu bara', 'Emas', 'Tembaga', 'Perikanan'],
                economicRanking: 13,
                internetPenetration: 95,
                mobilePenetration: 99,
                electricityAccess: 100,
                roadLength: 110000,
                railwayLength: 5000,
                airports: 70,
                seaports: 40,
                healthcareAccess: 95,
                educationIndex: 0.85,
                nationalMotto: 'Manfaat bagi seluruh umat manusia',
                nationalAnthem: 'Aegukga',
                nationalAnimal: 'Harimau Korea',
                nationalFlower: 'Bunga Rose of Sharon',
                nationalCuisine: ['Kimchi', 'Bibimbap', 'Bulgogi', 'Tteokbokki', 'KFC'],
                culturalHeritage: ['Seoul', 'Gyeongju', 'Jeju', 'Andong'],
                publicHolidays: ['Tahun Baru', 'Hari Kemerdekaan', 'Chuseok', 'Seollal'],
                socialRanking: 82,
                climate: 'Beragam',
                averageTemperature: 13,
                averageRainfall: 1300,
                forestArea: 64,
                protectedAreas: 10,
                biodiversityRank: 25,
                carbonEmissions: 12.0,
                environmentalIndex: 58,
                riskScore: 25,
                politicalStability: 70,
                crimeIndex: 18,
                militarySpending: 2.8,
                peaceIndex: 35,
                terrorismIndex: 10,
                refugeePopulation: 1000,
                opportunityScore: 80,
                easeOfDoingBusiness: 82,
                innovationIndex: 82,
                startupEcosystem: 80,
                investmentScore: 78,
                talentPool: 88,
                marketSize: 85,
                infrastructureQuality: 92,
                internetSpeed: 75,
                digitalAdoption: 95,
                techEcosystem: 92,
                aiReadiness: 85,
                startups: 4000,
                phoneCode: '+82',
                tld: '.kr',
                isoCode: 'KOR',
                isoCode2: 'KR',
                drivingSide: 'right',
                tags: ['negara', 'asian-timur', 'teknologi', 'k-pop', 'semikonduktor']
            }
        },
        // ==========================================================
        // 🇹🇼 TAIWAN
        // ==========================================================
        {
            text: 'Taiwan - Negara kepulauan di Asia Timur dengan ekonomi maju dan industri teknologi tinggi. Ibu kota: Taipei. Populasi: 23.5 juta jiwa. Mata uang: Dolar Taiwan (TWD). Bahasa: Mandarin, Taiwan. Sistem pemerintahan: Republik Demokratis. Pemimpin global dalam produksi semikonduktor (TSMC). Rumah bagi teknologi tinggi, budaya Tionghoa, dan keindahan alam. Pusat inovasi dan manufaktur chip terkemuka di dunia.',
            metadata: {
                category: 'country',
                region: 'asian-timur',
                name: 'Taiwan',
                officialName: 'Republik China (Taiwan)',
                shortName: 'TWN',
                capital: 'Taipei',
                capitalCoordinates: { lat: 25.0330, lng: 121.5654 },
                largestCity: 'New Taipei',
                demonym: 'Taiwan',
                subregion: 'Eastern Asia',
                area: 36193,
                areaRank: 137,
                coastline: 1566,
                highestPoint: 'Yushan',
                highestElevation: 3952,
                lowestPoint: 'Laut China Selatan',
                lowestElevation: 0,
                landBorders: [],
                coordinates: { lat: 23.5, lng: 121.0 },
                timezone: ['Waktu Taiwan'],
                utcOffset: ['+8'],
                population: 23500000,
                populationRank: 56,
                populationDensity: 649,
                populationGrowth: 0.1,
                medianAge: 42.0,
                lifeExpectancy: 80.0,
                fertilityRate: 1.1,
                urbanization: 78,
                ethnicGroups: [
                    { name: 'Han', percentage: 95.0 },
                    { name: 'Pribumi', percentage: 2.0 },
                    { name: 'Lainnya', percentage: 3.0 }
                ],
                religions: [
                    { name: 'Buddha', percentage: 35.0 },
                    { name: 'Tao', percentage: 33.0 },
                    { name: 'Kristen', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 27.0 }
                ],
                languages: [
                    { name: 'Mandarin', percentage: 100, official: true },
                    { name: 'Taiwan', percentage: 60 },
                    { name: 'Hakka', percentage: 10 }
                ],
                literacyRate: 98,
                governmentType: 'Republik Demokratis',
                independenceDay: '1945-10-25',
                nationalHoliday: '10 Oktober',
                legalSystem: 'Civil Law',
                constitution: '1947',
                administrativeDivisions: 22,
                memberships: ['APEC', 'WTO'],
                giniCoefficient: 34.0,
                hdi: 0.926,
                hdiRank: 14,
                corruptionIndex: 65,
                currency: 'Dolar Taiwan',
                currencyCode: 'TWD',
                gdp: 760000000000,
                gdpPerCapita: 32300,
                gdpPpp: 1300000000000,
                gdpGrowth: 3.5,
                inflation: 1.5,
                unemployment: 3.5,
                povertyRate: 12.0,
                mainIndustries: ['Semikonduktor', 'Elektronik', 'Teknologi', 'Manufaktur', 'Pariwisata'],
                exports: [
                    { item: 'Semikonduktor', value: 150000000000 },
                    { item: 'Elektronik', value: 80000000000 },
                    { item: 'Mesin', value: 50000000000 },
                    { item: 'Bahan kimia', value: 30000000000 }
                ],
                imports: [
                    { item: 'Elektronik', value: 80000000000 },
                    { item: 'Mesin', value: 60000000000 },
                    { item: 'Minyak', value: 40000000000 },
                    { item: 'Makanan', value: 20000000000 }
                ],
                tradeBalance: 100000000000,
                naturalResources: ['Emas', 'Tembaga', 'Batu bara', 'Perikanan'],
                economicRanking: 21,
                internetPenetration: 90,
                mobilePenetration: 96,
                electricityAccess: 100,
                roadLength: 40000,
                railwayLength: 1500,
                airports: 40,
                seaports: 20,
                healthcareAccess: 92,
                educationIndex: 0.82,
                nationalMotto: 'Kemakmuran, Harmoni, Keamanan',
                nationalAnthem: 'National Anthem',
                nationalAnimal: 'Beruang Formosa',
                nationalFlower: 'Bunga Plum',
                nationalCuisine: ['Bubble Tea', 'Stinky Tofu', 'Beef Noodle', 'Xiao Long Bao'],
                culturalHeritage: ['Taipei 101', 'Taroko Gorge', 'Sun Moon Lake', 'Kenting'],
                publicHolidays: ['Tahun Baru', 'Hari Nasional', 'Festival Musim Semi', 'Festival Perahu Naga'],
                socialRanking: 80,
                climate: 'Subtropis',
                averageTemperature: 24,
                averageRainfall: 2500,
                forestArea: 60,
                protectedAreas: 15,
                biodiversityRank: 20,
                carbonEmissions: 10.0,
                environmentalIndex: 55,
                riskScore: 35,
                politicalStability: 65,
                crimeIndex: 15,
                militarySpending: 1.8,
                peaceIndex: 30,
                terrorismIndex: 5,
                refugeePopulation: 0,
                opportunityScore: 78,
                easeOfDoingBusiness: 78,
                innovationIndex: 78,
                startupEcosystem: 75,
                investmentScore: 75,
                talentPool: 85,
                marketSize: 80,
                infrastructureQuality: 88,
                internetSpeed: 65,
                digitalAdoption: 88,
                techEcosystem: 88,
                aiReadiness: 80,
                startups: 2000,
                phoneCode: '+886',
                tld: '.tw',
                isoCode: 'TWN',
                isoCode2: 'TW',
                drivingSide: 'right',
                tags: ['negara', 'asian-timur', 'semikonduktor', 'tsmc', 'teknologi']
            }
        },
        // ==========================================================
        // 🇲🇳 MONGOLIA
        // ==========================================================
        {
            text: 'Mongolia - Negara di Asia Timur dengan padang rumput luas dan budaya nomaden. Ibu kota: Ulaanbaatar. Populasi: 3.3 juta jiwa. Mata uang: Tugrik (MNT). Bahasa: Mongolia. Sistem pemerintahan: Republik Parlementer. Kepadatan penduduk terendah di dunia. Kaya akan mineral tembaga, batu bara, dan emas. Rumah bagi Genghis Khan dan budaya pengembara. Padang rumput tak berujung dan tradisi menunggang kuda.',
            metadata: {
                category: 'country',
                region: 'asian-timur',
                name: 'Mongolia',
                officialName: 'Mongolia',
                shortName: 'MNG',
                capital: 'Ulaanbaatar',
                capitalCoordinates: { lat: 47.8864, lng: 106.9057 },
                largestCity: 'Ulaanbaatar',
                demonym: 'Mongolia',
                subregion: 'Eastern Asia',
                area: 1564116,
                areaRank: 19,
                coastline: 0,
                highestPoint: 'Gunung Khüiten',
                highestElevation: 4374,
                lowestPoint: 'Hoh Nuur',
                lowestElevation: 518,
                landBorders: ['China', 'Rusia'],
                coordinates: { lat: 46.0, lng: 105.0 },
                timezone: ['Waktu Mongolia'],
                utcOffset: ['+8'],
                population: 3300000,
                populationRank: 134,
                populationDensity: 2,
                populationGrowth: 1.5,
                medianAge: 28.0,
                lifeExpectancy: 70.0,
                fertilityRate: 2.5,
                urbanization: 68,
                ethnicGroups: [
                    { name: 'Khalkh', percentage: 85.0 },
                    { name: 'Kazakh', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 10.0 }
                ],
                religions: [
                    { name: 'Buddha', percentage: 53.0 },
                    { name: 'Tidak beragama', percentage: 39.0 },
                    { name: 'Kristen', percentage: 3.0 }
                ],
                languages: [
                    { name: 'Mongolia', percentage: 100, official: true },
                    { name: 'Rusia', percentage: 10 },
                    { name: 'Inggris', percentage: 5 }
                ],
                literacyRate: 98,
                governmentType: 'Republik Parlementer',
                independenceDay: '1921-07-11',
                nationalHoliday: '11 Juli',
                legalSystem: 'Civil Law',
                constitution: '1992',
                administrativeDivisions: 21,
                memberships: ['PBB', 'WTO', 'SCO'],
                giniCoefficient: 32.0,
                hdi: 0.737,
                hdiRank: 96,
                corruptionIndex: 38,
                currency: 'Tugrik',
                currencyCode: 'MNT',
                gdp: 15000000000,
                gdpPerCapita: 4540,
                gdpPpp: 50000000000,
                gdpGrowth: 5.0,
                inflation: 6.0,
                unemployment: 5.0,
                povertyRate: 20.0,
                mainIndustries: ['Tambang', 'Pertanian', 'Tekstil', 'Pariwisata'],
                exports: [
                    { item: 'Tembaga', value: 5000000000 },
                    { item: 'Batu bara', value: 3000000000 },
                    { item: 'Emas', value: 2000000000 },
                    { item: 'Kasmir', value: 1000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 3000000000 },
                    { item: 'Elektronik', value: 2000000000 },
                    { item: 'Minyak', value: 1000000000 },
                    { item: 'Makanan', value: 1000000000 }
                ],
                tradeBalance: 2000000000,
                naturalResources: ['Tembaga', 'Batu bara', 'Emas', 'Uranium', 'Timah'],
                economicRanking: 110,
                internetPenetration: 70,
                mobilePenetration: 85,
                electricityAccess: 95,
                roadLength: 50000,
                railwayLength: 2000,
                airports: 20,
                seaports: 0,
                healthcareAccess: 65,
                educationIndex: 0.65,
                nationalMotto: 'Tanah air, Kebanggaan, Kebebasan',
                nationalAnthem: 'Mongolia National Anthem',
                nationalAnimal: 'Kuda Przewalski',
                nationalFlower: 'Bunga Garam',
                nationalCuisine: ['Buuz', 'Khuushuur', 'Tsuivan', 'Airag', 'Boodog'],
                culturalHeritage: ['Ulaanbaatar', 'Gobi Gurvan Saikhan', 'Khorgo-Terkhiin'],
                publicHolidays: ['Naadam', 'Tahun Baru', 'Hari Kemerdekaan', 'Tsagaan Sar'],
                socialRanking: 55,
                climate: 'Kontinental',
                averageTemperature: 0,
                averageRainfall: 200,
                forestArea: 8,
                protectedAreas: 15,
                biodiversityRank: 35,
                carbonEmissions: 5.0,
                environmentalIndex: 45,
                riskScore: 40,
                politicalStability: 60,
                crimeIndex: 30,
                militarySpending: 1.0,
                peaceIndex: 45,
                terrorismIndex: 10,
                refugeePopulation: 0,
                opportunityScore: 55,
                easeOfDoingBusiness: 55,
                innovationIndex: 35,
                startupEcosystem: 40,
                investmentScore: 50,
                talentPool: 50,
                marketSize: 50,
                infrastructureQuality: 45,
                internetSpeed: 20,
                digitalAdoption: 55,
                techEcosystem: 40,
                aiReadiness: 30,
                startups: 50,
                phoneCode: '+976',
                tld: '.mn',
                isoCode: 'MNG',
                isoCode2: 'MN',
                drivingSide: 'right',
                tags: ['negara', 'asian-timur', 'nomaden', 'mineral', 'padang-rumput']
            }
        },
        // ==========================================================
        // 🇭🇰 HONG KONG
        // ==========================================================
        {
            text: 'Hong Kong - Wilayah administratif khusus China di Asia Timur dengan ekonomi kapitalis maju. Ibu kota: Victoria City. Populasi: 7.5 juta jiwa. Mata uang: Dolar Hong Kong (HKD). Bahasa: Kanton, Inggris, Mandarin. Sistem pemerintahan: Wilayah Administratif Khusus. Pusat keuangan global dan pintu gerbang perdagangan China-dunia. Rumah bagi keuangan, logistik, dan budaya hiburan. Kota dengan kebebasan ekonomi tertinggi di dunia.',
            metadata: {
                category: 'country',
                region: 'asian-timur',
                name: 'Hong Kong',
                officialName: 'Wilayah Administratif Khusus Hong Kong',
                shortName: 'HKG',
                capital: 'Victoria City',
                capitalCoordinates: { lat: 22.3193, lng: 114.1694 },
                largestCity: 'Kowloon',
                demonym: 'Hong Kong',
                subregion: 'Eastern Asia',
                area: 1104,
                areaRank: 174,
                coastline: 733,
                highestPoint: 'Tai Mo Shan',
                highestElevation: 958,
                lowestPoint: 'Laut China Selatan',
                lowestElevation: 0,
                landBorders: ['China'],
                coordinates: { lat: 22.25, lng: 114.17 },
                timezone: ['Waktu Hong Kong'],
                utcOffset: ['+8'],
                population: 7500000,
                populationRank: 100,
                populationDensity: 6790,
                populationGrowth: 0.1,
                medianAge: 45.0,
                lifeExpectancy: 85.0,
                fertilityRate: 1.1,
                urbanization: 100,
                ethnicGroups: [
                    { name: 'Cina', percentage: 92.0 },
                    { name: 'Filipina', percentage: 2.5 },
                    { name: 'India', percentage: 1.5 },
                    { name: 'Lainnya', percentage: 4.0 }
                ],
                religions: [
                    { name: 'Buddha', percentage: 30.0 },
                    { name: 'Tao', percentage: 20.0 },
                    { name: 'Kristen', percentage: 15.0 },
                    { name: 'Lainnya', percentage: 35.0 }
                ],
                languages: [
                    { name: 'Kanton', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 50, official: true },
                    { name: 'Mandarin', percentage: 30, official: true }
                ],
                literacyRate: 98,
                governmentType: 'Wilayah Administratif Khusus',
                independenceDay: '1997-07-01',
                nationalHoliday: '1 Juli',
                legalSystem: 'Common Law',
                constitution: 'Basic Law',
                administrativeDivisions: 18,
                memberships: ['PBB', 'WTO', 'APEC'],
                giniCoefficient: 53.9,
                hdi: 0.949,
                hdiRank: 4,
                corruptionIndex: 75,
                currency: 'Dolar Hong Kong',
                currencyCode: 'HKD',
                gdp: 400000000000,
                gdpPerCapita: 53300,
                gdpPpp: 550000000000,
                gdpGrowth: 3.0,
                inflation: 2.0,
                unemployment: 3.0,
                povertyRate: 15.0,
                mainIndustries: ['Keuangan', 'Perdagangan', 'Logistik', 'Pariwisata', 'Teknologi'],
                exports: [
                    { item: 'Keuangan', value: 100000000000 },
                    { item: 'Elektronik', value: 50000000000 },
                    { item: 'Tekstil', value: 30000000000 },
                    { item: 'Perhiasan', value: 20000000000 }
                ],
                imports: [
                    { item: 'Elektronik', value: 80000000000 },
                    { item: 'Mesin', value: 60000000000 },
                    { item: 'Minyak', value: 40000000000 },
                    { item: 'Makanan', value: 30000000000 }
                ],
                tradeBalance: -20000000000,
                naturalResources: ['Pelabuhan', 'Lokasi strategis'],
                economicRanking: 35,
                internetPenetration: 95,
                mobilePenetration: 99,
                electricityAccess: 100,
                roadLength: 2000,
                railwayLength: 100,
                airports: 2,
                seaports: 10,
                healthcareAccess: 98,
                educationIndex: 0.88,
                nationalMotto: 'Satu Negara, Dua Sistem',
                nationalAnthem: 'March of the Volunteers',
                nationalAnimal: 'Naga',
                nationalFlower: 'Bunga Anggrek',
                nationalCuisine: ['Dim Sum', 'Peking Duck', 'Hot Pot', 'Noodles', 'Bubble Tea'],
                culturalHeritage: ['Victoria Peak', 'Star Ferry', 'Tsim Sha Tsui', 'Disneyland'],
                publicHolidays: ['Tahun Baru', 'Hari Nasional', 'Festival Musim Semi', 'Festival Perahu Naga'],
                socialRanking: 85,
                climate: 'Subtropis',
                averageTemperature: 24,
                averageRainfall: 2400,
                forestArea: 20,
                protectedAreas: 40,
                biodiversityRank: 30,
                carbonEmissions: 6.0,
                environmentalIndex: 58,
                riskScore: 30,
                politicalStability: 70,
                crimeIndex: 12,
                militarySpending: 0.5,
                peaceIndex: 25,
                terrorismIndex: 5,
                refugeePopulation: 1000,
                opportunityScore: 85,
                easeOfDoingBusiness: 90,
                innovationIndex: 75,
                startupEcosystem: 80,
                investmentScore: 88,
                talentPool: 85,
                marketSize: 85,
                infrastructureQuality: 95,
                internetSpeed: 65,
                digitalAdoption: 92,
                techEcosystem: 85,
                aiReadiness: 78,
                startups: 3000,
                phoneCode: '+852',
                tld: '.hk',
                isoCode: 'HKG',
                isoCode2: 'HK',
                drivingSide: 'left',
                tags: ['negara', 'asian-timur', 'pusat-keuangan', 'perdagangan', 'global']
            }
        },
        // ==========================================================
        // 🇲🇴 MAKAU
        // ==========================================================
        {
            text: 'Makau - Wilayah Administratif Khusus China di Asia Timur dengan industri perjudian terbesar dunia. Ibu kota: Makau. Populasi: 700 ribu jiwa. Mata uang: Pataca (MOP). Bahasa: Kanton, Portugis. Sistem pemerintahan: Wilayah Administratif Khusus. Satu-satunya tempat di China dengan perjudian legal. Warisan budaya Portugis yang kuat. Pusat wisata dan hiburan terkemuka di Asia. Rumah bagi kasino terbesar di dunia.',
            metadata: {
                category: 'country',
                region: 'asian-timur',
                name: 'Makau',
                officialName: 'Wilayah Administratif Khusus Makau',
                shortName: 'MAC',
                capital: 'Makau',
                capitalCoordinates: { lat: 22.1987, lng: 113.5439 },
                largestCity: 'Makau',
                demonym: 'Makau',
                subregion: 'Eastern Asia',
                area: 33,
                areaRank: 179,
                coastline: 40,
                highestPoint: 'Coloane Alto',
                highestElevation: 172,
                lowestPoint: 'Laut China Selatan',
                lowestElevation: 0,
                landBorders: ['China'],
                coordinates: { lat: 22.17, lng: 113.55 },
                timezone: ['Waktu Makau'],
                utcOffset: ['+8'],
                population: 700000,
                populationRank: 167,
                populationDensity: 21212,
                populationGrowth: 0.5,
                medianAge: 40.0,
                lifeExpectancy: 84.0,
                fertilityRate: 1.2,
                urbanization: 100,
                ethnicGroups: [
                    { name: 'Cina', percentage: 88.0 },
                    { name: 'Portugis', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 7.0 }
                ],
                religions: [
                    { name: 'Buddha', percentage: 45.0 },
                    { name: 'Kristen', percentage: 20.0 },
                    { name: 'Tao', percentage: 15.0 },
                    { name: 'Lainnya', percentage: 20.0 }
                ],
                languages: [
                    { name: 'Kanton', percentage: 100, official: true },
                    { name: 'Portugis', percentage: 20, official: true },
                    { name: 'Mandarin', percentage: 15 }
                ],
                literacyRate: 95,
                governmentType: 'Wilayah Administratif Khusus',
                independenceDay: '1999-12-20',
                nationalHoliday: '20 Desember',
                legalSystem: 'Civil Law',
                constitution: 'Basic Law',
                administrativeDivisions: 7,
                memberships: ['WTO'],
                giniCoefficient: 35.0,
                hdi: 0.920,
                hdiRank: 20,
                corruptionIndex: 65,
                currency: 'Pataca',
                currencyCode: 'MOP',
                gdp: 50000000000,
                gdpPerCapita: 71400,
                gdpPpp: 60000000000,
                gdpGrowth: 4.0,
                inflation: 2.5,
                unemployment: 2.0,
                povertyRate: 5.0,
                mainIndustries: ['Perjudian', 'Pariwisata', 'Hiburan', 'Keuangan'],
                exports: [
                    { item: 'Perjudian', value: 30000000000 },
                    { item: 'Pariwisata', value: 10000000000 },
                    { item: 'Tekstil', value: 5000000000 }
                ],
                imports: [
                    { item: 'Elektronik', value: 10000000000 },
                    { item: 'Mesin', value: 8000000000 },
                    { item: 'Makanan', value: 5000000000 }
                ],
                tradeBalance: 10000000000,
                naturalResources: ['Pelabuhan'],
                economicRanking: 70,
                internetPenetration: 90,
                mobilePenetration: 96,
                electricityAccess: 100,
                roadLength: 400,
                railwayLength: 0,
                airports: 1,
                seaports: 5,
                healthcareAccess: 92,
                educationIndex: 0.78,
                nationalMotto: 'Satu Negara, Dua Sistem',
                nationalAnthem: 'March of the Volunteers',
                nationalAnimal: 'Naga',
                nationalFlower: 'Bunga Anggrek',
                nationalCuisine: ['Macanese Cuisine', 'Dim Sum', 'Portuguese Egg Tart', 'Peking Duck'],
                culturalHeritage: ['Makau', 'Ruins of St. Paul\'s', 'A-Ma Temple'],
                publicHolidays: ['Tahun Baru', 'Hari Nasional', 'Festival Musim Semi', 'Festival Perahu Naga'],
                socialRanking: 80,
                climate: 'Subtropis',
                averageTemperature: 24,
                averageRainfall: 2000,
                forestArea: 5,
                protectedAreas: 5,
                biodiversityRank: 50,
                carbonEmissions: 8.0,
                environmentalIndex: 50,
                riskScore: 25,
                politicalStability: 75,
                crimeIndex: 10,
                militarySpending: 0.5,
                peaceIndex: 20,
                terrorismIndex: 5,
                refugeePopulation: 0,
                opportunityScore: 75,
                easeOfDoingBusiness: 75,
                innovationIndex: 50,
                startupEcosystem: 55,
                investmentScore: 70,
                talentPool: 60,
                marketSize: 60,
                infrastructureQuality: 88,
                internetSpeed: 55,
                digitalAdoption: 80,
                techEcosystem: 55,
                aiReadiness: 45,
                startups: 100,
                phoneCode: '+853',
                tld: '.mo',
                isoCode: 'MAC',
                isoCode2: 'MO',
                drivingSide: 'right',
                tags: ['negara', 'asian-timur', 'perjudian', 'portugis', 'pariwisata']
            }
        },
        // ==========================================================
        // 🇹🇪 TIBET
        // ==========================================================
        {
            text: 'Tibet - Wilayah otonom di China dengan budaya Buddhis Tibet. Ibu kota: Lhasa. Populasi: 3.6 juta jiwa. Mata uang: Yuan (CNY). Bahasa: Tibet, Mandarin. Sistem pemerintahan: Wilayah Otonom. Rumah Istana Potala dan Gunung Everest. Budaya unik dengan pengaruh India dan China. Destinasi spiritual dan ekowisata terkemuka di dunia. Alam pegunungan Himalaya yang memukau.',
            metadata: {
                category: 'country',
                region: 'asian-timur',
                name: 'Tibet',
                officialName: 'Wilayah Otonom Tibet',
                shortName: 'TIB',
                capital: 'Lhasa',
                capitalCoordinates: { lat: 29.6500, lng: 91.1000 },
                largestCity: 'Lhasa',
                demonym: 'Tibet',
                subregion: 'Eastern Asia',
                area: 1228400,
                areaRank: 26,
                coastline: 0,
                highestPoint: 'Gunung Everest',
                highestElevation: 8848,
                lowestPoint: 'Lembah Yarlung Tsangpo',
                lowestElevation: 1000,
                landBorders: ['China', 'India', 'Nepal', 'Bhutan', 'Myanmar'],
                coordinates: { lat: 32.0, lng: 89.0 },
                timezone: ['Waktu China'],
                utcOffset: ['+8'],
                population: 3600000,
                populationRank: 130,
                populationDensity: 3,
                populationGrowth: 1.0,
                medianAge: 30.0,
                lifeExpectancy: 70.0,
                fertilityRate: 2.5,
                urbanization: 30,
                ethnicGroups: [
                    { name: 'Tibet', percentage: 90.0 },
                    { name: 'Han', percentage: 8.0 },
                    { name: 'Lainnya', percentage: 2.0 }
                ],
                religions: [
                    { name: 'Buddha', percentage: 80.0 },
                    { name: 'Tao', percentage: 10.0 },
                    { name: 'Kristen', percentage: 5.0 }
                ],
                languages: [
                    { name: 'Tibet', percentage: 100, official: true },
                    { name: 'Mandarin', percentage: 20, official: true }
                ],
                literacyRate: 80,
                governmentType: 'Wilayah Otonom',
                independenceDay: '1951-05-23',
                nationalHoliday: '1 Oktober',
                legalSystem: 'Civil Law',
                constitution: '1982',
                administrativeDivisions: 6,
                memberships: ['Tidak ada'],
                giniCoefficient: 30.0,
                hdi: 0.650,
                hdiRank: 130,
                corruptionIndex: 35,
                currency: 'Yuan',
                currencyCode: 'CNY',
                gdp: 20000000000,
                gdpPerCapita: 5550,
                gdpPpp: 40000000000,
                gdpGrowth: 8.0,
                inflation: 3.0,
                unemployment: 5.0,
                povertyRate: 15.0,
                mainIndustries: ['Pariwisata', 'Pertanian', 'Tambang', 'Kerajinan'],
                exports: [
                    { item: 'Pariwisata', value: 5000000000 },
                    { item: 'Kerajinan', value: 2000000000 },
                    { item: 'Pertanian', value: 1000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 3000000000 },
                    { item: 'Elektronik', value: 2000000000 },
                    { item: 'Makanan', value: 1000000000 }
                ],
                tradeBalance: -1000000000,
                naturalResources: ['Emas', 'Tembaga', 'Batu bara', 'Air'],
                economicRanking: 120,
                internetPenetration: 60,
                mobilePenetration: 75,
                electricityAccess: 90,
                roadLength: 10000,
                railwayLength: 1000,
                airports: 5,
                seaports: 0,
                healthcareAccess: 65,
                educationIndex: 0.55,
                nationalMotto: 'Kebebasan, Persatuan, Kemakmuran',
                nationalAnthem: 'March of the Volunteers',
                nationalAnimal: 'Yak',
                nationalFlower: 'Bunga Snow Lotus',
                nationalCuisine: ['Tsampa', 'Butter Tea', 'Momo', 'Thukpa', 'Chang'],
                culturalHeritage: ['Istana Potala', 'Lhasa', 'Gunung Everest', 'Tashilhunpo'],
                publicHolidays: ['Tahun Baru Tibet', 'Festival Musim Semi', 'Hari Nasional', 'Festival Perahu Naga'],
                socialRanking: 45,
                climate: 'Pegunungan',
                averageTemperature: 5,
                averageRainfall: 400,
                forestArea: 10,
                protectedAreas: 20,
                biodiversityRank: 10,
                carbonEmissions: 0.5,
                environmentalIndex: 55,
                riskScore: 45,
                politicalStability: 55,
                crimeIndex: 20,
                militarySpending: 1.0,
                peaceIndex: 40,
                terrorismIndex: 15,
                refugeePopulation: 1000,
                opportunityScore: 50,
                easeOfDoingBusiness: 40,
                innovationIndex: 30,
                startupEcosystem: 25,
                investmentScore: 35,
                talentPool: 40,
                marketSize: 45,
                infrastructureQuality: 40,
                internetSpeed: 15,
                digitalAdoption: 40,
                techEcosystem: 25,
                aiReadiness: 20,
                startups: 20,
                phoneCode: '+86',
                tld: '.cn',
                isoCode: 'TIB',
                isoCode2: 'TIB',
                drivingSide: 'right',
                tags: ['negara', 'asian-timur', 'tibet', 'buddhis', 'himachal']
            }
        }
    ];

    // ============================================================
    // PROSES DATA KE REGISTER
    // ============================================================
    for (let i = 0; i < data.length; i++) {
        window.__DATA_REGISTER.push(data[i]);
    }

    // ============================================================
    // LOGGER
    // ============================================================
    if (window.InternalLogger) {
        window.InternalLogger.info('CountryAsianTimur', '✅ Loaded ' + data.length + ' countries (SUPER LENGKAP - 8 NEGARA/WILAYAH!)');
    }

})();