/* ============================================================
   📁 dataries/country/eropan-tengah.js
   📌 DATA NEGARA EROPA TENGAH
   🔥 6 NEGARA — Polandia, Ceko, Hungaria, Slowakia, Austria, Swiss
   🔥 DATA SUPER LENGKAP — 100+ FIELD PER NEGARA!
   🔥 TANPA DUPLIKAT — SWISS & AUSTRIA HANYA DI SINI!
   ============================================================ */

(function() {
    'use strict';
    
    if (window.__CountryEropanTengahLoaded) return;
    window.__CountryEropanTengahLoaded = true;
    
    window.__DATA_REGISTER = window.__DATA_REGISTER || [];
    
    const data = [
        // ==========================================================
        // 🇵🇱 POLANDIA
        // ==========================================================
        {
            text: 'Polandia - Negara terbesar di Eropa Tengah dengan ekonomi berkembang pesat. Ibu kota: Warsawa. Populasi: 37 juta jiwa. Mata uang: Zloty (PLN). Bahasa: Polandia. Sistem pemerintahan: Republik Parlementer. Anggota UE dan NATO. Negara dengan sejarah panjang dan budaya kaya. Rumah bagi kastil-kastil megah, kota-kota bersejarah, dan industri otomotif yang berkembang. Pusat manufaktur dan logistik Eropa.',
            metadata: {
                category: 'country',
                region: 'eropan-tengah',
                name: 'Polandia',
                officialName: 'Republik Polandia',
                shortName: 'POL',
                capital: 'Warsawa',
                capitalCoordinates: { lat: 52.2297, lng: 21.0122 },
                largestCity: 'Warsawa',
                demonym: 'Polandia',
                subregion: 'Central Europe',
                area: 312696,
                areaRank: 69,
                coastline: 770,
                highestPoint: 'Rysy',
                highestElevation: 2499,
                lowestPoint: 'Danau Marzec',
                lowestElevation: -2,
                landBorders: ['Jerman', 'Ceko', 'Slovakia', 'Ukraina', 'Belarus', 'Lithuania', 'Rusia'],
                coordinates: { lat: 52.0, lng: 20.0 },
                timezone: ['Waktu Eropa Tengah'],
                utcOffset: ['+1'],
                population: 37000000,
                populationRank: 38,
                populationDensity: 118,
                populationGrowth: 0.0,
                medianAge: 42.0,
                lifeExpectancy: 78.0,
                fertilityRate: 1.3,
                urbanization: 60,
                ethnicGroups: [
                    { name: 'Polandia', percentage: 98.0 },
                    { name: 'Lainnya', percentage: 2.0 }
                ],
                religions: [
                    { name: 'Kristen Katolik', percentage: 87.0 },
                    { name: 'Kristen Ortodoks', percentage: 2.0 },
                    { name: 'Lainnya', percentage: 11.0 }
                ],
                languages: [
                    { name: 'Polandia', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 30 },
                    { name: 'Jerman', percentage: 10 }
                ],
                literacyRate: 99,
                governmentType: 'Republik Parlementer',
                independenceDay: '1918-11-11',
                nationalHoliday: '3 Mei',
                legalSystem: 'Civil Law',
                constitution: '1997',
                administrativeDivisions: 16,
                memberships: ['PBB', 'UE', 'NATO', 'OECD', 'WTO'],
                giniCoefficient: 30.2,
                hdi: 0.880,
                hdiRank: 34,
                corruptionIndex: 56,
                currency: 'Zloty',
                currencyCode: 'PLN',
                gdp: 800000000000,
                gdpPerCapita: 21600,
                gdpPpp: 1600000000000,
                gdpGrowth: 3.5,
                inflation: 4.0,
                unemployment: 3.0,
                povertyRate: 12.0,
                mainIndustries: ['Otomotif', 'Elektronik', 'Manufaktur', 'Pertanian', 'IT'],
                exports: [
                    { item: 'Otomotif', value: 50000000000 },
                    { item: 'Mesin', value: 40000000000 },
                    { item: 'Elektronik', value: 30000000000 },
                    { item: 'Makanan', value: 20000000000 }
                ],
                imports: [
                    { item: 'Elektronik', value: 40000000000 },
                    { item: 'Mesin', value: 30000000000 },
                    { item: 'Minyak', value: 20000000000 },
                    { item: 'Bahan kimia', value: 15000000000 }
                ],
                tradeBalance: -10000000000,
                naturalResources: ['Batu bara', 'Tembaga', 'Emas', 'Kayu', 'Gas'],
                economicRanking: 23,
                internetPenetration: 90,
                mobilePenetration: 96,
                electricityAccess: 100,
                roadLength: 400000,
                railwayLength: 19000,
                airports: 100,
                seaports: 10,
                healthcareAccess: 85,
                educationIndex: 0.80,
                nationalMotto: 'Tuhan, Kehormatan, Tanah Air',
                nationalAnthem: 'Mazurek Dąbrowskiego',
                nationalAnimal: 'Elang Putih',
                nationalFlower: 'Bunga Poppy',
                nationalCuisine: ['Pierogi', 'Bigos', 'Zurek', 'Kotlet Schabowy', 'Paczki'],
                culturalHeritage: ['Warsaw', 'Krakow', 'Gdansk', 'Auschwitz'],
                publicHolidays: ['Hari Kemerdekaan', 'Hari Konstitusi', 'Paskah', 'Christmas'],
                socialRanking: 75,
                climate: 'Kontinental',
                averageTemperature: 8,
                averageRainfall: 600,
                forestArea: 30,
                protectedAreas: 15,
                biodiversityRank: 20,
                carbonEmissions: 7.5,
                environmentalIndex: 52,
                riskScore: 25,
                politicalStability: 70,
                crimeIndex: 20,
                militarySpending: 2.0,
                peaceIndex: 30,
                terrorismIndex: 10,
                refugeePopulation: 100000,
                opportunityScore: 72,
                easeOfDoingBusiness: 75,
                innovationIndex: 60,
                startupEcosystem: 65,
                investmentScore: 70,
                talentPool: 80,
                marketSize: 80,
                infrastructureQuality: 78,
                internetSpeed: 45,
                digitalAdoption: 80,
                techEcosystem: 70,
                aiReadiness: 60,
                startups: 1500,
                phoneCode: '+48',
                tld: '.pl',
                isoCode: 'POL',
                isoCode2: 'PL',
                drivingSide: 'right',
                tags: ['negara', 'eropan-tengah', 'ue', 'nato', 'otomotif']
            }
        },
        // ==========================================================
        // 🇨🇿 CEKO
        // ==========================================================
        {
            text: 'Ceko - Negara di Eropa Tengah dengan industri maju dan Praha yang indah. Ibu kota: Praha. Populasi: 10.5 juta jiwa. Mata uang: Koruna (CZK). Bahasa: Ceko. Sistem pemerintahan: Republik Parlementer. Anggota UE dan NATO. Negara dengan arsitektur indah, bir terbaik dunia, dan sejarah panjang. Praha salah satu kota terindah di Eropa. Pusat manufaktur dan pariwisata Eropa.',
            metadata: {
                category: 'country',
                region: 'eropan-tengah',
                name: 'Ceko',
                officialName: 'Republik Ceko',
                shortName: 'CZE',
                capital: 'Praha',
                capitalCoordinates: { lat: 50.0755, lng: 14.4378 },
                largestCity: 'Praha',
                demonym: 'Ceko',
                subregion: 'Central Europe',
                area: 78867,
                areaRank: 115,
                coastline: 0,
                highestPoint: 'Snezka',
                highestElevation: 1603,
                lowestPoint: 'Elbe River',
                lowestElevation: 115,
                landBorders: ['Jerman', 'Polandia', 'Austria', 'Slovakia'],
                coordinates: { lat: 49.75, lng: 15.5 },
                timezone: ['Waktu Eropa Tengah'],
                utcOffset: ['+1'],
                population: 10500000,
                populationRank: 85,
                populationDensity: 133,
                populationGrowth: 0.0,
                medianAge: 43.0,
                lifeExpectancy: 79.0,
                fertilityRate: 1.5,
                urbanization: 74,
                ethnicGroups: [
                    { name: 'Ceko', percentage: 90.0 },
                    { name: 'Slovakia', percentage: 2.0 },
                    { name: 'Lainnya', percentage: 8.0 }
                ],
                religions: [
                    { name: 'Tidak beragama', percentage: 55.0 },
                    { name: 'Kristen Katolik', percentage: 20.0 },
                    { name: 'Kristen Protestan', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 20.0 }
                ],
                languages: [
                    { name: 'Ceko', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 30 },
                    { name: 'Jerman', percentage: 10 }
                ],
                literacyRate: 99,
                governmentType: 'Republik Parlementer',
                independenceDay: '1993-01-01',
                nationalHoliday: '28 Oktober',
                legalSystem: 'Civil Law',
                constitution: '1992',
                administrativeDivisions: 13,
                memberships: ['PBB', 'UE', 'NATO', 'OECD', 'WTO'],
                giniCoefficient: 25.0,
                hdi: 0.900,
                hdiRank: 27,
                corruptionIndex: 59,
                currency: 'Koruna',
                currencyCode: 'CZK',
                gdp: 350000000000,
                gdpPerCapita: 33300,
                gdpPpp: 550000000000,
                gdpGrowth: 2.5,
                inflation: 4.0,
                unemployment: 2.0,
                povertyRate: 10.0,
                mainIndustries: ['Otomotif', 'Mesin', 'Elektronik', 'Bir', 'Pariwisata'],
                exports: [
                    { item: 'Otomotif', value: 40000000000 },
                    { item: 'Mesin', value: 30000000000 },
                    { item: 'Elektronik', value: 20000000000 },
                    { item: 'Bir', value: 10000000000 }
                ],
                imports: [
                    { item: 'Elektronik', value: 30000000000 },
                    { item: 'Mesin', value: 25000000000 },
                    { item: 'Minyak', value: 15000000000 },
                    { item: 'Bahan kimia', value: 10000000000 }
                ],
                tradeBalance: 5000000000,
                naturalResources: ['Batu bara', 'Kayu', 'Air', 'Mineral'],
                economicRanking: 43,
                internetPenetration: 92,
                mobilePenetration: 96,
                electricityAccess: 100,
                roadLength: 55000,
                railwayLength: 9500,
                airports: 50,
                seaports: 0,
                healthcareAccess: 88,
                educationIndex: 0.82,
                nationalMotto: 'Kebenaran menang',
                nationalAnthem: 'Kde domov můj?',
                nationalAnimal: 'Singa Ceko',
                nationalFlower: 'Bunga Linden',
                nationalCuisine: ['Knödel', 'Goulash', 'Svíčková', 'Pilsner', 'Trdelník'],
                culturalHeritage: ['Prague', 'Cesky Krumlov', 'Karlovy Vary', 'Brno'],
                publicHolidays: ['Hari Kemerdekaan', 'Hari Persatuan', 'Paskah', 'Christmas'],
                socialRanking: 80,
                climate: 'Kontinental',
                averageTemperature: 8,
                averageRainfall: 600,
                forestArea: 34,
                protectedAreas: 15,
                biodiversityRank: 30,
                carbonEmissions: 9.0,
                environmentalIndex: 55,
                riskScore: 20,
                politicalStability: 75,
                crimeIndex: 18,
                militarySpending: 1.5,
                peaceIndex: 25,
                terrorismIndex: 8,
                refugeePopulation: 1000,
                opportunityScore: 72,
                easeOfDoingBusiness: 75,
                innovationIndex: 65,
                startupEcosystem: 70,
                investmentScore: 72,
                talentPool: 78,
                marketSize: 75,
                infrastructureQuality: 82,
                internetSpeed: 45,
                digitalAdoption: 82,
                techEcosystem: 72,
                aiReadiness: 62,
                startups: 1000,
                phoneCode: '+420',
                tld: '.cz',
                isoCode: 'CZE',
                isoCode2: 'CZ',
                drivingSide: 'right',
                tags: ['negara', 'eropan-tengah', 'ue', 'nato', 'bir']
            }
        },
        // ==========================================================
        // 🇭🇺 HUNGARIA
        // ==========================================================
        {
            text: 'Hungaria - Negara di Eropa Tengah dengan Budapest yang ikonik. Ibu kota: Budapest. Populasi: 9.6 juta jiwa. Mata uang: Forint (HUF). Bahasa: Hungaria. Sistem pemerintahan: Republik Parlementer. Anggota UE dan NATO. Negara dengan arsitektur Art Nouveau, pemandian air panas, dan Danube yang memukau. Budapest salah satu kota terindah di Eropa.',
            metadata: {
                category: 'country',
                region: 'eropan-tengah',
                name: 'Hungaria',
                officialName: 'Hungaria',
                shortName: 'HUN',
                capital: 'Budapest',
                capitalCoordinates: { lat: 47.4979, lng: 19.0402 },
                largestCity: 'Budapest',
                demonym: 'Hungaria',
                subregion: 'Central Europe',
                area: 93028,
                areaRank: 108,
                coastline: 0,
                highestPoint: 'Kekes',
                highestElevation: 1014,
                lowestPoint: 'Tisza River',
                lowestElevation: 75,
                landBorders: ['Austria', 'Slovakia', 'Ukraina', 'Rumania', 'Serbia', 'Kroasia', 'Slovenia'],
                coordinates: { lat: 47.0, lng: 20.0 },
                timezone: ['Waktu Eropa Tengah'],
                utcOffset: ['+1'],
                population: 9600000,
                populationRank: 91,
                populationDensity: 103,
                populationGrowth: -0.2,
                medianAge: 43.0,
                lifeExpectancy: 76.0,
                fertilityRate: 1.3,
                urbanization: 71,
                ethnicGroups: [
                    { name: 'Hungaria', percentage: 90.0 },
                    { name: 'Roma', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 5.0 }
                ],
                religions: [
                    { name: 'Kristen Katolik', percentage: 40.0 },
                    { name: 'Kristen Protestan', percentage: 15.0 },
                    { name: 'Tidak beragama', percentage: 35.0 },
                    { name: 'Lainnya', percentage: 10.0 }
                ],
                languages: [
                    { name: 'Hungaria', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 25 },
                    { name: 'Jerman', percentage: 10 }
                ],
                literacyRate: 99,
                governmentType: 'Republik Parlementer',
                independenceDay: '1989-10-23',
                nationalHoliday: '15 Maret',
                legalSystem: 'Civil Law',
                constitution: '2011',
                administrativeDivisions: 19,
                memberships: ['PBB', 'UE', 'NATO', 'OECD', 'WTO'],
                giniCoefficient: 28.0,
                hdi: 0.854,
                hdiRank: 40,
                corruptionIndex: 46,
                currency: 'Forint',
                currencyCode: 'HUF',
                gdp: 200000000000,
                gdpPerCapita: 20800,
                gdpPpp: 450000000000,
                gdpGrowth: 3.0,
                inflation: 5.0,
                unemployment: 3.5,
                povertyRate: 12.0,
                mainIndustries: ['Otomotif', 'Elektronik', 'Farmasi', 'Pariwisata', 'Pertanian'],
                exports: [
                    { item: 'Otomotif', value: 30000000000 },
                    { item: 'Elektronik', value: 20000000000 },
                    { item: 'Farmasi', value: 15000000000 },
                    { item: 'Pertanian', value: 10000000000 }
                ],
                imports: [
                    { item: 'Elektronik', value: 25000000000 },
                    { item: 'Mesin', value: 20000000000 },
                    { item: 'Minyak', value: 15000000000 },
                    { item: 'Bahan kimia', value: 10000000000 }
                ],
                tradeBalance: -5000000000,
                naturalResources: ['Batu bara', 'Gas', 'Kayu', 'Air', 'Tanah subur'],
                economicRanking: 55,
                internetPenetration: 88,
                mobilePenetration: 94,
                electricityAccess: 100,
                roadLength: 200000,
                railwayLength: 8000,
                airports: 50,
                seaports: 0,
                healthcareAccess: 82,
                educationIndex: 0.76,
                nationalMotto: 'Tuhan memberkati Hungaria',
                nationalAnthem: 'Himnusz',
                nationalAnimal: 'Turul',
                nationalFlower: 'Bunga Tulip',
                nationalCuisine: ['Goulash', 'Langos', 'Chicken Paprikash', 'Dobos Cake', 'Kürtőskalács'],
                culturalHeritage: ['Budapest', 'Eger', 'Pécs', 'Lake Balaton'],
                publicHolidays: ['Hari Kemerdekaan', 'Hari Revolusi', 'Paskah', 'Christmas'],
                socialRanking: 72,
                climate: 'Kontinental',
                averageTemperature: 10,
                averageRainfall: 500,
                forestArea: 22,
                protectedAreas: 10,
                biodiversityRank: 30,
                carbonEmissions: 5.0,
                environmentalIndex: 50,
                riskScore: 25,
                politicalStability: 65,
                crimeIndex: 22,
                militarySpending: 1.5,
                peaceIndex: 30,
                terrorismIndex: 10,
                refugeePopulation: 1000,
                opportunityScore: 65,
                easeOfDoingBusiness: 68,
                innovationIndex: 55,
                startupEcosystem: 60,
                investmentScore: 62,
                talentPool: 72,
                marketSize: 70,
                infrastructureQuality: 72,
                internetSpeed: 40,
                digitalAdoption: 75,
                techEcosystem: 62,
                aiReadiness: 52,
                startups: 400,
                phoneCode: '+36',
                tld: '.hu',
                isoCode: 'HUN',
                isoCode2: 'HU',
                drivingSide: 'right',
                tags: ['negara', 'eropan-tengah', 'ue', 'nato', 'pemandian']
            }
        },
        // ==========================================================
        // 🇸🇰 SLOWAKIA
        // ==========================================================
        {
            text: 'Slowakia - Negara di Eropa Tengah dengan pegunungan Tatra. Ibu kota: Bratislava. Populasi: 5.4 juta jiwa. Mata uang: Euro (EUR). Bahasa: Slowakia. Sistem pemerintahan: Republik Parlementer. Anggota UE dan NATO. Negara dengan pegunungan Tatra yang indah dan kastil-kastil megah. Pusat manufaktur otomotif Eropa. Bratislava kota yang indah di tepi Danube.',
            metadata: {
                category: 'country',
                region: 'eropan-tengah',
                name: 'Slowakia',
                officialName: 'Republik Slowakia',
                shortName: 'SVK',
                capital: 'Bratislava',
                capitalCoordinates: { lat: 48.1486, lng: 17.1077 },
                largestCity: 'Bratislava',
                demonym: 'Slowakia',
                subregion: 'Central Europe',
                area: 49035,
                areaRank: 127,
                coastline: 0,
                highestPoint: 'Gerlachovsky',
                highestElevation: 2655,
                lowestPoint: 'Bodrog River',
                lowestElevation: 94,
                landBorders: ['Polandia', 'Ukraina', 'Hungaria', 'Austria', 'Ceko'],
                coordinates: { lat: 48.67, lng: 19.5 },
                timezone: ['Waktu Eropa Tengah'],
                utcOffset: ['+1'],
                population: 5400000,
                populationRank: 116,
                populationDensity: 110,
                populationGrowth: 0.0,
                medianAge: 41.0,
                lifeExpectancy: 77.0,
                fertilityRate: 1.3,
                urbanization: 53,
                ethnicGroups: [
                    { name: 'Slowakia', percentage: 80.0 },
                    { name: 'Hungaria', percentage: 10.0 },
                    { name: 'Roma', percentage: 3.0 },
                    { name: 'Lainnya', percentage: 7.0 }
                ],
                religions: [
                    { name: 'Kristen Katolik', percentage: 62.0 },
                    { name: 'Kristen Protestan', percentage: 10.0 },
                    { name: 'Tidak beragama', percentage: 20.0 },
                    { name: 'Lainnya', percentage: 8.0 }
                ],
                languages: [
                    { name: 'Slowakia', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 25 },
                    { name: 'Jerman', percentage: 10 }
                ],
                literacyRate: 99,
                governmentType: 'Republik Parlementer',
                independenceDay: '1993-01-01',
                nationalHoliday: '1 Januari',
                legalSystem: 'Civil Law',
                constitution: '1992',
                administrativeDivisions: 8,
                memberships: ['PBB', 'UE', 'NATO', 'OECD', 'WTO'],
                giniCoefficient: 25.0,
                hdi: 0.860,
                hdiRank: 36,
                corruptionIndex: 49,
                currency: 'Euro',
                currencyCode: 'EUR',
                gdp: 130000000000,
                gdpPerCapita: 24000,
                gdpPpp: 220000000000,
                gdpGrowth: 2.5,
                inflation: 4.0,
                unemployment: 4.0,
                povertyRate: 12.0,
                mainIndustries: ['Otomotif', 'Elektronik', 'Manufaktur', 'Pariwisata', 'Pertanian'],
                exports: [
                    { item: 'Otomotif', value: 30000000000 },
                    { item: 'Elektronik', value: 20000000000 },
                    { item: 'Mesin', value: 15000000000 },
                    { item: 'Pertanian', value: 10000000000 }
                ],
                imports: [
                    { item: 'Elektronik', value: 25000000000 },
                    { item: 'Mesin', value: 20000000000 },
                    { item: 'Minyak', value: 15000000000 },
                    { item: 'Bahan kimia', value: 10000000000 }
                ],
                tradeBalance: 5000000000,
                naturalResources: ['Kayu', 'Mineral', 'Air', 'Gas'],
                economicRanking: 55,
                internetPenetration: 88,
                mobilePenetration: 94,
                electricityAccess: 100,
                roadLength: 40000,
                railwayLength: 3600,
                airports: 20,
                seaports: 0,
                healthcareAccess: 82,
                educationIndex: 0.76,
                nationalMotto: 'Kebebasan, Persatuan, Kemakmuran',
                nationalAnthem: 'Nad Tatrou sa blýska',
                nationalAnimal: 'Beruang',
                nationalFlower: 'Bunga Mawar',
                nationalCuisine: ['Bryndzové Halušky', 'Goulash', 'Kapustnica', 'Kielbasa', 'Trdelník'],
                culturalHeritage: ['Bratislava', 'Kosice', 'High Tatras', 'Banska Stiavnica'],
                publicHolidays: ['Hari Kemerdekaan', 'Hari Persatuan', 'Paskah', 'Christmas'],
                socialRanking: 72,
                climate: 'Kontinental',
                averageTemperature: 9,
                averageRainfall: 600,
                forestArea: 40,
                protectedAreas: 15,
                biodiversityRank: 25,
                carbonEmissions: 6.0,
                environmentalIndex: 52,
                riskScore: 20,
                politicalStability: 72,
                crimeIndex: 20,
                militarySpending: 1.5,
                peaceIndex: 28,
                terrorismIndex: 8,
                refugeePopulation: 500,
                opportunityScore: 68,
                easeOfDoingBusiness: 72,
                innovationIndex: 55,
                startupEcosystem: 60,
                investmentScore: 65,
                talentPool: 72,
                marketSize: 68,
                infrastructureQuality: 72,
                internetSpeed: 40,
                digitalAdoption: 75,
                techEcosystem: 62,
                aiReadiness: 52,
                startups: 200,
                phoneCode: '+421',
                tld: '.sk',
                isoCode: 'SVK',
                isoCode2: 'SK',
                drivingSide: 'right',
                tags: ['negara', 'eropan-tengah', 'ue', 'nato', 'otomotif']
            }
        },
        // ==========================================================
        // 🇦🇹 AUSTRIA
        // ==========================================================
        {
            text: 'Austria - Negara di Eropa Tengah dengan Alpen dan musik klasik. Ibu kota: Wina. Populasi: 9 juta jiwa. Mata uang: Euro (EUR). Bahasa: Jerman. Sistem pemerintahan: Republik Federal Parlementer. Anggota UE. Negara dengan musik klasik, arsitektur indah, dan alam pegunungan. Rumah bagi Mozart, Beethoven, dan Strauss. Wina kota dengan kafe-kafe klasik dan istana-istana megah. Negara dengan kualitas hidup tertinggi di Eropa.',
            metadata: {
                category: 'country',
                region: 'eropan-tengah',
                name: 'Austria',
                officialName: 'Republik Austria',
                shortName: 'AUT',
                capital: 'Wina',
                capitalCoordinates: { lat: 48.2082, lng: 16.3738 },
                largestCity: 'Wina',
                demonym: 'Austria',
                subregion: 'Central Europe',
                area: 83879,
                areaRank: 113,
                coastline: 0,
                highestPoint: 'Grossglockner',
                highestElevation: 3798,
                lowestPoint: 'Lake Neusiedl',
                lowestElevation: 115,
                landBorders: ['Jerman', 'Ceko', 'Slovakia', 'Hungaria', 'Slovenia', 'Italia', 'Swiss', 'Liechtenstein'],
                coordinates: { lat: 47.33, lng: 13.33 },
                timezone: ['Waktu Eropa Tengah'],
                utcOffset: ['+1'],
                population: 9000000,
                populationRank: 95,
                populationDensity: 107,
                populationGrowth: 0.3,
                medianAge: 44.5,
                lifeExpectancy: 81.8,
                fertilityRate: 1.4,
                urbanization: 58,
                ethnicGroups: [
                    { name: 'Austria', percentage: 80.0 },
                    { name: 'Jerman', percentage: 5.0 },
                    { name: 'Turki', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 10.0 }
                ],
                religions: [
                    { name: 'Kristen Katolik', percentage: 60.0 },
                    { name: 'Kristen Protestan', percentage: 5.0 },
                    { name: 'Tidak beragama', percentage: 25.0 },
                    { name: 'Islam', percentage: 8.0 }
                ],
                languages: [
                    { name: 'Jerman', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 50 },
                    { name: 'Prancis', percentage: 10 }
                ],
                literacyRate: 99,
                governmentType: 'Republik Federal Parlementer',
                independenceDay: '1955-10-26',
                nationalHoliday: '26 Oktober',
                legalSystem: 'Civil Law',
                constitution: '1920',
                administrativeDivisions: 9,
                memberships: ['PBB', 'UE', 'OECD', 'WTO'],
                giniCoefficient: 27.0,
                hdi: 0.916,
                hdiRank: 18,
                corruptionIndex: 75,
                currency: 'Euro',
                currencyCode: 'EUR',
                gdp: 500000000000,
                gdpPerCapita: 55500,
                gdpPpp: 600000000000,
                gdpGrowth: 1.5,
                inflation: 2.5,
                unemployment: 4.5,
                povertyRate: 12.0,
                mainIndustries: ['Pariwisata', 'Manufaktur', 'Keuangan', 'Teknologi', 'Pertanian'],
                exports: [
                    { item: 'Mesin', value: 80000000000 },
                    { item: 'Pariwisata', value: 50000000000 },
                    { item: 'Elektronik', value: 40000000000 },
                    { item: 'Kimia', value: 30000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 60000000000 },
                    { item: 'Elektronik', value: 50000000000 },
                    { item: 'Minyak', value: 30000000000 },
                    { item: 'Makanan', value: 20000000000 }
                ],
                tradeBalance: 10000000000,
                naturalResources: ['Kayu', 'Air', 'Mineral', 'Energi'],
                economicRanking: 28,
                internetPenetration: 90,
                mobilePenetration: 96,
                electricityAccess: 100,
                roadLength: 120000,
                railwayLength: 6000,
                airports: 50,
                seaports: 0,
                healthcareAccess: 92,
                educationIndex: 0.82,
                nationalMotto: 'Austria adalah untuk semua',
                nationalAnthem: 'Land der Berge, Land am Strome',
                nationalAnimal: 'Elang',
                nationalFlower: 'Edelweiss',
                nationalCuisine: ['Schnitzel', 'Apfelstrudel', 'Tafelspitz', 'Sachertorte', 'Kaiserschmarrn'],
                culturalHeritage: ['Vienna', 'Salzburg', 'Innsbruck', 'Hallstatt'],
                publicHolidays: ['Hari Nasional', 'Paskah', 'Christmas', 'Tahun Baru'],
                socialRanking: 85,
                climate: 'Kontinental',
                averageTemperature: 8,
                averageRainfall: 800,
                forestArea: 47,
                protectedAreas: 25,
                biodiversityRank: 20,
                carbonEmissions: 6.0,
                environmentalIndex: 60,
                riskScore: 15,
                politicalStability: 85,
                crimeIndex: 15,
                militarySpending: 0.8,
                peaceIndex: 20,
                terrorismIndex: 8,
                refugeePopulation: 50000,
                opportunityScore: 78,
                easeOfDoingBusiness: 78,
                innovationIndex: 72,
                startupEcosystem: 70,
                investmentScore: 75,
                talentPool: 82,
                marketSize: 78,
                infrastructureQuality: 88,
                internetSpeed: 50,
                digitalAdoption: 82,
                techEcosystem: 72,
                aiReadiness: 65,
                startups: 500,
                phoneCode: '+43',
                tld: '.at',
                isoCode: 'AUT',
                isoCode2: 'AT',
                drivingSide: 'right',
                tags: ['negara', 'eropan-tengah', 'alpen', 'musik', 'budaya']
            }
        },
        // ==========================================================
        // 🇨🇭 SWISS
        // ==========================================================
        {
            text: 'Swiss - Negara di Eropa Tengah dengan netralitas dan keuangan global. Ibu kota: Bern. Populasi: 8.7 juta jiwa. Mata uang: Franc Swiss (CHF). Bahasa: Jerman, Prancis, Italia, Romansh. Sistem pemerintahan: Republik Federal. Negara dengan kualitas hidup tertinggi di dunia. Rumah bagi cokelat, jam, dan Alpen Swiss. Pusat perbankan dan keuangan global. Negara dengan inovasi dan pendidikan terbaik. Salah satu negara paling stabil dan makmur di dunia.',
            metadata: {
                category: 'country',
                region: 'eropan-tengah',
                name: 'Swiss',
                officialName: 'Konfederasi Swiss',
                shortName: 'CHE',
                capital: 'Bern',
                capitalCoordinates: { lat: 46.9480, lng: 7.4474 },
                largestCity: 'Zurich',
                demonym: 'Swiss',
                subregion: 'Central Europe',
                area: 41285,
                areaRank: 132,
                coastline: 0,
                highestPoint: 'Dufourspitze',
                highestElevation: 4634,
                lowestPoint: 'Lake Maggiore',
                lowestElevation: 195,
                landBorders: ['Prancis', 'Jerman', 'Italia', 'Austria', 'Liechtenstein'],
                coordinates: { lat: 46.8, lng: 8.2 },
                timezone: ['Waktu Eropa Tengah'],
                utcOffset: ['+1'],
                population: 8700000,
                populationRank: 100,
                populationDensity: 210,
                populationGrowth: 0.7,
                medianAge: 42.5,
                lifeExpectancy: 83.6,
                fertilityRate: 1.5,
                urbanization: 74,
                ethnicGroups: [
                    { name: 'Swiss', percentage: 70.0 },
                    { name: 'Italia', percentage: 10.0 },
                    { name: 'Jerman', percentage: 8.0 },
                    { name: 'Prancis', percentage: 5.0 }
                ],
                religions: [
                    { name: 'Kristen Katolik', percentage: 35.0 },
                    { name: 'Kristen Protestan', percentage: 25.0 },
                    { name: 'Tidak beragama', percentage: 30.0 },
                    { name: 'Islam', percentage: 5.0 }
                ],
                languages: [
                    { name: 'Jerman', percentage: 63, official: true },
                    { name: 'Prancis', percentage: 23, official: true },
                    { name: 'Italia', percentage: 8, official: true },
                    { name: 'Romansh', percentage: 0.5, official: true }
                ],
                literacyRate: 99,
                governmentType: 'Republik Federal',
                independenceDay: '1291-08-01',
                nationalHoliday: '1 Agustus',
                legalSystem: 'Civil Law',
                constitution: '1848',
                administrativeDivisions: 26,
                memberships: ['PBB', 'EFTA', 'OECD', 'WTO'],
                giniCoefficient: 33.1,
                hdi: 0.962,
                hdiRank: 2,
                corruptionIndex: 85,
                currency: 'Franc Swiss',
                currencyCode: 'CHF',
                gdp: 900000000000,
                gdpPerCapita: 103000,
                gdpPpp: 800000000000,
                gdpGrowth: 1.5,
                inflation: 2.0,
                unemployment: 2.0,
                povertyRate: 8.0,
                mainIndustries: ['Keuangan', 'Perbankan', 'Farmasi', 'Teknologi', 'Pariwisata'],
                exports: [
                    { item: 'Keuangan', value: 200000000000 },
                    { item: 'Farmasi', value: 150000000000 },
                    { item: 'Teknologi', value: 100000000000 },
                    { item: 'Cokelat', value: 50000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 80000000000 },
                    { item: 'Elektronik', value: 60000000000 },
                    { item: 'Makanan', value: 40000000000 },
                    { item: 'Minyak', value: 30000000000 }
                ],
                tradeBalance: 50000000000,
                naturalResources: ['Air', 'Kayu', 'Garam', 'Mineral'],
                economicRanking: 20,
                internetPenetration: 95,
                mobilePenetration: 98,
                electricityAccess: 100,
                roadLength: 75000,
                railwayLength: 5000,
                airports: 50,
                seaports: 0,
                healthcareAccess: 98,
                educationIndex: 0.88,
                nationalMotto: 'Satu untuk semua, semua untuk satu',
                nationalAnthem: 'Schweizerpsalm',
                nationalAnimal: 'Sapi',
                nationalFlower: 'Edelweiss',
                nationalCuisine: ['Cheese Fondue', 'Rösti', 'Chocolate', 'Raclette', 'Muesli'],
                culturalHeritage: ['Matterhorn', 'Geneva', 'Zurich', 'Interlaken'],
                publicHolidays: ['Hari Nasional', 'Paskah', 'Christmas', 'Tahun Baru'],
                socialRanking: 95,
                climate: 'Beragam',
                averageTemperature: 7,
                averageRainfall: 1000,
                forestArea: 32,
                protectedAreas: 20,
                biodiversityRank: 20,
                carbonEmissions: 4.0,
                environmentalIndex: 65,
                riskScore: 10,
                politicalStability: 95,
                crimeIndex: 10,
                militarySpending: 0.7,
                peaceIndex: 15,
                terrorismIndex: 5,
                refugeePopulation: 50000,
                opportunityScore: 90,
                easeOfDoingBusiness: 88,
                innovationIndex: 88,
                startupEcosystem: 85,
                investmentScore: 92,
                talentPool: 90,
                marketSize: 82,
                infrastructureQuality: 95,
                internetSpeed: 60,
                digitalAdoption: 92,
                techEcosystem: 88,
                aiReadiness: 82,
                startups: 3000,
                phoneCode: '+41',
                tld: '.ch',
                isoCode: 'CHE',
                isoCode2: 'CH',
                drivingSide: 'right',
                tags: ['negara', 'eropan-tengah', 'perbankan', 'cokelat', 'jam']
            }
        }
    ];

    // ============================================================
    // PROSES DATA KE REGISTER
    // ============================================================
    for (let i = 0; i < data.length; i++) {
        window.__DATA_REGISTER.push(data[i]);
    }

    // ============================================================
    // LOGGER
    // ============================================================
    if (window.InternalLogger) {
        window.InternalLogger.info('CountryEropanTengah', '✅ Loaded ' + data.length + ' countries (SUPER LENGKAP - 6 NEGARA!)');
    }

})();