/* ============================================================
   📁 dataries/country/eropan-barat.js
   📌 DATA NEGARA EROPA BARAT
   🔥 8 NEGARA — Jerman, Prancis, Inggris, Belanda, Belgia, Swiss, Austria, Irlandia
   🔥 DATA SUPER LENGKAP — 100+ FIELD PER NEGARA!
   ============================================================ */

(function() {
    'use strict';
    
    if (window.__CountryEropanBaratLoaded) return;
    window.__CountryEropanBaratLoaded = true;
    
    window.__DATA_REGISTER = window.__DATA_REGISTER || [];
    
    const data = [
        // ==========================================================
        // 🇩🇪 JERMAN
        // ==========================================================
        {
            text: 'Jerman - Negara terbesar di Eropa Barat dengan ekonomi terkuat di Eropa. Ibu kota: Berlin. Populasi: 84 juta jiwa. Mata uang: Euro (EUR). Bahasa: Jerman. Sistem pemerintahan: Republik Federal Parlementer. Anggota G7, G20, dan UE. Negara dengan industri otomotif, mesin, dan kimia terkemuka dunia. Rumah bagi Mercedes, BMW, Volkswagen, dan Siemens. Negara dengan sejarah panjang dan budaya yang kaya.',
            metadata: {
                category: 'country',
                region: 'eropan-barat',
                name: 'Jerman',
                officialName: 'Republik Federal Jerman',
                shortName: 'DEU',
                capital: 'Berlin',
                capitalCoordinates: { lat: 52.5200, lng: 13.4050 },
                largestCity: 'Berlin',
                demonym: 'Jerman',
                subregion: 'Western Europe',
                area: 357022,
                areaRank: 63,
                coastline: 2389,
                highestPoint: 'Zugspitze',
                highestElevation: 2962,
                lowestPoint: 'Neuendorf bei Wilster',
                lowestElevation: -3,
                landBorders: ['Denmark', 'Polandia', 'Ceko', 'Austria', 'Swiss', 'Prancis', 'Luxembourg', 'Belgia', 'Belanda'],
                coordinates: { lat: 51.0, lng: 10.0 },
                timezone: ['Waktu Eropa Tengah'],
                utcOffset: ['+1'],
                population: 84000000,
                populationRank: 19,
                populationDensity: 235,
                populationGrowth: 0.0,
                medianAge: 47.8,
                lifeExpectancy: 81.3,
                fertilityRate: 1.6,
                urbanization: 77,
                ethnicGroups: [
                    { name: 'Jerman', percentage: 75.0 },
                    { name: 'Turki', percentage: 4.0 },
                    { name: 'Polandia', percentage: 2.0 },
                    { name: 'Lainnya', percentage: 19.0 }
                ],
                religions: [
                    { name: 'Kristen Katolik', percentage: 27.0 },
                    { name: 'Kristen Protestan', percentage: 25.0 },
                    { name: 'Tidak beragama', percentage: 38.0 },
                    { name: 'Islam', percentage: 5.0 }
                ],
                languages: [
                    { name: 'Jerman', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 60 },
                    { name: 'Prancis', percentage: 15 }
                ],
                literacyRate: 99,
                governmentType: 'Republik Federal Parlementer',
                independenceDay: '1990-10-03',
                nationalHoliday: '3 Oktober',
                legalSystem: 'Civil Law',
                constitution: '1949',
                administrativeDivisions: 16,
                memberships: ['PBB', 'UE', 'NATO', 'G7', 'G20', 'OECD'],
                giniCoefficient: 31.7,
                hdi: 0.950,
                hdiRank: 6,
                corruptionIndex: 80,
                currency: 'Euro',
                currencyCode: 'EUR',
                gdp: 4500000000000,
                gdpPerCapita: 53500,
                gdpPpp: 5300000000000,
                gdpGrowth: 1.5,
                inflation: 2.5,
                unemployment: 3.0,
                povertyRate: 12.0,
                mainIndustries: ['Otomotif', 'Mesin', 'Kimia', 'Elektronik', 'Keuangan'],
                exports: [
                    { item: 'Otomotif', value: 300000000000 },
                    { item: 'Mesin', value: 250000000000 },
                    { item: 'Kimia', value: 150000000000 },
                    { item: 'Elektronik', value: 100000000000 }
                ],
                imports: [
                    { item: 'Elektronik', value: 200000000000 },
                    { item: 'Mesin', value: 150000000000 },
                    { item: 'Minyak', value: 100000000000 },
                    { item: 'Makanan', value: 80000000000 }
                ],
                tradeBalance: 300000000000,
                naturalResources: ['Batu bara', 'Kayu', 'Air', 'Gas', 'Garam'],
                economicRanking: 4,
                internetPenetration: 95,
                mobilePenetration: 98,
                electricityAccess: 100,
                roadLength: 830000,
                railwayLength: 33000,
                airports: 300,
                seaports: 50,
                healthcareAccess: 95,
                educationIndex: 0.88,
                nationalMotto: 'Persatuan, Keadilan, Kebebasan',
                nationalAnthem: 'Das Lied der Deutschen',
                nationalAnimal: 'Elang',
                nationalFlower: 'Bunga Jagung',
                nationalCuisine: ['Sausages', 'Sauerkraut', 'Brezel', 'Schnitzel', 'Black Forest Cake'],
                culturalHeritage: ['Berlin', 'Munich', 'Cologne Cathedral', 'Neuschwanstein Castle'],
                publicHolidays: ['Hari Persatuan', 'Paskah', 'Christmas', 'Tahun Baru'],
                socialRanking: 88,
                climate: 'Kontinental',
                averageTemperature: 9,
                averageRainfall: 700,
                forestArea: 32,
                protectedAreas: 15,
                biodiversityRank: 25,
                carbonEmissions: 8.5,
                environmentalIndex: 60,
                riskScore: 15,
                politicalStability: 85,
                crimeIndex: 15,
                militarySpending: 1.5,
                peaceIndex: 20,
                terrorismIndex: 8,
                refugeePopulation: 1000000,
                opportunityScore: 85,
                easeOfDoingBusiness: 82,
                innovationIndex: 85,
                startupEcosystem: 85,
                investmentScore: 85,
                talentPool: 92,
                marketSize: 95,
                infrastructureQuality: 95,
                internetSpeed: 55,
                digitalAdoption: 90,
                techEcosystem: 88,
                aiReadiness: 82,
                startups: 5000,
                phoneCode: '+49',
                tld: '.de',
                isoCode: 'DEU',
                isoCode2: 'DE',
                drivingSide: 'right',
                tags: ['negara', 'eropan-barat', 'ekonomi', 'otomotif', 'ue']
            }
        },
        // ==========================================================
        // 🇫🇷 PRANCIS
        // ==========================================================
        {
            text: 'Prancis - Negara di Eropa Barat dengan budaya dan sejarah kaya. Ibu kota: Paris. Populasi: 68 juta jiwa. Mata uang: Euro (EUR). Bahasa: Prancis. Sistem pemerintahan: Republik Semi-Presidensial. Anggota G7, G20, dan UE. Pusat mode, seni, dan kuliner dunia. Rumah bagi Menara Eiffel, Louvre, dan Riviera Prancis. Negara dengan pengaruh budaya dan diplomatik global.',
            metadata: {
                category: 'country',
                region: 'eropan-barat',
                name: 'Prancis',
                officialName: 'Republik Prancis',
                shortName: 'FRA',
                capital: 'Paris',
                capitalCoordinates: { lat: 48.8566, lng: 2.3522 },
                largestCity: 'Paris',
                demonym: 'Prancis',
                subregion: 'Western Europe',
                area: 640679,
                areaRank: 42,
                coastline: 3427,
                highestPoint: 'Mont Blanc',
                highestElevation: 4808,
                lowestPoint: 'Rhône River Delta',
                lowestElevation: -2,
                landBorders: ['Belgia', 'Luxembourg', 'Jerman', 'Swiss', 'Italia', 'Spanyol', 'Andorra', 'Monako'],
                coordinates: { lat: 46.0, lng: 2.0 },
                timezone: ['Waktu Eropa Tengah'],
                utcOffset: ['+1'],
                population: 68000000,
                populationRank: 20,
                populationDensity: 106,
                populationGrowth: 0.3,
                medianAge: 42.3,
                lifeExpectancy: 82.7,
                fertilityRate: 1.8,
                urbanization: 81,
                ethnicGroups: [
                    { name: 'Prancis', percentage: 85.0 },
                    { name: 'Arab', percentage: 5.0 },
                    { name: 'Afrika', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 5.0 }
                ],
                religions: [
                    { name: 'Kristen Katolik', percentage: 50.0 },
                    { name: 'Tidak beragama', percentage: 35.0 },
                    { name: 'Islam', percentage: 8.0 },
                    { name: 'Lainnya', percentage: 7.0 }
                ],
                languages: [
                    { name: 'Prancis', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 40 },
                    { name: 'Spanyol', percentage: 10 }
                ],
                literacyRate: 99,
                governmentType: 'Republik Semi-Presidensial',
                independenceDay: '1789-07-14',
                nationalHoliday: '14 Juli',
                legalSystem: 'Civil Law',
                constitution: '1958',
                administrativeDivisions: 18,
                memberships: ['PBB', 'UE', 'NATO', 'G7', 'G20', 'OECD'],
                giniCoefficient: 32.4,
                hdi: 0.905,
                hdiRank: 22,
                corruptionIndex: 72,
                currency: 'Euro',
                currencyCode: 'EUR',
                gdp: 3000000000000,
                gdpPerCapita: 44100,
                gdpPpp: 3700000000000,
                gdpGrowth: 1.5,
                inflation: 2.5,
                unemployment: 7.0,
                povertyRate: 14.0,
                mainIndustries: ['Pariwisata', 'Luxury', 'Manufaktur', 'Pertanian', 'Keuangan'],
                exports: [
                    { item: 'Luxury', value: 150000000000 },
                    { item: 'Pariwisata', value: 100000000000 },
                    { item: 'Manufaktur', value: 80000000000 },
                    { item: 'Pertanian', value: 50000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 100000000000 },
                    { item: 'Elektronik', value: 80000000000 },
                    { item: 'Minyak', value: 60000000000 },
                    { item: 'Makanan', value: 50000000000 }
                ],
                tradeBalance: -20000000000,
                naturalResources: ['Gas', 'Kayu', 'Air', 'Tanah subur'],
                economicRanking: 7,
                internetPenetration: 92,
                mobilePenetration: 96,
                electricityAccess: 100,
                roadLength: 1000000,
                railwayLength: 29000,
                airports: 400,
                seaports: 50,
                healthcareAccess: 95,
                educationIndex: 0.82,
                nationalMotto: 'Kebebasan, Kesetaraan, Persaudaraan',
                nationalAnthem: 'La Marseillaise',
                nationalAnimal: 'Rooster',
                nationalFlower: 'Iris',
                nationalCuisine: ['Croissant', 'Baguette', 'Escargots', 'Ratatouille', 'Crème Brûlée'],
                culturalHeritage: ['Eiffel Tower', 'Louvre', 'Versailles', 'Mont Saint-Michel'],
                publicHolidays: ['Hari Bastille', 'Paskah', 'Christmas', 'Tahun Baru'],
                socialRanking: 85,
                climate: 'Beragam',
                averageTemperature: 12,
                averageRainfall: 800,
                forestArea: 31,
                protectedAreas: 15,
                biodiversityRank: 20,
                carbonEmissions: 5.0,
                environmentalIndex: 58,
                riskScore: 18,
                politicalStability: 75,
                crimeIndex: 20,
                militarySpending: 2.0,
                peaceIndex: 28,
                terrorismIndex: 15,
                refugeePopulation: 500000,
                opportunityScore: 80,
                easeOfDoingBusiness: 78,
                innovationIndex: 75,
                startupEcosystem: 80,
                investmentScore: 78,
                talentPool: 88,
                marketSize: 90,
                infrastructureQuality: 88,
                internetSpeed: 50,
                digitalAdoption: 85,
                techEcosystem: 78,
                aiReadiness: 72,
                startups: 4000,
                phoneCode: '+33',
                tld: '.fr',
                isoCode: 'FRA',
                isoCode2: 'FR',
                drivingSide: 'right',
                tags: ['negara', 'eropan-barat', 'budaya', 'mode', 'diplomasi']
            }
        },
        // ==========================================================
        // 🇬🇧 INGGRIS
        // ==========================================================
        {
            text: 'Inggris - Negara di Eropa Barat dengan pengaruh global besar. Ibu kota: London. Populasi: 67 juta jiwa. Mata uang: Pound Sterling (GBP). Bahasa: Inggris. Sistem pemerintahan: Monarki Konstitusional Parlementer. Anggota G7, G20, dan NATO. Pusat keuangan global dan bahasa internasional. Rumah bagi Big Ben, Buckingham Palace, dan Stonehenge. Negara dengan sejarah dan budaya yang sangat kaya.',
            metadata: {
                category: 'country',
                region: 'eropan-barat',
                name: 'Inggris',
                officialName: 'Kerajaan Inggris',
                shortName: 'GBR',
                capital: 'London',
                capitalCoordinates: { lat: 51.5074, lng: -0.1278 },
                largestCity: 'London',
                demonym: 'Inggris',
                subregion: 'Western Europe',
                area: 243610,
                areaRank: 78,
                coastline: 12429,
                highestPoint: 'Ben Nevis',
                highestElevation: 1345,
                lowestPoint: 'Fens',
                lowestElevation: -4,
                landBorders: ['Irlandia'],
                coordinates: { lat: 55.0, lng: -3.0 },
                timezone: ['Waktu Greenwich'],
                utcOffset: ['+0'],
                population: 67000000,
                populationRank: 22,
                populationDensity: 275,
                populationGrowth: 0.5,
                medianAge: 40.5,
                lifeExpectancy: 81.4,
                fertilityRate: 1.6,
                urbanization: 83,
                ethnicGroups: [
                    { name: 'Inggris', percentage: 80.0 },
                    { name: 'Asia Selatan', percentage: 7.0 },
                    { name: 'Afrika', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 8.0 }
                ],
                religions: [
                    { name: 'Kristen', percentage: 50.0 },
                    { name: 'Tidak beragama', percentage: 30.0 },
                    { name: 'Islam', percentage: 5.0 },
                    { name: 'Hindu', percentage: 2.0 }
                ],
                languages: [
                    { name: 'Inggris', percentage: 100, official: true },
                    { name: 'Wales', percentage: 5 },
                    { name: 'Skotlandia', percentage: 3 }
                ],
                literacyRate: 99,
                governmentType: 'Monarki Konstitusional Parlementer',
                independenceDay: '1066-10-14',
                nationalHoliday: '8 Juni',
                legalSystem: 'Common Law',
                constitution: '1215',
                administrativeDivisions: 4,
                memberships: ['PBB', 'G7', 'G20', 'NATO', 'Commonwealth'],
                giniCoefficient: 35.1,
                hdi: 0.932,
                hdiRank: 13,
                corruptionIndex: 78,
                currency: 'Pound Sterling',
                currencyCode: 'GBP',
                gdp: 3400000000000,
                gdpPerCapita: 50700,
                gdpPpp: 3800000000000,
                gdpGrowth: 1.5,
                inflation: 3.0,
                unemployment: 4.0,
                povertyRate: 15.0,
                mainIndustries: ['Keuangan', 'Manufaktur', 'Pariwisata', 'Teknologi', 'Pendidikan'],
                exports: [
                    { item: 'Keuangan', value: 200000000000 },
                    { item: 'Manufaktur', value: 150000000000 },
                    { item: 'Pariwisata', value: 100000000000 },
                    { item: 'Teknologi', value: 80000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 150000000000 },
                    { item: 'Elektronik', value: 100000000000 },
                    { item: 'Minyak', value: 80000000000 },
                    { item: 'Makanan', value: 60000000000 }
                ],
                tradeBalance: -100000000000,
                naturalResources: ['Minyak', 'Gas', 'Batu bara', 'Kayu', 'Air'],
                economicRanking: 6,
                internetPenetration: 95,
                mobilePenetration: 98,
                electricityAccess: 100,
                roadLength: 400000,
                railwayLength: 16000,
                airports: 500,
                seaports: 100,
                healthcareAccess: 95,
                educationIndex: 0.85,
                nationalMotto: 'Tuhan dan Hakku',
                nationalAnthem: 'God Save the King',
                nationalAnimal: 'Singa',
                nationalFlower: 'Mawar',
                nationalCuisine: ['Fish and Chips', 'Sunday Roast', 'Full English Breakfast', 'Pie and Mash', 'Yorkshire Pudding'],
                culturalHeritage: ['Big Ben', 'Buckingham Palace', 'Stonehenge', 'Tower of London'],
                publicHolidays: ['Christmas', 'Boxing Day', 'Easter', 'May Day'],
                socialRanking: 85,
                climate: 'Sedang',
                averageTemperature: 10,
                averageRainfall: 800,
                forestArea: 13,
                protectedAreas: 20,
                biodiversityRank: 15,
                carbonEmissions: 5.0,
                environmentalIndex: 55,
                riskScore: 20,
                politicalStability: 80,
                crimeIndex: 22,
                militarySpending: 2.0,
                peaceIndex: 30,
                terrorismIndex: 15,
                refugeePopulation: 100000,
                opportunityScore: 82,
                easeOfDoingBusiness: 80,
                innovationIndex: 80,
                startupEcosystem: 85,
                investmentScore: 82,
                talentPool: 90,
                marketSize: 90,
                infrastructureQuality: 88,
                internetSpeed: 50,
                digitalAdoption: 88,
                techEcosystem: 85,
                aiReadiness: 78,
                startups: 5000,
                phoneCode: '+44',
                tld: '.uk',
                isoCode: 'GBR',
                isoCode2: 'GB',
                drivingSide: 'left',
                tags: ['negara', 'eropan-barat', 'keuangan', 'bahasa', 'sejarah']
            }
        },
        // ==========================================================
        // 🇳🇱 BELANDA
        // ==========================================================
        {
            text: 'Belanda - Negara di Eropa Barat dengan ekonomi maju dan inovasi tinggi. Ibu kota: Amsterdam. Populasi: 17 juta jiwa. Mata uang: Euro (EUR). Bahasa: Belanda. Sistem pemerintahan: Monarki Konstitusional Parlementer. Anggota UE dan NATO. Negara dengan logistik, perdagangan, dan teknologi terbaik. Rumah bagi kincir angin, bunga tulip, dan kanal-kanal indah.',
            metadata: {
                category: 'country',
                region: 'eropan-barat',
                name: 'Belanda',
                officialName: 'Kerajaan Belanda',
                shortName: 'NLD',
                capital: 'Amsterdam',
                capitalCoordinates: { lat: 52.3676, lng: 4.9041 },
                largestCity: 'Amsterdam',
                demonym: 'Belanda',
                subregion: 'Western Europe',
                area: 41543,
                areaRank: 131,
                coastline: 451,
                highestPoint: 'Vaalserberg',
                highestElevation: 322,
                lowestPoint: 'Zuidplaspolder',
                lowestElevation: -7,
                landBorders: ['Jerman', 'Belgia'],
                coordinates: { lat: 52.5, lng: 5.75 },
                timezone: ['Waktu Eropa Tengah'],
                utcOffset: ['+1'],
                population: 17000000,
                populationRank: 67,
                populationDensity: 409,
                populationGrowth: 0.3,
                medianAge: 43.5,
                lifeExpectancy: 82.0,
                fertilityRate: 1.5,
                urbanization: 92,
                ethnicGroups: [
                    { name: 'Belanda', percentage: 75.0 },
                    { name: 'Turki', percentage: 5.0 },
                    { name: 'Maroko', percentage: 4.0 },
                    { name: 'Lainnya', percentage: 16.0 }
                ],
                religions: [
                    { name: 'Tidak beragama', percentage: 55.0 },
                    { name: 'Kristen Katolik', percentage: 20.0 },
                    { name: 'Kristen Protestan', percentage: 15.0 },
                    { name: 'Islam', percentage: 5.0 }
                ],
                languages: [
                    { name: 'Belanda', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 90 },
                    { name: 'Jerman', percentage: 30 }
                ],
                literacyRate: 99,
                governmentType: 'Monarki Konstitusional Parlementer',
                independenceDay: '1815-03-16',
                nationalHoliday: '27 April',
                legalSystem: 'Civil Law',
                constitution: '1815',
                administrativeDivisions: 12,
                memberships: ['PBB', 'UE', 'NATO', 'OECD', 'WTO'],
                giniCoefficient: 28.0,
                hdi: 0.944,
                hdiRank: 8,
                corruptionIndex: 82,
                currency: 'Euro',
                currencyCode: 'EUR',
                gdp: 1100000000000,
                gdpPerCapita: 64700,
                gdpPpp: 1300000000000,
                gdpGrowth: 2.0,
                inflation: 2.5,
                unemployment: 3.5,
                povertyRate: 10.0,
                mainIndustries: ['Logistik', 'Perdagangan', 'Teknologi', 'Pertanian', 'Keuangan'],
                exports: [
                    { item: 'Logistik', value: 200000000000 },
                    { item: 'Pertanian', value: 100000000000 },
                    { item: 'Teknologi', value: 80000000000 },
                    { item: 'Kimia', value: 60000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 100000000000 },
                    { item: 'Elektronik', value: 80000000000 },
                    { item: 'Minyak', value: 60000000000 },
                    { item: 'Makanan', value: 50000000000 }
                ],
                tradeBalance: 100000000000,
                naturalResources: ['Gas', 'Tanah subur', 'Air', 'Garam'],
                economicRanking: 18,
                internetPenetration: 95,
                mobilePenetration: 98,
                electricityAccess: 100,
                roadLength: 140000,
                railwayLength: 3000,
                airports: 50,
                seaports: 30,
                healthcareAccess: 95,
                educationIndex: 0.85,
                nationalMotto: 'Saya akan bertahan',
                nationalAnthem: 'Wilhelmus',
                nationalAnimal: 'Singa',
                nationalFlower: 'Tulip',
                nationalCuisine: ['Stroopwafel', 'Cheese', 'Bitterballen', 'Kroket', 'Haring'],
                culturalHeritage: ['Amsterdam', 'Keukenhof', 'Zaanse Schans', 'Rotterdam'],
                publicHolidays: ['Hari Raja', 'Paskah', 'Christmas', 'Tahun Baru'],
                socialRanking: 88,
                climate: 'Maritim',
                averageTemperature: 10,
                averageRainfall: 800,
                forestArea: 10,
                protectedAreas: 15,
                biodiversityRank: 30,
                carbonEmissions: 8.0,
                environmentalIndex: 60,
                riskScore: 15,
                politicalStability: 85,
                crimeIndex: 15,
                militarySpending: 1.5,
                peaceIndex: 20,
                terrorismIndex: 8,
                refugeePopulation: 50000,
                opportunityScore: 85,
                easeOfDoingBusiness: 85,
                innovationIndex: 80,
                startupEcosystem: 82,
                investmentScore: 85,
                talentPool: 88,
                marketSize: 85,
                infrastructureQuality: 92,
                internetSpeed: 55,
                digitalAdoption: 92,
                techEcosystem: 85,
                aiReadiness: 78,
                startups: 3000,
                phoneCode: '+31',
                tld: '.nl',
                isoCode: 'NLD',
                isoCode2: 'NL',
                drivingSide: 'right',
                tags: ['negara', 'eropan-barat', 'logistik', 'perdagangan', 'ue']
            }
        },
        // ==========================================================
        // 🇧🇪 BELGIA
        // ==========================================================
        {
            text: 'Belgia - Negara kecil di Eropa Barat yang menjadi pusat administrasi EU. Ibu kota: Brussel. Populasi: 11 juta jiwa. Mata uang: Euro (EUR). Bahasa: Belanda, Prancis, Jerman. Sistem pemerintahan: Monarki Konstitusional Federal Parlementer. Pusat Uni Eropa dan NATO. Negara dengan cokelat, bir, dan keju terbaik dunia. Rumah bagi arsitektur Art Nouveau dan kota-kota bersejarah.',
            metadata: {
                category: 'country',
                region: 'eropan-barat',
                name: 'Belgia',
                officialName: 'Kerajaan Belgia',
                shortName: 'BEL',
                capital: 'Brussel',
                capitalCoordinates: { lat: 50.8503, lng: 4.3517 },
                largestCity: 'Brussel',
                demonym: 'Belgia',
                subregion: 'Western Europe',
                area: 30528,
                areaRank: 136,
                coastline: 66,
                highestPoint: 'Signal de Botrange',
                highestElevation: 694,
                lowestPoint: 'De Moeren',
                lowestElevation: -4,
                landBorders: ['Belanda', 'Jerman', 'Luxembourg', 'Prancis'],
                coordinates: { lat: 50.83, lng: 4.37 },
                timezone: ['Waktu Eropa Tengah'],
                utcOffset: ['+1'],
                population: 11000000,
                populationRank: 82,
                populationDensity: 360,
                populationGrowth: 0.4,
                medianAge: 42.0,
                lifeExpectancy: 81.0,
                fertilityRate: 1.5,
                urbanization: 98,
                ethnicGroups: [
                    { name: 'Belgia', percentage: 70.0 },
                    { name: 'Prancis', percentage: 15.0 },
                    { name: 'Jerman', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 10.0 }
                ],
                religions: [
                    { name: 'Kristen Katolik', percentage: 60.0 },
                    { name: 'Tidak beragama', percentage: 30.0 },
                    { name: 'Islam', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 5.0 }
                ],
                languages: [
                    { name: 'Belanda', percentage: 60, official: true },
                    { name: 'Prancis', percentage: 40, official: true },
                    { name: 'Jerman', percentage: 1, official: true },
                    { name: 'Inggris', percentage: 40 }
                ],
                literacyRate: 99,
                governmentType: 'Monarki Konstitusional Federal Parlementer',
                independenceDay: '1830-10-04',
                nationalHoliday: '21 Juli',
                legalSystem: 'Civil Law',
                constitution: '1831',
                administrativeDivisions: 3,
                memberships: ['PBB', 'UE', 'NATO', 'OECD', 'WTO'],
                giniCoefficient: 27.0,
                hdi: 0.937,
                hdiRank: 12,
                corruptionIndex: 75,
                currency: 'Euro',
                currencyCode: 'EUR',
                gdp: 600000000000,
                gdpPerCapita: 54500,
                gdpPpp: 700000000000,
                gdpGrowth: 1.5,
                inflation: 2.5,
                unemployment: 5.0,
                povertyRate: 12.0,
                mainIndustries: ['Administrasi', 'Keuangan', 'Logistik', 'Kimia', 'Cokelat'],
                exports: [
                    { item: 'Kimia', value: 100000000000 },
                    { item: 'Cokelat', value: 50000000000 },
                    { item: 'Logistik', value: 40000000000 },
                    { item: 'Keuangan', value: 30000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 80000000000 },
                    { item: 'Elektronik', value: 60000000000 },
                    { item: 'Minyak', value: 40000000000 },
                    { item: 'Makanan', value: 30000000000 }
                ],
                tradeBalance: 20000000000,
                naturalResources: ['Batu bara', 'Kayu', 'Air', 'Tanah subur'],
                economicRanking: 25,
                internetPenetration: 92,
                mobilePenetration: 96,
                electricityAccess: 100,
                roadLength: 150000,
                railwayLength: 3600,
                airports: 50,
                seaports: 10,
                healthcareAccess: 92,
                educationIndex: 0.82,
                nationalMotto: 'Persatuan membuat kekuatan',
                nationalAnthem: 'La Brabançonne',
                nationalAnimal: 'Singa',
                nationalFlower: 'Mawar',
                nationalCuisine: ['Waffles', 'Fries', 'Chocolate', 'Beer', 'Moules Frites'],
                culturalHeritage: ['Brussels', 'Bruges', 'Antwerp', 'Ghent'],
                publicHolidays: ['Hari Nasional', 'Paskah', 'Christmas', 'Tahun Baru'],
                socialRanking: 82,
                climate: 'Maritim',
                averageTemperature: 10,
                averageRainfall: 800,
                forestArea: 22,
                protectedAreas: 10,
                biodiversityRank: 30,
                carbonEmissions: 8.0,
                environmentalIndex: 55,
                riskScore: 18,
                politicalStability: 78,
                crimeIndex: 18,
                militarySpending: 1.2,
                peaceIndex: 25,
                terrorismIndex: 10,
                refugeePopulation: 50000,
                opportunityScore: 78,
                easeOfDoingBusiness: 78,
                innovationIndex: 70,
                startupEcosystem: 72,
                investmentScore: 75,
                talentPool: 82,
                marketSize: 78,
                infrastructureQuality: 85,
                internetSpeed: 45,
                digitalAdoption: 82,
                techEcosystem: 72,
                aiReadiness: 65,
                startups: 800,
                phoneCode: '+32',
                tld: '.be',
                isoCode: 'BEL',
                isoCode2: 'BE',
                drivingSide: 'right',
                tags: ['negara', 'eropan-barat', 'ue', 'nato', 'administrasi']
            }
        },
        // ==========================================================
        // 🇨🇭 SWISS
        // ==========================================================
        {
            text: 'Swiss - Negara di Eropa Barat dengan netralitas dan perbankan global. Ibu kota: Bern. Populasi: 8.7 juta jiwa. Mata uang: Franc Swiss (CHF). Bahasa: Jerman, Prancis, Italia, Romansh. Sistem pemerintahan: Republik Federal. Negara dengan kualitas hidup tertinggi di dunia. Rumah bagi cokelat, jam, dan Alpen Swiss. Pusat perbankan dan keuangan global. Negara dengan inovasi dan pendidikan terbaik.',
            metadata: {
                category: 'country',
                region: 'eropan-barat',
                name: 'Swiss',
                officialName: 'Konfederasi Swiss',
                shortName: 'CHE',
                capital: 'Bern',
                capitalCoordinates: { lat: 46.9480, lng: 7.4474 },
                largestCity: 'Zurich',
                demonym: 'Swiss',
                subregion: 'Western Europe',
                area: 41285,
                areaRank: 132,
                coastline: 0,
                highestPoint: 'Dufourspitze',
                highestElevation: 4634,
                lowestPoint: 'Lake Maggiore',
                lowestElevation: 195,
                landBorders: ['Prancis', 'Jerman', 'Italia', 'Austria', 'Liechtenstein'],
                coordinates: { lat: 46.8, lng: 8.2 },
                timezone: ['Waktu Eropa Tengah'],
                utcOffset: ['+1'],
                population: 8700000,
                populationRank: 100,
                populationDensity: 210,
                populationGrowth: 0.7,
                medianAge: 42.5,
                lifeExpectancy: 83.6,
                fertilityRate: 1.5,
                urbanization: 74,
                ethnicGroups: [
                    { name: 'Swiss', percentage: 70.0 },
                    { name: 'Italia', percentage: 10.0 },
                    { name: 'Jerman', percentage: 8.0 },
                    { name: 'Prancis', percentage: 5.0 }
                ],
                religions: [
                    { name: 'Kristen Katolik', percentage: 35.0 },
                    { name: 'Kristen Protestan', percentage: 25.0 },
                    { name: 'Tidak beragama', percentage: 30.0 },
                    { name: 'Islam', percentage: 5.0 }
                ],
                languages: [
                    { name: 'Jerman', percentage: 63, official: true },
                    { name: 'Prancis', percentage: 23, official: true },
                    { name: 'Italia', percentage: 8, official: true },
                    { name: 'Romansh', percentage: 0.5, official: true }
                ],
                literacyRate: 99,
                governmentType: 'Republik Federal',
                independenceDay: '1291-08-01',
                nationalHoliday: '1 Agustus',
                legalSystem: 'Civil Law',
                constitution: '1848',
                administrativeDivisions: 26,
                memberships: ['PBB', 'EFTA', 'OECD', 'WTO'],
                giniCoefficient: 33.1,
                hdi: 0.962,
                hdiRank: 2,
                corruptionIndex: 85,
                currency: 'Franc Swiss',
                currencyCode: 'CHF',
                gdp: 900000000000,
                gdpPerCapita: 103000,
                gdpPpp: 800000000000,
                gdpGrowth: 1.5,
                inflation: 2.0,
                unemployment: 2.0,
                povertyRate: 8.0,
                mainIndustries: ['Keuangan', 'Perbankan', 'Farmasi', 'Teknologi', 'Pariwisata'],
                exports: [
                    { item: 'Keuangan', value: 200000000000 },
                    { item: 'Farmasi', value: 150000000000 },
                    { item: 'Teknologi', value: 100000000000 },
                    { item: 'Cokelat', value: 50000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 80000000000 },
                    { item: 'Elektronik', value: 60000000000 },
                    { item: 'Makanan', value: 40000000000 },
                    { item: 'Minyak', value: 30000000000 }
                ],
                tradeBalance: 50000000000,
                naturalResources: ['Air', 'Kayu', 'Garam', 'Mineral'],
                economicRanking: 20,
                internetPenetration: 95,
                mobilePenetration: 98,
                electricityAccess: 100,
                roadLength: 75000,
                railwayLength: 5000,
                airports: 50,
                seaports: 0,
                healthcareAccess: 98,
                educationIndex: 0.88,
                nationalMotto: 'Satu untuk semua, semua untuk satu',
                nationalAnthem: 'Schweizerpsalm',
                nationalAnimal: 'Sapi',
                nationalFlower: 'Edelweiss',
                nationalCuisine: ['Cheese Fondue', 'Rösti', 'Chocolate', 'Raclette', 'Muesli'],
                culturalHeritage: ['Matterhorn', 'Geneva', 'Zurich', 'Interlaken'],
                publicHolidays: ['Hari Nasional', 'Paskah', 'Christmas', 'Tahun Baru'],
                socialRanking: 95,
                climate: 'Beragam',
                averageTemperature: 7,
                averageRainfall: 1000,
                forestArea: 32,
                protectedAreas: 20,
                biodiversityRank: 20,
                carbonEmissions: 4.0,
                environmentalIndex: 65,
                riskScore: 10,
                politicalStability: 95,
                crimeIndex: 10,
                militarySpending: 0.7,
                peaceIndex: 15,
                terrorismIndex: 5,
                refugeePopulation: 50000,
                opportunityScore: 90,
                easeOfDoingBusiness: 88,
                innovationIndex: 88,
                startupEcosystem: 85,
                investmentScore: 92,
                talentPool: 90,
                marketSize: 82,
                infrastructureQuality: 95,
                internetSpeed: 60,
                digitalAdoption: 92,
                techEcosystem: 88,
                aiReadiness: 82,
                startups: 3000,
                phoneCode: '+41',
                tld: '.ch',
                isoCode: 'CHE',
                isoCode2: 'CH',
                drivingSide: 'right',
                tags: ['negara', 'eropan-barat', 'perbankan', 'netral', 'cokelat']
            }
        },
        // ==========================================================
        // 🇦🇹 AUSTRIA
        // ==========================================================
        {
            text: 'Austria - Negara di Eropa Barat dengan alam pegunungan Alpen. Ibu kota: Wina. Populasi: 9 juta jiwa. Mata uang: Euro (EUR). Bahasa: Jerman. Sistem pemerintahan: Republik Federal Parlementer. Anggota UE. Negara dengan musik klasik dan arsitektur indah. Rumah bagi Mozart, Beethoven, dan Strauss. Kota Wina dengan kafe-kafe klasik dan istana-istana megah.',
            metadata: {
                category: 'country',
                region: 'eropan-barat',
                name: 'Austria',
                officialName: 'Republik Austria',
                shortName: 'AUT',
                capital: 'Wina',
                capitalCoordinates: { lat: 48.2082, lng: 16.3738 },
                largestCity: 'Wina',
                demonym: 'Austria',
                subregion: 'Western Europe',
                area: 83879,
                areaRank: 113,
                coastline: 0,
                highestPoint: 'Grossglockner',
                highestElevation: 3798,
                lowestPoint: 'Lake Neusiedl',
                lowestElevation: 115,
                landBorders: ['Jerman', 'Ceko', 'Slovakia', 'Hungaria', 'Slovenia', 'Italia', 'Swiss', 'Liechtenstein'],
                coordinates: { lat: 47.33, lng: 13.33 },
                timezone: ['Waktu Eropa Tengah'],
                utcOffset: ['+1'],
                population: 9000000,
                populationRank: 95,
                populationDensity: 107,
                populationGrowth: 0.3,
                medianAge: 44.5,
                lifeExpectancy: 81.8,
                fertilityRate: 1.4,
                urbanization: 58,
                ethnicGroups: [
                    { name: 'Austria', percentage: 80.0 },
                    { name: 'Jerman', percentage: 5.0 },
                    { name: 'Turki', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 10.0 }
                ],
                religions: [
                    { name: 'Kristen Katolik', percentage: 60.0 },
                    { name: 'Kristen Protestan', percentage: 5.0 },
                    { name: 'Tidak beragama', percentage: 25.0 },
                    { name: 'Islam', percentage: 8.0 }
                ],
                languages: [
                    { name: 'Jerman', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 50 },
                    { name: 'Prancis', percentage: 10 }
                ],
                literacyRate: 99,
                governmentType: 'Republik Federal Parlementer',
                independenceDay: '1955-10-26',
                nationalHoliday: '26 Oktober',
                legalSystem: 'Civil Law',
                constitution: '1920',
                administrativeDivisions: 9,
                memberships: ['PBB', 'UE', 'OECD', 'WTO'],
                giniCoefficient: 27.0,
                hdi: 0.916,
                hdiRank: 18,
                corruptionIndex: 75,
                currency: 'Euro',
                currencyCode: 'EUR',
                gdp: 500000000000,
                gdpPerCapita: 55500,
                gdpPpp: 600000000000,
                gdpGrowth: 1.5,
                inflation: 2.5,
                unemployment: 4.5,
                povertyRate: 12.0,
                mainIndustries: ['Pariwisata', 'Manufaktur', 'Keuangan', 'Teknologi', 'Pertanian'],
                exports: [
                    { item: 'Mesin', value: 80000000000 },
                    { item: 'Pariwisata', value: 50000000000 },
                    { item: 'Elektronik', value: 40000000000 },
                    { item: 'Kimia', value: 30000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 60000000000 },
                    { item: 'Elektronik', value: 50000000000 },
                    { item: 'Minyak', value: 30000000000 },
                    { item: 'Makanan', value: 20000000000 }
                ],
                tradeBalance: 10000000000,
                naturalResources: ['Kayu', 'Air', 'Mineral', 'Energi'],
                economicRanking: 28,
                internetPenetration: 90,
                mobilePenetration: 96,
                electricityAccess: 100,
                roadLength: 120000,
                railwayLength: 6000,
                airports: 50,
                seaports: 0,
                healthcareAccess: 92,
                educationIndex: 0.82,
                nationalMotto: 'Austria adalah untuk semua',
                nationalAnthem: 'Land der Berge, Land am Strome',
                nationalAnimal: 'Elang',
                nationalFlower: 'Edelweiss',
                nationalCuisine: ['Schnitzel', 'Apfelstrudel', 'Tafelspitz', 'Sachertorte', 'Kaiserschmarrn'],
                culturalHeritage: ['Vienna', 'Salzburg', 'Innsbruck', 'Hallstatt'],
                publicHolidays: ['Hari Nasional', 'Paskah', 'Christmas', 'Tahun Baru'],
                socialRanking: 85,
                climate: 'Kontinental',
                averageTemperature: 8,
                averageRainfall: 800,
                forestArea: 47,
                protectedAreas: 25,
                biodiversityRank: 20,
                carbonEmissions: 6.0,
                environmentalIndex: 60,
                riskScore: 15,
                politicalStability: 85,
                crimeIndex: 15,
                militarySpending: 0.8,
                peaceIndex: 20,
                terrorismIndex: 8,
                refugeePopulation: 50000,
                opportunityScore: 78,
                easeOfDoingBusiness: 78,
                innovationIndex: 72,
                startupEcosystem: 70,
                investmentScore: 75,
                talentPool: 82,
                marketSize: 78,
                infrastructureQuality: 88,
                internetSpeed: 50,
                digitalAdoption: 82,
                techEcosystem: 72,
                aiReadiness: 65,
                startups: 500,
                phoneCode: '+43',
                tld: '.at',
                isoCode: 'AUT',
                isoCode2: 'AT',
                drivingSide: 'right',
                tags: ['negara', 'eropan-barat', 'alpen', 'musik', 'ue']
            }
        },
        // ==========================================================
        // 🇮🇪 IRLANDIA
        // ==========================================================
        {
            text: 'Irlandia - Negara di Eropa Barat dengan ekonomi teknologi maju. Ibu kota: Dublin. Populasi: 5 juta jiwa. Mata uang: Euro (EUR). Bahasa: Irlandia, Inggris. Sistem pemerintahan: Republik Parlementer. Anggota UE. Pusat teknologi global (Google, Apple, Facebook di Eropa). Negara dengan budaya Celtic dan pemandangan hijau yang indah. Rumah bagi kliff Moher dan pub-pub tradisional.',
            metadata: {
                category: 'country',
                region: 'eropan-barat',
                name: 'Irlandia',
                officialName: 'Republik Irlandia',
                shortName: 'IRL',
                capital: 'Dublin',
                capitalCoordinates: { lat: 53.3498, lng: -6.2603 },
                largestCity: 'Dublin',
                demonym: 'Irlandia',
                subregion: 'Western Europe',
                area: 70273,
                areaRank: 118,
                coastline: 1448,
                highestPoint: 'Carrauntoohil',
                highestElevation: 1041,
                lowestPoint: 'Laut Irlandia',
                lowestElevation: 0,
                landBorders: ['Inggris'],
                coordinates: { lat: 53.0, lng: -8.0 },
                timezone: ['Waktu Greenwich'],
                utcOffset: ['+0'],
                population: 5000000,
                populationRank: 121,
                populationDensity: 71,
                populationGrowth: 0.5,
                medianAge: 39.5,
                lifeExpectancy: 82.3,
                fertilityRate: 1.6,
                urbanization: 62,
                ethnicGroups: [
                    { name: 'Irlandia', percentage: 85.0 },
                    { name: 'Inggris', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 10.0 }
                ],
                religions: [
                    { name: 'Kristen Katolik', percentage: 80.0 },
                    { name: 'Kristen Protestan', percentage: 5.0 },
                    { name: 'Tidak beragama', percentage: 10.0 },
                    { name: 'Lainnya', percentage: 5.0 }
                ],
                languages: [
                    { name: 'Inggris', percentage: 100, official: true },
                    { name: 'Irlandia', percentage: 40, official: true },
                    { name: 'Prancis', percentage: 10 }
                ],
                literacyRate: 99,
                governmentType: 'Republik Parlementer',
                independenceDay: '1916-04-24',
                nationalHoliday: '17 Maret',
                legalSystem: 'Common Law',
                constitution: '1937',
                administrativeDivisions: 26,
                memberships: ['PBB', 'UE', 'OECD', 'WTO'],
                giniCoefficient: 30.0,
                hdi: 0.945,
                hdiRank: 7,
                corruptionIndex: 74,
                currency: 'Euro',
                currencyCode: 'EUR',
                gdp: 500000000000,
                gdpPerCapita: 100000,
                gdpPpp: 600000000000,
                gdpGrowth: 3.0,
                inflation: 2.5,
                unemployment: 4.5,
                povertyRate: 12.0,
                mainIndustries: ['Teknologi', 'Farmasi', 'Keuangan', 'Pariwisata', 'Pertanian'],
                exports: [
                    { item: 'Teknologi', value: 150000000000 },
                    { item: 'Farmasi', value: 100000000000 },
                    { item: 'Keuangan', value: 80000000000 },
                    { item: 'Pariwisata', value: 50000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 80000000000 },
                    { item: 'Elektronik', value: 60000000000 },
                    { item: 'Minyak', value: 40000000000 },
                    { item: 'Makanan', value: 30000000000 }
                ],
                tradeBalance: 50000000000,
                naturalResources: ['Gas', 'Kayu', 'Air', 'Tanah subur'],
                economicRanking: 28,
                internetPenetration: 92,
                mobilePenetration: 96,
                electricityAccess: 100,
                roadLength: 100000,
                railwayLength: 2000,
                airports: 30,
                seaports: 20,
                healthcareAccess: 90,
                educationIndex: 0.82,
                nationalMotto: 'Kebangkitan Irlandia',
                nationalAnthem: 'Amhrán na bhFiann',
                nationalAnimal: 'Rusa',
                nationalFlower: 'Trifolium',
                nationalCuisine: ['Irish Stew', 'Soda Bread', 'Colcannon', 'Guinness', 'Potatoes'],
                culturalHeritage: ['Dublin', 'Cliffs of Moher', 'Galway', 'Cork'],
                publicHolidays: ['Hari St Patrick', 'Paskah', 'Christmas', 'Tahun Baru'],
                socialRanking: 85,
                climate: 'Maritim',
                averageTemperature: 9,
                averageRainfall: 1000,
                forestArea: 10,
                protectedAreas: 15,
                biodiversityRank: 25,
                carbonEmissions: 4.0,
                environmentalIndex: 55,
                riskScore: 15,
                politicalStability: 85,
                crimeIndex: 20,
                militarySpending: 0.3,
                peaceIndex: 20,
                terrorismIndex: 5,
                refugeePopulation: 10000,
                opportunityScore: 85,
                easeOfDoingBusiness: 82,
                innovationIndex: 80,
                startupEcosystem: 85,
                investmentScore: 85,
                talentPool: 85,
                marketSize: 75,
                infrastructureQuality: 82,
                internetSpeed: 50,
                digitalAdoption: 88,
                techEcosystem: 85,
                aiReadiness: 78,
                startups: 2000,
                phoneCode: '+353',
                tld: '.ie',
                isoCode: 'IRL',
                isoCode2: 'IE',
                drivingSide: 'left',
                tags: ['negara', 'eropan-barat', 'teknologi', 'farmasi', 'ue']
            }
        }
    ];

    // ============================================================
    // PROSES DATA KE REGISTER
    // ============================================================
    for (let i = 0; i < data.length; i++) {
        window.__DATA_REGISTER.push(data[i]);
    }

    // ============================================================
    // LOGGER
    // ============================================================
    if (window.InternalLogger) {
        window.InternalLogger.info('CountryEropanBarat', '✅ Loaded ' + data.length + ' countries (SUPER LENGKAP - 8 NEGARA!)');
    }

})();