const data = [
    
    
    
    {
        text: 'Afrika Selatan - Negara paling selatan di Afrika dengan ekonomi maju. Ibu kota: Pretoria. Populasi: 60 juta jiwa. Mata uang: Rand (ZAR). Bahasa: 11 bahasa resmi. Sistem pemerintahan: Republik Parlementer. Anggota G20, BRICS, dan AU. Negara dengan tambang emas, platinum, dan berlian terbesar di dunia. Rumah bagi Table Mountain, Cape Town, dan Safari Afrika.',
        metadata: {
            category: 'country',
            region: 'african-selatan',
            name: 'Afrika Selatan',
            officialName: 'Republik Afrika Selatan',
            shortName: 'ZAF',
            capital: 'Pretoria',
            capitalCoordinates: { lat: -25.7479, lng: 28.2293 },
            largestCity: 'Johannesburg',
            demonym: 'Afrika Selatan',
            subregion: 'South Africa',
            area: 1221037,
            areaRank: 24,
            coastline: 2798,
            highestPoint: 'Mafadi',
            highestElevation: 3450,
            lowestPoint: 'Laut Atlantik',
            lowestElevation: 0,
            landBorders: ['Namibia', 'Botswana', 'Zimbabwe', 'Mozambik', 'Eswatini', 'Lesotho'],
            coordinates: { lat: -30.0, lng: 25.0 },
            timezone: ['Waktu Afrika Selatan'],
            utcOffset: ['+2'],
            population: 60000000,
            populationRank: 25,
            populationDensity: 49,
            populationGrowth: 1.0,
            medianAge: 28.0,
            lifeExpectancy: 65.0,
            fertilityRate: 2.3,
            urbanization: 67,
            ethnicGroups: [
                { name: 'Kulit Hitam', percentage: 80.0 },
                { name: 'Kulit Putih', percentage: 8.0 },
                { name: 'Coloured', percentage: 9.0 },
                { name: 'India', percentage: 3.0 }
            ],
            religions: [
                { name: 'Kristen', percentage: 80.0 },
                { name: 'Lainnya', percentage: 20.0 }
            ],
            languages: [
                { name: 'Zulu', percentage: 100, official: true },
                { name: 'Xhosa', percentage: 80, official: true },
                { name: 'Inggris', percentage: 60, official: true },
                { name: 'Afrikaans', percentage: 50, official: true }
            ],
            literacyRate: 94,
            governmentType: 'Republik Parlementer',
            independenceDay: '1910-05-31',
            nationalHoliday: '27 April',
            legalSystem: 'Common Law',
            constitution: '1996',
            administrativeDivisions: 9,
            memberships: ['PBB', 'AU', 'G20', 'BRICS', 'Commonwealth'],
            giniCoefficient: 63.0,
            hdi: 0.709,
            hdiRank: 114,
            corruptionIndex: 44,
            currency: 'Rand',
            currencyCode: 'ZAR',
            gdp: 400000000000,
            gdpPerCapita: 6660,
            gdpPpp: 950000000000,
            gdpGrowth: 1.5,
            inflation: 5.0,
            unemployment: 30.0,
            povertyRate: 40.0,
            mainIndustries: ['Tambang', 'Manufaktur', 'Pertanian', 'Pariwisata', 'Keuangan'],
            exports: [
                { item: 'Emas', value: 40000000000 },
                { item: 'Platinum', value: 30000000000 },
                { item: 'Berlian', value: 20000000000 },
                { item: 'Pariwisata', value: 10000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 30000000000 },
                { item: 'Elektronik', value: 20000000000 },
                { item: 'Minyak', value: 15000000000 },
                { item: 'Makanan', value: 10000000000 }
            ],
            tradeBalance: 10000000000,
            naturalResources: ['Emas', 'Platinum', 'Berlian', 'Batu bara', 'Besi'],
            economicRanking: 35,
            internetPenetration: 70,
            mobilePenetration: 90,
            electricityAccess: 85,
            roadLength: 750000,
            railwayLength: 20000,
            airports: 200,
            seaports: 20,
            healthcareAccess: 65,
            educationIndex: 0.65,
            nationalMotto: 'Bersatu dalam Keragaman',
            nationalAnthem: 'Nkosi Sikelel\' iAfrika',
            nationalAnimal: 'Springbok',
            nationalFlower: 'Protea',
            nationalCuisine: ['Bobotie', 'Biltong', 'Braai', 'Potjiekos', 'Malva Pudding'],
            culturalHeritage: ['Cape Town', 'Table Mountain', 'Kruger Park', 'Robben Island'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 55,
            climate: 'Beragam',
            averageTemperature: 20,
            averageRainfall: 500,
            forestArea: 8,
            protectedAreas: 10,
            biodiversityRank: 6,
            carbonEmissions: 8.0,
            environmentalIndex: 48,
            riskScore: 45,
            politicalStability: 60,
            crimeIndex: 55,
            militarySpending: 1.0,
            peaceIndex: 55,
            terrorismIndex: 20,
            refugeePopulation: 10000,
            opportunityScore: 55,
            easeOfDoingBusiness: 60,
            innovationIndex: 50,
            startupEcosystem: 55,
            investmentScore: 55,
            talentPool: 75,
            marketSize: 80,
            infrastructureQuality: 60,
            internetSpeed: 35,
            digitalAdoption: 65,
            techEcosystem: 55,
            aiReadiness: 50,
            startups: 300,
            phoneCode: '+27',
            tld: '.za',
            isoCode: 'ZAF',
            isoCode2: 'ZA',
            drivingSide: 'left',
            tags: ['negara', 'african-selatan', 'g20', 'brics', 'tambang']
        }
    },
    
    
    
    {
        text: 'Namibia - Negara di Afrika Selatan dengan gurun Namib dan tambang. Ibu kota: Windhoek. Populasi: 2.5 juta jiwa. Mata uang: Dolar Namibia (NAD). Bahasa: Inggris. Sistem pemerintahan: Republik Semi-Presidensial. Rumah bagi gurun Namib tertua di dunia dan keanekaragaman hayati unik.',
        metadata: {
            category: 'country',
            region: 'african-selatan',
            name: 'Namibia',
            officialName: 'Republik Namibia',
            shortName: 'NAM',
            capital: 'Windhoek',
            capitalCoordinates: { lat: -22.5609, lng: 17.0658 },
            largestCity: 'Windhoek',
            demonym: 'Namibia',
            subregion: 'South Africa',
            area: 825615,
            areaRank: 34,
            coastline: 1572,
            highestPoint: 'Königstein',
            highestElevation: 2573,
            lowestPoint: 'Laut Atlantik',
            lowestElevation: 0,
            landBorders: ['Angola', 'Botswana', 'Afrika Selatan'],
            coordinates: { lat: -22.0, lng: 17.0 },
            timezone: ['Waktu Namibia'],
            utcOffset: ['+2'],
            population: 2500000,
            populationRank: 140,
            populationDensity: 3,
            populationGrowth: 1.5,
            medianAge: 28.0,
            lifeExpectancy: 64.0,
            fertilityRate: 3.0,
            urbanization: 52,
            ethnicGroups: [
                { name: 'Ovambo', percentage: 50.0 },
                { name: 'Kavango', percentage: 10.0 },
                { name: 'Kulit Putih', percentage: 8.0 },
                { name: 'Lainnya', percentage: 32.0 }
            ],
            religions: [
                { name: 'Kristen', percentage: 90.0 },
                { name: 'Lainnya', percentage: 10.0 }
            ],
            languages: [
                { name: 'Inggris', percentage: 100, official: true },
                { name: 'Afrikaans', percentage: 30 },
                { name: 'Oshiwambo', percentage: 20 }
            ],
            literacyRate: 92,
            governmentType: 'Republik Semi-Presidensial',
            independenceDay: '1990-03-21',
            nationalHoliday: '21 Maret',
            legalSystem: 'Common Law',
            constitution: '1990',
            administrativeDivisions: 14,
            memberships: ['PBB', 'AU', 'Commonwealth'],
            giniCoefficient: 59.1,
            hdi: 0.646,
            hdiRank: 130,
            corruptionIndex: 53,
            currency: 'Dolar Namibia',
            currencyCode: 'NAD',
            gdp: 15000000000,
            gdpPerCapita: 6000,
            gdpPpp: 30000000000,
            gdpGrowth: 3.5,
            inflation: 4.0,
            unemployment: 30.0,
            povertyRate: 20.0,
            mainIndustries: ['Tambang', 'Perikanan', 'Pariwisata', 'Pertanian'],
            exports: [
                { item: 'Berlian', value: 5000000000 },
                { item: 'Uranium', value: 3000000000 },
                { item: 'Perikanan', value: 2000000000 },
                { item: 'Pariwisata', value: 1000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 3000000000 },
                { item: 'Elektronik', value: 2000000000 },
                { item: 'Makanan', value: 1500000000 },
                { item: 'Minyak', value: 1000000000 }
            ],
            tradeBalance: 2000000000,
            naturalResources: ['Berlian', 'Uranium', 'Emas', 'Tembaga', 'Perikanan'],
            economicRanking: 80,
            internetPenetration: 50,
            mobilePenetration: 75,
            electricityAccess: 60,
            roadLength: 45000,
            railwayLength: 2500,
            airports: 30,
            seaports: 5,
            healthcareAccess: 55,
            educationIndex: 0.58,
            nationalMotto: 'Kebebasan, Keadilan, Kemakmuran',
            nationalAnthem: 'Namibia, Land of the Brave',
            nationalAnimal: 'Oryx',
            nationalFlower: 'Welwitschia',
            nationalCuisine: ['Kapana', 'Braai', 'Biltong', 'Pap', 'Potjiekos'],
            culturalHeritage: ['Sossusvlei', 'Etosha', 'Fish River Canyon', 'Windhoek'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 50,
            climate: 'Gurun',
            averageTemperature: 22,
            averageRainfall: 250,
            forestArea: 10,
            protectedAreas: 20,
            biodiversityRank: 15,
            carbonEmissions: 1.0,
            environmentalIndex: 55,
            riskScore: 35,
            politicalStability: 70,
            crimeIndex: 30,
            militarySpending: 1.0,
            peaceIndex: 40,
            terrorismIndex: 10,
            refugeePopulation: 0,
            opportunityScore: 45,
            easeOfDoingBusiness: 50,
            innovationIndex: 35,
            startupEcosystem: 30,
            investmentScore: 45,
            talentPool: 45,
            marketSize: 40,
            infrastructureQuality: 50,
            internetSpeed: 20,
            digitalAdoption: 45,
            techEcosystem: 35,
            aiReadiness: 30,
            startups: 20,
            phoneCode: '+264',
            tld: '.na',
            isoCode: 'NAM',
            isoCode2: 'NA',
            drivingSide: 'right',
            tags: ['negara', 'african-selatan', 'gurun', 'tambang', 'safari']
        }
    },
    
    
    
    {
        text: 'Botswana - Negara di Afrika Selatan dengan ekonomi stabil dan intan. Ibu kota: Gaborone. Populasi: 2.4 juta jiwa. Mata uang: Pula (BWP). Bahasa: Inggris, Setswana. Sistem pemerintahan: Republik Parlementer. Negara dengan ekonomi paling stabil di Afrika dan Delta Okavango yang indah.',
        metadata: {
            category: 'country',
            region: 'african-selatan',
            name: 'Botswana',
            officialName: 'Republik Botswana',
            shortName: 'BWA',
            capital: 'Gaborone',
            capitalCoordinates: { lat: -24.6282, lng: 25.9231 },
            largestCity: 'Gaborone',
            demonym: 'Botswana',
            subregion: 'South Africa',
            area: 581730,
            areaRank: 47,
            coastline: 0,
            highestPoint: 'Otse Hill',
            highestElevation: 1491,
            lowestPoint: 'Sungai Limpopo',
            lowestElevation: 513,
            landBorders: ['Namibia', 'Zambia', 'Zimbabwe', 'Afrika Selatan'],
            coordinates: { lat: -22.0, lng: 24.0 },
            timezone: ['Waktu Botswana'],
            utcOffset: ['+2'],
            population: 2400000,
            populationRank: 142,
            populationDensity: 4,
            populationGrowth: 1.5,
            medianAge: 25.0,
            lifeExpectancy: 68.0,
            fertilityRate: 2.5,
            urbanization: 70,
            ethnicGroups: [
                { name: 'Tswana', percentage: 85.0 },
                { name: 'Lainnya', percentage: 15.0 }
            ],
            religions: [
                { name: 'Kristen', percentage: 80.0 },
                { name: 'Lainnya', percentage: 20.0 }
            ],
            languages: [
                { name: 'Inggris', percentage: 100, official: true },
                { name: 'Setswana', percentage: 80, official: true }
            ],
            literacyRate: 88,
            governmentType: 'Republik Parlementer',
            independenceDay: '1966-09-30',
            nationalHoliday: '30 September',
            legalSystem: 'Common Law',
            constitution: '1966',
            administrativeDivisions: 10,
            memberships: ['PBB', 'AU', 'Commonwealth'],
            giniCoefficient: 53.3,
            hdi: 0.735,
            hdiRank: 97,
            corruptionIndex: 55,
            currency: 'Pula',
            currencyCode: 'BWP',
            gdp: 20000000000,
            gdpPerCapita: 8330,
            gdpPpp: 50000000000,
            gdpGrowth: 4.0,
            inflation: 3.0,
            unemployment: 20.0,
            povertyRate: 15.0,
            mainIndustries: ['Intan', 'Pariwisata', 'Pertanian', 'Tekstil'],
            exports: [
                { item: 'Intan', value: 8000000000 },
                { item: 'Pariwisata', value: 3000000000 },
                { item: 'Pertanian', value: 2000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 3000000000 },
                { item: 'Elektronik', value: 2000000000 },
                { item: 'Makanan', value: 1500000000 },
                { item: 'Minyak', value: 1000000000 }
            ],
            tradeBalance: 3000000000,
            naturalResources: ['Intan', 'Emas', 'Tembaga', 'Perikanan'],
            economicRanking: 80,
            internetPenetration: 55,
            mobilePenetration: 80,
            electricityAccess: 80,
            roadLength: 20000,
            railwayLength: 1000,
            airports: 20,
            seaports: 0,
            healthcareAccess: 60,
            educationIndex: 0.62,
            nationalMotto: 'Hujan',
            nationalAnthem: 'Fatshe leno la rona',
            nationalAnimal: 'Zebra',
            nationalFlower: 'Bunga Kalahari',
            nationalCuisine: ['Seswaa', 'Morogo', 'Pap', 'Bogobe', 'Mopane'],
            culturalHeritage: ['Okavango Delta', 'Gaborone', 'Chobe', 'Kalahari'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 60,
            climate: 'Subtropis',
            averageTemperature: 22,
            averageRainfall: 400,
            forestArea: 20,
            protectedAreas: 25,
            biodiversityRank: 10,
            carbonEmissions: 1.0,
            environmentalIndex: 55,
            riskScore: 30,
            politicalStability: 80,
            crimeIndex: 25,
            militarySpending: 1.0,
            peaceIndex: 35,
            terrorismIndex: 5,
            refugeePopulation: 0,
            opportunityScore: 50,
            easeOfDoingBusiness: 55,
            innovationIndex: 35,
            startupEcosystem: 30,
            investmentScore: 50,
            talentPool: 45,
            marketSize: 40,
            infrastructureQuality: 55,
            internetSpeed: 25,
            digitalAdoption: 45,
            techEcosystem: 35,
            aiReadiness: 30,
            startups: 20,
            phoneCode: '+267',
            tld: '.bw',
            isoCode: 'BWA',
            isoCode2: 'BW',
            drivingSide: 'left',
            tags: ['negara', 'african-selatan', 'intan', 'stabil', 'delta']
        }
    },
    
    
    
    {
        text: 'Zambia - Negara di Afrika Selatan dengan tambang tembaga dan Victoria Falls. Ibu kota: Lusaka. Populasi: 20 juta jiwa. Mata uang: Kwacha (ZMW). Bahasa: Inggris. Sistem pemerintahan: Republik Presidensial. Rumah bagi Air Terjun Victoria dan tambang tembaga terbesar di Afrika.',
        metadata: {
            category: 'country',
            region: 'african-selatan',
            name: 'Zambia',
            officialName: 'Republik Zambia',
            shortName: 'ZMB',
            capital: 'Lusaka',
            capitalCoordinates: { lat: -15.3875, lng: 28.3228 },
            largestCity: 'Lusaka',
            demonym: 'Zambia',
            subregion: 'South Africa',
            area: 752612,
            areaRank: 38,
            coastline: 0,
            highestPoint: 'Mafinga Central',
            highestElevation: 2339,
            lowestPoint: 'Sungai Zambezi',
            lowestElevation: 329,
            landBorders: ['Tanzania', 'Kongo', 'Angola', 'Namibia', 'Botswana', 'Zimbabwe', 'Mozambik', 'Malawi'],
            coordinates: { lat: -15.0, lng: 30.0 },
            timezone: ['Waktu Zambia'],
            utcOffset: ['+2'],
            population: 20000000,
            populationRank: 62,
            populationDensity: 26,
            populationGrowth: 2.5,
            medianAge: 18.0,
            lifeExpectancy: 64.0,
            fertilityRate: 4.5,
            urbanization: 45,
            ethnicGroups: [
                { name: 'Bemba', percentage: 35.0 },
                { name: 'Tonga', percentage: 15.0 },
                { name: 'Lainnya', percentage: 50.0 }
            ],
            religions: [
                { name: 'Kristen', percentage: 85.0 },
                { name: 'Lainnya', percentage: 15.0 }
            ],
            languages: [
                { name: 'Inggris', percentage: 100, official: true },
                { name: 'Bemba', percentage: 30 },
                { name: 'Nyanja', percentage: 20 }
            ],
            literacyRate: 83,
            governmentType: 'Republik Presidensial',
            independenceDay: '1964-10-24',
            nationalHoliday: '24 Oktober',
            legalSystem: 'Common Law',
            constitution: '1991',
            administrativeDivisions: 10,
            memberships: ['PBB', 'AU', 'Commonwealth'],
            giniCoefficient: 57.1,
            hdi: 0.584,
            hdiRank: 146,
            corruptionIndex: 33,
            currency: 'Kwacha',
            currencyCode: 'ZMW',
            gdp: 25000000000,
            gdpPerCapita: 1250,
            gdpPpp: 75000000000,
            gdpGrowth: 4.0,
            inflation: 7.0,
            unemployment: 10.0,
            povertyRate: 50.0,
            mainIndustries: ['Tambang', 'Pertanian', 'Pariwisata', 'Manufaktur'],
            exports: [
                { item: 'Tembaga', value: 10000000000 },
                { item: 'Pariwisata', value: 3000000000 },
                { item: 'Pertanian', value: 2000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 5000000000 },
                { item: 'Elektronik', value: 3000000000 },
                { item: 'Minyak', value: 2000000000 },
                { item: 'Makanan', value: 1500000000 }
            ],
            tradeBalance: 2000000000,
            naturalResources: ['Tembaga', 'Emas', 'Uranium', 'Kayu', 'Air'],
            economicRanking: 80,
            internetPenetration: 35,
            mobilePenetration: 60,
            electricityAccess: 45,
            roadLength: 40000,
            railwayLength: 2000,
            airports: 30,
            seaports: 0,
            healthcareAccess: 45,
            educationIndex: 0.52,
            nationalMotto: 'Satu Zambia, Satu Bangsa',
            nationalAnthem: 'Stand and Sing of Zambia, Proud and Free',
            nationalAnimal: 'Fish Eagle',
            nationalFlower: 'Bougainvillea',
            nationalCuisine: ['Nshima', 'Kapenta', 'Chikanda', 'Ifisashi', 'Vitumbuwa'],
            culturalHeritage: ['Victoria Falls', 'Lusaka', 'Livingstone', 'South Luangwa'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 40,
            climate: 'Subtropis',
            averageTemperature: 22,
            averageRainfall: 800,
            forestArea: 50,
            protectedAreas: 15,
            biodiversityRank: 10,
            carbonEmissions: 0.5,
            environmentalIndex: 48,
            riskScore: 45,
            politicalStability: 55,
            crimeIndex: 40,
            militarySpending: 1.0,
            peaceIndex: 50,
            terrorismIndex: 15,
            refugeePopulation: 5000,
            opportunityScore: 45,
            easeOfDoingBusiness: 45,
            innovationIndex: 30,
            startupEcosystem: 30,
            investmentScore: 40,
            talentPool: 50,
            marketSize: 60,
            infrastructureQuality: 35,
            internetSpeed: 15,
            digitalAdoption: 35,
            techEcosystem: 30,
            aiReadiness: 25,
            startups: 20,
            phoneCode: '+260',
            tld: '.zm',
            isoCode: 'ZMB',
            isoCode2: 'ZM',
            drivingSide: 'left',
            tags: ['negara', 'african-selatan', 'tembaga', 'victoria-falls', 'pertanian']
        }
    },
    
    
    
    {
        text: 'Zimbabwe - Negara di Afrika Selatan dengan Victoria Falls dan pertanian. Ibu kota: Harare. Populasi: 16 juta jiwa. Mata uang: Dolar Zimbabwe (ZWL). Bahasa: Inggris, Shona, Ndebele. Sistem pemerintahan: Republik Presidensial. Negara dengan Victoria Falls dan reruntuhan Great Zimbabwe.',
        metadata: {
            category: 'country',
            region: 'african-selatan',
            name: 'Zimbabwe',
            officialName: 'Republik Zimbabwe',
            shortName: 'ZWE',
            capital: 'Harare',
            capitalCoordinates: { lat: -17.8252, lng: 31.0335 },
            largestCity: 'Harare',
            demonym: 'Zimbabwe',
            subregion: 'South Africa',
            area: 390757,
            areaRank: 60,
            coastline: 0,
            highestPoint: 'Inyangani',
            highestElevation: 2592,
            lowestPoint: 'Sungai Runde',
            lowestElevation: 162,
            landBorders: ['Zambia', 'Mozambik', 'Afrika Selatan', 'Botswana'],
            coordinates: { lat: -20.0, lng: 30.0 },
            timezone: ['Waktu Zimbabwe'],
            utcOffset: ['+2'],
            population: 16000000,
            populationRank: 72,
            populationDensity: 41,
            populationGrowth: 1.5,
            medianAge: 20.0,
            lifeExpectancy: 61.0,
            fertilityRate: 3.5,
            urbanization: 38,
            ethnicGroups: [
                { name: 'Shona', percentage: 80.0 },
                { name: 'Ndebele', percentage: 15.0 },
                { name: 'Lainnya', percentage: 5.0 }
            ],
            religions: [
                { name: 'Kristen', percentage: 85.0 },
                { name: 'Lainnya', percentage: 15.0 }
            ],
            languages: [
                { name: 'Inggris', percentage: 100, official: true },
                { name: 'Shona', percentage: 80, official: true },
                { name: 'Ndebele', percentage: 20, official: true }
            ],
            literacyRate: 86,
            governmentType: 'Republik Presidensial',
            independenceDay: '1980-04-18',
            nationalHoliday: '18 April',
            legalSystem: 'Common Law',
            constitution: '2013',
            administrativeDivisions: 8,
            memberships: ['PBB', 'AU', 'Commonwealth'],
            giniCoefficient: 44.3,
            hdi: 0.571,
            hdiRank: 150,
            corruptionIndex: 24,
            currency: 'Dolar Zimbabwe',
            currencyCode: 'ZWL',
            gdp: 30000000000,
            gdpPerCapita: 1870,
            gdpPpp: 70000000000,
            gdpGrowth: 3.0,
            inflation: 50.0,
            unemployment: 10.0,
            povertyRate: 40.0,
            mainIndustries: ['Pertanian', 'Tambang', 'Manufaktur', 'Pariwisata'],
            exports: [
                { item: 'Emas', value: 5000000000 },
                { item: 'Tembakau', value: 3000000000 },
                { item: 'Pariwisata', value: 2000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 3000000000 },
                { item: 'Elektronik', value: 2000000000 },
                { item: 'Minyak', value: 1500000000 },
                { item: 'Makanan', value: 1000000000 }
            ],
            tradeBalance: -2000000000,
            naturalResources: ['Emas', 'Tembakau', 'Batu bara', 'Kayu'],
            economicRanking: 90,
            internetPenetration: 30,
            mobilePenetration: 55,
            electricityAccess: 40,
            roadLength: 90000,
            railwayLength: 3000,
            airports: 30,
            seaports: 0,
            healthcareAccess: 45,
            educationIndex: 0.55,
            nationalMotto: 'Persatuan, Kebebasan, Keadilan',
            nationalAnthem: 'National Anthem of Zimbabwe',
            nationalAnimal: 'Steenbok',
            nationalFlower: 'Flame Lily',
            nationalCuisine: ['Sadza', 'Nyama', 'Kapenta', 'Muriwo', 'Bota'],
            culturalHeritage: ['Victoria Falls', 'Great Zimbabwe', 'Harare', 'Matobo'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 35,
            climate: 'Subtropis',
            averageTemperature: 22,
            averageRainfall: 700,
            forestArea: 40,
            protectedAreas: 15,
            biodiversityRank: 15,
            carbonEmissions: 0.5,
            environmentalIndex: 45,
            riskScore: 60,
            politicalStability: 40,
            crimeIndex: 45,
            militarySpending: 1.0,
            peaceIndex: 60,
            terrorismIndex: 20,
            refugeePopulation: 5000,
            opportunityScore: 35,
            easeOfDoingBusiness: 35,
            innovationIndex: 25,
            startupEcosystem: 25,
            investmentScore: 30,
            talentPool: 50,
            marketSize: 55,
            infrastructureQuality: 30,
            internetSpeed: 12,
            digitalAdoption: 30,
            techEcosystem: 25,
            aiReadiness: 20,
            startups: 15,
            phoneCode: '+263',
            tld: '.zw',
            isoCode: 'ZWE',
            isoCode2: 'ZW',
            drivingSide: 'left',
            tags: ['negara', 'african-selatan', 'victoria-falls', 'pertanian', 'sejarah']
        }
    },
    
    
    
    {
        text: 'Eswatini - Kerajaan di Afrika Selatan dengan budaya Swazi. Ibu kota: Mbabane. Populasi: 1.1 juta jiwa. Mata uang: Lilangeni (SZL). Bahasa: Swazi, Inggris. Sistem pemerintahan: Monarki Absolut. Satu-satunya monarki absolut di Afrika. Kaya akan hutan dan pertanian.',
        metadata: {
            category: 'country',
            region: 'african-selatan',
            name: 'Eswatini',
            officialName: 'Kerajaan Eswatini',
            shortName: 'SWZ',
            capital: 'Mbabane',
            capitalCoordinates: { lat: -26.3183, lng: 31.1394 },
            largestCity: 'Mbabane',
            demonym: 'Eswatini',
            subregion: 'South Africa',
            area: 17364,
            areaRank: 153,
            coastline: 0,
            highestPoint: 'Emlembe',
            highestElevation: 1862,
            lowestPoint: 'Sungai Maputo',
            lowestElevation: 21,
            landBorders: ['Afrika Selatan', 'Mozambik'],
            coordinates: { lat: -26.5, lng: 31.5 },
            timezone: ['Waktu Eswatini'],
            utcOffset: ['+2'],
            population: 1100000,
            populationRank: 156,
            populationDensity: 63,
            populationGrowth: 1.0,
            medianAge: 22.0,
            lifeExpectancy: 60.0,
            fertilityRate: 3.0,
            urbanization: 24,
            ethnicGroups: [
                { name: 'Swazi', percentage: 90.0 },
                { name: 'Lainnya', percentage: 10.0 }
            ],
            religions: [
                { name: 'Kristen', percentage: 90.0 },
                { name: 'Lainnya', percentage: 10.0 }
            ],
            languages: [
                { name: 'Swazi', percentage: 100, official: true },
                { name: 'Inggris', percentage: 60, official: true }
            ],
            literacyRate: 88,
            governmentType: 'Monarki Absolut',
            independenceDay: '1968-09-06',
            nationalHoliday: '6 September',
            legalSystem: 'Common Law',
            constitution: '2005',
            administrativeDivisions: 4,
            memberships: ['PBB', 'AU', 'Commonwealth'],
            giniCoefficient: 50.0,
            hdi: 0.610,
            hdiRank: 138,
            corruptionIndex: 38,
            currency: 'Lilangeni',
            currencyCode: 'SZL',
            gdp: 5000000000,
            gdpPerCapita: 4540,
            gdpPpp: 12000000000,
            gdpGrowth: 2.5,
            inflation: 4.0,
            unemployment: 25.0,
            povertyRate: 40.0,
            mainIndustries: ['Pertanian', 'Tekstil', 'Keuangan', 'Pariwisata'],
            exports: [
                { item: 'Gula', value: 1000000000 },
                { item: 'Tekstil', value: 800000000 },
                { item: 'Pertanian', value: 500000000 }
            ],
            imports: [
                { item: 'Mesin', value: 800000000 },
                { item: 'Elektronik', value: 600000000 },
                { item: 'Makanan', value: 400000000 },
                { item: 'Minyak', value: 300000000 }
            ],
            tradeBalance: 200000000,
            naturalResources: ['Gula', 'Kayu', 'Emas', 'Batu bara'],
            economicRanking: 100,
            internetPenetration: 30,
            mobilePenetration: 55,
            electricityAccess: 60,
            roadLength: 3000,
            railwayLength: 0,
            airports: 5,
            seaports: 0,
            healthcareAccess: 50,
            educationIndex: 0.52,
            nationalMotto: 'Kita adalah benteng',
            nationalAnthem: 'Nkulunkulu Mnikati wetibusiso temaSwati',
            nationalAnimal: 'Lion',
            nationalFlower: 'Bunga Edelweiss',
            nationalCuisine: ['Sishwala', 'Emasi', 'Umncweba', 'Sidvudvu', 'Tinhlama'],
            culturalHeritage: ['Mbabane', 'Manzini', 'Mlilwane', 'Hlane'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 40,
            climate: 'Subtropis',
            averageTemperature: 20,
            averageRainfall: 800,
            forestArea: 30,
            protectedAreas: 10,
            biodiversityRank: 25,
            carbonEmissions: 0.5,
            environmentalIndex: 45,
            riskScore: 40,
            politicalStability: 60,
            crimeIndex: 30,
            militarySpending: 0.5,
            peaceIndex: 45,
            terrorismIndex: 5,
            refugeePopulation: 0,
            opportunityScore: 40,
            easeOfDoingBusiness: 45,
            innovationIndex: 30,
            startupEcosystem: 25,
            investmentScore: 40,
            talentPool: 40,
            marketSize: 30,
            infrastructureQuality: 45,
            internetSpeed: 15,
            digitalAdoption: 30,
            techEcosystem: 25,
            aiReadiness: 20,
            startups: 10,
            phoneCode: '+268',
            tld: '.sz',
            isoCode: 'SWZ',
            isoCode2: 'SZ',
            drivingSide: 'left',
            tags: ['negara', 'african-selatan', 'monarki', 'swazi', 'hutan']
        }
    },
    
    
    
    {
        text: 'Lesotho - Kerajaan di Afrika Selatan yang terkepung oleh Afrika Selatan. Ibu kota: Maseru. Populasi: 2.1 juta jiwa. Mata uang: Loti (LSL). Bahasa: Sesotho, Inggris. Sistem pemerintahan: Monarki Konstitusional. Satu-satunya negara di Afrika yang terletak di atas 1000 meter. Kaya akan air dan tekstil.',
        metadata: {
            category: 'country',
            region: 'african-selatan',
            name: 'Lesotho',
            officialName: 'Kerajaan Lesotho',
            shortName: 'LSO',
            capital: 'Maseru',
            capitalCoordinates: { lat: -29.3100, lng: 27.4800 },
            largestCity: 'Maseru',
            demonym: 'Lesotho',
            subregion: 'South Africa',
            area: 30355,
            areaRank: 137,
            coastline: 0,
            highestPoint: 'Thabana Ntlenyana',
            highestElevation: 3482,
            lowestPoint: 'Sungai Orange',
            lowestElevation: 1400,
            landBorders: ['Afrika Selatan'],
            coordinates: { lat: -29.5, lng: 28.5 },
            timezone: ['Waktu Lesotho'],
            utcOffset: ['+2'],
            population: 2100000,
            populationRank: 144,
            populationDensity: 69,
            populationGrowth: 0.5,
            medianAge: 22.0,
            lifeExpectancy: 55.0,
            fertilityRate: 3.0,
            urbanization: 28,
            ethnicGroups: [
                { name: 'Sesotho', percentage: 99.0 },
                { name: 'Lainnya', percentage: 1.0 }
            ],
            religions: [
                { name: 'Kristen', percentage: 90.0 },
                { name: 'Lainnya', percentage: 10.0 }
            ],
            languages: [
                { name: 'Sesotho', percentage: 100, official: true },
                { name: 'Inggris', percentage: 50, official: true }
            ],
            literacyRate: 79,
            governmentType: 'Monarki Konstitusional',
            independenceDay: '1966-10-04',
            nationalHoliday: '4 Oktober',
            legalSystem: 'Common Law',
            constitution: '1993',
            administrativeDivisions: 10,
            memberships: ['PBB', 'AU', 'Commonwealth'],
            giniCoefficient: 44.0,
            hdi: 0.514,
            hdiRank: 168,
            corruptionIndex: 40,
            currency: 'Loti',
            currencyCode: 'LSL',
            gdp: 3000000000,
            gdpPerCapita: 1420,
            gdpPpp: 8000000000,
            gdpGrowth: 2.0,
            inflation: 4.0,
            unemployment: 25.0,
            povertyRate: 50.0,
            mainIndustries: ['Tekstil', 'Air', 'Pertanian', 'Pariwisata'],
            exports: [
                { item: 'Tekstil', value: 1000000000 },
                { item: 'Air', value: 500000000 },
                { item: 'Pertanian', value: 300000000 }
            ],
            imports: [
                { item: 'Mesin', value: 500000000 },
                { item: 'Elektronik', value: 400000000 },
                { item: 'Makanan', value: 300000000 },
                { item: 'Minyak', value: 200000000 }
            ],
            tradeBalance: 200000000,
            naturalResources: ['Air', 'Tekstil', 'Emas', 'Kayu'],
            economicRanking: 110,
            internetPenetration: 25,
            mobilePenetration: 50,
            electricityAccess: 50,
            roadLength: 5000,
            railwayLength: 0,
            airports: 5,
            seaports: 0,
            healthcareAccess: 45,
            educationIndex: 0.48,
            nationalMotto: 'Kedamaian, Hujan, Kemakmuran',
            nationalAnthem: 'Lesotho Fatse La Bontata Rona',
            nationalAnimal: 'Kuda',
            nationalFlower: 'Bunga Merah',
            nationalCuisine: ['Papa', 'Moroho', 'Likhobe', 'Mohloha', 'Mokopu'],
            culturalHeritage: ['Maseru', 'Thaba Bosiu', 'Maluti', 'Sani Pass'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 35,
            climate: 'Pegunungan',
            averageTemperature: 15,
            averageRainfall: 800,
            forestArea: 2,
            protectedAreas: 5,
            biodiversityRank: 30,
            carbonEmissions: 0.1,
            environmentalIndex: 42,
            riskScore: 50,
            politicalStability: 55,
            crimeIndex: 40,
            militarySpending: 0.5,
            peaceIndex: 50,
            terrorismIndex: 10,
            refugeePopulation: 0,
            opportunityScore: 35,
            easeOfDoingBusiness: 40,
            innovationIndex: 25,
            startupEcosystem: 20,
            investmentScore: 35,
            talentPool: 40,
            marketSize: 35,
            infrastructureQuality: 35,
            internetSpeed: 10,
            digitalAdoption: 25,
            techEcosystem: 20,
            aiReadiness: 15,
            startups: 5,
            phoneCode: '+266',
            tld: '.ls',
            isoCode: 'LSO',
            isoCode2: 'LS',
            drivingSide: 'left',
            tags: ['negara', 'african-selatan', 'pegunungan', 'air', 'tekstil']
        }
    },
    
    
    
    {
        text: 'Mozambik - Negara di Afrika Selatan dengan pesisir Samudra Hindia. Ibu kota: Maputo. Populasi: 33 juta jiwa. Mata uang: Metical (MZN). Bahasa: Portugis. Sistem pemerintahan: Republik Presidensial. Anggota PBB, AU, dan SADC. Kaya gas alam, batu bara, dan pariwisata. Rumah bagi kepulauan Bazaruto dan pantai-pantai indah.',
        metadata: {
            category: 'country',
            region: 'african-selatan',
            name: 'Mozambik',
            officialName: 'Republik Mozambik',
            shortName: 'MOZ',
            capital: 'Maputo',
            capitalCoordinates: { lat: -25.9692, lng: 32.5732 },
            largestCity: 'Maputo',
            demonym: 'Mozambik',
            subregion: 'South Africa',
            area: 801590,
            areaRank: 35,
            coastline: 2470,
            highestPoint: 'Monte Binga',
            highestElevation: 2436,
            lowestPoint: 'Samudra Hindia',
            lowestElevation: 0,
            landBorders: ['Tanzania', 'Malawi', 'Zambia', 'Zimbabwe', 'Afrika Selatan', 'Eswatini'],
            coordinates: { lat: -18.0, lng: 35.0 },
            timezone: ['Waktu Mozambik'],
            utcOffset: ['+2'],
            population: 33000000,
            populationRank: 45,
            populationDensity: 41,
            populationGrowth: 2.5,
            medianAge: 18.0,
            lifeExpectancy: 60.0,
            fertilityRate: 5.0,
            urbanization: 38,
            ethnicGroups: [
                { name: 'Makua', percentage: 25.0 },
                { name: 'Tsonga', percentage: 15.0 },
                { name: 'Lainnya', percentage: 60.0 }
            ],
            religions: [
                { name: 'Kristen', percentage: 60.0 },
                { name: 'Islam', percentage: 20.0 },
                { name: 'Lainnya', percentage: 20.0 }
            ],
            languages: [
                { name: 'Portugis', percentage: 100, official: true },
                { name: 'Swahili', percentage: 20 }
            ],
            literacyRate: 60,
            governmentType: 'Republik Presidensial',
            independenceDay: '1975-06-25',
            nationalHoliday: '25 Juni',
            legalSystem: 'Civil Law',
            constitution: '2004',
            administrativeDivisions: 10,
            memberships: ['PBB', 'AU', 'SADC', 'Commonwealth'],
            giniCoefficient: 54.0,
            hdi: 0.456,
            hdiRank: 178,
            corruptionIndex: 26,
            currency: 'Metical',
            currencyCode: 'MZN',
            gdp: 20000000000,
            gdpPerCapita: 600,
            gdpPpp: 50000000000,
            gdpGrowth: 5.0,
            inflation: 5.0,
            unemployment: 20.0,
            povertyRate: 60.0,
            mainIndustries: ['Gas', 'Pertanian', 'Pariwisata', 'Tambang', 'Manufaktur'],
            exports: [
                { item: 'Gas', value: 5000000000 },
                { item: 'Batu bara', value: 3000000000 },
                { item: 'Pariwisata', value: 2000000000 },
                { item: 'Pertanian', value: 1000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 3000000000 },
                { item: 'Elektronik', value: 2000000000 },
                { item: 'Minyak', value: 1500000000 },
                { item: 'Makanan', value: 1000000000 }
            ],
            tradeBalance: 2000000000,
            naturalResources: ['Gas', 'Batu bara', 'Emas', 'Kayu', 'Perikanan'],
            economicRanking: 80,
            internetPenetration: 25,
            mobilePenetration: 50,
            electricityAccess: 30,
            roadLength: 30000,
            railwayLength: 3000,
            airports: 50,
            seaports: 20,
            healthcareAccess: 35,
            educationIndex: 0.42,
            nationalMotto: 'Kebebasan, Kemakmuran, Persatuan',
            nationalAnthem: 'Pátria Amada',
            nationalAnimal: 'Gajah',
            nationalFlower: 'Bunga Anggrek',
            nationalCuisine: ['Matapa', 'Xima', 'Frango', 'Peri-peri', 'Piri-piri'],
            culturalHeritage: ['Maputo', 'Bazaruto', 'Gorongosa', 'Mozambique Island'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 30,
            climate: 'Tropis',
            averageTemperature: 25,
            averageRainfall: 1000,
            forestArea: 30,
            protectedAreas: 10,
            biodiversityRank: 12,
            carbonEmissions: 0.5,
            environmentalIndex: 42,
            riskScore: 55,
            politicalStability: 50,
            crimeIndex: 40,
            militarySpending: 1.0,
            peaceIndex: 55,
            terrorismIndex: 25,
            refugeePopulation: 5000,
            opportunityScore: 40,
            easeOfDoingBusiness: 40,
            innovationIndex: 25,
            startupEcosystem: 20,
            investmentScore: 35,
            talentPool: 45,
            marketSize: 65,
            infrastructureQuality: 30,
            internetSpeed: 10,
            digitalAdoption: 25,
            techEcosystem: 20,
            aiReadiness: 15,
            startups: 15,
            phoneCode: '+258',
            tld: '.mz',
            isoCode: 'MOZ',
            isoCode2: 'MZ',
            drivingSide: 'left',
            tags: ['negara', 'african-selatan', 'gas', 'pariwisata', 'pesisir']
        }
    }
];

export const DATA = data;




if (window.InternalLogger) {
    window.InternalLogger.info('CountryAfricanSelatan', '✅ Loaded ' + data.length + ' countries (SUPER LENGKAP - 8 NEGARA!)');
}
