const data = [
    
    
    
    {
        text: 'Nigeria - Negara terbesar di Afrika dengan ekonomi dan populasi terbesar. Ibu kota: Abuja. Populasi: 220 juta jiwa. Mata uang: Naira (NGN). Bahasa: Inggris. Sistem pemerintahan: Republik Federal Presidensial. Anggota PBB, AU, dan OPEC. Rumah bagi Nollywood, industri film terbesar kedua di dunia. Ekonomi terbesar di Afrika dengan minyak, fintech, dan startup berkembang pesat.',
        metadata: {
            category: 'country',
            region: 'african-barat',
            name: 'Nigeria',
            officialName: 'Republik Federal Nigeria',
            shortName: 'NGA',
            capital: 'Abuja',
            capitalCoordinates: { lat: 9.0765, lng: 7.3986 },
            largestCity: 'Lagos',
            demonym: 'Nigeria',
            subregion: 'West Africa',
            area: 923768,
            areaRank: 32,
            coastline: 853,
            highestPoint: 'Chappal Waddi',
            highestElevation: 2419,
            lowestPoint: 'Laut Atlantik',
            lowestElevation: 0,
            landBorders: ['Benin', 'Niger', 'Chad', 'Kamerun'],
            coordinates: { lat: 8.0, lng: 8.0 },
            timezone: ['Waktu Nigeria'],
            utcOffset: ['+1'],
            population: 220000000,
            populationRank: 6,
            populationDensity: 238,
            populationGrowth: 2.5,
            medianAge: 18.0,
            lifeExpectancy: 55.0,
            fertilityRate: 5.0,
            urbanization: 52,
            ethnicGroups: [
                { name: 'Hausa', percentage: 30.0 },
                { name: 'Yoruba', percentage: 20.0 },
                { name: 'Igbo', percentage: 18.0 },
                { name: 'Lainnya', percentage: 32.0 }
            ],
            religions: [
                { name: 'Islam', percentage: 50.0 },
                { name: 'Kristen', percentage: 45.0 },
                { name: 'Lainnya', percentage: 5.0 }
            ],
            languages: [
                { name: 'Inggris', percentage: 100, official: true },
                { name: 'Hausa', percentage: 30 },
                { name: 'Yoruba', percentage: 20 },
                { name: 'Igbo', percentage: 18 }
            ],
            literacyRate: 62,
            governmentType: 'Republik Federal Presidensial',
            independenceDay: '1960-10-01',
            nationalHoliday: '1 Oktober',
            legalSystem: 'Common Law',
            constitution: '1999',
            administrativeDivisions: 36,
            memberships: ['PBB', 'AU', 'OPEC', 'Commonwealth'],
            giniCoefficient: 35.0,
            hdi: 0.539,
            hdiRank: 161,
            corruptionIndex: 26,
            currency: 'Naira',
            currencyCode: 'NGN',
            gdp: 500000000000,
            gdpPerCapita: 2270,
            gdpPpp: 1300000000000,
            gdpGrowth: 3.0,
            inflation: 15.0,
            unemployment: 30.0,
            povertyRate: 40.0,
            mainIndustries: ['Minyak', 'Fintech', 'Nollywood', 'Pertanian', 'Manufaktur'],
            exports: [
                { item: 'Minyak', value: 50000000000 },
                { item: 'Gas', value: 20000000000 },
                { item: 'Pertanian', value: 10000000000 },
                { item: 'Fintech', value: 5000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 20000000000 },
                { item: 'Elektronik', value: 15000000000 },
                { item: 'Makanan', value: 10000000000 },
                { item: 'Bahan kimia', value: 8000000000 }
            ],
            tradeBalance: 10000000000,
            naturalResources: ['Minyak', 'Gas', 'Emas', 'Batu bara', 'Tanah subur'],
            economicRanking: 35,
            internetPenetration: 45,
            mobilePenetration: 70,
            electricityAccess: 55,
            roadLength: 200000,
            railwayLength: 4000,
            airports: 100,
            seaports: 20,
            healthcareAccess: 40,
            educationIndex: 0.48,
            nationalMotto: 'Persatuan dan Iman',
            nationalAnthem: 'Arise, O Compatriots',
            nationalAnimal: 'Elang',
            nationalFlower: 'Bunga Raya',
            nationalCuisine: ['Jollof Rice', 'Pounded Yam', 'Egusi Soup', 'Suya', 'Moi Moi'],
            culturalHeritage: ['Lagos', 'Abuja', 'Ibadan', 'Kano'],
            publicHolidays: ['Hari Kemerdekaan', 'Idul Fitri', 'Idul Adha', 'Christmas'],
            socialRanking: 35,
            climate: 'Tropis',
            averageTemperature: 27,
            averageRainfall: 1500,
            forestArea: 10,
            protectedAreas: 5,
            biodiversityRank: 8,
            carbonEmissions: 0.5,
            environmentalIndex: 38,
            riskScore: 55,
            politicalStability: 45,
            crimeIndex: 50,
            militarySpending: 0.5,
            peaceIndex: 60,
            terrorismIndex: 50,
            refugeePopulation: 10000,
            opportunityScore: 55,
            easeOfDoingBusiness: 45,
            innovationIndex: 50,
            startupEcosystem: 60,
            investmentScore: 50,
            talentPool: 80,
            marketSize: 95,
            infrastructureQuality: 35,
            internetSpeed: 20,
            digitalAdoption: 45,
            techEcosystem: 55,
            aiReadiness: 40,
            startups: 500,
            phoneCode: '+234',
            tld: '.ng',
            isoCode: 'NGA',
            isoCode2: 'NG',
            drivingSide: 'right',
            tags: ['negara', 'african-barat', 'minyak', 'nollywood', 'fintech']
        }
    },
    
    
    
    {
        text: 'Ghana - Negara di Afrika Barat dengan ekonomi stabil dan budaya. Ibu kota: Accra. Populasi: 33 juta jiwa. Mata uang: Cedi (GHS). Bahasa: Inggris. Sistem pemerintahan: Republik Presidensial. Anggota PBB, AU, dan Commonwealth. Negara dengan kakao, emas, dan minyak. Demokrasi stabil dan pertumbuhan ekonomi yang baik.',
        metadata: {
            category: 'country',
            region: 'african-barat',
            name: 'Ghana',
            officialName: 'Republik Ghana',
            shortName: 'GHA',
            capital: 'Accra',
            capitalCoordinates: { lat: 5.6037, lng: -0.1870 },
            largestCity: 'Accra',
            demonym: 'Ghana',
            subregion: 'West Africa',
            area: 238533,
            areaRank: 80,
            coastline: 539,
            highestPoint: 'Mount Afadjato',
            highestElevation: 880,
            lowestPoint: 'Laut Atlantik',
            lowestElevation: 0,
            landBorders: ['Pantai Gading', 'Burkina Faso', 'Togo'],
            coordinates: { lat: 8.0, lng: -2.0 },
            timezone: ['Waktu Ghana'],
            utcOffset: ['+0'],
            population: 33000000,
            populationRank: 45,
            populationDensity: 138,
            populationGrowth: 2.0,
            medianAge: 22.0,
            lifeExpectancy: 64.0,
            fertilityRate: 3.5,
            urbanization: 57,
            ethnicGroups: [
                { name: 'Akan', percentage: 45.0 },
                { name: 'Mole-Dagbon', percentage: 15.0 },
                { name: 'Ewe', percentage: 15.0 },
                { name: 'Lainnya', percentage: 25.0 }
            ],
            religions: [
                { name: 'Kristen', percentage: 70.0 },
                { name: 'Islam', percentage: 18.0 },
                { name: 'Lainnya', percentage: 12.0 }
            ],
            languages: [
                { name: 'Inggris', percentage: 100, official: true },
                { name: 'Akan', percentage: 40 },
                { name: 'Ewe', percentage: 15 }
            ],
            literacyRate: 79,
            governmentType: 'Republik Presidensial',
            independenceDay: '1957-03-06',
            nationalHoliday: '6 Maret',
            legalSystem: 'Common Law',
            constitution: '1992',
            administrativeDivisions: 16,
            memberships: ['PBB', 'AU', 'Commonwealth', 'ECOWAS'],
            giniCoefficient: 43.5,
            hdi: 0.611,
            hdiRank: 136,
            corruptionIndex: 43,
            currency: 'Cedi',
            currencyCode: 'GHS',
            gdp: 80000000000,
            gdpPerCapita: 2420,
            gdpPpp: 200000000000,
            gdpGrowth: 5.0,
            inflation: 10.0,
            unemployment: 5.0,
            povertyRate: 20.0,
            mainIndustries: ['Kakao', 'Emas', 'Minyak', 'Pariwisata', 'Teknologi'],
            exports: [
                { item: 'Kakao', value: 15000000000 },
                { item: 'Emas', value: 10000000000 },
                { item: 'Minyak', value: 8000000000 },
                { item: 'Pariwisata', value: 3000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 8000000000 },
                { item: 'Elektronik', value: 6000000000 },
                { item: 'Minyak', value: 4000000000 },
                { item: 'Makanan', value: 3000000000 }
            ],
            tradeBalance: 5000000000,
            naturalResources: ['Kakao', 'Emas', 'Minyak', 'Kayu'],
            economicRanking: 70,
            internetPenetration: 50,
            mobilePenetration: 75,
            electricityAccess: 85,
            roadLength: 70000,
            railwayLength: 1000,
            airports: 30,
            seaports: 10,
            healthcareAccess: 55,
            educationIndex: 0.58,
            nationalMotto: 'Kebebasan dan Keadilan',
            nationalAnthem: 'God Bless Our Homeland Ghana',
            nationalAnimal: 'Elang',
            nationalFlower: 'Bunga Hibiscus',
            nationalCuisine: ['Jollof Rice', 'Fufu', 'Banku', 'Waakye', 'Kelewele'],
            culturalHeritage: ['Accra', 'Kumasi', 'Cape Coast Castle', 'Kakum'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 55,
            climate: 'Tropis',
            averageTemperature: 27,
            averageRainfall: 1200,
            forestArea: 15,
            protectedAreas: 8,
            biodiversityRank: 15,
            carbonEmissions: 0.5,
            environmentalIndex: 45,
            riskScore: 40,
            politicalStability: 70,
            crimeIndex: 30,
            militarySpending: 0.5,
            peaceIndex: 45,
            terrorismIndex: 15,
            refugeePopulation: 5000,
            opportunityScore: 55,
            easeOfDoingBusiness: 55,
            innovationIndex: 45,
            startupEcosystem: 50,
            investmentScore: 50,
            talentPool: 60,
            marketSize: 75,
            infrastructureQuality: 50,
            internetSpeed: 20,
            digitalAdoption: 45,
            techEcosystem: 45,
            aiReadiness: 35,
            startups: 100,
            phoneCode: '+233',
            tld: '.gh',
            isoCode: 'GHA',
            isoCode2: 'GH',
            drivingSide: 'right',
            tags: ['negara', 'african-barat', 'kakao', 'emas', 'stabil']
        }
    },
    
    
    
    {
        text: 'Pantai Gading - Negara di Afrika Barat dengan ekonomi pertanian. Ibu kota: Yamoussoukro. Populasi: 27 juta jiwa. Mata uang: Franc CFA (XOF). Bahasa: Prancis. Sistem pemerintahan: Republik Presidensial. Negara dengan kakao terbesar di dunia dan ekonomi pertanian yang maju.',
        metadata: {
            category: 'country',
            region: 'african-barat',
            name: 'Pantai Gading',
            officialName: 'Republik Pantai Gading',
            shortName: 'CIV',
            capital: 'Yamoussoukro',
            capitalCoordinates: { lat: 6.8276, lng: -5.2893 },
            largestCity: 'Abidjan',
            demonym: 'Pantai Gading',
            subregion: 'West Africa',
            area: 322463,
            areaRank: 68,
            coastline: 515,
            highestPoint: 'Mont Niénokoué',
            highestElevation: 1752,
            lowestPoint: 'Laut Atlantik',
            lowestElevation: 0,
            landBorders: ['Liberia', 'Guinea', 'Mali', 'Burkina Faso', 'Ghana'],
            coordinates: { lat: 8.0, lng: -5.0 },
            timezone: ['Waktu Pantai Gading'],
            utcOffset: ['+0'],
            population: 27000000,
            populationRank: 49,
            populationDensity: 83,
            populationGrowth: 2.0,
            medianAge: 22.0,
            lifeExpectancy: 58.0,
            fertilityRate: 4.5,
            urbanization: 51,
            ethnicGroups: [
                { name: 'Akan', percentage: 40.0 },
                { name: 'Krou', percentage: 20.0 },
                { name: 'Mande', percentage: 20.0 },
                { name: 'Lainnya', percentage: 20.0 }
            ],
            religions: [
                { name: 'Islam', percentage: 40.0 },
                { name: 'Kristen', percentage: 35.0 },
                { name: 'Lainnya', percentage: 25.0 }
            ],
            languages: [
                { name: 'Prancis', percentage: 100, official: true },
                { name: 'Lainnya', percentage: 20 }
            ],
            literacyRate: 48,
            governmentType: 'Republik Presidensial',
            independenceDay: '1960-08-07',
            nationalHoliday: '7 Agustus',
            legalSystem: 'Civil Law',
            constitution: '2016',
            administrativeDivisions: 14,
            memberships: ['PBB', 'AU', 'ECOWAS', 'WTO'],
            giniCoefficient: 41.5,
            hdi: 0.538,
            hdiRank: 162,
            corruptionIndex: 36,
            currency: 'Franc CFA',
            currencyCode: 'XOF',
            gdp: 70000000000,
            gdpPerCapita: 2590,
            gdpPpp: 160000000000,
            gdpGrowth: 6.0,
            inflation: 3.0,
            unemployment: 5.0,
            povertyRate: 30.0,
            mainIndustries: ['Kakao', 'Kopi', 'Pertanian', 'Manufaktur', 'Pariwisata'],
            exports: [
                { item: 'Kakao', value: 15000000000 },
                { item: 'Kopi', value: 8000000000 },
                { item: 'Minyak', value: 5000000000 },
                { item: 'Pertanian', value: 3000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 8000000000 },
                { item: 'Elektronik', value: 6000000000 },
                { item: 'Makanan', value: 4000000000 },
                { item: 'Minyak', value: 3000000000 }
            ],
            tradeBalance: 5000000000,
            naturalResources: ['Kakao', 'Kopi', 'Emas', 'Kayu', 'Minyak'],
            economicRanking: 70,
            internetPenetration: 40,
            mobilePenetration: 65,
            electricityAccess: 70,
            roadLength: 80000,
            railwayLength: 600,
            airports: 30,
            seaports: 10,
            healthcareAccess: 45,
            educationIndex: 0.42,
            nationalMotto: 'Persatuan, Disiplin, Keadilan',
            nationalAnthem: 'L\'Abidjanaise',
            nationalAnimal: 'Gajah',
            nationalFlower: 'Bunga Anggrek',
            nationalCuisine: ['Attiéké', 'Alloco', 'Kedjenou', 'Foutou', 'Garba'],
            culturalHeritage: ['Abidjan', 'Yamoussoukro', 'Grand-Bassam', 'Man'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 40,
            climate: 'Tropis',
            averageTemperature: 27,
            averageRainfall: 1500,
            forestArea: 20,
            protectedAreas: 8,
            biodiversityRank: 15,
            carbonEmissions: 0.5,
            environmentalIndex: 42,
            riskScore: 45,
            politicalStability: 50,
            crimeIndex: 35,
            militarySpending: 1.0,
            peaceIndex: 55,
            terrorismIndex: 20,
            refugeePopulation: 5000,
            opportunityScore: 45,
            easeOfDoingBusiness: 45,
            innovationIndex: 30,
            startupEcosystem: 30,
            investmentScore: 40,
            talentPool: 55,
            marketSize: 70,
            infrastructureQuality: 40,
            internetSpeed: 15,
            digitalAdoption: 35,
            techEcosystem: 30,
            aiReadiness: 25,
            startups: 30,
            phoneCode: '+225',
            tld: '.ci',
            isoCode: 'CIV',
            isoCode2: 'CI',
            drivingSide: 'right',
            tags: ['negara', 'african-barat', 'kakao', 'pertanian', 'ekonomi']
        }
    },
    
    
    
    {
        text: 'Senegal - Negara di Afrika Barat dengan demokrasi stabil. Ibu kota: Dakar. Populasi: 18 juta jiwa. Mata uang: Franc CFA (XOF). Bahasa: Prancis. Sistem pemerintahan: Republik Presidensial. Negara dengan demokrasi stabil dan pariwisata maju. Rumah bagi Danau Retba (Danau Pink) dan pulau Gorée.',
        metadata: {
            category: 'country',
            region: 'african-barat',
            name: 'Senegal',
            officialName: 'Republik Senegal',
            shortName: 'SEN',
            capital: 'Dakar',
            capitalCoordinates: { lat: 14.7167, lng: -17.4677 },
            largestCity: 'Dakar',
            demonym: 'Senegal',
            subregion: 'West Africa',
            area: 196722,
            areaRank: 86,
            coastline: 531,
            highestPoint: 'Mont Ibel',
            highestElevation: 648,
            lowestPoint: 'Laut Atlantik',
            lowestElevation: 0,
            landBorders: ['Mauritania', 'Mali', 'Guinea', 'Guinea-Bissau', 'Gambia'],
            coordinates: { lat: 14.0, lng: -14.0 },
            timezone: ['Waktu Senegal'],
            utcOffset: ['+0'],
            population: 18000000,
            populationRank: 66,
            populationDensity: 91,
            populationGrowth: 2.5,
            medianAge: 19.0,
            lifeExpectancy: 68.0,
            fertilityRate: 4.5,
            urbanization: 48,
            ethnicGroups: [
                { name: 'Wolof', percentage: 40.0 },
                { name: 'Fula', percentage: 20.0 },
                { name: 'Serer', percentage: 15.0 },
                { name: 'Lainnya', percentage: 25.0 }
            ],
            religions: [
                { name: 'Islam', percentage: 95.0 },
                { name: 'Kristen', percentage: 4.0 },
                { name: 'Lainnya', percentage: 1.0 }
            ],
            languages: [
                { name: 'Prancis', percentage: 100, official: true },
                { name: 'Wolof', percentage: 80 },
                { name: 'Lainnya', percentage: 20 }
            ],
            literacyRate: 58,
            governmentType: 'Republik Presidensial',
            independenceDay: '1960-04-04',
            nationalHoliday: '4 April',
            legalSystem: 'Civil Law',
            constitution: '2001',
            administrativeDivisions: 14,
            memberships: ['PBB', 'AU', 'ECOWAS', 'WTO'],
            giniCoefficient: 40.3,
            hdi: 0.514,
            hdiRank: 168,
            corruptionIndex: 45,
            currency: 'Franc CFA',
            currencyCode: 'XOF',
            gdp: 30000000000,
            gdpPerCapita: 1660,
            gdpPpp: 75000000000,
            gdpGrowth: 5.0,
            inflation: 3.0,
            unemployment: 5.0,
            povertyRate: 30.0,
            mainIndustries: ['Pariwisata', 'Pertanian', 'Perikanan', 'Tekstil', 'Tambang'],
            exports: [
                { item: 'Pariwisata', value: 5000000000 },
                { item: 'Perikanan', value: 3000000000 },
                { item: 'Pertanian', value: 2000000000 },
                { item: 'Emas', value: 1000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 5000000000 },
                { item: 'Elektronik', value: 4000000000 },
                { item: 'Makanan', value: 3000000000 },
                { item: 'Minyak', value: 2000000000 }
            ],
            tradeBalance: -1000000000,
            naturalResources: ['Perikanan', 'Emas', 'Fosfat', 'Kayu'],
            economicRanking: 80,
            internetPenetration: 40,
            mobilePenetration: 65,
            electricityAccess: 70,
            roadLength: 15000,
            railwayLength: 1000,
            airports: 20,
            seaports: 10,
            healthcareAccess: 50,
            educationIndex: 0.48,
            nationalMotto: 'Satu Orang, Satu Tujuan, Satu Iman',
            nationalAnthem: 'Pincez Tous vos Koras, Frappez les Balafons',
            nationalAnimal: 'Singa',
            nationalFlower: 'Bunga Baobab',
            nationalCuisine: ['Thiebou Djeun', 'Yassa', 'Mafe', 'Sombi', 'Ngalakh'],
            culturalHeritage: ['Dakar', 'Gorée Island', 'Saint-Louis', 'Lake Retba'],
            publicHolidays: ['Hari Kemerdekaan', 'Idul Fitri', 'Idul Adha', 'Christmas'],
            socialRanking: 45,
            climate: 'Tropis',
            averageTemperature: 27,
            averageRainfall: 600,
            forestArea: 10,
            protectedAreas: 8,
            biodiversityRank: 20,
            carbonEmissions: 0.5,
            environmentalIndex: 45,
            riskScore: 40,
            politicalStability: 65,
            crimeIndex: 30,
            militarySpending: 1.0,
            peaceIndex: 45,
            terrorismIndex: 20,
            refugeePopulation: 10000,
            opportunityScore: 45,
            easeOfDoingBusiness: 50,
            innovationIndex: 35,
            startupEcosystem: 35,
            investmentScore: 40,
            talentPool: 50,
            marketSize: 60,
            infrastructureQuality: 45,
            internetSpeed: 15,
            digitalAdoption: 35,
            techEcosystem: 30,
            aiReadiness: 25,
            startups: 30,
            phoneCode: '+221',
            tld: '.sn',
            isoCode: 'SEN',
            isoCode2: 'SN',
            drivingSide: 'right',
            tags: ['negara', 'african-barat', 'stabil', 'pariwisata', 'demokrasi']
        }
    },
    
    
    
    {
        text: 'Mali - Negara di Afrika Barat dengan sejarah dan budaya. Ibu kota: Bamako. Populasi: 23 juta jiwa. Mata uang: Franc CFA (XOF). Bahasa: Prancis. Sistem pemerintahan: Republik Semi-Presidensial. Rumah bagi Timbuktu dan sejarah Kekaisaran Mali yang kaya.',
        metadata: {
            category: 'country',
            region: 'african-barat',
            name: 'Mali',
            officialName: 'Republik Mali',
            shortName: 'MLI',
            capital: 'Bamako',
            capitalCoordinates: { lat: 12.6392, lng: -8.0029 },
            largestCity: 'Bamako',
            demonym: 'Mali',
            subregion: 'West Africa',
            area: 1240192,
            areaRank: 23,
            coastline: 0,
            highestPoint: 'Hombori Tondo',
            highestElevation: 1155,
            lowestPoint: 'Sungai Senegal',
            lowestElevation: 23,
            landBorders: ['Mauritania', 'Aljazair', 'Niger', 'Burkina Faso', 'Pantai Gading', 'Guinea', 'Senegal'],
            coordinates: { lat: 17.0, lng: -4.0 },
            timezone: ['Waktu Mali'],
            utcOffset: ['+0'],
            population: 23000000,
            populationRank: 59,
            populationDensity: 18,
            populationGrowth: 3.0,
            medianAge: 16.0,
            lifeExpectancy: 59.0,
            fertilityRate: 6.0,
            urbanization: 46,
            ethnicGroups: [
                { name: 'Bambara', percentage: 35.0 },
                { name: 'Fula', percentage: 15.0 },
                { name: 'Soninke', percentage: 10.0 },
                { name: 'Lainnya', percentage: 40.0 }
            ],
            religions: [
                { name: 'Islam', percentage: 95.0 },
                { name: 'Kristen', percentage: 3.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            languages: [
                { name: 'Prancis', percentage: 100, official: true },
                { name: 'Bambara', percentage: 60 }
            ],
            literacyRate: 35,
            governmentType: 'Republik Semi-Presidensial',
            independenceDay: '1960-09-22',
            nationalHoliday: '22 September',
            legalSystem: 'Civil Law',
            constitution: '1992',
            administrativeDivisions: 19,
            memberships: ['PBB', 'AU', 'ECOWAS', 'WTO'],
            giniCoefficient: 33.0,
            hdi: 0.434,
            hdiRank: 181,
            corruptionIndex: 29,
            currency: 'Franc CFA',
            currencyCode: 'XOF',
            gdp: 20000000000,
            gdpPerCapita: 860,
            gdpPpp: 50000000000,
            gdpGrowth: 3.0,
            inflation: 3.0,
            unemployment: 5.0,
            povertyRate: 45.0,
            mainIndustries: ['Pertanian', 'Tambang', 'Tekstil', 'Pariwisata'],
            exports: [
                { item: 'Emas', value: 5000000000 },
                { item: 'Kapas', value: 3000000000 },
                { item: 'Pertanian', value: 2000000000 },
                { item: 'Pariwisata', value: 1000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 3000000000 },
                { item: 'Elektronik', value: 2000000000 },
                { item: 'Minyak', value: 1500000000 },
                { item: 'Makanan', value: 1000000000 }
            ],
            tradeBalance: 2000000000,
            naturalResources: ['Emas', 'Kapas', 'Kayu', 'Uranium'],
            economicRanking: 90,
            internetPenetration: 25,
            mobilePenetration: 50,
            electricityAccess: 50,
            roadLength: 30000,
            railwayLength: 700,
            airports: 20,
            seaports: 0,
            healthcareAccess: 35,
            educationIndex: 0.38,
            nationalMotto: 'Satu Orang, Satu Tujuan, Satu Iman',
            nationalAnthem: 'Pour l\'Afrique et pour toi, Mali',
            nationalAnimal: 'Elang',
            nationalFlower: 'Bunga Baobab',
            nationalCuisine: ['Tiguadege', 'Mafe', 'Yassa', 'Fufu', 'Couscous'],
            culturalHeritage: ['Timbuktu', 'Bamako', 'Djenne', 'Gao'],
            publicHolidays: ['Hari Kemerdekaan', 'Idul Fitri', 'Idul Adha', 'Christmas'],
            socialRanking: 30,
            climate: 'Gurun',
            averageTemperature: 30,
            averageRainfall: 300,
            forestArea: 5,
            protectedAreas: 5,
            biodiversityRank: 25,
            carbonEmissions: 0.1,
            environmentalIndex: 38,
            riskScore: 65,
            politicalStability: 35,
            crimeIndex: 40,
            militarySpending: 2.0,
            peaceIndex: 65,
            terrorismIndex: 50,
            refugeePopulation: 10000,
            opportunityScore: 30,
            easeOfDoingBusiness: 30,
            innovationIndex: 20,
            startupEcosystem: 15,
            investmentScore: 25,
            talentPool: 40,
            marketSize: 60,
            infrastructureQuality: 25,
            internetSpeed: 8,
            digitalAdoption: 20,
            techEcosystem: 15,
            aiReadiness: 10,
            startups: 10,
            phoneCode: '+223',
            tld: '.ml',
            isoCode: 'MLI',
            isoCode2: 'ML',
            drivingSide: 'right',
            tags: ['negara', 'african-barat', 'sejarah', 'budaya', 'timbuktu']
        }
    },
    
    
    
    {
        text: 'Kamerun - Negara di Afrika Barat dengan keanekaragaman. Ibu kota: Yaoundé. Populasi: 27 juta jiwa. Mata uang: Franc CFA (XAF). Bahasa: Inggris, Prancis. Sistem pemerintahan: Republik Presidensial. Negara dengan keanekaragaman hayati dan budaya. Sering disebut "Afrika Mini" karena keragaman ekosistemnya.',
        metadata: {
            category: 'country',
            region: 'african-barat',
            name: 'Kamerun',
            officialName: 'Republik Kamerun',
            shortName: 'CMR',
            capital: 'Yaoundé',
            capitalCoordinates: { lat: 3.8480, lng: 11.5021 },
            largestCity: 'Douala',
            demonym: 'Kamerun',
            subregion: 'West Africa',
            area: 475442,
            areaRank: 53,
            coastline: 402,
            highestPoint: 'Fako',
            highestElevation: 4095,
            lowestPoint: 'Laut Atlantik',
            lowestElevation: 0,
            landBorders: ['Nigeria', 'Chad', 'Republik Afrika Tengah', 'Kongo', 'Gabon', 'Guinea Khatulistiwa'],
            coordinates: { lat: 6.0, lng: 12.0 },
            timezone: ['Waktu Kamerun'],
            utcOffset: ['+1'],
            population: 27000000,
            populationRank: 49,
            populationDensity: 56,
            populationGrowth: 2.5,
            medianAge: 18.0,
            lifeExpectancy: 60.0,
            fertilityRate: 4.5,
            urbanization: 56,
            ethnicGroups: [
                { name: 'Bantu', percentage: 40.0 },
                { name: 'Fulani', percentage: 20.0 },
                { name: 'Lainnya', percentage: 40.0 }
            ],
            religions: [
                { name: 'Kristen', percentage: 60.0 },
                { name: 'Islam', percentage: 20.0 },
                { name: 'Lainnya', percentage: 20.0 }
            ],
            languages: [
                { name: 'Prancis', percentage: 100, official: true },
                { name: 'Inggris', percentage: 20, official: true }
            ],
            literacyRate: 77,
            governmentType: 'Republik Presidensial',
            independenceDay: '1960-01-01',
            nationalHoliday: '1 Januari',
            legalSystem: 'Civil Law',
            constitution: '1972',
            administrativeDivisions: 10,
            memberships: ['PBB', 'AU', 'ECOWAS', 'WTO'],
            giniCoefficient: 46.5,
            hdi: 0.563,
            hdiRank: 153,
            corruptionIndex: 25,
            currency: 'Franc CFA',
            currencyCode: 'XAF',
            gdp: 50000000000,
            gdpPerCapita: 1850,
            gdpPpp: 120000000000,
            gdpGrowth: 4.0,
            inflation: 3.0,
            unemployment: 5.0,
            povertyRate: 30.0,
            mainIndustries: ['Pertanian', 'Minyak', 'Manufaktur', 'Pariwisata', 'Kayu'],
            exports: [
                { item: 'Minyak', value: 10000000000 },
                { item: 'Kayu', value: 5000000000 },
                { item: 'Pertanian', value: 3000000000 },
                { item: 'Kakao', value: 2000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 5000000000 },
                { item: 'Elektronik', value: 4000000000 },
                { item: 'Makanan', value: 3000000000 },
                { item: 'Minyak', value: 2000000000 }
            ],
            tradeBalance: 3000000000,
            naturalResources: ['Minyak', 'Kayu', 'Emas', 'Kakao', 'Biji besi'],
            economicRanking: 80,
            internetPenetration: 35,
            mobilePenetration: 60,
            electricityAccess: 55,
            roadLength: 50000,
            railwayLength: 1000,
            airports: 30,
            seaports: 10,
            healthcareAccess: 45,
            educationIndex: 0.52,
            nationalMotto: 'Kebebasan, Kemakmuran, Persatuan',
            nationalAnthem: 'Ô Cameroun, Berceau de nos Ancêtres',
            nationalAnimal: 'Gajah',
            nationalFlower: 'Bunga Anggrek',
            nationalCuisine: ['Ndolé', 'Eru', 'Poulet DG', 'Koki', 'Bouillie'],
            culturalHeritage: ['Yaoundé', 'Douala', 'Buea', 'Waza'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 40,
            climate: 'Tropis',
            averageTemperature: 25,
            averageRainfall: 1500,
            forestArea: 40,
            protectedAreas: 10,
            biodiversityRank: 7,
            carbonEmissions: 0.5,
            environmentalIndex: 45,
            riskScore: 50,
            politicalStability: 45,
            crimeIndex: 40,
            militarySpending: 1.0,
            peaceIndex: 55,
            terrorismIndex: 25,
            refugeePopulation: 5000,
            opportunityScore: 45,
            easeOfDoingBusiness: 45,
            innovationIndex: 30,
            startupEcosystem: 30,
            investmentScore: 40,
            talentPool: 55,
            marketSize: 70,
            infrastructureQuality: 40,
            internetSpeed: 15,
            digitalAdoption: 35,
            techEcosystem: 30,
            aiReadiness: 25,
            startups: 20,
            phoneCode: '+237',
            tld: '.cm',
            isoCode: 'CMR',
            isoCode2: 'CM',
            drivingSide: 'right',
            tags: ['negara', 'african-barat', 'biodiversitas', 'pertanian', 'ekonomi']
        }
    }
];

export const DATA = data;




if (window.InternalLogger) {
    window.InternalLogger.info('CountryAfricanBarat', '✅ Loaded ' + data.length + ' countries (SUPER LENGKAP - 16 NEGARA!)');
}
