/* ============================================================
   📁 dataries/country/american-utara.js
   📌 DATA NEGARA AMERIKA UTARA
   🔥 3 NEGARA — Amerika Serikat, Kanada, Meksiko
   🔥 DATA SUPER LENGKAP — 100+ FIELD PER NEGARA!
   ============================================================ */

(function() {
    'use strict';
    
    if (window.__CountryAmericanUtaraLoaded) return;
    window.__CountryAmericanUtaraLoaded = true;
    
    window.__DATA_REGISTER = window.__DATA_REGISTER || [];
    
    const data = [
        // ==========================================================
        // 🇺🇸 AMERIKA SERIKAT
        // ==========================================================
        {
            text: 'Amerika Serikat - Negara adidaya di Amerika Utara dengan ekonomi dan militer terbesar dunia. Ibu kota: Washington D.C. Populasi: 334 juta jiwa. Mata uang: Dolar AS (USD). Bahasa: Inggris. Sistem pemerintahan: Republik Federal Konstitusional. Anggota G7, G20, NATO, dan PBB. Pusat teknologi, hiburan, dan keuangan global. Rumah bagi Silicon Valley, Hollywood, dan Wall Street. Negara dengan pengaruh global terbesar di dunia.',
            metadata: {
                category: 'country',
                region: 'american-utara',
                name: 'Amerika Serikat',
                officialName: 'Amerika Serikat',
                shortName: 'USA',
                capital: 'Washington D.C.',
                capitalCoordinates: { lat: 38.9072, lng: -77.0369 },
                largestCity: 'New York City',
                demonym: 'Amerika',
                subregion: 'Northern America',
                area: 9833517,
                areaRank: 3,
                coastline: 19924,
                highestPoint: 'Denali',
                highestElevation: 6190,
                lowestPoint: 'Death Valley',
                lowestElevation: -86,
                landBorders: ['Kanada', 'Meksiko'],
                coordinates: { lat: 38.0, lng: -97.0 },
                timezone: ['UTC-5 hingga UTC-10'],
                utcOffset: ['-5', '-6', '-7', '-8', '-9', '-10'],
                population: 334000000,
                populationRank: 3,
                populationDensity: 34,
                populationGrowth: 0.5,
                medianAge: 38.5,
                lifeExpectancy: 77.0,
                fertilityRate: 1.6,
                urbanization: 83,
                ethnicGroups: [
                    { name: 'Kulit Putih', percentage: 61.6 },
                    { name: 'Hispanik', percentage: 18.7 },
                    { name: 'Kulit Hitam', percentage: 12.4 },
                    { name: 'Asia', percentage: 6.0 }
                ],
                religions: [
                    { name: 'Kristen', percentage: 63.0 },
                    { name: 'Tidak beragama', percentage: 26.0 },
                    { name: 'Yahudi', percentage: 2.0 },
                    { name: 'Islam', percentage: 1.0 }
                ],
                languages: [
                    { name: 'Inggris', percentage: 80, official: true },
                    { name: 'Spanyol', percentage: 13 },
                    { name: 'Lainnya', percentage: 7 }
                ],
                literacyRate: 99,
                governmentType: 'Republik Federal Konstitusional',
                independenceDay: '1776-07-04',
                nationalHoliday: '4 Juli',
                legalSystem: 'Common Law',
                constitution: '1788',
                administrativeDivisions: 50,
                memberships: ['PBB', 'G7', 'G20', 'NATO', 'OECD', 'WTO'],
                giniCoefficient: 41.4,
                hdi: 0.921,
                hdiRank: 17,
                corruptionIndex: 67,
                currency: 'Dolar AS',
                currencyCode: 'USD',
                gdp: 26000000000000,
                gdpPerCapita: 77800,
                gdpPpp: 26000000000000,
                gdpGrowth: 2.1,
                inflation: 3.0,
                unemployment: 3.5,
                povertyRate: 11.0,
                mainIndustries: ['Teknologi', 'Keuangan', 'Manufaktur', 'Pariwisata', 'Pertanian'],
                exports: [
                    { item: 'Teknologi', value: 500000000000 },
                    { item: 'Mesin', value: 400000000000 },
                    { item: 'Keuangan', value: 300000000000 },
                    { item: 'Pertanian', value: 200000000000 }
                ],
                imports: [
                    { item: 'Elektronik', value: 600000000000 },
                    { item: 'Mesin', value: 500000000000 },
                    { item: 'Minyak', value: 400000000000 },
                    { item: 'Makanan', value: 300000000000 }
                ],
                tradeBalance: -800000000000,
                naturalResources: ['Batu bara', 'Gas', 'Minyak', 'Emas', 'Kayu', 'Tanah subur'],
                economicRanking: 1,
                internetPenetration: 92,
                mobilePenetration: 97,
                electricityAccess: 100,
                roadLength: 6800000,
                railwayLength: 220000,
                airports: 15000,
                seaports: 300,
                healthcareAccess: 85,
                educationIndex: 0.82,
                nationalMotto: 'In God We Trust',
                nationalAnthem: 'The Star-Spangled Banner',
                nationalAnimal: 'Elang Botak',
                nationalFlower: 'Mawar',
                nationalCuisine: ['Hamburger', 'Hot Dog', 'Pizza', 'Fried Chicken', 'Apple Pie'],
                culturalHeritage: ['Statue of Liberty', 'Grand Canyon', 'Yellowstone', 'Hollywood'],
                publicHolidays: ['Hari Kemerdekaan', 'Thanksgiving', 'Christmas', 'Tahun Baru'],
                socialRanking: 78,
                climate: 'Beragam',
                averageTemperature: 12,
                averageRainfall: 700,
                forestArea: 33,
                protectedAreas: 15,
                biodiversityRank: 6,
                carbonEmissions: 14.5,
                environmentalIndex: 45,
                riskScore: 25,
                politicalStability: 70,
                crimeIndex: 30,
                militarySpending: 3.5,
                peaceIndex: 35,
                terrorismIndex: 20,
                refugeePopulation: 100000,
                opportunityScore: 85,
                easeOfDoingBusiness: 82,
                innovationIndex: 90,
                startupEcosystem: 95,
                investmentScore: 85,
                talentPool: 95,
                marketSize: 100,
                infrastructureQuality: 85,
                internetSpeed: 55,
                digitalAdoption: 90,
                techEcosystem: 95,
                aiReadiness: 90,
                startups: 50000,
                phoneCode: '+1',
                tld: '.us',
                isoCode: 'USA',
                isoCode2: 'US',
                drivingSide: 'right',
                tags: ['negara', 'american-utara', 'adidaya', 'teknologi', 'g7']
            }
        },
        // ==========================================================
        // 🇨🇦 KANADA
        // ==========================================================
        {
            text: 'Kanada - Negara di Amerika Utara dengan alam dan sumber daya melimpah. Ibu kota: Ottawa. Populasi: 39 juta jiwa. Mata uang: Dolar Kanada (CAD). Bahasa: Inggris, Prancis. Sistem pemerintahan: Monarki Konstitusional Federal Parlementer. Anggota G7, G20, NATO, dan Commonwealth. Pemimpin global dalam energi terbarukan dan AI. Rumah bagi Niagara Falls, Rocky Mountains, dan budaya multikultural.',
            metadata: {
                category: 'country',
                region: 'american-utara',
                name: 'Kanada',
                officialName: 'Kanada',
                shortName: 'CAN',
                capital: 'Ottawa',
                capitalCoordinates: { lat: 45.4215, lng: -75.6972 },
                largestCity: 'Toronto',
                demonym: 'Kanada',
                subregion: 'Northern America',
                area: 9984670,
                areaRank: 2,
                coastline: 202080,
                highestPoint: 'Mount Logan',
                highestElevation: 5959,
                lowestPoint: 'Laut Atlantik',
                lowestElevation: 0,
                landBorders: ['Amerika Serikat'],
                coordinates: { lat: 45.4, lng: -75.7 },
                timezone: ['UTC-3.5 hingga UTC-8'],
                utcOffset: ['-3.5', '-4', '-5', '-6', '-7', '-8'],
                population: 39000000,
                populationRank: 38,
                populationDensity: 4,
                populationGrowth: 1.0,
                medianAge: 41.0,
                lifeExpectancy: 82.0,
                fertilityRate: 1.5,
                urbanization: 81,
                ethnicGroups: [
                    { name: 'Kulit Putih', percentage: 72.0 },
                    { name: 'Asia', percentage: 15.0 },
                    { name: 'Pribumi', percentage: 5.0 },
                    { name: 'Kulit Hitam', percentage: 4.0 }
                ],
                religions: [
                    { name: 'Kristen', percentage: 55.0 },
                    { name: 'Tidak beragama', percentage: 35.0 },
                    { name: 'Islam', percentage: 4.0 },
                    { name: 'Hindu', percentage: 2.0 }
                ],
                languages: [
                    { name: 'Inggris', percentage: 75, official: true },
                    { name: 'Prancis', percentage: 25, official: true },
                    { name: 'Lainnya', percentage: 10 }
                ],
                literacyRate: 99,
                governmentType: 'Monarki Konstitusional Federal Parlementer',
                independenceDay: '1867-07-01',
                nationalHoliday: '1 Juli',
                legalSystem: 'Common Law',
                constitution: '1982',
                administrativeDivisions: 10,
                memberships: ['PBB', 'G7', 'G20', 'NATO', 'Commonwealth', 'OECD'],
                giniCoefficient: 32.0,
                hdi: 0.936,
                hdiRank: 11,
                corruptionIndex: 74,
                currency: 'Dolar Kanada',
                currencyCode: 'CAD',
                gdp: 2100000000000,
                gdpPerCapita: 53800,
                gdpPpp: 2300000000000,
                gdpGrowth: 2.5,
                inflation: 2.5,
                unemployment: 5.0,
                povertyRate: 9.0,
                mainIndustries: ['Sumber daya alam', 'Manufaktur', 'Teknologi', 'Keuangan', 'Pariwisata'],
                exports: [
                    { item: 'Minyak', value: 150000000000 },
                    { item: 'Kayu', value: 100000000000 },
                    { item: 'Teknologi', value: 80000000000 },
                    { item: 'Manufaktur', value: 60000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 150000000000 },
                    { item: 'Elektronik', value: 100000000000 },
                    { item: 'Minyak', value: 80000000000 },
                    { item: 'Makanan', value: 60000000000 }
                ],
                tradeBalance: -20000000000,
                naturalResources: ['Minyak', 'Gas', 'Kayu', 'Emas', 'Besi', 'Air'],
                economicRanking: 10,
                internetPenetration: 92,
                mobilePenetration: 97,
                electricityAccess: 100,
                roadLength: 1400000,
                railwayLength: 50000,
                airports: 1500,
                seaports: 100,
                healthcareAccess: 92,
                educationIndex: 0.82,
                nationalMotto: 'Dari Laut ke Laut',
                nationalAnthem: 'O Canada',
                nationalAnimal: 'Berang-berang',
                nationalFlower: 'Maple Leaf',
                nationalCuisine: ['Poutine', 'Maple Syrup', 'Butter Tarts', 'Nanaimo Bars', 'Smoked Meat'],
                culturalHeritage: ['Niagara Falls', 'Banff', 'Vancouver', 'Quebec City'],
                publicHolidays: ['Hari Kanada', 'Thanksgiving', 'Christmas', 'Tahun Baru'],
                socialRanking: 88,
                climate: 'Beragam',
                averageTemperature: 5,
                averageRainfall: 600,
                forestArea: 40,
                protectedAreas: 10,
                biodiversityRank: 10,
                carbonEmissions: 15.0,
                environmentalIndex: 55,
                riskScore: 15,
                politicalStability: 90,
                crimeIndex: 18,
                militarySpending: 1.2,
                peaceIndex: 20,
                terrorismIndex: 8,
                refugeePopulation: 50000,
                opportunityScore: 80,
                easeOfDoingBusiness: 82,
                innovationIndex: 78,
                startupEcosystem: 80,
                investmentScore: 80,
                talentPool: 88,
                marketSize: 85,
                infrastructureQuality: 85,
                internetSpeed: 50,
                digitalAdoption: 88,
                techEcosystem: 82,
                aiReadiness: 78,
                startups: 3000,
                phoneCode: '+1',
                tld: '.ca',
                isoCode: 'CAN',
                isoCode2: 'CA',
                drivingSide: 'right',
                tags: ['negara', 'american-utara', 'g7', 'nato', 'ai']
            }
        },
        // ==========================================================
        // 🇲🇽 MEKSIKO
        // ==========================================================
        {
            text: 'Meksiko - Negara di Amerika Utara dengan ekonomi dan budaya kaya. Ibu kota: Mexico City. Populasi: 130 juta jiwa. Mata uang: Peso (MXN). Bahasa: Spanyol. Sistem pemerintahan: Republik Federal Presidensial. Anggota G20, USMCA, dan OECD. Pusat manufaktur dan ekspor utama. Rumah bagi peradaban Maya dan Aztec, serta masakan Meksiko yang mendunia.',
            metadata: {
                category: 'country',
                region: 'american-utara',
                name: 'Meksiko',
                officialName: 'Meksiko',
                shortName: 'MEX',
                capital: 'Mexico City',
                capitalCoordinates: { lat: 19.4326, lng: -99.1332 },
                largestCity: 'Mexico City',
                demonym: 'Meksiko',
                subregion: 'Central America',
                area: 1964375,
                areaRank: 13,
                coastline: 9330,
                highestPoint: 'Pico de Orizaba',
                highestElevation: 5636,
                lowestPoint: 'Laut Pasifik',
                lowestElevation: 0,
                landBorders: ['Amerika Serikat', 'Guatemala', 'Belize'],
                coordinates: { lat: 23.0, lng: -102.0 },
                timezone: ['UTC-6 hingga UTC-8'],
                utcOffset: ['-6', '-7', '-8'],
                population: 130000000,
                populationRank: 10,
                populationDensity: 66,
                populationGrowth: 0.8,
                medianAge: 29.0,
                lifeExpectancy: 75.0,
                fertilityRate: 2.0,
                urbanization: 80,
                ethnicGroups: [
                    { name: 'Mestizo', percentage: 62.0 },
                    { name: 'Pribumi', percentage: 20.0 },
                    { name: 'Kulit Putih', percentage: 10.0 },
                    { name: 'Lainnya', percentage: 8.0 }
                ],
                religions: [
                    { name: 'Kristen Katolik', percentage: 80.0 },
                    { name: 'Kristen Protestan', percentage: 10.0 },
                    { name: 'Tidak beragama', percentage: 8.0 },
                    { name: 'Lainnya', percentage: 2.0 }
                ],
                languages: [
                    { name: 'Spanyol', percentage: 100, official: true },
                    { name: 'Nahuatl', percentage: 5 },
                    { name: 'Maya', percentage: 3 }
                ],
                literacyRate: 95,
                governmentType: 'Republik Federal Presidensial',
                independenceDay: '1810-09-16',
                nationalHoliday: '16 September',
                legalSystem: 'Civil Law',
                constitution: '1917',
                administrativeDivisions: 31,
                memberships: ['PBB', 'G20', 'USMCA', 'OECD', 'WTO'],
                giniCoefficient: 43.4,
                hdi: 0.779,
                hdiRank: 74,
                corruptionIndex: 32,
                currency: 'Peso',
                currencyCode: 'MXN',
                gdp: 1800000000000,
                gdpPerCapita: 13800,
                gdpPpp: 3000000000000,
                gdpGrowth: 2.5,
                inflation: 4.5,
                unemployment: 3.0,
                povertyRate: 30.0,
                mainIndustries: ['Manufaktur', 'Otomotif', 'Elektronik', 'Pariwisata', 'Pertanian'],
                exports: [
                    { item: 'Otomotif', value: 150000000000 },
                    { item: 'Elektronik', value: 100000000000 },
                    { item: 'Manufaktur', value: 80000000000 },
                    { item: 'Minyak', value: 60000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 150000000000 },
                    { item: 'Elektronik', value: 100000000000 },
                    { item: 'Minyak', value: 80000000000 },
                    { item: 'Makanan', value: 60000000000 }
                ],
                tradeBalance: 10000000000,
                naturalResources: ['Minyak', 'Gas', 'Emas', 'Perak', 'Kayu', 'Tanah subur'],
                economicRanking: 15,
                internetPenetration: 75,
                mobilePenetration: 90,
                electricityAccess: 98,
                roadLength: 400000,
                railwayLength: 26000,
                airports: 100,
                seaports: 50,
                healthcareAccess: 70,
                educationIndex: 0.62,
                nationalMotto: 'Tanah air dan kebebasan',
                nationalAnthem: 'Himno Nacional Mexicano',
                nationalAnimal: 'Elang Emas',
                nationalFlower: 'Dahlia',
                nationalCuisine: ['Tacos', 'Guacamole', 'Enchiladas', 'Tamales', 'Churros'],
                culturalHeritage: ['Chichen Itza', 'Teotihuacan', 'Mexico City', 'Cancun'],
                publicHolidays: ['Hari Kemerdekaan', 'Hari Revolusi', 'Christmas', 'Tahun Baru'],
                socialRanking: 60,
                climate: 'Beragam',
                averageTemperature: 22,
                averageRainfall: 800,
                forestArea: 34,
                protectedAreas: 12,
                biodiversityRank: 5,
                carbonEmissions: 3.5,
                environmentalIndex: 42,
                riskScore: 45,
                politicalStability: 55,
                crimeIndex: 45,
                militarySpending: 0.7,
                peaceIndex: 55,
                terrorismIndex: 15,
                refugeePopulation: 10000,
                opportunityScore: 65,
                easeOfDoingBusiness: 60,
                innovationIndex: 55,
                startupEcosystem: 60,
                investmentScore: 60,
                talentPool: 80,
                marketSize: 90,
                infrastructureQuality: 60,
                internetSpeed: 25,
                digitalAdoption: 65,
                techEcosystem: 60,
                aiReadiness: 50,
                startups: 1000,
                phoneCode: '+52',
                tld: '.mx',
                isoCode: 'MEX',
                isoCode2: 'MX',
                drivingSide: 'right',
                tags: ['negara', 'american-utara', 'g20', 'manufaktur', 'usmca']
            }
        }
    ];

    // ============================================================
    // PROSES DATA KE REGISTER
    // ============================================================
    for (let i = 0; i < data.length; i++) {
        window.__DATA_REGISTER.push(data[i]);
    }

    // ============================================================
    // LOGGER
    // ============================================================
    if (window.InternalLogger) {
        window.InternalLogger.info('CountryAmericanUtara', '✅ Loaded ' + data.length + ' countries (SUPER LENGKAP - 3 NEGARA!)');
    }

})();