const data = [
    
    
    
    {
        text: 'Guatemala - Negara di Amerika Tengah dengan budaya Maya dan alam indah. Ibu kota: Guatemala City. Populasi: 18 juta jiwa. Mata uang: Quetzal (GTQ). Bahasa: Spanyol. Sistem pemerintahan: Republik Presidensial. Negara dengan peradaban Maya, Tikal, dan Danau Atitlan. Budaya yang kaya dan alam yang indah.',
        metadata: {
            category: 'country',
            region: 'american-tengah',
            name: 'Guatemala',
            officialName: 'Republik Guatemala',
            shortName: 'GTM',
            capital: 'Guatemala City',
            capitalCoordinates: { lat: 14.6349, lng: -90.5069 },
            largestCity: 'Guatemala City',
            demonym: 'Guatemala',
            subregion: 'Central America',
            area: 108889,
            areaRank: 105,
            coastline: 400,
            highestPoint: 'Volcan Tajumulco',
            highestElevation: 4220,
            lowestPoint: 'Laut Pasifik',
            lowestElevation: 0,
            landBorders: ['Meksiko', 'Belize', 'Honduras', 'El Salvador'],
            coordinates: { lat: 15.5, lng: -90.25 },
            timezone: ['Waktu Guatemala'],
            utcOffset: ['-6'],
            population: 18000000,
            populationRank: 66,
            populationDensity: 165,
            populationGrowth: 1.5,
            medianAge: 23.0,
            lifeExpectancy: 74.0,
            fertilityRate: 2.5,
            urbanization: 52,
            ethnicGroups: [
                { name: 'Maya', percentage: 40.0 },
                { name: 'Mestizo', percentage: 40.0 },
                { name: 'Kulit Putih', percentage: 18.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 45.0 },
                { name: 'Kristen Protestan', percentage: 40.0 },
                { name: 'Maya', percentage: 10.0 },
                { name: 'Lainnya', percentage: 5.0 }
            ],
            languages: [
                { name: 'Spanyol', percentage: 100, official: true },
                { name: 'Maya', percentage: 20 },
                { name: 'Lainnya', percentage: 10 }
            ],
            literacyRate: 80,
            governmentType: 'Republik Presidensial',
            independenceDay: '1821-09-15',
            nationalHoliday: '15 September',
            legalSystem: 'Civil Law',
            constitution: '1985',
            administrativeDivisions: 22,
            memberships: ['PBB', 'OAS', 'CAFTA', 'SICA'],
            giniCoefficient: 48.3,
            hdi: 0.663,
            hdiRank: 124,
            corruptionIndex: 30,
            currency: 'Quetzal',
            currencyCode: 'GTQ',
            gdp: 100000000000,
            gdpPerCapita: 5550,
            gdpPpp: 150000000000,
            gdpGrowth: 3.5,
            inflation: 3.5,
            unemployment: 2.5,
            povertyRate: 40.0,
            mainIndustries: ['Pertanian', 'Tekstil', 'Pariwisata', 'Manufaktur'],
            exports: [
                { item: 'Pertanian', value: 20000000000 },
                { item: 'Tekstil', value: 15000000000 },
                { item: 'Pariwisata', value: 10000000000 },
                { item: 'Manufaktur', value: 5000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 15000000000 },
                { item: 'Elektronik', value: 10000000000 },
                { item: 'Minyak', value: 8000000000 },
                { item: 'Makanan', value: 6000000000 }
            ],
            tradeBalance: -5000000000,
            naturalResources: ['Kayu', 'Emas', 'Perak', 'Tanah subur'],
            economicRanking: 65,
            internetPenetration: 55,
            mobilePenetration: 75,
            electricityAccess: 90,
            roadLength: 60000,
            railwayLength: 800,
            airports: 30,
            seaports: 5,
            healthcareAccess: 55,
            educationIndex: 0.52,
            nationalMotto: 'Bebas dan Berdaulat',
            nationalAnthem: 'Guatemala Feliz',
            nationalAnimal: 'Quetzal',
            nationalFlower: 'Monja Blanca',
            nationalCuisine: ['Pepian', 'Kak\'ik', 'Rellenitos', 'Tostadas', 'Tamales'],
            culturalHeritage: ['Tikal', 'Antigua', 'Lake Atitlan', 'Guatemala City'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 45,
            climate: 'Tropis',
            averageTemperature: 22,
            averageRainfall: 1500,
            forestArea: 30,
            protectedAreas: 10,
            biodiversityRank: 10,
            carbonEmissions: 1.0,
            environmentalIndex: 42,
            riskScore: 50,
            politicalStability: 50,
            crimeIndex: 45,
            militarySpending: 0.5,
            peaceIndex: 55,
            terrorismIndex: 15,
            refugeePopulation: 1000,
            opportunityScore: 45,
            easeOfDoingBusiness: 50,
            innovationIndex: 30,
            startupEcosystem: 35,
            investmentScore: 40,
            talentPool: 55,
            marketSize: 70,
            infrastructureQuality: 45,
            internetSpeed: 15,
            digitalAdoption: 40,
            techEcosystem: 35,
            aiReadiness: 25,
            startups: 50,
            phoneCode: '+502',
            tld: '.gt',
            isoCode: 'GTM',
            isoCode2: 'GT',
            drivingSide: 'right',
            tags: ['negara', 'american-tengah', 'maya', 'sejarah', 'budaya']
        }
    },
    
    
    
    {
        text: 'Honduras - Negara di Amerika Tengah dengan alam dan budaya kaya. Ibu kota: Tegucigalpa. Populasi: 10 juta jiwa. Mata uang: Lempira (HNL). Bahasa: Spanyol. Sistem pemerintahan: Republik Presidensial. Negara dengan pantai Karibia dan alam yang indah. Rumah bagi peradaban Maya dan Copán.',
        metadata: {
            category: 'country',
            region: 'american-tengah',
            name: 'Honduras',
            officialName: 'Republik Honduras',
            shortName: 'HND',
            capital: 'Tegucigalpa',
            capitalCoordinates: { lat: 14.0650, lng: -87.1715 },
            largestCity: 'Tegucigalpa',
            demonym: 'Honduras',
            subregion: 'Central America',
            area: 112492,
            areaRank: 101,
            coastline: 820,
            highestPoint: 'Cerro Las Minas',
            highestElevation: 2870,
            lowestPoint: 'Laut Karibia',
            lowestElevation: 0,
            landBorders: ['Guatemala', 'El Salvador', 'Nikaragua'],
            coordinates: { lat: 15.0, lng: -86.5 },
            timezone: ['Waktu Honduras'],
            utcOffset: ['-6'],
            population: 10000000,
            populationRank: 90,
            populationDensity: 89,
            populationGrowth: 1.5,
            medianAge: 24.0,
            lifeExpectancy: 75.0,
            fertilityRate: 2.2,
            urbanization: 55,
            ethnicGroups: [
                { name: 'Mestizo', percentage: 90.0 },
                { name: 'Pribumi', percentage: 7.0 },
                { name: 'Kulit Hitam', percentage: 2.0 },
                { name: 'Kulit Putih', percentage: 1.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 50.0 },
                { name: 'Kristen Protestan', percentage: 40.0 },
                { name: 'Tidak beragama', percentage: 8.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            languages: [
                { name: 'Spanyol', percentage: 100, official: true },
                { name: 'Inggris', percentage: 10 },
                { name: 'Miskito', percentage: 5 }
            ],
            literacyRate: 88,
            governmentType: 'Republik Presidensial',
            independenceDay: '1821-09-15',
            nationalHoliday: '15 September',
            legalSystem: 'Civil Law',
            constitution: '1982',
            administrativeDivisions: 18,
            memberships: ['PBB', 'OAS', 'SICA', 'CAFTA'],
            giniCoefficient: 48.2,
            hdi: 0.634,
            hdiRank: 132,
            corruptionIndex: 24,
            currency: 'Lempira',
            currencyCode: 'HNL',
            gdp: 30000000000,
            gdpPerCapita: 3000,
            gdpPpp: 50000000000,
            gdpGrowth: 3.5,
            inflation: 4.0,
            unemployment: 6.0,
            povertyRate: 50.0,
            mainIndustries: ['Pertanian', 'Manufaktur', 'Pariwisata', 'Tambang'],
            exports: [
                { item: 'Pertanian', value: 10000000000 },
                { item: 'Tekstil', value: 5000000000 },
                { item: 'Manufaktur', value: 3000000000 },
                { item: 'Pariwisata', value: 2000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 5000000000 },
                { item: 'Elektronik', value: 4000000000 },
                { item: 'Minyak', value: 3000000000 },
                { item: 'Makanan', value: 2000000000 }
            ],
            tradeBalance: -3000000000,
            naturalResources: ['Kayu', 'Emas', 'Perak', 'Tanah subur'],
            economicRanking: 80,
            internetPenetration: 50,
            mobilePenetration: 70,
            electricityAccess: 85,
            roadLength: 15000,
            railwayLength: 800,
            airports: 30,
            seaports: 10,
            healthcareAccess: 50,
            educationIndex: 0.52,
            nationalMotto: 'Bebas, Berdaulat, dan Independen',
            nationalAnthem: 'Himno Nacional de Honduras',
            nationalAnimal: 'Rusa Ekor Putih',
            nationalFlower: 'Bunga Orchid',
            nationalCuisine: ['Baleadas', 'Pupusas', 'Tamales', 'Sopa de Caracol', 'Pastelitos'],
            culturalHeritage: ['Copán', 'Tegucigalpa', 'San Pedro Sula', 'Bay Islands'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 40,
            climate: 'Tropis',
            averageTemperature: 27,
            averageRainfall: 1000,
            forestArea: 30,
            protectedAreas: 10,
            biodiversityRank: 15,
            carbonEmissions: 1.0,
            environmentalIndex: 40,
            riskScore: 55,
            politicalStability: 45,
            crimeIndex: 55,
            militarySpending: 1.0,
            peaceIndex: 60,
            terrorismIndex: 15,
            refugeePopulation: 1000,
            opportunityScore: 40,
            easeOfDoingBusiness: 45,
            innovationIndex: 30,
            startupEcosystem: 35,
            investmentScore: 35,
            talentPool: 50,
            marketSize: 60,
            infrastructureQuality: 40,
            internetSpeed: 15,
            digitalAdoption: 40,
            techEcosystem: 30,
            aiReadiness: 25,
            startups: 30,
            phoneCode: '+504',
            tld: '.hn',
            isoCode: 'HND',
            isoCode2: 'HN',
            drivingSide: 'right',
            tags: ['negara', 'american-tengah', 'karibia', 'budaya', 'sejarah']
        }
    },
    
    
    
    {
        text: 'Nikaragua - Negara di Amerika Tengah dengan danau dan gunung berapi. Ibu kota: Managua. Populasi: 6.7 juta jiwa. Mata uang: Córdoba (NIO). Bahasa: Spanyol. Sistem pemerintahan: Republik Presidensial. Negara dengan Danau Nikaragua dan gunung berapi aktif. Alam yang indah dan budaya yang kaya.',
        metadata: {
            category: 'country',
            region: 'american-tengah',
            name: 'Nikaragua',
            officialName: 'Republik Nikaragua',
            shortName: 'NIC',
            capital: 'Managua',
            capitalCoordinates: { lat: 12.1364, lng: -86.2514 },
            largestCity: 'Managua',
            demonym: 'Nikaragua',
            subregion: 'Central America',
            area: 130375,
            areaRank: 96,
            coastline: 910,
            highestPoint: 'Mogoton',
            highestElevation: 2107,
            lowestPoint: 'Laut Karibia',
            lowestElevation: 0,
            landBorders: ['Honduras', 'Kosta Rika'],
            coordinates: { lat: 13.0, lng: -85.0 },
            timezone: ['Waktu Nikaragua'],
            utcOffset: ['-6'],
            population: 6700000,
            populationRank: 108,
            populationDensity: 51,
            populationGrowth: 1.0,
            medianAge: 27.0,
            lifeExpectancy: 74.0,
            fertilityRate: 2.2,
            urbanization: 60,
            ethnicGroups: [
                { name: 'Mestizo', percentage: 70.0 },
                { name: 'Kulit Putih', percentage: 15.0 },
                { name: 'Kulit Hitam', percentage: 10.0 },
                { name: 'Pribumi', percentage: 5.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 60.0 },
                { name: 'Kristen Protestan', percentage: 30.0 },
                { name: 'Tidak beragama', percentage: 8.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            languages: [
                { name: 'Spanyol', percentage: 100, official: true },
                { name: 'Inggris', percentage: 10 },
                { name: 'Pribumi', percentage: 5 }
            ],
            literacyRate: 82,
            governmentType: 'Republik Presidensial',
            independenceDay: '1821-09-15',
            nationalHoliday: '15 September',
            legalSystem: 'Civil Law',
            constitution: '1987',
            administrativeDivisions: 15,
            memberships: ['PBB', 'OAS', 'SICA', 'CAFTA'],
            giniCoefficient: 46.2,
            hdi: 0.660,
            hdiRank: 126,
            corruptionIndex: 22,
            currency: 'Córdoba',
            currencyCode: 'NIO',
            gdp: 15000000000,
            gdpPerCapita: 2240,
            gdpPpp: 40000000000,
            gdpGrowth: 3.0,
            inflation: 5.0,
            unemployment: 6.0,
            povertyRate: 30.0,
            mainIndustries: ['Pertanian', 'Manufaktur', 'Pariwisata', 'Energi'],
            exports: [
                { item: 'Pertanian', value: 5000000000 },
                { item: 'Manufaktur', value: 3000000000 },
                { item: 'Pariwisata', value: 2000000000 },
                { item: 'Energi', value: 1000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 3000000000 },
                { item: 'Elektronik', value: 2000000000 },
                { item: 'Minyak', value: 1500000000 },
                { item: 'Makanan', value: 1000000000 }
            ],
            tradeBalance: -3000000000,
            naturalResources: ['Kayu', 'Emas', 'Perak', 'Tanah subur'],
            economicRanking: 90,
            internetPenetration: 50,
            mobilePenetration: 70,
            electricityAccess: 85,
            roadLength: 20000,
            railwayLength: 0,
            airports: 20,
            seaports: 5,
            healthcareAccess: 55,
            educationIndex: 0.52,
            nationalMotto: 'Bebas, Berdaulat, dan Independen',
            nationalAnthem: 'Himno Nacional de Nicaragua',
            nationalAnimal: 'Burung Kolibri',
            nationalFlower: 'Sacuanjoche',
            nationalCuisine: ['Gallo Pinto', 'Nacatamales', 'Vigorón', 'Quesillo', 'Indio Viejo'],
            culturalHeritage: ['Managua', 'Granada', 'Leon', 'San Juan del Sur'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 45,
            climate: 'Tropis',
            averageTemperature: 27,
            averageRainfall: 1000,
            forestArea: 25,
            protectedAreas: 10,
            biodiversityRank: 20,
            carbonEmissions: 0.8,
            environmentalIndex: 45,
            riskScore: 50,
            politicalStability: 45,
            crimeIndex: 50,
            militarySpending: 0.5,
            peaceIndex: 60,
            terrorismIndex: 10,
            refugeePopulation: 0,
            opportunityScore: 40,
            easeOfDoingBusiness: 45,
            innovationIndex: 30,
            startupEcosystem: 35,
            investmentScore: 35,
            talentPool: 50,
            marketSize: 55,
            infrastructureQuality: 40,
            internetSpeed: 15,
            digitalAdoption: 40,
            techEcosystem: 30,
            aiReadiness: 25,
            startups: 20,
            phoneCode: '+505',
            tld: '.ni',
            isoCode: 'NIC',
            isoCode2: 'NI',
            drivingSide: 'right',
            tags: ['negara', 'american-tengah', 'danau', 'gunung-berapi', 'budaya']
        }
    },
    
    
    
    {
        text: 'Kosta Rika - Negara di Amerika Tengah dengan keanekaragaman hayati dan pariwisata. Ibu kota: San José. Populasi: 5.1 juta jiwa. Mata uang: Colón (CRC). Bahasa: Spanyol. Sistem pemerintahan: Republik Presidensial. Negara tanpa tentara dan dengan keanekaragaman hayati terbaik. Rumah bagi hutan hujan, gunung berapi, dan pantai-pantai indah.',
        metadata: {
            category: 'country',
            region: 'american-tengah',
            name: 'Kosta Rika',
            officialName: 'Republik Kosta Rika',
            shortName: 'CRI',
            capital: 'San José',
            capitalCoordinates: { lat: 9.9281, lng: -84.0907 },
            largestCity: 'San José',
            demonym: 'Kosta Rika',
            subregion: 'Central America',
            area: 51100,
            areaRank: 126,
            coastline: 1290,
            highestPoint: 'Cerro Chirripo',
            highestElevation: 3820,
            lowestPoint: 'Laut Pasifik',
            lowestElevation: 0,
            landBorders: ['Nikaragua', 'Panama'],
            coordinates: { lat: 10.0, lng: -84.0 },
            timezone: ['Waktu Kosta Rika'],
            utcOffset: ['-6'],
            population: 5100000,
            populationRank: 120,
            populationDensity: 100,
            populationGrowth: 0.8,
            medianAge: 33.0,
            lifeExpectancy: 80.0,
            fertilityRate: 1.5,
            urbanization: 80,
            ethnicGroups: [
                { name: 'Kulit Putih', percentage: 65.0 },
                { name: 'Mestizo', percentage: 20.0 },
                { name: 'Kulit Hitam', percentage: 10.0 },
                { name: 'Pribumi', percentage: 5.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 70.0 },
                { name: 'Kristen Protestan', percentage: 20.0 },
                { name: 'Tidak beragama', percentage: 8.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            languages: [
                { name: 'Spanyol', percentage: 100, official: true },
                { name: 'Inggris', percentage: 20 },
                { name: 'Pribumi', percentage: 5 }
            ],
            literacyRate: 97,
            governmentType: 'Republik Presidensial',
            independenceDay: '1821-09-15',
            nationalHoliday: '15 September',
            legalSystem: 'Civil Law',
            constitution: '1949',
            administrativeDivisions: 7,
            memberships: ['PBB', 'OAS', 'SICA', 'CAFTA'],
            giniCoefficient: 47.0,
            hdi: 0.810,
            hdiRank: 58,
            corruptionIndex: 56,
            currency: 'Colón',
            currencyCode: 'CRC',
            gdp: 65000000000,
            gdpPerCapita: 12700,
            gdpPpp: 100000000000,
            gdpGrowth: 3.5,
            inflation: 2.5,
            unemployment: 8.0,
            povertyRate: 15.0,
            mainIndustries: ['Pariwisata', 'Pertanian', 'Manufaktur', 'Teknologi'],
            exports: [
                { item: 'Pariwisata', value: 30000000000 },
                { item: 'Pertanian', value: 20000000000 },
                { item: 'Manufaktur', value: 15000000000 },
                { item: 'Teknologi', value: 10000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 15000000000 },
                { item: 'Elektronik', value: 10000000000 },
                { item: 'Minyak', value: 8000000000 },
                { item: 'Makanan', value: 6000000000 }
            ],
            tradeBalance: -2000000000,
            naturalResources: ['Kayu', 'Emas', 'Tanah subur', 'Air'],
            economicRanking: 65,
            internetPenetration: 80,
            mobilePenetration: 92,
            electricityAccess: 100,
            roadLength: 40000,
            railwayLength: 1000,
            airports: 20,
            seaports: 10,
            healthcareAccess: 88,
            educationIndex: 0.78,
            nationalMotto: 'Kebebasan, Kesetaraan, Persaudaraan',
            nationalAnthem: 'Himno Nacional de Costa Rica',
            nationalAnimal: 'Rusa Ekor Putih',
            nationalFlower: 'Guaria Morada',
            nationalCuisine: ['Gallo Pinto', 'Casado', 'Tamales', 'Olla de Carne', 'Chifrijo'],
            culturalHeritage: ['San José', 'Arenal', 'Monteverde', 'Puerto Viejo'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 78,
            climate: 'Tropis',
            averageTemperature: 25,
            averageRainfall: 1500,
            forestArea: 50,
            protectedAreas: 25,
            biodiversityRank: 5,
            carbonEmissions: 1.5,
            environmentalIndex: 65,
            riskScore: 20,
            politicalStability: 85,
            crimeIndex: 25,
            militarySpending: 0.0,
            peaceIndex: 20,
            terrorismIndex: 5,
            refugeePopulation: 1000,
            opportunityScore: 65,
            easeOfDoingBusiness: 65,
            innovationIndex: 50,
            startupEcosystem: 55,
            investmentScore: 60,
            talentPool: 65,
            marketSize: 55,
            infrastructureQuality: 65,
            internetSpeed: 30,
            digitalAdoption: 65,
            techEcosystem: 55,
            aiReadiness: 45,
            startups: 150,
            phoneCode: '+506',
            tld: '.cr',
            isoCode: 'CRI',
            isoCode2: 'CR',
            drivingSide: 'right',
            tags: ['negara', 'american-tengah', 'biodiversitas', 'pariwisata', 'tanpa-tentara']
        }
    },
    
    
    
    {
        text: 'Panama - Negara di Amerika Tengah dengan terusan dan ekonomi maju. Ibu kota: Panama City. Populasi: 4.4 juta jiwa. Mata uang: Balboa (PAB), Dolar AS (USD). Bahasa: Spanyol. Sistem pemerintahan: Republik Presidensial. Negara dengan Terusan Panama yang ikonik. Pusat logistik dan keuangan global. Ekonomi terbaik di Amerika Tengah.',
        metadata: {
            category: 'country',
            region: 'american-tengah',
            name: 'Panama',
            officialName: 'Republik Panama',
            shortName: 'PAN',
            capital: 'Panama City',
            capitalCoordinates: { lat: 8.9824, lng: -79.5199 },
            largestCity: 'Panama City',
            demonym: 'Panama',
            subregion: 'Central America',
            area: 75417,
            areaRank: 117,
            coastline: 2490,
            highestPoint: 'Volcan Barú',
            highestElevation: 3474,
            lowestPoint: 'Laut Pasifik',
            lowestElevation: 0,
            landBorders: ['Kosta Rika', 'Kolombia'],
            coordinates: { lat: 9.0, lng: -80.0 },
            timezone: ['Waktu Panama'],
            utcOffset: ['-5'],
            population: 4400000,
            populationRank: 126,
            populationDensity: 58,
            populationGrowth: 1.2,
            medianAge: 30.0,
            lifeExpectancy: 78.0,
            fertilityRate: 2.2,
            urbanization: 68,
            ethnicGroups: [
                { name: 'Mestizo', percentage: 65.0 },
                { name: 'Kulit Hitam', percentage: 15.0 },
                { name: 'Kulit Putih', percentage: 10.0 },
                { name: 'Pribumi', percentage: 10.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 70.0 },
                { name: 'Kristen Protestan', percentage: 20.0 },
                { name: 'Tidak beragama', percentage: 8.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            languages: [
                { name: 'Spanyol', percentage: 100, official: true },
                { name: 'Inggris', percentage: 20 },
                { name: 'Pribumi', percentage: 10 }
            ],
            literacyRate: 95,
            governmentType: 'Republik Presidensial',
            independenceDay: '1903-11-03',
            nationalHoliday: '3 November',
            legalSystem: 'Civil Law',
            constitution: '1972',
            administrativeDivisions: 10,
            memberships: ['PBB', 'OAS', 'SICA', 'CAFTA'],
            giniCoefficient: 50.0,
            hdi: 0.815,
            hdiRank: 53,
            corruptionIndex: 38,
            currency: 'Balboa',
            currencyCode: 'PAB',
            gdp: 80000000000,
            gdpPerCapita: 18100,
            gdpPpp: 150000000000,
            gdpGrowth: 5.0,
            inflation: 2.0,
            unemployment: 5.0,
            povertyRate: 15.0,
            mainIndustries: ['Logistik', 'Keuangan', 'Pariwisata', 'Manufaktur', 'Pertanian'],
            exports: [
                { item: 'Logistik', value: 30000000000 },
                { item: 'Keuangan', value: 20000000000 },
                { item: 'Pariwisata', value: 15000000000 },
                { item: 'Pertanian', value: 10000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 20000000000 },
                { item: 'Elektronik', value: 15000000000 },
                { item: 'Minyak', value: 10000000000 },
                { item: 'Makanan', value: 8000000000 }
            ],
            tradeBalance: 10000000000,
            naturalResources: ['Kayu', 'Emas', 'Perak', 'Tanah subur'],
            economicRanking: 50,
            internetPenetration: 80,
            mobilePenetration: 90,
            electricityAccess: 100,
            roadLength: 15000,
            railwayLength: 600,
            airports: 20,
            seaports: 10,
            healthcareAccess: 80,
            educationIndex: 0.72,
            nationalMotto: 'Untuk kepentingan dunia',
            nationalAnthem: 'Himno Istmeño',
            nationalAnimal: 'Elang',
            nationalFlower: 'Santa Rita',
            nationalCuisine: ['Sancocho', 'Ceviche', 'Arroz con Pollo', 'Patacones', 'Ropa Vieja'],
            culturalHeritage: ['Panama City', 'Casco Viejo', 'Panama Canal', 'San Blas'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 72,
            climate: 'Tropis',
            averageTemperature: 27,
            averageRainfall: 1500,
            forestArea: 50,
            protectedAreas: 15,
            biodiversityRank: 8,
            carbonEmissions: 2.5,
            environmentalIndex: 55,
            riskScore: 25,
            politicalStability: 75,
            crimeIndex: 30,
            militarySpending: 0.5,
            peaceIndex: 30,
            terrorismIndex: 5,
            refugeePopulation: 0,
            opportunityScore: 70,
            easeOfDoingBusiness: 72,
            innovationIndex: 55,
            startupEcosystem: 60,
            investmentScore: 65,
            talentPool: 65,
            marketSize: 60,
            infrastructureQuality: 75,
            internetSpeed: 35,
            digitalAdoption: 70,
            techEcosystem: 60,
            aiReadiness: 50,
            startups: 100,
            phoneCode: '+507',
            tld: '.pa',
            isoCode: 'PAN',
            isoCode2: 'PA',
            drivingSide: 'right',
            tags: ['negara', 'american-tengah', 'terusan', 'logistik', 'keuangan']
        }
    },
    
    
    
    {
        text: 'Belize - Negara di Amerika Tengah dengan bahasa Inggris dan alam indah. Ibu kota: Belmopan. Populasi: 400 ribu jiwa. Mata uang: Dolar Belize (BZD). Bahasa: Inggris. Sistem pemerintahan: Monarki Konstitusional Parlementer. Negara dengan pantai Karibia dan terumbu karang. Bahasa Inggris resmi. Destinasi wisata alam dan budaya Maya.',
        metadata: {
            category: 'country',
            region: 'american-tengah',
            name: 'Belize',
            officialName: 'Belize',
            shortName: 'BLZ',
            capital: 'Belmopan',
            capitalCoordinates: { lat: 17.2510, lng: -88.7712 },
            largestCity: 'Belize City',
            demonym: 'Belize',
            subregion: 'Central America',
            area: 22966,
            areaRank: 147,
            coastline: 386,
            highestPoint: 'Doyle\'s Delight',
            highestElevation: 1124,
            lowestPoint: 'Laut Karibia',
            lowestElevation: 0,
            landBorders: ['Meksiko', 'Guatemala'],
            coordinates: { lat: 17.25, lng: -88.75 },
            timezone: ['Waktu Belize'],
            utcOffset: ['-6'],
            population: 400000,
            populationRank: 172,
            populationDensity: 17,
            populationGrowth: 1.5,
            medianAge: 26.0,
            lifeExpectancy: 74.0,
            fertilityRate: 2.3,
            urbanization: 45,
            ethnicGroups: [
                { name: 'Mestizo', percentage: 50.0 },
                { name: 'Kulit Hitam', percentage: 25.0 },
                { name: 'Maya', percentage: 15.0 },
                { name: 'Kulit Putih', percentage: 10.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 40.0 },
                { name: 'Kristen Protestan', percentage: 35.0 },
                { name: 'Tidak beragama', percentage: 20.0 },
                { name: 'Lainnya', percentage: 5.0 }
            ],
            languages: [
                { name: 'Inggris', percentage: 100, official: true },
                { name: 'Spanyol', percentage: 50 },
                { name: 'Kreol', percentage: 40 },
                { name: 'Maya', percentage: 10 }
            ],
            literacyRate: 82,
            governmentType: 'Monarki Konstitusional Parlementer',
            independenceDay: '1981-09-21',
            nationalHoliday: '21 September',
            legalSystem: 'Common Law',
            constitution: '1981',
            administrativeDivisions: 6,
            memberships: ['PBB', 'CARICOM', 'Commonwealth', 'OAS', 'SICA'],
            giniCoefficient: 42.0,
            hdi: 0.683,
            hdiRank: 118,
            corruptionIndex: 40,
            currency: 'Dolar Belize',
            currencyCode: 'BZD',
            gdp: 3000000000,
            gdpPerCapita: 7500,
            gdpPpp: 4000000000,
            gdpGrowth: 3.5,
            inflation: 2.5,
            unemployment: 8.0,
            povertyRate: 30.0,
            mainIndustries: ['Pariwisata', 'Pertanian', 'Keuangan', 'Manufaktur'],
            exports: [
                { item: 'Pariwisata', value: 1000000000 },
                { item: 'Pertanian', value: 800000000 },
                { item: 'Manufaktur', value: 500000000 },
                { item: 'Keuangan', value: 300000000 }
            ],
            imports: [
                { item: 'Mesin', value: 500000000 },
                { item: 'Elektronik', value: 300000000 },
                { item: 'Makanan', value: 200000000 },
                { item: 'Minyak', value: 150000000 }
            ],
            tradeBalance: -500000000,
            naturalResources: ['Kayu', 'Perikanan', 'Tanah subur'],
            economicRanking: 100,
            internetPenetration: 60,
            mobilePenetration: 75,
            electricityAccess: 90,
            roadLength: 3000,
            railwayLength: 0,
            airports: 10,
            seaports: 5,
            healthcareAccess: 65,
            educationIndex: 0.62,
            nationalMotto: 'Di bawah naungan, saya berkembang',
            nationalAnthem: 'Land of the Free',
            nationalAnimal: 'Tapir',
            nationalFlower: 'Black Orchid',
            nationalCuisine: ['Rice and Beans', 'Stew Chicken', 'Fry Jacks', 'Conch Fritters', 'Pupusas'],
            culturalHeritage: ['Belize City', 'Belmopan', 'San Ignacio', 'Caye Caulker'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 55,
            climate: 'Tropis',
            averageTemperature: 27,
            averageRainfall: 1500,
            forestArea: 60,
            protectedAreas: 20,
            biodiversityRank: 10,
            carbonEmissions: 1.5,
            environmentalIndex: 55,
            riskScore: 35,
            politicalStability: 75,
            crimeIndex: 35,
            militarySpending: 0.5,
            peaceIndex: 35,
            terrorismIndex: 5,
            refugeePopulation: 0,
            opportunityScore: 50,
            easeOfDoingBusiness: 55,
            innovationIndex: 35,
            startupEcosystem: 40,
            investmentScore: 45,
            talentPool: 45,
            marketSize: 35,
            infrastructureQuality: 50,
            internetSpeed: 20,
            digitalAdoption: 45,
            techEcosystem: 35,
            aiReadiness: 30,
            startups: 20,
            phoneCode: '+501',
            tld: '.bz',
            isoCode: 'BLZ',
            isoCode2: 'BZ',
            drivingSide: 'right',
            tags: ['negara', 'american-tengah', 'karibia', 'inggris', 'terumbu']
        }
    },
    
    
    
    {
        text: 'El Salvador - Negara di Amerika Tengah dengan ekonomi dan budaya kaya. Ibu kota: San Salvador. Populasi: 6.5 juta jiwa. Mata uang: Dolar AS (USD). Bahasa: Spanyol. Sistem pemerintahan: Republik Presidensial. Negara dengan pantai-pantai indah dan budaya kaya. Pemimpin global dalam adopsi Bitcoin. Ekonomi dengan pertumbuhan tinggi dan inovasi.',
        metadata: {
            category: 'country',
            region: 'american-tengah',
            name: 'El Salvador',
            officialName: 'Republik El Salvador',
            shortName: 'SLV',
            capital: 'San Salvador',
            capitalCoordinates: { lat: 13.6929, lng: -89.2182 },
            largestCity: 'San Salvador',
            demonym: 'El Salvador',
            subregion: 'Central America',
            area: 21041,
            areaRank: 148,
            coastline: 307,
            highestPoint: 'Cerro El Pital',
            highestElevation: 2730,
            lowestPoint: 'Laut Pasifik',
            lowestElevation: 0,
            landBorders: ['Guatemala', 'Honduras'],
            coordinates: { lat: 13.8333, lng: -88.9167 },
            timezone: ['Waktu El Salvador'],
            utcOffset: ['-6'],
            population: 6500000,
            populationRank: 107,
            populationDensity: 309,
            populationGrowth: 0.5,
            medianAge: 28.0,
            lifeExpectancy: 73.0,
            fertilityRate: 2.0,
            urbanization: 73,
            ethnicGroups: [
                { name: 'Mestizo', percentage: 86.0 },
                { name: 'Kulit Putih', percentage: 12.0 },
                { name: 'Pribumi', percentage: 2.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 50.0 },
                { name: 'Kristen Protestan', percentage: 40.0 },
                { name: 'Tidak beragama', percentage: 8.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            languages: [
                { name: 'Spanyol', percentage: 100, official: true },
                { name: 'Nahuatl', percentage: 5 },
                { name: 'Inggris', percentage: 10 }
            ],
            literacyRate: 89,
            governmentType: 'Republik Presidensial',
            independenceDay: '1821-09-15',
            nationalHoliday: '15 September',
            legalSystem: 'Civil Law',
            constitution: '1983',
            administrativeDivisions: 14,
            memberships: ['PBB', 'OAS', 'SICA', 'CAFTA'],
            giniCoefficient: 38.0,
            hdi: 0.706,
            hdiRank: 115,
            corruptionIndex: 34,
            currency: 'Dolar AS',
            currencyCode: 'USD',
            gdp: 35000000000,
            gdpPerCapita: 5380,
            gdpPpp: 60000000000,
            gdpGrowth: 3.0,
            inflation: 3.5,
            unemployment: 6.0,
            povertyRate: 25.0,
            mainIndustries: ['Manufaktur', 'Pertanian', 'Pariwisata', 'Keuangan', 'Bitcoin'],
            exports: [
                { item: 'Manufaktur', value: 10000000000 },
                { item: 'Pertanian', value: 5000000000 },
                { item: 'Pariwisata', value: 3000000000 },
                { item: 'Keuangan', value: 2000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 5000000000 },
                { item: 'Elektronik', value: 4000000000 },
                { item: 'Minyak', value: 3000000000 },
                { item: 'Makanan', value: 2000000000 }
            ],
            tradeBalance: -2000000000,
            naturalResources: ['Emas', 'Perak', 'Kayu', 'Tanah subur'],
            economicRanking: 80,
            internetPenetration: 60,
            mobilePenetration: 80,
            electricityAccess: 95,
            roadLength: 10000,
            railwayLength: 0,
            airports: 20,
            seaports: 5,
            healthcareAccess: 65,
            educationIndex: 0.62,
            nationalMotto: 'Kebebasan, Kemakmuran, Kejayaan',
            nationalAnthem: 'Himno Nacional de El Salvador',
            nationalAnimal: 'Motmot',
            nationalFlower: 'Bunga Izote',
            nationalCuisine: ['Pupusas', 'Tamales', 'Yuca Frita', 'Sopa de Pescado', 'Pastelitos'],
            culturalHeritage: ['San Salvador', 'Santa Ana', 'San Miguel', 'La Libertad'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 50,
            climate: 'Tropis',
            averageTemperature: 27,
            averageRainfall: 1000,
            forestArea: 10,
            protectedAreas: 5,
            biodiversityRank: 20,
            carbonEmissions: 1.5,
            environmentalIndex: 42,
            riskScore: 45,
            politicalStability: 55,
            crimeIndex: 45,
            militarySpending: 0.5,
            peaceIndex: 55,
            terrorismIndex: 10,
            refugeePopulation: 1000,
            opportunityScore: 50,
            easeOfDoingBusiness: 55,
            innovationIndex: 40,
            startupEcosystem: 45,
            investmentScore: 50,
            talentPool: 55,
            marketSize: 60,
            infrastructureQuality: 50,
            internetSpeed: 20,
            digitalAdoption: 55,
            techEcosystem: 45,
            aiReadiness: 40,
            startups: 50,
            phoneCode: '+503',
            tld: '.sv',
            isoCode: 'SLV',
            isoCode2: 'SV',
            drivingSide: 'right',
            tags: ['negara', 'american-tengah', 'bitcoin', 'pariwisata', 'budaya']
        }
    },
    
    
    
    {
        text: 'Kuba - Negara kepulauan di Karibia dengan budaya dan sejarah kaya. Ibu kota: Havana. Populasi: 11.3 juta jiwa. Mata uang: Peso Kuba (CUP). Bahasa: Spanyol. Sistem pemerintahan: Republik Sosialis. Negara dengan musik, tari, dan budaya Karibia yang kaya. Rumah bagi cerutu terbaik dunia dan arsitektur kolonial.',
        metadata: {
            category: 'country',
            region: 'american-tengah',
            name: 'Kuba',
            officialName: 'Republik Kuba',
            shortName: 'CUB',
            capital: 'Havana',
            capitalCoordinates: { lat: 23.1136, lng: -82.3666 },
            largestCity: 'Havana',
            demonym: 'Kuba',
            subregion: 'Caribbean',
            area: 109884,
            areaRank: 104,
            coastline: 3735,
            highestPoint: 'Pico Turquino',
            highestElevation: 1974,
            lowestPoint: 'Laut Karibia',
            lowestElevation: 0,
            landBorders: [],
            coordinates: { lat: 22.0, lng: -79.0 },
            timezone: ['Waktu Kuba'],
            utcOffset: ['-5'],
            population: 11300000,
            populationRank: 82,
            populationDensity: 103,
            populationGrowth: -0.1,
            medianAge: 42.0,
            lifeExpectancy: 79.0,
            fertilityRate: 1.5,
            urbanization: 77,
            ethnicGroups: [
                { name: 'Kulit Putih', percentage: 64.0 },
                { name: 'Kulit Hitam', percentage: 9.0 },
                { name: 'Mestizo', percentage: 27.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 60.0 },
                { name: 'Santeria', percentage: 10.0 },
                { name: 'Tidak beragama', percentage: 25.0 },
                { name: 'Lainnya', percentage: 5.0 }
            ],
            languages: [
                { name: 'Spanyol', percentage: 100, official: true },
                { name: 'Inggris', percentage: 10 }
            ],
            literacyRate: 99,
            governmentType: 'Republik Sosialis',
            independenceDay: '1902-05-20',
            nationalHoliday: '1 Januari',
            legalSystem: 'Civil Law',
            constitution: '2019',
            administrativeDivisions: 15,
            memberships: ['PBB', 'ALBA', 'CARICOM'],
            giniCoefficient: 38.0,
            hdi: 0.764,
            hdiRank: 83,
            corruptionIndex: 45,
            currency: 'Peso Kuba',
            currencyCode: 'CUP',
            gdp: 100000000000,
            gdpPerCapita: 8850,
            gdpPpp: 150000000000,
            gdpGrowth: 1.5,
            inflation: 5.0,
            unemployment: 2.0,
            povertyRate: 10.0,
            mainIndustries: ['Pariwisata', 'Manufaktur', 'Pertanian', 'Tambang'],
            exports: [
                { item: 'Nikèl', value: 5000000000 },
                { item: 'Pariwisata', value: 4000000000 },
                { item: 'Tembakau', value: 3000000000 },
                { item: 'Gula', value: 2000000000 }
            ],
            imports: [
                { item: 'Makanan', value: 5000000000 },
                { item: 'Mesin', value: 4000000000 },
                { item: 'Minyak', value: 3000000000 },
                { item: 'Elektronik', value: 2000000000 }
            ],
            tradeBalance: -2000000000,
            naturalResources: ['Nikèl', 'Tembaga', 'Gula', 'Kayu', 'Tembakau'],
            economicRanking: 65,
            internetPenetration: 60,
            mobilePenetration: 75,
            electricityAccess: 100,
            roadLength: 60000,
            railwayLength: 4000,
            airports: 20,
            seaports: 10,
            healthcareAccess: 95,
            educationIndex: 0.75,
            nationalMotto: 'Tanah air atau mati',
            nationalAnthem: 'La Bayamesa',
            nationalAnimal: 'Trogon',
            nationalFlower: 'Mariposa',
            nationalCuisine: ['Ropa Vieja', 'Moros y Cristianos', 'Yuca', 'Tostones', 'Cuban Sandwich'],
            culturalHeritage: ['Havana', 'Trinidad', 'Varadero', 'Santiago'],
            publicHolidays: ['Hari Kemerdekaan', 'Hari Revolusi', 'Christmas', 'Tahun Baru'],
            socialRanking: 65,
            climate: 'Tropis',
            averageTemperature: 26,
            averageRainfall: 1000,
            forestArea: 25,
            protectedAreas: 15,
            biodiversityRank: 15,
            carbonEmissions: 2.5,
            environmentalIndex: 50,
            riskScore: 40,
            politicalStability: 60,
            crimeIndex: 30,
            militarySpending: 2.5,
            peaceIndex: 45,
            terrorismIndex: 10,
            refugeePopulation: 5000,
            opportunityScore: 45,
            easeOfDoingBusiness: 35,
            innovationIndex: 35,
            startupEcosystem: 30,
            investmentScore: 35,
            talentPool: 65,
            marketSize: 60,
            infrastructureQuality: 50,
            internetSpeed: 15,
            digitalAdoption: 45,
            techEcosystem: 35,
            aiReadiness: 30,
            startups: 50,
            phoneCode: '+53',
            tld: '.cu',
            isoCode: 'CUB',
            isoCode2: 'CU',
            drivingSide: 'right',
            tags: ['negara', 'american-tengah', 'karibia', 'sejarah', 'budaya']
        }
    }
];

export const DATA = data;




if (window.InternalLogger) {
    window.InternalLogger.info('CountryAmericanTengah', '✅ Loaded ' + data.length + ' countries (SUPER LENGKAP - 8 NEGARA!)');
}
