const data = [
    // ==========================================================
    // 🇧🇷 BRASIL
    // ==========================================================
    {
        text: 'Brasil - Negara terbesar di Amerika Selatan dengan ekonomi dan Amazon. Ibu kota: Brasilia. Populasi: 215 juta jiwa. Mata uang: Real (BRL). Bahasa: Portugis. Sistem pemerintahan: Republik Federal Presidensial. Anggota G20, BRICS, dan PBB. Negara dengan hutan Amazon terbesar di dunia dan keanekaragaman hayati terkaya. Rumah bagi karnaval Rio, sepak bola, dan pantai Copacabana.',
        metadata: {
            category: 'country',
            region: 'american-selatan',
            name: 'Brasil',
            officialName: 'Republik Federal Brasil',
            shortName: 'BRA',
            capital: 'Brasilia',
            capitalCoordinates: { lat: -15.7939, lng: -47.8828 },
            largestCity: 'São Paulo',
            demonym: 'Brasil',
            subregion: 'South America',
            area: 8515767,
            areaRank: 5,
            coastline: 7491,
            highestPoint: 'Pico da Neblina',
            highestElevation: 2995,
            lowestPoint: 'Laut Atlantik',
            lowestElevation: 0,
            landBorders: ['Argentina', 'Bolivia', 'Kolombia', 'Guyana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela'],
            coordinates: { lat: -14.0, lng: -51.0 },
            timezone: ['UTC-5 hingga UTC-2'],
            utcOffset: ['-5', '-4', '-3', '-2'],
            population: 215000000,
            populationRank: 6,
            populationDensity: 25,
            populationGrowth: 0.7,
            medianAge: 33.0,
            lifeExpectancy: 76.0,
            fertilityRate: 1.7,
            urbanization: 87,
            ethnicGroups: [
                { name: 'Kulit Putih', percentage: 47.7 },
                { name: 'Pardo', percentage: 43.1 },
                { name: 'Kulit Hitam', percentage: 7.6 },
                { name: 'Asia', percentage: 1.1 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 65.0 },
                { name: 'Kristen Protestan', percentage: 22.0 },
                { name: 'Tidak beragama', percentage: 8.0 },
                { name: 'Lainnya', percentage: 5.0 }
            ],
            languages: [
                { name: 'Portugis', percentage: 100, official: true },
                { name: 'Inggris', percentage: 10 },
                { name: 'Spanyol', percentage: 5 }
            ],
            literacyRate: 93,
            governmentType: 'Republik Federal Presidensial',
            independenceDay: '1822-09-07',
            nationalHoliday: '7 September',
            legalSystem: 'Civil Law',
            constitution: '1988',
            administrativeDivisions: 26,
            memberships: ['PBB', 'G20', 'BRICS', 'OECD', 'WTO'],
            giniCoefficient: 53.9,
            hdi: 0.765,
            hdiRank: 82,
            corruptionIndex: 38,
            currency: 'Real',
            currencyCode: 'BRL',
            gdp: 2100000000000,
            gdpPerCapita: 9760,
            gdpPpp: 4000000000000,
            gdpGrowth: 2.5,
            inflation: 4.5,
            unemployment: 8.0,
            povertyRate: 20.0,
            mainIndustries: ['Pertanian', 'Tambang', 'Manufaktur', 'Pariwisata', 'Energi'],
            exports: [
                { item: 'Kedelai', value: 100000000000 },
                { item: 'Biji besi', value: 80000000000 },
                { item: 'Minyak', value: 60000000000 },
                { item: 'Daging', value: 40000000000 }
            ],
            imports: [
                { item: 'Elektronik', value: 80000000000 },
                { item: 'Mesin', value: 70000000000 },
                { item: 'Minyak', value: 50000000000 },
                { item: 'Bahan kimia', value: 40000000000 }
            ],
            tradeBalance: 50000000000,
            naturalResources: ['Biji besi', 'Emas', 'Minyak', 'Kayu', 'Air', 'Tanah subur'],
            economicRanking: 12,
            internetPenetration: 70,
            mobilePenetration: 85,
            electricityAccess: 100,
            roadLength: 1700000,
            railwayLength: 29000,
            airports: 4000,
            seaports: 100,
            healthcareAccess: 75,
            educationIndex: 0.65,
            nationalMotto: 'Kemerdekaan atau Mati',
            nationalAnthem: 'Hino Nacional Brasileiro',
            nationalAnimal: 'Jaguar',
            nationalFlower: 'Bunga Ipê',
            nationalCuisine: ['Feijoada', 'Churrasco', 'Acarajé', 'Coxinha', 'Brigadeiro'],
            culturalHeritage: ['Rio de Janeiro', 'Amazon', 'Iguazu Falls', 'Salvador'],
            publicHolidays: ['Hari Kemerdekaan', 'Karnaval', 'Christmas', 'Tahun Baru'],
            socialRanking: 55,
            climate: 'Beragam',
            averageTemperature: 25,
            averageRainfall: 1500,
            forestArea: 60,
            protectedAreas: 15,
            biodiversityRank: 1,
            carbonEmissions: 2.5,
            environmentalIndex: 45,
            riskScore: 40,
            politicalStability: 50,
            crimeIndex: 50,
            militarySpending: 1.5,
            peaceIndex: 55,
            terrorismIndex: 10,
            refugeePopulation: 10000,
            opportunityScore: 60,
            easeOfDoingBusiness: 55,
            innovationIndex: 50,
            startupEcosystem: 60,
            investmentScore: 55,
            talentPool: 80,
            marketSize: 90,
            infrastructureQuality: 55,
            internetSpeed: 30,
            digitalAdoption: 65,
            techEcosystem: 60,
            aiReadiness: 50,
            startups: 1500,
            phoneCode: '+55',
            tld: '.br',
            isoCode: 'BRA',
            isoCode2: 'BR',
            drivingSide: 'right',
            tags: ['negara', 'american-selatan', 'g20', 'brics', 'amazon']
        }
    },
    // ==========================================================
    // 🇦🇷 ARGENTINA
    // ==========================================================
    {
        text: 'Argentina - Negara di Amerika Selatan dengan budaya tango dan ekonomi agrikultur. Ibu kota: Buenos Aires. Populasi: 46 juta jiwa. Mata uang: Peso (ARS). Bahasa: Spanyol. Sistem pemerintahan: Republik Federal Presidensial. Anggota G20 dan Mercosur. Negara dengan pampas luas, daging sapi terbaik, dan wine Malbec terkenal. Rumah bagi Patagonia dan Air Terjun Iguazu.',
        metadata: {
            category: 'country',
            region: 'american-selatan',
            name: 'Argentina',
            officialName: 'Republik Argentina',
            shortName: 'ARG',
            capital: 'Buenos Aires',
            capitalCoordinates: { lat: -34.6037, lng: -58.3816 },
            largestCity: 'Buenos Aires',
            demonym: 'Argentina',
            subregion: 'South America',
            area: 2780400,
            areaRank: 8,
            coastline: 4989,
            highestPoint: 'Aconcagua',
            highestElevation: 6960,
            lowestPoint: 'Laguna del Carbón',
            lowestElevation: -105,
            landBorders: ['Chili', 'Bolivia', 'Paraguay', 'Brasil', 'Uruguay'],
            coordinates: { lat: -34.0, lng: -64.0 },
            timezone: ['UTC-3'],
            utcOffset: ['-3'],
            population: 46000000,
            populationRank: 31,
            populationDensity: 16,
            populationGrowth: 0.5,
            medianAge: 32.0,
            lifeExpectancy: 78.0,
            fertilityRate: 1.9,
            urbanization: 92,
            ethnicGroups: [
                { name: 'Kulit Putih', percentage: 85.0 },
                { name: 'Mestizo', percentage: 10.0 },
                { name: 'Pribumi', percentage: 3.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 70.0 },
                { name: 'Kristen Protestan', percentage: 15.0 },
                { name: 'Tidak beragama', percentage: 12.0 },
                { name: 'Lainnya', percentage: 3.0 }
            ],
            languages: [
                { name: 'Spanyol', percentage: 100, official: true },
                { name: 'Inggris', percentage: 15 },
                { name: 'Italia', percentage: 5 }
            ],
            literacyRate: 99,
            governmentType: 'Republik Federal Presidensial',
            independenceDay: '1816-07-09',
            nationalHoliday: '9 Juli',
            legalSystem: 'Civil Law',
            constitution: '1853',
            administrativeDivisions: 23,
            memberships: ['PBB', 'G20', 'Mercosur', 'WTO'],
            giniCoefficient: 41.4,
            hdi: 0.845,
            hdiRank: 46,
            corruptionIndex: 38,
            currency: 'Peso',
            currencyCode: 'ARS',
            gdp: 600000000000,
            gdpPerCapita: 13040,
            gdpPpp: 1200000000000,
            gdpGrowth: 2.0,
            inflation: 50.0,
            unemployment: 8.0,
            povertyRate: 35.0,
            mainIndustries: ['Pertanian', 'Manufaktur', 'Tambang', 'Pariwisata', 'Teknologi'],
            exports: [
                { item: 'Kedelai', value: 30000000000 },
                { item: 'Daging', value: 20000000000 },
                { item: 'Gandum', value: 15000000000 },
                { item: 'Wine', value: 10000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 30000000000 },
                { item: 'Elektronik', value: 20000000000 },
                { item: 'Minyak', value: 15000000000 },
                { item: 'Bahan kimia', value: 10000000000 }
            ],
            tradeBalance: 5000000000,
            naturalResources: ['Tanah subur', 'Emas', 'Lithium', 'Gas', 'Minyak'],
            economicRanking: 25,
            internetPenetration: 85,
            mobilePenetration: 92,
            electricityAccess: 100,
            roadLength: 700000,
            railwayLength: 36000,
            airports: 1000,
            seaports: 50,
            healthcareAccess: 85,
            educationIndex: 0.78,
            nationalMotto: 'Dalam Persatuan dan Kebebasan',
            nationalAnthem: 'Himno Nacional Argentino',
            nationalAnimal: 'Rufous Hornero',
            nationalFlower: 'Ceibo',
            nationalCuisine: ['Asado', 'Empanadas', 'Milanesa', 'Mate', 'Dulce de Leche'],
            culturalHeritage: ['Buenos Aires', 'Iguazu Falls', 'Patagonia', 'Mendoza'],
            publicHolidays: ['Hari Kemerdekaan', 'Hari Revolusi', 'Paskah', 'Christmas'],
            socialRanking: 65,
            climate: 'Beragam',
            averageTemperature: 15,
            averageRainfall: 600,
            forestArea: 10,
            protectedAreas: 8,
            biodiversityRank: 15,
            carbonEmissions: 4.0,
            environmentalIndex: 50,
            riskScore: 55,
            politicalStability: 45,
            crimeIndex: 40,
            militarySpending: 0.8,
            peaceIndex: 50,
            terrorismIndex: 10,
            refugeePopulation: 5000,
            opportunityScore: 50,
            easeOfDoingBusiness: 45,
            innovationIndex: 45,
            startupEcosystem: 50,
            investmentScore: 45,
            talentPool: 75,
            marketSize: 80,
            infrastructureQuality: 60,
            internetSpeed: 35,
            digitalAdoption: 70,
            techEcosystem: 55,
            aiReadiness: 45,
            startups: 500,
            phoneCode: '+54',
            tld: '.ar',
            isoCode: 'ARG',
            isoCode2: 'AR',
            drivingSide: 'right',
            tags: ['negara', 'american-selatan', 'g20', 'tango', 'daging']
        }
    },
    // ==========================================================
    // 🇨🇴 KOLOMBIA
    // ==========================================================
    {
        text: 'Kolombia - Negara di Amerika Selatan dengan kopi dan keanekaragaman hayati. Ibu kota: Bogota. Populasi: 52 juta jiwa. Mata uang: Peso (COP). Bahasa: Spanyol. Sistem pemerintahan: Republik Presidensial. Anggota OECD dan PBB. Negara dengan kopi terbaik dunia, keanekaragaman hayati terkaya, dan pemandangan Andes yang indah.',
        metadata: {
            category: 'country',
            region: 'american-selatan',
            name: 'Kolombia',
            officialName: 'Republik Kolombia',
            shortName: 'COL',
            capital: 'Bogota',
            capitalCoordinates: { lat: 4.7110, lng: -74.0721 },
            largestCity: 'Bogota',
            demonym: 'Kolombia',
            subregion: 'South America',
            area: 1141748,
            areaRank: 25,
            coastline: 3208,
            highestPoint: 'Pico Cristóbal Colón',
            highestElevation: 5775,
            lowestPoint: 'Laut Pasifik',
            lowestElevation: 0,
            landBorders: ['Ekuador', 'Peru', 'Brasil', 'Venezuela', 'Panama'],
            coordinates: { lat: 4.0, lng: -72.0 },
            timezone: ['UTC-5'],
            utcOffset: ['-5'],
            population: 52000000,
            populationRank: 28,
            populationDensity: 45,
            populationGrowth: 0.9,
            medianAge: 31.0,
            lifeExpectancy: 77.0,
            fertilityRate: 1.8,
            urbanization: 81,
            ethnicGroups: [
                { name: 'Mestizo', percentage: 50.0 },
                { name: 'Kulit Putih', percentage: 25.0 },
                { name: 'Kulit Hitam', percentage: 15.0 },
                { name: 'Pribumi', percentage: 5.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 75.0 },
                { name: 'Kristen Protestan', percentage: 15.0 },
                { name: 'Tidak beragama', percentage: 8.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            languages: [
                { name: 'Spanyol', percentage: 100, official: true },
                { name: 'Inggris', percentage: 10 },
                { name: 'Pribumi', percentage: 5 }
            ],
            literacyRate: 95,
            governmentType: 'Republik Presidensial',
            independenceDay: '1810-07-20',
            nationalHoliday: '20 Juli',
            legalSystem: 'Civil Law',
            constitution: '1991',
            administrativeDivisions: 32,
            memberships: ['PBB', 'OECD', 'WTO', 'OAS'],
            giniCoefficient: 51.0,
            hdi: 0.767,
            hdiRank: 81,
            corruptionIndex: 39,
            currency: 'Peso',
            currencyCode: 'COP',
            gdp: 350000000000,
            gdpPerCapita: 6730,
            gdpPpp: 800000000000,
            gdpGrowth: 3.5,
            inflation: 4.5,
            unemployment: 10.0,
            povertyRate: 30.0,
            mainIndustries: ['Kopi', 'Pertanian', 'Manufaktur', 'Pariwisata', 'Energi'],
            exports: [
                { item: 'Kopi', value: 30000000000 },
                { item: 'Minyak', value: 20000000000 },
                { item: 'Emas', value: 15000000000 },
                { item: 'Bunga', value: 10000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 30000000000 },
                { item: 'Elektronik', value: 20000000000 },
                { item: 'Minyak', value: 15000000000 },
                { item: 'Makanan', value: 10000000000 }
            ],
            tradeBalance: -5000000000,
            naturalResources: ['Emas', 'Minyak', 'Kopi', 'Batu bara', 'Tanah subur'],
            economicRanking: 40,
            internetPenetration: 70,
            mobilePenetration: 85,
            electricityAccess: 100,
            roadLength: 200000,
            railwayLength: 2000,
            airports: 1000,
            seaports: 50,
            healthcareAccess: 78,
            educationIndex: 0.68,
            nationalMotto: 'Kebebasan dan Ketertiban',
            nationalAnthem: 'Himno Nacional de Colombia',
            nationalAnimal: 'Condor Andes',
            nationalFlower: 'Orchid',
            nationalCuisine: ['Bandeja Paisa', 'Arepa', 'Sancocho', 'Empanadas', 'Ajiaco'],
            culturalHeritage: ['Bogota', 'Medellin', 'Cartagena', 'Coffee Region'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 60,
            climate: 'Beragam',
            averageTemperature: 22,
            averageRainfall: 1000,
            forestArea: 50,
            protectedAreas: 15,
            biodiversityRank: 2,
            carbonEmissions: 1.5,
            environmentalIndex: 50,
            riskScore: 45,
            politicalStability: 50,
            crimeIndex: 45,
            militarySpending: 2.0,
            peaceIndex: 55,
            terrorismIndex: 30,
            refugeePopulation: 100000,
            opportunityScore: 55,
            easeOfDoingBusiness: 55,
            innovationIndex: 45,
            startupEcosystem: 55,
            investmentScore: 50,
            talentPool: 75,
            marketSize: 80,
            infrastructureQuality: 55,
            internetSpeed: 25,
            digitalAdoption: 60,
            techEcosystem: 55,
            aiReadiness: 45,
            startups: 300,
            phoneCode: '+57',
            tld: '.co',
            isoCode: 'COL',
            isoCode2: 'CO',
            drivingSide: 'right',
            tags: ['negara', 'american-selatan', 'kopi', 'oecd', 'biodiversitas']
        }
    },
    // ==========================================================
    // 🇨🇱 CHILI
    // ==========================================================
    {
        text: 'Chili - Negara di Amerika Selatan dengan tambang tembaga dan anggur. Ibu kota: Santiago. Populasi: 19.5 juta jiwa. Mata uang: Peso (CLP). Bahasa: Spanyol. Sistem pemerintahan: Republik Presidensial. Anggota OECD dan PBB. Negara dengan tembaga terbesar dunia, wine berkualitas tinggi, dan pemandangan Patagonia yang indah.',
        metadata: {
            category: 'country',
            region: 'american-selatan',
            name: 'Chili',
            officialName: 'Republik Chili',
            shortName: 'CHL',
            capital: 'Santiago',
            capitalCoordinates: { lat: -33.4489, lng: -70.6693 },
            largestCity: 'Santiago',
            demonym: 'Chili',
            subregion: 'South America',
            area: 756102,
            areaRank: 37,
            coastline: 6435,
            highestPoint: 'Ojos del Salado',
            highestElevation: 6893,
            lowestPoint: 'Laut Pasifik',
            lowestElevation: 0,
            landBorders: ['Argentina', 'Bolivia', 'Peru'],
            coordinates: { lat: -30.0, lng: -71.0 },
            timezone: ['UTC-3 hingga UTC-5'],
            utcOffset: ['-3', '-4', '-5'],
            population: 19500000,
            populationRank: 62,
            populationDensity: 26,
            populationGrowth: 0.5,
            medianAge: 35.0,
            lifeExpectancy: 80.0,
            fertilityRate: 1.5,
            urbanization: 88,
            ethnicGroups: [
                { name: 'Kulit Putih', percentage: 60.0 },
                { name: 'Mestizo', percentage: 30.0 },
                { name: 'Pribumi', percentage: 8.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 60.0 },
                { name: 'Kristen Protestan', percentage: 20.0 },
                { name: 'Tidak beragama', percentage: 15.0 },
                { name: 'Lainnya', percentage: 5.0 }
            ],
            languages: [
                { name: 'Spanyol', percentage: 100, official: true },
                { name: 'Inggris', percentage: 20 },
                { name: 'Pribumi', percentage: 5 }
            ],
            literacyRate: 97,
            governmentType: 'Republik Presidensial',
            independenceDay: '1818-02-12',
            nationalHoliday: '18 September',
            legalSystem: 'Civil Law',
            constitution: '1980',
            administrativeDivisions: 16,
            memberships: ['PBB', 'OECD', 'APEC', 'WTO'],
            giniCoefficient: 44.4,
            hdi: 0.855,
            hdiRank: 41,
            corruptionIndex: 67,
            currency: 'Peso',
            currencyCode: 'CLP',
            gdp: 350000000000,
            gdpPerCapita: 17950,
            gdpPpp: 500000000000,
            gdpGrowth: 2.5,
            inflation: 4.0,
            unemployment: 8.0,
            povertyRate: 10.0,
            mainIndustries: ['Tambang', 'Pertanian', 'Manufaktur', 'Pariwisata', 'Keuangan'],
            exports: [
                { item: 'Tembaga', value: 40000000000 },
                { item: 'Wine', value: 20000000000 },
                { item: 'Bahan kimia', value: 15000000000 },
                { item: 'Pertanian', value: 10000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 20000000000 },
                { item: 'Elektronik', value: 15000000000 },
                { item: 'Minyak', value: 10000000000 },
                { item: 'Makanan', value: 8000000000 }
            ],
            tradeBalance: 10000000000,
            naturalResources: ['Tembaga', 'Lithium', 'Emas', 'Wine', 'Tanah subur'],
            economicRanking: 45,
            internetPenetration: 88,
            mobilePenetration: 95,
            electricityAccess: 100,
            roadLength: 80000,
            railwayLength: 6000,
            airports: 500,
            seaports: 50,
            healthcareAccess: 88,
            educationIndex: 0.78,
            nationalMotto: 'Dengan alasan atau kekuatan',
            nationalAnthem: 'Himno Nacional de Chile',
            nationalAnimal: 'Condor Andes',
            nationalFlower: 'Copihue',
            nationalCuisine: ['Empanadas', 'Pastel de Choclo', 'Curanto', 'Completo', 'Ceviche'],
            culturalHeritage: ['Santiago', 'Valparaiso', 'Easter Island', 'Patagonia'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 72,
            climate: 'Beragam',
            averageTemperature: 14,
            averageRainfall: 300,
            forestArea: 20,
            protectedAreas: 15,
            biodiversityRank: 12,
            carbonEmissions: 4.5,
            environmentalIndex: 55,
            riskScore: 25,
            politicalStability: 70,
            crimeIndex: 30,
            militarySpending: 1.5,
            peaceIndex: 35,
            terrorismIndex: 10,
            refugeePopulation: 5000,
            opportunityScore: 65,
            easeOfDoingBusiness: 68,
            innovationIndex: 55,
            startupEcosystem: 60,
            investmentScore: 65,
            talentPool: 72,
            marketSize: 70,
            infrastructureQuality: 72,
            internetSpeed: 40,
            digitalAdoption: 75,
            techEcosystem: 65,
            aiReadiness: 55,
            startups: 400,
            phoneCode: '+56',
            tld: '.cl',
            isoCode: 'CHL',
            isoCode2: 'CL',
            drivingSide: 'right',
            tags: ['negara', 'american-selatan', 'tembaga', 'anggur', 'oecd']
        }
    },
    // ==========================================================
    // 🇵🇪 PERU
    // ==========================================================
    {
        text: 'Peru - Negara di Amerika Selatan dengan peradaban Inca dan Machu Picchu. Ibu kota: Lima. Populasi: 34 juta jiwa. Mata uang: Sol (PEN). Bahasa: Spanyol, Quechua. Sistem pemerintahan: Republik Presidensial. Anggota APEC dan PBB. Negara dengan Machu Picchu, salah satu keajaiban dunia. Rumah bagi sejarah Inca, budaya kaya, dan keanekaragaman hayati Amazon.',
        metadata: {
            category: 'country',
            region: 'american-selatan',
            name: 'Peru',
            officialName: 'Republik Peru',
            shortName: 'PER',
            capital: 'Lima',
            capitalCoordinates: { lat: -12.0464, lng: -77.0428 },
            largestCity: 'Lima',
            demonym: 'Peru',
            subregion: 'South America',
            area: 1285216,
            areaRank: 19,
            coastline: 2414,
            highestPoint: 'Huascarán',
            highestElevation: 6768,
            lowestPoint: 'Laut Pasifik',
            lowestElevation: 0,
            landBorders: ['Ekuador', 'Kolombia', 'Brasil', 'Bolivia', 'Chili'],
            coordinates: { lat: -10.0, lng: -76.0 },
            timezone: ['UTC-5'],
            utcOffset: ['-5'],
            population: 34000000,
            populationRank: 43,
            populationDensity: 26,
            populationGrowth: 1.0,
            medianAge: 28.0,
            lifeExpectancy: 76.0,
            fertilityRate: 2.0,
            urbanization: 78,
            ethnicGroups: [
                { name: 'Pribumi', percentage: 45.0 },
                { name: 'Mestizo', percentage: 37.0 },
                { name: 'Kulit Putih', percentage: 15.0 },
                { name: 'Lainnya', percentage: 3.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 75.0 },
                { name: 'Kristen Protestan', percentage: 15.0 },
                { name: 'Tidak beragama', percentage: 8.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            languages: [
                { name: 'Spanyol', percentage: 100, official: true },
                { name: 'Quechua', percentage: 13, official: true },
                { name: 'Aymara', percentage: 2 }
            ],
            literacyRate: 94,
            governmentType: 'Republik Presidensial',
            independenceDay: '1821-07-28',
            nationalHoliday: '28 Juli',
            legalSystem: 'Civil Law',
            constitution: '1993',
            administrativeDivisions: 25,
            memberships: ['PBB', 'APEC', 'WTO', 'OAS'],
            giniCoefficient: 43.0,
            hdi: 0.762,
            hdiRank: 84,
            corruptionIndex: 36,
            currency: 'Sol',
            currencyCode: 'PEN',
            gdp: 250000000000,
            gdpPerCapita: 7350,
            gdpPpp: 500000000000,
            gdpGrowth: 3.5,
            inflation: 3.0,
            unemployment: 5.0,
            povertyRate: 20.0,
            mainIndustries: ['Tambang', 'Pertanian', 'Pariwisata', 'Manufaktur', 'Perikanan'],
            exports: [
                { item: 'Tembaga', value: 40000000000 },
                { item: 'Emas', value: 20000000000 },
                { item: 'Seng', value: 15000000000 },
                { item: 'Pariwisata', value: 10000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 20000000000 },
                { item: 'Elektronik', value: 15000000000 },
                { item: 'Minyak', value: 10000000000 },
                { item: 'Makanan', value: 8000000000 }
            ],
            tradeBalance: 10000000000,
            naturalResources: ['Tembaga', 'Emas', 'Seng', 'Lithium', 'Kayu', 'Perikanan'],
            economicRanking: 50,
            internetPenetration: 65,
            mobilePenetration: 80,
            electricityAccess: 98,
            roadLength: 140000,
            railwayLength: 2000,
            airports: 300,
            seaports: 30,
            healthcareAccess: 70,
            educationIndex: 0.62,
            nationalMotto: 'Kebebasan, Kemakmuran, Persatuan',
            nationalAnthem: 'Himno Nacional del Perú',
            nationalAnimal: 'Vicuña',
            nationalFlower: 'Cantuta',
            nationalCuisine: ['Ceviche', 'Lomo Saltado', 'Causa', 'Aji de Gallina', 'Pisco Sour'],
            culturalHeritage: ['Machu Picchu', 'Lima', 'Cusco', 'Nazca Lines'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 55,
            climate: 'Beragam',
            averageTemperature: 20,
            averageRainfall: 500,
            forestArea: 55,
            protectedAreas: 15,
            biodiversityRank: 4,
            carbonEmissions: 1.5,
            environmentalIndex: 50,
            riskScore: 40,
            politicalStability: 55,
            crimeIndex: 40,
            militarySpending: 1.0,
            peaceIndex: 50,
            terrorismIndex: 20,
            refugeePopulation: 5000,
            opportunityScore: 55,
            easeOfDoingBusiness: 55,
            innovationIndex: 45,
            startupEcosystem: 50,
            investmentScore: 50,
            talentPool: 65,
            marketSize: 75,
            infrastructureQuality: 55,
            internetSpeed: 25,
            digitalAdoption: 55,
            techEcosystem: 45,
            aiReadiness: 40,
            startups: 200,
            phoneCode: '+51',
            tld: '.pe',
            isoCode: 'PER',
            isoCode2: 'PE',
            drivingSide: 'right',
            tags: ['negara', 'american-selatan', 'inca', 'machu-picchu', 'pariwisata']
        }
    },
    // ==========================================================
    // 🇻🇪 VENEZUELA
    // ==========================================================
    {
        text: 'Venezuela - Negara di Amerika Selatan dengan cadangan minyak terbesar. Ibu kota: Caracas. Populasi: 28 juta jiwa. Mata uang: Bolivar (VES). Bahasa: Spanyol. Sistem pemerintahan: Republik Federal Presidensial. Anggota OPEC dan PBB. Negara dengan cadangan minyak terbesar di dunia, Angel Falls (air terjun tertinggi di dunia), dan keindahan alam Karibia.',
        metadata: {
            category: 'country',
            region: 'american-selatan',
            name: 'Venezuela',
            officialName: 'Republik Federal Venezuela',
            shortName: 'VEN',
            capital: 'Caracas',
            capitalCoordinates: { lat: 10.4806, lng: -66.9036 },
            largestCity: 'Caracas',
            demonym: 'Venezuela',
            subregion: 'South America',
            area: 916445,
            areaRank: 32,
            coastline: 2800,
            highestPoint: 'Pico Bolívar',
            highestElevation: 4978,
            lowestPoint: 'Laut Karibia',
            lowestElevation: 0,
            landBorders: ['Kolombia', 'Brasil', 'Guyana'],
            coordinates: { lat: 8.0, lng: -66.0 },
            timezone: ['UTC-4'],
            utcOffset: ['-4'],
            population: 28000000,
            populationRank: 50,
            populationDensity: 31,
            populationGrowth: -0.5,
            medianAge: 29.0,
            lifeExpectancy: 72.0,
            fertilityRate: 2.0,
            urbanization: 88,
            ethnicGroups: [
                { name: 'Mestizo', percentage: 50.0 },
                { name: 'Kulit Putih', percentage: 35.0 },
                { name: 'Kulit Hitam', percentage: 10.0 },
                { name: 'Pribumi', percentage: 5.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 75.0 },
                { name: 'Kristen Protestan', percentage: 15.0 },
                { name: 'Tidak beragama', percentage: 8.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            languages: [
                { name: 'Spanyol', percentage: 100, official: true },
                { name: 'Inggris', percentage: 10 },
                { name: 'Pribumi', percentage: 5 }
            ],
            literacyRate: 97,
            governmentType: 'Republik Federal Presidensial',
            independenceDay: '1811-07-05',
            nationalHoliday: '5 Juli',
            legalSystem: 'Civil Law',
            constitution: '1999',
            administrativeDivisions: 23,
            memberships: ['PBB', 'OPEC', 'OAS', 'Mercosur'],
            giniCoefficient: 45.0,
            hdi: 0.711,
            hdiRank: 112,
            corruptionIndex: 16,
            currency: 'Bolivar',
            currencyCode: 'VES',
            gdp: 100000000000,
            gdpPerCapita: 3570,
            gdpPpp: 300000000000,
            gdpGrowth: -5.0,
            inflation: 400.0,
            unemployment: 30.0,
            povertyRate: 60.0,
            mainIndustries: ['Minyak', 'Gas', 'Manufaktur', 'Pertanian', 'Pariwisata'],
            exports: [
                { item: 'Minyak', value: 50000000000 },
                { item: 'Gas', value: 20000000000 },
                { item: 'Petrokimia', value: 10000000000 },
                { item: 'Aluminium', value: 5000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 20000000000 },
                { item: 'Elektronik', value: 15000000000 },
                { item: 'Makanan', value: 10000000000 },
                { item: 'Bahan kimia', value: 8000000000 }
            ],
            tradeBalance: 10000000000,
            naturalResources: ['Minyak', 'Gas', 'Emas', 'Biji besi', 'Batu bara'],
            economicRanking: 60,
            internetPenetration: 60,
            mobilePenetration: 75,
            electricityAccess: 95,
            roadLength: 100000,
            railwayLength: 500,
            airports: 200,
            seaports: 30,
            healthcareAccess: 60,
            educationIndex: 0.62,
            nationalMotto: 'Tuhan dan Federasi',
            nationalAnthem: 'Gloria al Bravo Pueblo',
            nationalAnimal: 'Pendulum',
            nationalFlower: 'Orchid',
            nationalCuisine: ['Arepa', 'Cachapa', 'Hallaca', 'Pabellón', 'Empanadas'],
            culturalHeritage: ['Caracas', 'Angel Falls', 'Isla Margarita', 'Los Llanos'],
            publicHolidays: ['Hari Kemerdekaan', 'Hari Revolusi', 'Paskah', 'Christmas'],
            socialRanking: 35,
            climate: 'Tropis',
            averageTemperature: 25,
            averageRainfall: 800,
            forestArea: 50,
            protectedAreas: 10,
            biodiversityRank: 7,
            carbonEmissions: 6.0,
            environmentalIndex: 40,
            riskScore: 80,
            politicalStability: 20,
            crimeIndex: 60,
            militarySpending: 2.5,
            peaceIndex: 70,
            terrorismIndex: 20,
            refugeePopulation: 1000000,
            opportunityScore: 25,
            easeOfDoingBusiness: 25,
            innovationIndex: 20,
            startupEcosystem: 20,
            investmentScore: 25,
            talentPool: 60,
            marketSize: 70,
            infrastructureQuality: 30,
            internetSpeed: 15,
            digitalAdoption: 35,
            techEcosystem: 25,
            aiReadiness: 20,
            startups: 30,
            phoneCode: '+58',
            tld: '.ve',
            isoCode: 'VEN',
            isoCode2: 'VE',
            drivingSide: 'right',
            tags: ['negara', 'american-selatan', 'minyak', 'opec', 'krisis']
        }
    },
    // ==========================================================
    // 🇪🇨 EKUADOR
    // ==========================================================
    {
        text: 'Ekuador - Negara di Amerika Selatan dengan Galapagos dan pisang. Ibu kota: Quito. Populasi: 18 juta jiwa. Mata uang: Dolar AS (USD). Bahasa: Spanyol. Sistem pemerintahan: Republik Presidensial. Anggota PBB dan OPEC. Negara dengan Kepulauan Galapagos, Andes yang indah, dan pisang terbaik dunia.',
        metadata: {
            category: 'country',
            region: 'american-selatan',
            name: 'Ekuador',
            officialName: 'Republik Ekuador',
            shortName: 'ECU',
            capital: 'Quito',
            capitalCoordinates: { lat: -0.1807, lng: -78.4678 },
            largestCity: 'Guayaquil',
            demonym: 'Ekuador',
            subregion: 'South America',
            area: 283561,
            areaRank: 73,
            coastline: 2237,
            highestPoint: 'Chimborazo',
            highestElevation: 6267,
            lowestPoint: 'Laut Pasifik',
            lowestElevation: 0,
            landBorders: ['Kolombia', 'Peru'],
            coordinates: { lat: -2.0, lng: -77.5 },
            timezone: ['UTC-5'],
            utcOffset: ['-5'],
            population: 18000000,
            populationRank: 66,
            populationDensity: 63,
            populationGrowth: 1.0,
            medianAge: 28.0,
            lifeExpectancy: 77.0,
            fertilityRate: 2.0,
            urbanization: 63,
            ethnicGroups: [
                { name: 'Mestizo', percentage: 65.0 },
                { name: 'Kulit Putih', percentage: 15.0 },
                { name: 'Pribumi', percentage: 10.0 },
                { name: 'Kulit Hitam', percentage: 8.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 80.0 },
                { name: 'Kristen Protestan', percentage: 15.0 },
                { name: 'Tidak beragama', percentage: 3.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            languages: [
                { name: 'Spanyol', percentage: 100, official: true },
                { name: 'Quechua', percentage: 5 },
                { name: 'Inggris', percentage: 10 }
            ],
            literacyRate: 95,
            governmentType: 'Republik Presidensial',
            independenceDay: '1809-08-10',
            nationalHoliday: '10 Agustus',
            legalSystem: 'Civil Law',
            constitution: '2008',
            administrativeDivisions: 24,
            memberships: ['PBB', 'OPEC', 'WTO', 'OAS'],
            giniCoefficient: 45.0,
            hdi: 0.759,
            hdiRank: 86,
            corruptionIndex: 34,
            currency: 'Dolar AS',
            currencyCode: 'USD',
            gdp: 120000000000,
            gdpPerCapita: 6660,
            gdpPpp: 250000000000,
            gdpGrowth: 2.5,
            inflation: 3.0,
            unemployment: 4.0,
            povertyRate: 25.0,
            mainIndustries: ['Pisang', 'Pariwisata', 'Minyak', 'Pertanian', 'Manufaktur'],
            exports: [
                { item: 'Pisang', value: 10000000000 },
                { item: 'Minyak', value: 8000000000 },
                { item: 'Pariwisata', value: 5000000000 },
                { item: 'Bunga', value: 3000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 10000000000 },
                { item: 'Elektronik', value: 8000000000 },
                { item: 'Minyak', value: 5000000000 },
                { item: 'Makanan', value: 3000000000 }
            ],
            tradeBalance: -5000000000,
            naturalResources: ['Minyak', 'Gas', 'Emas', 'Kayu', 'Pisang', 'Perikanan'],
            economicRanking: 60,
            internetPenetration: 60,
            mobilePenetration: 75,
            electricityAccess: 100,
            roadLength: 40000,
            railwayLength: 1000,
            airports: 200,
            seaports: 20,
            healthcareAccess: 70,
            educationIndex: 0.62,
            nationalMotto: 'Tuhan, Tanah air, Kebebasan',
            nationalAnthem: 'Salve, Oh Patria',
            nationalAnimal: 'Condor Andes',
            nationalFlower: 'Orchid',
            nationalCuisine: ['Ceviche', 'Encebollado', 'Llapingacho', 'Hornado', 'Tigrillo'],
            culturalHeritage: ['Quito', 'Galapagos', 'Guayaquil', 'Cuenca'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 55,
            climate: 'Beragam',
            averageTemperature: 20,
            averageRainfall: 1000,
            forestArea: 50,
            protectedAreas: 15,
            biodiversityRank: 8,
            carbonEmissions: 2.0,
            environmentalIndex: 55,
            riskScore: 40,
            politicalStability: 50,
            crimeIndex: 45,
            militarySpending: 1.5,
            peaceIndex: 50,
            terrorismIndex: 15,
            refugeePopulation: 5000,
            opportunityScore: 50,
            easeOfDoingBusiness: 50,
            innovationIndex: 40,
            startupEcosystem: 45,
            investmentScore: 45,
            talentPool: 60,
            marketSize: 65,
            infrastructureQuality: 50,
            internetSpeed: 20,
            digitalAdoption: 50,
            techEcosystem: 40,
            aiReadiness: 35,
            startups: 100,
            phoneCode: '+593',
            tld: '.ec',
            isoCode: 'ECU',
            isoCode2: 'EC',
            drivingSide: 'right',
            tags: ['negara', 'american-selatan', 'galapagos', 'pisang', 'opec']
        }
    },
    // ==========================================================
    // 🇧🇴 BOLIVIA
    // ==========================================================
    {
        text: 'Bolivia - Negara di Amerika Selatan dengan Salar de Uyuni dan litium. Ibu kota: Sucre. Populasi: 12 juta jiwa. Mata uang: Boliviano (BOB). Bahasa: Spanyol, Quechua, Aymara. Sistem pemerintahan: Republik Presidensial. Anggota PBB dan Mercosur. Negara dengan Salar de Uyuni (danau garam terbesar dunia), litium terbesar, dan budaya Andes yang kaya.',
        metadata: {
            category: 'country',
            region: 'american-selatan',
            name: 'Bolivia',
            officialName: 'Negara Multinasional Bolivia',
            shortName: 'BOL',
            capital: 'Sucre',
            capitalCoordinates: { lat: -19.0333, lng: -65.2627 },
            largestCity: 'Santa Cruz',
            demonym: 'Bolivia',
            subregion: 'South America',
            area: 1098581,
            areaRank: 27,
            coastline: 0,
            highestPoint: 'Nevado Sajama',
            highestElevation: 6542,
            lowestPoint: 'Paraguay River',
            lowestElevation: 90,
            landBorders: ['Peru', 'Chili', 'Argentina', 'Paraguay', 'Brasil'],
            coordinates: { lat: -17.0, lng: -65.0 },
            timezone: ['UTC-4'],
            utcOffset: ['-4'],
            population: 12000000,
            populationRank: 80,
            populationDensity: 11,
            populationGrowth: 1.5,
            medianAge: 25.0,
            lifeExpectancy: 71.0,
            fertilityRate: 2.5,
            urbanization: 70,
            ethnicGroups: [
                { name: 'Pribumi', percentage: 55.0 },
                { name: 'Mestizo', percentage: 30.0 },
                { name: 'Kulit Putih', percentage: 10.0 },
                { name: 'Lainnya', percentage: 5.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 75.0 },
                { name: 'Kristen Protestan', percentage: 15.0 },
                { name: 'Tidak beragama', percentage: 8.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            languages: [
                { name: 'Spanyol', percentage: 100, official: true },
                { name: 'Quechua', percentage: 30, official: true },
                { name: 'Aymara', percentage: 20, official: true }
            ],
            literacyRate: 93,
            governmentType: 'Republik Presidensial',
            independenceDay: '1825-08-06',
            nationalHoliday: '6 Agustus',
            legalSystem: 'Civil Law',
            constitution: '2009',
            administrativeDivisions: 9,
            memberships: ['PBB', 'Mercosur', 'WTO', 'OAS'],
            giniCoefficient: 41.6,
            hdi: 0.718,
            hdiRank: 107,
            corruptionIndex: 33,
            currency: 'Boliviano',
            currencyCode: 'BOB',
            gdp: 50000000000,
            gdpPerCapita: 4160,
            gdpPpp: 120000000000,
            gdpGrowth: 3.5,
            inflation: 3.0,
            unemployment: 4.0,
            povertyRate: 35.0,
            mainIndustries: ['Tambang', 'Pertanian', 'Manufaktur', 'Pariwisata', 'Energi'],
            exports: [
                { item: 'Lithium', value: 15000000000 },
                { item: 'Gas', value: 10000000000 },
                { item: 'Emas', value: 8000000000 },
                { item: 'Perak', value: 5000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 8000000000 },
                { item: 'Elektronik', value: 6000000000 },
                { item: 'Minyak', value: 4000000000 },
                { item: 'Makanan', value: 3000000000 }
            ],
            tradeBalance: 5000000000,
            naturalResources: ['Lithium', 'Gas', 'Emas', 'Perak', 'Tanah subur'],
            economicRanking: 80,
            internetPenetration: 50,
            mobilePenetration: 70,
            electricityAccess: 90,
            roadLength: 50000,
            railwayLength: 3000,
            airports: 100,
            seaports: 0,
            healthcareAccess: 60,
            educationIndex: 0.58,
            nationalMotto: 'Kebebasan, Kemakmuran, Persatuan',
            nationalAnthem: 'Himno Nacional de Bolivia',
            nationalAnimal: 'Llama',
            nationalFlower: 'Patujú',
            nationalCuisine: ['Salteñas', 'Pique Macho', 'Silpancho', 'Api', 'Chicha'],
            culturalHeritage: ['Salar de Uyuni', 'La Paz', 'Sucre', 'Tiwanaku'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 50,
            climate: 'Beragam',
            averageTemperature: 15,
            averageRainfall: 500,
            forestArea: 50,
            protectedAreas: 15,
            biodiversityRank: 10,
            carbonEmissions: 1.5,
            environmentalIndex: 50,
            riskScore: 50,
            politicalStability: 50,
            crimeIndex: 40,
            militarySpending: 1.0,
            peaceIndex: 55,
            terrorismIndex: 15,
            refugeePopulation: 1000,
            opportunityScore: 45,
            easeOfDoingBusiness: 45,
            innovationIndex: 35,
            startupEcosystem: 35,
            investmentScore: 40,
            talentPool: 55,
            marketSize: 60,
            infrastructureQuality: 40,
            internetSpeed: 15,
            digitalAdoption: 40,
            techEcosystem: 35,
            aiReadiness: 30,
            startups: 50,
            phoneCode: '+591',
            tld: '.bo',
            isoCode: 'BOL',
            isoCode2: 'BO',
            drivingSide: 'right',
            tags: ['negara', 'american-selatan', 'litium', 'uyuni', 'garam']
        }
    },
    // ==========================================================
    // 🇵🇾 PARAGUAY
    // ==========================================================
    {
        text: 'Paraguay - Negara di Amerika Selatan tanpa laut dengan pertanian. Ibu kota: Asuncion. Populasi: 7.5 juta jiwa. Mata uang: Guarani (PYG). Bahasa: Spanyol, Guarani. Sistem pemerintahan: Republik Presidensial. Anggota PBB dan Mercosur. Negara dengan ekonomi pertanian yang berkembang dan budaya Guarani yang kaya.',
        metadata: {
            category: 'country',
            region: 'american-selatan',
            name: 'Paraguay',
            officialName: 'Republik Paraguay',
            shortName: 'PRY',
            capital: 'Asuncion',
            capitalCoordinates: { lat: -25.2637, lng: -57.5759 },
            largestCity: 'Asuncion',
            demonym: 'Paraguay',
            subregion: 'South America',
            area: 406752,
            areaRank: 59,
            coastline: 0,
            highestPoint: 'Cerro Peró',
            highestElevation: 842,
            lowestPoint: 'Paraguay River',
            lowestElevation: 46,
            landBorders: ['Bolivia', 'Argentina', 'Brasil'],
            coordinates: { lat: -23.0, lng: -58.0 },
            timezone: ['UTC-4'],
            utcOffset: ['-4'],
            population: 7500000,
            populationRank: 102,
            populationDensity: 18,
            populationGrowth: 1.2,
            medianAge: 26.0,
            lifeExpectancy: 74.0,
            fertilityRate: 2.4,
            urbanization: 62,
            ethnicGroups: [
                { name: 'Mestizo', percentage: 85.0 },
                { name: 'Kulit Putih', percentage: 10.0 },
                { name: 'Pribumi', percentage: 3.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 85.0 },
                { name: 'Kristen Protestan', percentage: 10.0 },
                { name: 'Tidak beragama', percentage: 3.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            languages: [
                { name: 'Spanyol', percentage: 100, official: true },
                { name: 'Guarani', percentage: 90, official: true },
                { name: 'Inggris', percentage: 5 }
            ],
            literacyRate: 95,
            governmentType: 'Republik Presidensial',
            independenceDay: '1811-05-14',
            nationalHoliday: '14 Mei',
            legalSystem: 'Civil Law',
            constitution: '1992',
            administrativeDivisions: 17,
            memberships: ['PBB', 'Mercosur', 'WTO', 'OAS'],
            giniCoefficient: 43.0,
            hdi: 0.728,
            hdiRank: 99,
            corruptionIndex: 30,
            currency: 'Guarani',
            currencyCode: 'PYG',
            gdp: 40000000000,
            gdpPerCapita: 5330,
            gdpPpp: 100000000000,
            gdpGrowth: 4.0,
            inflation: 4.0,
            unemployment: 5.0,
            povertyRate: 20.0,
            mainIndustries: ['Pertanian', 'Manufaktur', 'Tekstil', 'Energi', 'Pariwisata'],
            exports: [
                { item: 'Kedelai', value: 15000000000 },
                { item: 'Daging', value: 8000000000 },
                { item: 'Energi', value: 5000000000 },
                { item: 'Tekstil', value: 3000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 5000000000 },
                { item: 'Elektronik', value: 4000000000 },
                { item: 'Minyak', value: 3000000000 },
                { item: 'Makanan', value: 2000000000 }
            ],
            tradeBalance: 5000000000,
            naturalResources: ['Tanah subur', 'Kayu', 'Energi', 'Air'],
            economicRanking: 80,
            internetPenetration: 55,
            mobilePenetration: 75,
            electricityAccess: 100,
            roadLength: 30000,
            railwayLength: 0,
            airports: 100,
            seaports: 0,
            healthcareAccess: 65,
            educationIndex: 0.58,
            nationalMotto: 'Kebebasan, Kemakmuran, Persatuan',
            nationalAnthem: 'Himno Nacional Paraguayo',
            nationalAnimal: 'Burung Kolibri',
            nationalFlower: 'Bunga Mburucuyá',
            nationalCuisine: ['Sopa Paraguaya', 'Chipa', 'Mbeju', 'Asado', 'Tereré'],
            culturalHeritage: ['Asuncion', 'Ciudad del Este', 'Encarnación', 'San Ignacio'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 55,
            climate: 'Subtropis',
            averageTemperature: 25,
            averageRainfall: 1000,
            forestArea: 40,
            protectedAreas: 10,
            biodiversityRank: 20,
            carbonEmissions: 1.0,
            environmentalIndex: 48,
            riskScore: 40,
            politicalStability: 60,
            crimeIndex: 35,
            militarySpending: 0.5,
            peaceIndex: 45,
            terrorismIndex: 10,
            refugeePopulation: 0,
            opportunityScore: 50,
            easeOfDoingBusiness: 55,
            innovationIndex: 35,
            startupEcosystem: 40,
            investmentScore: 45,
            talentPool: 55,
            marketSize: 60,
            infrastructureQuality: 50,
            internetSpeed: 20,
            digitalAdoption: 45,
            techEcosystem: 35,
            aiReadiness: 30,
            startups: 30,
            phoneCode: '+595',
            tld: '.py',
            isoCode: 'PRY',
            isoCode2: 'PY',
            drivingSide: 'right',
            tags: ['negara', 'american-selatan', 'pertanian', 'kedelai', 'mercosur']
        }
    },
    // ==========================================================
    // 🇺🇾 URUGUAY
    // ==========================================================
    {
        text: 'Uruguay - Negara kecil di Amerika Selatan dengan ekonomi stabil. Ibu kota: Montevideo. Populasi: 3.4 juta jiwa. Mata uang: Peso (UYU). Bahasa: Spanyol. Sistem pemerintahan: Republik Presidensial. Anggota PBB dan Mercosur. Negara dengan ekonomi paling stabil di Amerika Selatan, kualitas hidup tinggi, dan teknologi maju.',
        metadata: {
            category: 'country',
            region: 'american-selatan',
            name: 'Uruguay',
            officialName: 'Republik Oriental Uruguay',
            shortName: 'URY',
            capital: 'Montevideo',
            capitalCoordinates: { lat: -34.9011, lng: -56.1645 },
            largestCity: 'Montevideo',
            demonym: 'Uruguay',
            subregion: 'South America',
            area: 176215,
            areaRank: 89,
            coastline: 660,
            highestPoint: 'Cerro Catedral',
            highestElevation: 514,
            lowestPoint: 'Laut Atlantik',
            lowestElevation: 0,
            landBorders: ['Argentina', 'Brasil'],
            coordinates: { lat: -33.0, lng: -56.0 },
            timezone: ['UTC-3'],
            utcOffset: ['-3'],
            population: 3400000,
            populationRank: 133,
            populationDensity: 19,
            populationGrowth: 0.2,
            medianAge: 35.0,
            lifeExpectancy: 78.0,
            fertilityRate: 1.5,
            urbanization: 95,
            ethnicGroups: [
                { name: 'Kulit Putih', percentage: 85.0 },
                { name: 'Mestizo', percentage: 10.0 },
                { name: 'Kulit Hitam', percentage: 3.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 60.0 },
                { name: 'Kristen Protestan', percentage: 15.0 },
                { name: 'Tidak beragama', percentage: 20.0 },
                { name: 'Lainnya', percentage: 5.0 }
            ],
            languages: [
                { name: 'Spanyol', percentage: 100, official: true },
                { name: 'Inggris', percentage: 20 },
                { name: 'Portugis', percentage: 10 }
            ],
            literacyRate: 98,
            governmentType: 'Republik Presidensial',
            independenceDay: '1825-08-25',
            nationalHoliday: '25 Agustus',
            legalSystem: 'Civil Law',
            constitution: '1967',
            administrativeDivisions: 19,
            memberships: ['PBB', 'Mercosur', 'WTO', 'OAS'],
            giniCoefficient: 39.7,
            hdi: 0.817,
            hdiRank: 57,
            corruptionIndex: 71,
            currency: 'Peso',
            currencyCode: 'UYU',
            gdp: 80000000000,
            gdpPerCapita: 23500,
            gdpPpp: 100000000000,
            gdpGrowth: 2.5,
            inflation: 5.0,
            unemployment: 7.0,
            povertyRate: 10.0,
            mainIndustries: ['Pertanian', 'Manufaktur', 'Keuangan', 'Pariwisata', 'Teknologi'],
            exports: [
                { item: 'Daging', value: 20000000000 },
                { item: 'Kedelai', value: 15000000000 },
                { item: 'Beras', value: 10000000000 },
                { item: 'Keuangan', value: 8000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 10000000000 },
                { item: 'Elektronik', value: 8000000000 },
                { item: 'Minyak', value: 5000000000 },
                { item: 'Makanan', value: 3000000000 }
            ],
            tradeBalance: 5000000000,
            naturalResources: ['Tanah subur', 'Air', 'Kayu', 'Energi'],
            economicRanking: 70,
            internetPenetration: 85,
            mobilePenetration: 92,
            electricityAccess: 100,
            roadLength: 80000,
            railwayLength: 3000,
            airports: 100,
            seaports: 10,
            healthcareAccess: 88,
            educationIndex: 0.78,
            nationalMotto: 'Kebebasan atau Mati',
            nationalAnthem: 'Himno Nacional de Uruguay',
            nationalAnimal: 'Burung Kolibri',
            nationalFlower: 'Ceibo',
            nationalCuisine: ['Asado', 'Chivito', 'Empanadas', 'Milanesa', 'Dulce de Leche'],
            culturalHeritage: ['Montevideo', 'Colonia', 'Punta del Este', 'Salto'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 78,
            climate: 'Subtropis',
            averageTemperature: 17,
            averageRainfall: 1000,
            forestArea: 10,
            protectedAreas: 10,
            biodiversityRank: 25,
            carbonEmissions: 2.0,
            environmentalIndex: 55,
            riskScore: 20,
            politicalStability: 85,
            crimeIndex: 25,
            militarySpending: 1.0,
            peaceIndex: 25,
            terrorismIndex: 5,
            refugeePopulation: 1000,
            opportunityScore: 65,
            easeOfDoingBusiness: 68,
            innovationIndex: 55,
            startupEcosystem: 60,
            investmentScore: 65,
            talentPool: 65,
            marketSize: 60,
            infrastructureQuality: 72,
            internetSpeed: 40,
            digitalAdoption: 75,
            techEcosystem: 65,
            aiReadiness: 55,
            startups: 100,
            phoneCode: '+598',
            tld: '.uy',
            isoCode: 'URY',
            isoCode2: 'UY',
            drivingSide: 'right',
            tags: ['negara', 'american-selatan', 'stabil', 'teknologi', 'mercosur']
        }
    },
    // ==========================================================
    // 🇬🇾 GUYANA
    // ==========================================================
    {
        text: 'Guyana - Negara di Amerika Selatan dengan ekonomi minyak baru. Ibu kota: Georgetown. Populasi: 0.8 juta jiwa. Mata uang: Dolar Guyana (GYD). Bahasa: Inggris. Sistem pemerintahan: Republik Parlementer. Anggota PBB dan CARICOM. Negara dengan ekonomi minyak yang berkembang pesat dan hutan hujan Amazon yang indah.',
        metadata: {
            category: 'country',
            region: 'american-selatan',
            name: 'Guyana',
            officialName: 'Republik Kooperatif Guyana',
            shortName: 'GUY',
            capital: 'Georgetown',
            capitalCoordinates: { lat: 6.8013, lng: -58.1551 },
            largestCity: 'Georgetown',
            demonym: 'Guyana',
            subregion: 'South America',
            area: 214969,
            areaRank: 83,
            coastline: 459,
            highestPoint: 'Mount Roraima',
            highestElevation: 2810,
            lowestPoint: 'Laut Atlantik',
            lowestElevation: 0,
            landBorders: ['Venezuela', 'Brasil', 'Suriname'],
            coordinates: { lat: 5.0, lng: -59.0 },
            timezone: ['UTC-4'],
            utcOffset: ['-4'],
            population: 800000,
            populationRank: 164,
            populationDensity: 4,
            populationGrowth: 0.5,
            medianAge: 27.0,
            lifeExpectancy: 70.0,
            fertilityRate: 2.5,
            urbanization: 28,
            ethnicGroups: [
                { name: 'India', percentage: 40.0 },
                { name: 'Kulit Hitam', percentage: 30.0 },
                { name: 'Mestizo', percentage: 20.0 },
                { name: 'Pribumi', percentage: 10.0 }
            ],
            religions: [
                { name: 'Kristen', percentage: 60.0 },
                { name: 'Hindu', percentage: 30.0 },
                { name: 'Islam', percentage: 7.0 },
                { name: 'Lainnya', percentage: 3.0 }
            ],
            languages: [
                { name: 'Inggris', percentage: 100, official: true },
                { name: 'Hindi', percentage: 30 },
                { name: 'Kreol', percentage: 20 }
            ],
            literacyRate: 85,
            governmentType: 'Republik Parlementer',
            independenceDay: '1966-05-26',
            nationalHoliday: '23 Februari',
            legalSystem: 'Common Law',
            constitution: '1980',
            administrativeDivisions: 10,
            memberships: ['PBB', 'CARICOM', 'Commonwealth', 'OAS'],
            giniCoefficient: 44.0,
            hdi: 0.714,
            hdiRank: 108,
            corruptionIndex: 38,
            currency: 'Dolar Guyana',
            currencyCode: 'GYD',
            gdp: 15000000000,
            gdpPerCapita: 18750,
            gdpPpp: 30000000000,
            gdpGrowth: 50.0,
            inflation: 4.0,
            unemployment: 8.0,
            povertyRate: 20.0,
            mainIndustries: ['Minyak', 'Tambang', 'Pertanian', 'Manufaktur', 'Pariwisata'],
            exports: [
                { item: 'Minyak', value: 10000000000 },
                { item: 'Emas', value: 5000000000 },
                { item: 'Kayu', value: 2000000000 },
                { item: 'Beras', value: 1000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 5000000000 },
                { item: 'Elektronik', value: 3000000000 },
                { item: 'Makanan', value: 2000000000 },
                { item: 'Minyak', value: 1000000000 }
            ],
            tradeBalance: 5000000000,
            naturalResources: ['Minyak', 'Emas', 'Kayu', 'Perikanan', 'Tanah subur'],
            economicRanking: 90,
            internetPenetration: 50,
            mobilePenetration: 70,
            electricityAccess: 90,
            roadLength: 8000,
            railwayLength: 0,
            airports: 50,
            seaports: 10,
            healthcareAccess: 60,
            educationIndex: 0.55,
            nationalMotto: 'Satu orang, satu bangsa, satu takdir',
            nationalAnthem: 'Dear Land of Guyana, of Rivers and Plains',
            nationalAnimal: 'Jaguar',
            nationalFlower: 'Victoria Amazonica',
            nationalCuisine: ['Pepperpot', 'Roti', 'Curry', 'Fried Rice', 'Metemgee'],
            culturalHeritage: ['Georgetown', 'Kaieteur Falls', 'Rupununi', 'Bartica'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 50,
            climate: 'Tropis',
            averageTemperature: 27,
            averageRainfall: 2000,
            forestArea: 85,
            protectedAreas: 10,
            biodiversityRank: 10,
            carbonEmissions: 2.0,
            environmentalIndex: 55,
            riskScore: 35,
            politicalStability: 65,
            crimeIndex: 35,
            militarySpending: 0.5,
            peaceIndex: 40,
            terrorismIndex: 10,
            refugeePopulation: 0,
            opportunityScore: 60,
            easeOfDoingBusiness: 55,
            innovationIndex: 35,
            startupEcosystem: 35,
            investmentScore: 55,
            talentPool: 45,
            marketSize: 35,
            infrastructureQuality: 40,
            internetSpeed: 15,
            digitalAdoption: 40,
            techEcosystem: 30,
            aiReadiness: 25,
            startups: 20,
            phoneCode: '+592',
            tld: '.gy',
            isoCode: 'GUY',
            isoCode2: 'GY',
            drivingSide: 'left',
            tags: ['negara', 'american-selatan', 'minyak', 'caricom', 'pertumbuhan']
        }
    },
    // ==========================================================
    // 🇸🇷 SURINAME
    // ==========================================================
    {
        text: 'Suriname - Negara di Amerika Selatan dengan hutan tropis dan aluminium. Ibu kota: Paramaribo. Populasi: 0.6 juta jiwa. Mata uang: Dolar Suriname (SRD). Bahasa: Belanda. Sistem pemerintahan: Republik Presidensial. Anggota PBB dan CARICOM. Negara dengan hutan hujan Amazon yang luas, keanekaragaman hayati, dan budaya multikultural.',
        metadata: {
            category: 'country',
            region: 'american-selatan',
            name: 'Suriname',
            officialName: 'Republik Suriname',
            shortName: 'SUR',
            capital: 'Paramaribo',
            capitalCoordinates: { lat: 5.8520, lng: -55.2038 },
            largestCity: 'Paramaribo',
            demonym: 'Suriname',
            subregion: 'South America',
            area: 163820,
            areaRank: 90,
            coastline: 386,
            highestPoint: 'Julianatop',
            highestElevation: 1280,
            lowestPoint: 'Laut Atlantik',
            lowestElevation: 0,
            landBorders: ['Guyana', 'Brasil', 'Prancis'],
            coordinates: { lat: 4.0, lng: -56.0 },
            timezone: ['UTC-3'],
            utcOffset: ['-3'],
            population: 600000,
            populationRank: 169,
            populationDensity: 4,
            populationGrowth: 0.5,
            medianAge: 28.0,
            lifeExpectancy: 71.0,
            fertilityRate: 2.2,
            urbanization: 66,
            ethnicGroups: [
                { name: 'India', percentage: 27.0 },
                { name: 'Kulit Hitam', percentage: 25.0 },
                { name: 'Jawa', percentage: 15.0 },
                { name: 'Pribumi', percentage: 10.0 }
            ],
            religions: [
                { name: 'Kristen', percentage: 50.0 },
                { name: 'Hindu', percentage: 25.0 },
                { name: 'Islam', percentage: 20.0 },
                { name: 'Lainnya', percentage: 5.0 }
            ],
            languages: [
                { name: 'Belanda', percentage: 100, official: true },
                { name: 'Sranan Tongo', percentage: 40 },
                { name: 'Inggris', percentage: 20 },
                { name: 'Hindi', percentage: 10 }
            ],
            literacyRate: 95,
            governmentType: 'Republik Presidensial',
            independenceDay: '1975-11-25',
            nationalHoliday: '25 November',
            legalSystem: 'Civil Law',
            constitution: '1987',
            administrativeDivisions: 10,
            memberships: ['PBB', 'CARICOM', 'Commonwealth', 'OAS'],
            giniCoefficient: 40.0,
            hdi: 0.738,
            hdiRank: 94,
            corruptionIndex: 38,
            currency: 'Dolar Suriname',
            currencyCode: 'SRD',
            gdp: 5000000000,
            gdpPerCapita: 8330,
            gdpPpp: 10000000000,
            gdpGrowth: 2.0,
            inflation: 10.0,
            unemployment: 8.0,
            povertyRate: 20.0,
            mainIndustries: ['Aluminium', 'Tambang', 'Pertanian', 'Pariwisata', 'Manufaktur'],
            exports: [
                { item: 'Aluminium', value: 2000000000 },
                { item: 'Emas', value: 1000000000 },
                { item: 'Kayu', value: 500000000 },
                { item: 'Pertanian', value: 300000000 }
            ],
            imports: [
                { item: 'Mesin', value: 1000000000 },
                { item: 'Elektronik', value: 800000000 },
                { item: 'Makanan', value: 500000000 },
                { item: 'Minyak', value: 300000000 }
            ],
            tradeBalance: 200000000,
            naturalResources: ['Aluminium', 'Emas', 'Kayu', 'Perikanan', 'Tanah subur'],
            economicRanking: 100,
            internetPenetration: 55,
            mobilePenetration: 75,
            electricityAccess: 95,
            roadLength: 4000,
            railwayLength: 0,
            airports: 50,
            seaports: 10,
            healthcareAccess: 65,
            educationIndex: 0.62,
            nationalMotto: 'Keadilan, Kebebasan, Kemakmuran',
            nationalAnthem: 'God zij met ons Suriname',
            nationalAnimal: 'Jaguar',
            nationalFlower: 'Faya Lobi',
            nationalCuisine: ['Roti', 'Pom', 'Moksi Alesi', 'Saoto Soup', 'Kip Pastei'],
            culturalHeritage: ['Paramaribo', 'Brownsberg', 'Galibi', 'Brokopondo'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 55,
            climate: 'Tropis',
            averageTemperature: 27,
            averageRainfall: 2000,
            forestArea: 90,
            protectedAreas: 10,
            biodiversityRank: 8,
            carbonEmissions: 2.0,
            environmentalIndex: 58,
            riskScore: 35,
            politicalStability: 70,
            crimeIndex: 30,
            militarySpending: 0.5,
            peaceIndex: 35,
            terrorismIndex: 5,
            refugeePopulation: 0,
            opportunityScore: 50,
            easeOfDoingBusiness: 50,
            innovationIndex: 35,
            startupEcosystem: 30,
            investmentScore: 45,
            talentPool: 45,
            marketSize: 30,
            infrastructureQuality: 45,
            internetSpeed: 15,
            digitalAdoption: 40,
            techEcosystem: 30,
            aiReadiness: 25,
            startups: 15,
            phoneCode: '+597',
            tld: '.sr',
            isoCode: 'SUR',
            isoCode2: 'SR',
            drivingSide: 'left',
            tags: ['negara', 'american-selatan', 'amazon', 'aluminium', 'caricom']
        }
    }
];

export const DATA = data;

// ============================================================
// LOGGER
// ============================================================
if (window.InternalLogger) {
    window.InternalLogger.info('CountryAmericanSelatan', '✅ Loaded ' + data.length + ' countries (SUPER LENGKAP - 12 NEGARA!)');
}
