/* ============================================================
   📁 dataries/country/asian-barat.js
   📌 DATA NEGARA ASIA BARAT (TIMUR TENGAH)
   🔥 16 NEGARA — Arab Saudi, Iran, Irak, Turki, Suriah, Yaman, Oman, UAE, Qatar, Kuwait, Bahrain, Yordania, Lebanon, Israel, Siprus, Palestina
   🔥 DATA SUPER LENGKAP — 100+ FIELD PER NEGARA!
   ============================================================ */

(function() {
    'use strict';
    
    if (window.__CountryAsianBaratLoaded) return;
    window.__CountryAsianBaratLoaded = true;
    
    window.__DATA_REGISTER = window.__DATA_REGISTER || [];
    
    const data = [
        // ==========================================================
        // 🇸🇦 ARAB SAUDI
        // ==========================================================
        {
            text: 'Arab Saudi - Negara terbesar di Asia Barat dan pusat Islam. Ibu kota: Riyadh. Populasi: 36 juta jiwa. Mata uang: Riyal Saudi (SAR). Bahasa: Arab. Sistem pemerintahan: Monarki Absolut. Cadangan minyak terbesar dunia. Rumah kota suci Mekah dan Madinah. Visi 2030 untuk diversifikasi ekonomi. Negara dengan pengaruh global terbesar di Timur Tengah.',
            metadata: {
                category: 'country',
                region: 'asian-barat',
                name: 'Arab Saudi',
                officialName: 'Kerajaan Arab Saudi',
                shortName: 'KSA',
                capital: 'Riyadh',
                capitalCoordinates: { lat: 24.7136, lng: 46.6753 },
                largestCity: 'Riyadh',
                demonym: 'Saudi',
                subregion: 'Western Asia',
                area: 2149690,
                areaRank: 13,
                coastline: 2640,
                highestPoint: 'Jabal Sawda',
                highestElevation: 3133,
                lowestPoint: 'Laut Merah',
                lowestElevation: 0,
                landBorders: ['Irak', 'Yordania', 'Kuwait', 'Oman', 'Qatar', 'UAE', 'Yaman'],
                coordinates: { lat: 24.0, lng: 45.0 },
                timezone: ['Waktu Arab'],
                utcOffset: ['+3'],
                population: 36000000,
                populationRank: 41,
                populationDensity: 16,
                populationGrowth: 1.5,
                medianAge: 31.8,
                lifeExpectancy: 76.8,
                fertilityRate: 2.2,
                urbanization: 84,
                ethnicGroups: [
                    { name: 'Arab', percentage: 90.0 },
                    { name: 'Afro-Asia', percentage: 10.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 93.0 },
                    { name: 'Kristen', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 2.0 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 30 }
                ],
                literacyRate: 95,
                governmentType: 'Monarki Absolut',
                independenceDay: '1932-09-23',
                nationalHoliday: '23 September',
                legalSystem: 'Hukum Syariah',
                constitution: 'Basic Law 1992',
                administrativeDivisions: 13,
                memberships: ['PBB', 'OPEC', 'G20', 'Liga Arab', 'OKI'],
                giniCoefficient: 45.9,
                hdi: 0.854,
                hdiRank: 40,
                corruptionIndex: 53,
                currency: 'Riyal Saudi',
                currencyCode: 'SAR',
                gdp: 1100000000000,
                gdpPerCapita: 30500,
                gdpPpp: 2100000000000,
                gdpGrowth: 3.2,
                inflation: 2.5,
                unemployment: 5.0,
                povertyRate: 1.0,
                mainIndustries: ['Minyak', 'Gas', 'Petrokimia', 'Pariwisata', 'Keuangan'],
                exports: [
                    { item: 'Minyak', value: 200000000000 },
                    { item: 'Petrokimia', value: 50000000000 },
                    { item: 'Plastik', value: 20000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 50000000000 },
                    { item: 'Elektronik', value: 30000000000 },
                    { item: 'Makanan', value: 25000000000 }
                ],
                tradeBalance: 150000000000,
                naturalResources: ['Minyak', 'Gas', 'Emas', 'Fosfat', 'Batu bara'],
                economicRanking: 18,
                internetPenetration: 92,
                mobilePenetration: 98,
                electricityAccess: 100,
                roadLength: 221000,
                railwayLength: 4000,
                airports: 200,
                seaports: 25,
                healthcareAccess: 90,
                educationIndex: 0.78,
                nationalMotto: 'Tidak ada tuhan selain Allah',
                nationalAnthem: 'As-Salam al-Malaki',
                nationalAnimal: 'Unta',
                nationalFlower: 'Bunga Gurun',
                nationalCuisine: ['Kabsa', 'Mandi', 'Shawarma', 'Falafel', 'Hummus'],
                culturalHeritage: ['Mekah', 'Madinah', 'Al-Ula', 'Diriyah'],
                publicHolidays: ['Idul Fitri', 'Idul Adha', 'Hari Nasional', 'Tahun Baru Islam'],
                socialRanking: 70,
                climate: 'Gurun',
                averageTemperature: 30,
                averageRainfall: 100,
                forestArea: 0.5,
                protectedAreas: 15,
                biodiversityRank: 60,
                carbonEmissions: 18.0,
                environmentalIndex: 40,
                riskScore: 30,
                politicalStability: 65,
                crimeIndex: 25,
                militarySpending: 8.0,
                peaceIndex: 40,
                terrorismIndex: 35,
                refugeePopulation: 500000,
                opportunityScore: 75,
                easeOfDoingBusiness: 72,
                innovationIndex: 45,
                startupEcosystem: 55,
                investmentScore: 78,
                talentPool: 70,
                marketSize: 85,
                infrastructureQuality: 85,
                internetSpeed: 40,
                digitalAdoption: 85,
                techEcosystem: 60,
                aiReadiness: 50,
                startups: 500,
                phoneCode: '+966',
                tld: '.sa',
                isoCode: 'SAU',
                isoCode2: 'SA',
                drivingSide: 'right',
                tags: ['negara', 'asian-barat', 'minyak', 'islam', 'mekah']
            }
        },
        // ==========================================================
        // 🇮🇷 IRAN
        // ==========================================================
        {
            text: 'Iran - Negara di Asia Barat dengan sejarah dan budaya Persia kuno. Ibu kota: Teheran. Populasi: 88 juta jiwa. Mata uang: Rial Iran (IRR). Bahasa: Persia. Sistem pemerintahan: Republik Islam. Cadangan gas alam terbesar dunia. Pemain utama geopolitik Timur Tengah. Rumah bagi peradaban Persia, arsitektur Islam, dan kekayaan budaya. Kekuatan regional dengan pengaruh di Irak, Suriah, dan Lebanon.',
            metadata: {
                category: 'country',
                region: 'asian-barat',
                name: 'Iran',
                officialName: 'Republik Islam Iran',
                shortName: 'IRN',
                capital: 'Teheran',
                capitalCoordinates: { lat: 35.6892, lng: 51.3890 },
                largestCity: 'Teheran',
                demonym: 'Iran',
                subregion: 'Western Asia',
                area: 1648195,
                areaRank: 17,
                coastline: 2440,
                highestPoint: 'Gunung Damavand',
                highestElevation: 5610,
                lowestPoint: 'Laut Kaspia',
                lowestElevation: -28,
                landBorders: ['Afghanistan', 'Armenia', 'Azerbaijan', 'Irak', 'Pakistan', 'Turki', 'Turkmenistan'],
                coordinates: { lat: 32.0, lng: 53.0 },
                timezone: ['Waktu Iran'],
                utcOffset: ['+3.5'],
                population: 88000000,
                populationRank: 17,
                populationDensity: 52,
                populationGrowth: 1.0,
                medianAge: 33.0,
                lifeExpectancy: 76.7,
                fertilityRate: 1.7,
                urbanization: 76,
                ethnicGroups: [
                    { name: 'Persia', percentage: 61.0 },
                    { name: 'Azerbaijan', percentage: 16.0 },
                    { name: 'Kurdi', percentage: 10.0 },
                    { name: 'Lur', percentage: 6.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 99.0 },
                    { name: 'Zoroaster', percentage: 0.5 },
                    { name: 'Kristen', percentage: 0.3 }
                ],
                languages: [
                    { name: 'Persia', percentage: 100, official: true },
                    { name: 'Azerbaijan', percentage: 16 },
                    { name: 'Kurdi', percentage: 10 }
                ],
                literacyRate: 86,
                governmentType: 'Republik Islam',
                independenceDay: '1979-04-01',
                nationalHoliday: '11 Februari',
                legalSystem: 'Hukum Syariah',
                constitution: '1979',
                administrativeDivisions: 31,
                memberships: ['PBB', 'OPEC', 'OKI', 'Non-Aligned Movement'],
                giniCoefficient: 40.0,
                hdi: 0.783,
                hdiRank: 70,
                corruptionIndex: 25,
                currency: 'Rial Iran',
                currencyCode: 'IRR',
                gdp: 400000000000,
                gdpPerCapita: 4540,
                gdpPpp: 1200000000000,
                gdpGrowth: 2.5,
                inflation: 40.0,
                unemployment: 12.0,
                povertyRate: 18.0,
                mainIndustries: ['Minyak', 'Gas', 'Petrokimia', 'Otomotif', 'Tekstil'],
                exports: [
                    { item: 'Minyak', value: 50000000000 },
                    { item: 'Gas', value: 30000000000 },
                    { item: 'Petrokimia', value: 20000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 40000000000 },
                    { item: 'Elektronik', value: 20000000000 },
                    { item: 'Makanan', value: 15000000000 }
                ],
                tradeBalance: 20000000000,
                naturalResources: ['Minyak', 'Gas', 'Tembaga', 'Emas', 'Besi'],
                economicRanking: 28,
                internetPenetration: 70,
                mobilePenetration: 85,
                electricityAccess: 100,
                roadLength: 200000,
                railwayLength: 13000,
                airports: 100,
                seaports: 15,
                healthcareAccess: 80,
                educationIndex: 0.72,
                nationalMotto: 'Kemerdekaan, Kebebasan, Republik Islam',
                nationalAnthem: 'Soroud-e Melli-e Jomhouri-e Eslami-e Iran',
                nationalAnimal: 'Singa Persia',
                nationalFlower: 'Mawar Merah',
                nationalCuisine: ['Kebab', 'Tahdig', 'Fesenjan', 'Ghormeh Sabzi', 'Baghali Polo'],
                culturalHeritage: ['Persepolis', 'Isfahan', 'Shiraz', 'Teheran'],
                publicHolidays: ['Nowruz', 'Idul Fitri', 'Idul Adha', 'Ashura'],
                socialRanking: 55,
                climate: 'Beragam',
                averageTemperature: 20,
                averageRainfall: 250,
                forestArea: 7,
                protectedAreas: 10,
                biodiversityRank: 30,
                carbonEmissions: 7.5,
                environmentalIndex: 35,
                riskScore: 60,
                politicalStability: 35,
                crimeIndex: 30,
                militarySpending: 2.5,
                peaceIndex: 65,
                terrorismIndex: 45,
                refugeePopulation: 800000,
                opportunityScore: 50,
                easeOfDoingBusiness: 35,
                innovationIndex: 40,
                startupEcosystem: 45,
                investmentScore: 35,
                talentPool: 75,
                marketSize: 85,
                infrastructureQuality: 55,
                internetSpeed: 15,
                digitalAdoption: 60,
                techEcosystem: 45,
                aiReadiness: 35,
                startups: 300,
                phoneCode: '+98',
                tld: '.ir',
                isoCode: 'IRN',
                isoCode2: 'IR',
                drivingSide: 'right',
                tags: ['negara', 'asian-barat', 'persia', 'gas-alam', 'geopolitik']
            }
        },
        // ==========================================================
        // 🇮🇶 IRAK
        // ==========================================================
        {
            text: 'Irak - Negara di Asia Barat dengan peradaban Mesopotamia kuno. Ibu kota: Baghdad. Populasi: 44 juta jiwa. Mata uang: Dinar Irak (IQD). Bahasa: Arab, Kurdi. Sistem pemerintahan: Republik Federal Parlementer. Cadangan minyak terbesar ke-5 dunia. Rumah kota suci Najaf dan Karbala. Situs arkeologi Babilonia dan Ur. Negara dengan sejarah peradaban tertua di dunia.',
            metadata: {
                category: 'country',
                region: 'asian-barat',
                name: 'Irak',
                officialName: 'Republik Irak',
                shortName: 'IRQ',
                capital: 'Baghdad',
                capitalCoordinates: { lat: 33.3152, lng: 44.3661 },
                largestCity: 'Baghdad',
                demonym: 'Irak',
                subregion: 'Western Asia',
                area: 438317,
                areaRank: 58,
                coastline: 58,
                highestPoint: 'Cheekha Dar',
                highestElevation: 3611,
                lowestPoint: 'Teluk Persia',
                lowestElevation: 0,
                landBorders: ['Turki', 'Iran', 'Kuwait', 'Arab Saudi', 'Yordania', 'Suriah'],
                coordinates: { lat: 33.0, lng: 44.0 },
                timezone: ['Waktu Irak'],
                utcOffset: ['+3'],
                population: 44000000,
                populationRank: 35,
                populationDensity: 100,
                populationGrowth: 2.0,
                medianAge: 21.0,
                lifeExpectancy: 70.5,
                fertilityRate: 3.5,
                urbanization: 70,
                ethnicGroups: [
                    { name: 'Arab', percentage: 75.0 },
                    { name: 'Kurdi', percentage: 15.0 },
                    { name: 'Turkmen', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 5.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 95.0 },
                    { name: 'Kristen', percentage: 3.0 },
                    { name: 'Yazidi', percentage: 1.0 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Kurdi', percentage: 20, official: true },
                    { name: 'Turkmen', percentage: 5 }
                ],
                literacyRate: 85,
                governmentType: 'Republik Federal Parlementer',
                independenceDay: '1932-10-03',
                nationalHoliday: '3 Oktober',
                legalSystem: 'Hukum Sipil',
                constitution: '2005',
                administrativeDivisions: 19,
                memberships: ['PBB', 'OPEC', 'Liga Arab', 'OKI'],
                giniCoefficient: 29.5,
                hdi: 0.674,
                hdiRank: 120,
                corruptionIndex: 23,
                currency: 'Dinar Irak',
                currencyCode: 'IQD',
                gdp: 300000000000,
                gdpPerCapita: 6810,
                gdpPpp: 800000000000,
                gdpGrowth: 4.5,
                inflation: 3.0,
                unemployment: 15.0,
                povertyRate: 20.0,
                mainIndustries: ['Minyak', 'Gas', 'Pertanian', 'Konstruksi', 'Tekstil'],
                exports: [
                    { item: 'Minyak', value: 100000000000 },
                    { item: 'Gas', value: 10000000000 },
                    { item: 'Kurma', value: 1000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 30000000000 },
                    { item: 'Elektronik', value: 20000000000 },
                    { item: 'Makanan', value: 15000000000 }
                ],
                tradeBalance: 40000000000,
                naturalResources: ['Minyak', 'Gas', 'Fosfat', 'Sulfur'],
                economicRanking: 55,
                internetPenetration: 60,
                mobilePenetration: 75,
                electricityAccess: 90,
                roadLength: 60000,
                railwayLength: 2000,
                airports: 30,
                seaports: 5,
                healthcareAccess: 60,
                educationIndex: 0.55,
                nationalMotto: 'Kemerdekaan, Persatuan, Kemakmuran',
                nationalAnthem: 'Mawtini',
                nationalAnimal: 'Elang Emas',
                nationalFlower: 'Mawar Gurun',
                nationalCuisine: ['Kebab', 'Dolma', 'Masgouf', 'Tabbouleh', 'Baklava'],
                culturalHeritage: ['Babilonia', 'Ur', 'Najaf', 'Karbala', 'Baghdad'],
                publicHolidays: ['Idul Fitri', 'Idul Adha', 'Ashura', 'Hari Kemerdekaan'],
                socialRanking: 40,
                climate: 'Gurun',
                averageTemperature: 28,
                averageRainfall: 150,
                forestArea: 2,
                protectedAreas: 5,
                biodiversityRank: 45,
                carbonEmissions: 4.5,
                environmentalIndex: 30,
                riskScore: 75,
                politicalStability: 25,
                crimeIndex: 50,
                militarySpending: 3.5,
                peaceIndex: 80,
                terrorismIndex: 60,
                refugeePopulation: 200000,
                opportunityScore: 45,
                easeOfDoingBusiness: 40,
                innovationIndex: 30,
                startupEcosystem: 25,
                investmentScore: 35,
                talentPool: 60,
                marketSize: 80,
                infrastructureQuality: 35,
                internetSpeed: 12,
                digitalAdoption: 45,
                techEcosystem: 30,
                aiReadiness: 25,
                startups: 100,
                phoneCode: '+964',
                tld: '.iq',
                isoCode: 'IRQ',
                isoCode2: 'IQ',
                drivingSide: 'right',
                tags: ['negara', 'asian-barat', 'mesopotamia', 'minyak', 'sejarah-kuno']
            }
        },
        // ==========================================================
        // 🇹🇷 TURKI
        // ==========================================================
        {
            text: 'Turki - Negara di persimpangan Asia dan Eropa dengan sejarah Ottoman. Ibu kota: Ankara. Populasi: 85 juta jiwa. Mata uang: Lira Turki (TRY). Bahasa: Turki. Sistem pemerintahan: Republik Presidensial. Anggota NATO dan G20. Jembatan antara Timur dan Barat dengan warisan Bizantium dan Ottoman. Rumah bagi Istanbul, Cappadocia, dan Hagia Sophia. Negara dengan pengaruh budaya dan geopolitik besar.',
            metadata: {
                category: 'country',
                region: 'asian-barat',
                name: 'Turki',
                officialName: 'Republik Turki',
                shortName: 'TUR',
                capital: 'Ankara',
                capitalCoordinates: { lat: 39.9334, lng: 32.8597 },
                largestCity: 'Istanbul',
                demonym: 'Turki',
                subregion: 'Western Asia',
                area: 783562,
                areaRank: 36,
                coastline: 7200,
                highestPoint: 'Gunung Ararat',
                highestElevation: 5137,
                lowestPoint: 'Laut Hitam',
                lowestElevation: 0,
                landBorders: ['Suriah', 'Irak', 'Iran', 'Georgia', 'Armenia', 'Azerbaijan', 'Yunani', 'Bulgaria'],
                coordinates: { lat: 39.0, lng: 35.0 },
                timezone: ['Waktu Turki'],
                utcOffset: ['+3'],
                population: 85000000,
                populationRank: 18,
                populationDensity: 108,
                populationGrowth: 0.7,
                medianAge: 33.5,
                lifeExpectancy: 78.5,
                fertilityRate: 1.9,
                urbanization: 76,
                ethnicGroups: [
                    { name: 'Turki', percentage: 75.0 },
                    { name: 'Kurdi', percentage: 18.0 },
                    { name: 'Lainnya', percentage: 7.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 89.0 },
                    { name: 'Kristen', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 6.0 }
                ],
                languages: [
                    { name: 'Turki', percentage: 100, official: true },
                    { name: 'Kurdi', percentage: 18 },
                    { name: 'Inggris', percentage: 20 }
                ],
                literacyRate: 96,
                governmentType: 'Republik Presidensial',
                independenceDay: '1923-10-29',
                nationalHoliday: '29 Oktober',
                legalSystem: 'Civil Law',
                constitution: '1982',
                administrativeDivisions: 81,
                memberships: ['PBB', 'NATO', 'G20', 'OKI', 'OECD'],
                giniCoefficient: 41.9,
                hdi: 0.820,
                hdiRank: 54,
                corruptionIndex: 43,
                currency: 'Lira Turki',
                currencyCode: 'TRY',
                gdp: 906000000000,
                gdpPerCapita: 10660,
                gdpPpp: 3200000000000,
                gdpGrowth: 4.5,
                inflation: 20.0,
                unemployment: 10.0,
                povertyRate: 15.0,
                mainIndustries: ['Otomotif', 'Tekstil', 'Pariwisata', 'Pertanian', 'Manufaktur'],
                exports: [
                    { item: 'Otomotif', value: 30000000000 },
                    { item: 'Tekstil', value: 25000000000 },
                    { item: 'Elektronik', value: 20000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 40000000000 },
                    { item: 'Minyak', value: 30000000000 },
                    { item: 'Elektronik', value: 25000000000 }
                ],
                tradeBalance: -20000000000,
                naturalResources: ['Batubara', 'Tembaga', 'Emas', 'Besi', 'Marmer'],
                economicRanking: 19,
                internetPenetration: 88,
                mobilePenetration: 95,
                electricityAccess: 100,
                roadLength: 68000,
                railwayLength: 11000,
                airports: 100,
                seaports: 30,
                healthcareAccess: 85,
                educationIndex: 0.75,
                nationalMotto: 'Kedamaian di rumah, kedamaian di dunia',
                nationalAnthem: 'Istiklal Marşı',
                nationalAnimal: 'Serigala Abu-abu',
                nationalFlower: 'Tulip',
                nationalCuisine: ['Kebab', 'Baklava', 'Köfte', 'Pide', 'Börek'],
                culturalHeritage: ['Istanbul', 'Cappadocia', 'Pamukkale', 'Hagia Sophia'],
                publicHolidays: ['Hari Republik', 'Idul Fitri', 'Idul Adha', 'Hari Kemerdekaan'],
                socialRanking: 65,
                climate: 'Beragam',
                averageTemperature: 15,
                averageRainfall: 600,
                forestArea: 27,
                protectedAreas: 10,
                biodiversityRank: 20,
                carbonEmissions: 5.0,
                environmentalIndex: 45,
                riskScore: 45,
                politicalStability: 45,
                crimeIndex: 35,
                militarySpending: 2.5,
                peaceIndex: 55,
                terrorismIndex: 45,
                refugeePopulation: 4000000,
                opportunityScore: 72,
                easeOfDoingBusiness: 68,
                innovationIndex: 50,
                startupEcosystem: 60,
                investmentScore: 60,
                talentPool: 80,
                marketSize: 85,
                infrastructureQuality: 75,
                internetSpeed: 35,
                digitalAdoption: 78,
                techEcosystem: 65,
                aiReadiness: 50,
                startups: 1500,
                phoneCode: '+90',
                tld: '.tr',
                isoCode: 'TUR',
                isoCode2: 'TR',
                drivingSide: 'right',
                tags: ['negara', 'asian-barat', 'nato', 'jembatan-budaya', 'sejarah']
            }
        },
        // ==========================================================
        // 🇸🇾 SURIAH
        // ==========================================================
        {
            text: 'Suriah - Negara di Asia Barat dengan sejarah peradaban kuno. Ibu kota: Damaskus. Populasi: 22 juta jiwa. Mata uang: Pound Suriah (SYP). Bahasa: Arab. Sistem pemerintahan: Republik Presidensial. Damaskus salah satu kota tertua di dunia. Warisan budaya Romawi, Bizantium, dan Islam. Negara dengan sejarah panjang dan konflik berkepanjangan.',
            metadata: {
                category: 'country',
                region: 'asian-barat',
                name: 'Suriah',
                officialName: 'Republik Arab Suriah',
                shortName: 'SYR',
                capital: 'Damaskus',
                capitalCoordinates: { lat: 33.5138, lng: 36.2765 },
                largestCity: 'Damaskus',
                demonym: 'Suriah',
                subregion: 'Western Asia',
                area: 185180,
                areaRank: 87,
                coastline: 193,
                highestPoint: 'Gunung Hermon',
                highestElevation: 2814,
                lowestPoint: 'Danau Tiberias',
                lowestElevation: -200,
                landBorders: ['Turki', 'Irak', 'Yordania', 'Israel', 'Lebanon'],
                coordinates: { lat: 35.0, lng: 38.0 },
                timezone: ['Waktu Suriah'],
                utcOffset: ['+3'],
                population: 22000000,
                populationRank: 60,
                populationDensity: 118,
                populationGrowth: 2.5,
                medianAge: 23.0,
                lifeExpectancy: 73.0,
                fertilityRate: 2.8,
                urbanization: 55,
                ethnicGroups: [
                    { name: 'Arab', percentage: 80.0 },
                    { name: 'Kurdi', percentage: 10.0 },
                    { name: 'Turkmen', percentage: 5.0 },
                    { name: 'Lainnya', percentage: 5.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 87.0 },
                    { name: 'Kristen', percentage: 10.0 },
                    { name: 'Druze', percentage: 3.0 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Kurdi', percentage: 10 },
                    { name: 'Armenia', percentage: 3 }
                ],
                literacyRate: 86,
                governmentType: 'Republik Presidensial',
                independenceDay: '1946-04-17',
                nationalHoliday: '17 April',
                legalSystem: 'Civil Law',
                constitution: '2012',
                administrativeDivisions: 14,
                memberships: ['PBB', 'Liga Arab', 'OKI'],
                giniCoefficient: 35.0,
                hdi: 0.577,
                hdiRank: 150,
                corruptionIndex: 20,
                currency: 'Pound Suriah',
                currencyCode: 'SYP',
                gdp: 60000000000,
                gdpPerCapita: 2720,
                gdpPpp: 200000000000,
                gdpGrowth: -5.0,
                inflation: 50.0,
                unemployment: 30.0,
                povertyRate: 50.0,
                mainIndustries: ['Minyak', 'Pertanian', 'Tekstil', 'Pariwisata'],
                exports: [
                    { item: 'Minyak', value: 5000000000 },
                    { item: 'Tekstil', value: 2000000000 },
                    { item: 'Pertanian', value: 1000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 5000000000 },
                    { item: 'Makanan', value: 3000000000 },
                    { item: 'Elektronik', value: 2000000000 }
                ],
                tradeBalance: -3000000000,
                naturalResources: ['Minyak', 'Gas', 'Fosfat', 'Besi'],
                economicRanking: 85,
                internetPenetration: 40,
                mobilePenetration: 60,
                electricityAccess: 70,
                roadLength: 40000,
                railwayLength: 2000,
                airports: 15,
                seaports: 4,
                healthcareAccess: 40,
                educationIndex: 0.45,
                nationalMotto: 'Persatuan, Kebebasan, Sosialisme',
                nationalAnthem: 'Humat ad-Diyar',
                nationalAnimal: 'Elang',
                nationalFlower: 'Mawar Gurun',
                nationalCuisine: ['Kebab', 'Hummus', 'Falafel', 'Baklava', 'Tabbouleh'],
                culturalHeritage: ['Damaskus', 'Aleppo', 'Palmyra', 'Bosra'],
                publicHolidays: ['Idul Fitri', 'Idul Adha', 'Hari Kemerdekaan', 'Tahun Baru'],
                socialRanking: 25,
                climate: 'Gurun',
                averageTemperature: 25,
                averageRainfall: 200,
                forestArea: 5,
                protectedAreas: 3,
                biodiversityRank: 50,
                carbonEmissions: 2.5,
                environmentalIndex: 25,
                riskScore: 85,
                politicalStability: 15,
                crimeIndex: 55,
                militarySpending: 5.0,
                peaceIndex: 85,
                terrorismIndex: 70,
                refugeePopulation: 6000000,
                opportunityScore: 25,
                easeOfDoingBusiness: 25,
                innovationIndex: 20,
                startupEcosystem: 15,
                investmentScore: 15,
                talentPool: 45,
                marketSize: 60,
                infrastructureQuality: 20,
                internetSpeed: 8,
                digitalAdoption: 25,
                techEcosystem: 15,
                aiReadiness: 15,
                startups: 20,
                phoneCode: '+963',
                tld: '.sy',
                isoCode: 'SYR',
                isoCode2: 'SY',
                drivingSide: 'right',
                tags: ['negara', 'asian-barat', 'sejarah-kuno', 'damaskus', 'warisan-budaya']
            }
        },
        // ==========================================================
        // 🇾🇪 YAMAN
        // ==========================================================
        {
            text: 'Yaman - Negara di Asia Barat dengan sejarah kuno dan budaya kaya. Ibu kota: Sanaa. Populasi: 33 juta jiwa. Mata uang: Rial Yaman (YER). Bahasa: Arab. Sistem pemerintahan: Republik Presidensial. Arsitektur kuno unik di Sanaa dan Shibam. Terkenal kopi Mocha dan rempah-rempah. Negara dengan warisan budaya kuno dan konflik berkepanjangan.',
            metadata: {
                category: 'country',
                region: 'asian-barat',
                name: 'Yaman',
                officialName: 'Republik Yaman',
                shortName: 'YEM',
                capital: 'Sanaa',
                capitalCoordinates: { lat: 15.3694, lng: 44.1910 },
                largestCity: 'Sanaa',
                demonym: 'Yaman',
                subregion: 'Western Asia',
                area: 527968,
                areaRank: 49,
                coastline: 1906,
                highestPoint: 'Jabal An Nabi Shu\'ayb',
                highestElevation: 3666,
                lowestPoint: 'Laut Arab',
                lowestElevation: 0,
                landBorders: ['Arab Saudi', 'Oman'],
                coordinates: { lat: 15.0, lng: 48.0 },
                timezone: ['Waktu Yaman'],
                utcOffset: ['+3'],
                population: 33000000,
                populationRank: 43,
                populationDensity: 62,
                populationGrowth: 2.0,
                medianAge: 20.0,
                lifeExpectancy: 66.0,
                fertilityRate: 3.5,
                urbanization: 38,
                ethnicGroups: [
                    { name: 'Arab', percentage: 95.0 },
                    { name: 'Afro-Arab', percentage: 5.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 99.0 },
                    { name: 'Kristen', percentage: 0.5 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true }
                ],
                literacyRate: 70,
                governmentType: 'Republik Presidensial',
                independenceDay: '1990-05-22',
                nationalHoliday: '22 Mei',
                legalSystem: 'Hukum Syariah',
                constitution: '1990',
                administrativeDivisions: 22,
                memberships: ['PBB', 'Liga Arab', 'OKI'],
                giniCoefficient: 36.7,
                hdi: 0.455,
                hdiRank: 179,
                corruptionIndex: 18,
                currency: 'Rial Yaman',
                currencyCode: 'YER',
                gdp: 20000000000,
                gdpPerCapita: 610,
                gdpPpp: 65000000000,
                gdpGrowth: -8.0,
                inflation: 40.0,
                unemployment: 25.0,
                povertyRate: 60.0,
                mainIndustries: ['Minyak', 'Gas', 'Pertanian', 'Pariwisata'],
                exports: [
                    { item: 'Minyak', value: 5000000000 },
                    { item: 'Kopi', value: 1000000000 },
                    { item: 'Rempah', value: 500000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 3000000000 },
                    { item: 'Makanan', value: 2500000000 },
                    { item: 'Elektronik', value: 1000000000 }
                ],
                tradeBalance: -1000000000,
                naturalResources: ['Minyak', 'Gas', 'Emas', 'Tembaga', 'Garam'],
                economicRanking: 90,
                internetPenetration: 30,
                mobilePenetration: 50,
                electricityAccess: 60,
                roadLength: 30000,
                railwayLength: 0,
                airports: 15,
                seaports: 5,
                healthcareAccess: 35,
                educationIndex: 0.38,
                nationalMotto: 'Allah, Bangsa, Kemerdekaan',
                nationalAnthem: 'United Republic',
                nationalAnimal: 'Elang',
                nationalFlower: 'Mawar Gurun',
                nationalCuisine: ['Saltah', 'Mandi', 'Kabsa', 'Bint Al-Sahn'],
                culturalHeritage: ['Shibam', 'Sanaa', 'Zabid', 'Socotra'],
                publicHolidays: ['Idul Fitri', 'Idul Adha', 'Hari Kemerdekaan', 'Ashura'],
                socialRanking: 20,
                climate: 'Gurun',
                averageTemperature: 30,
                averageRainfall: 100,
                forestArea: 1,
                protectedAreas: 2,
                biodiversityRank: 55,
                carbonEmissions: 0.5,
                environmentalIndex: 20,
                riskScore: 90,
                politicalStability: 10,
                crimeIndex: 50,
                militarySpending: 4.0,
                peaceIndex: 90,
                terrorismIndex: 75,
                refugeePopulation: 100000,
                opportunityScore: 20,
                easeOfDoingBusiness: 20,
                innovationIndex: 15,
                startupEcosystem: 10,
                investmentScore: 15,
                talentPool: 35,
                marketSize: 50,
                infrastructureQuality: 15,
                internetSpeed: 5,
                digitalAdoption: 20,
                techEcosystem: 10,
                aiReadiness: 10,
                startups: 10,
                phoneCode: '+967',
                tld: '.ye',
                isoCode: 'YEM',
                isoCode2: 'YE',
                drivingSide: 'right',
                tags: ['negara', 'asian-barat', 'kopi-mocha', 'arsitektur-kuno', 'rempah']
            }
        },
        // ==========================================================
        // 🇴🇲 OMAN
        // ==========================================================
        {
            text: 'Oman - Negara di Asia Barat dengan sejarah maritim dan budaya kaya. Ibu kota: Muskat. Populasi: 4.5 juta jiwa. Mata uang: Rial Oman (OMR). Bahasa: Arab. Sistem pemerintahan: Monarki Absolut. Ekonomi berbasis minyak dan gas. Benteng-benteng kuno dan pelabuhan bersejarah. Salah satu negara paling stabil di Timur Tengah.',
            metadata: {
                category: 'country',
                region: 'asian-barat',
                name: 'Oman',
                officialName: 'Kesultanan Oman',
                shortName: 'OMN',
                capital: 'Muskat',
                capitalCoordinates: { lat: 23.5880, lng: 58.3829 },
                largestCity: 'Muskat',
                demonym: 'Oman',
                subregion: 'Western Asia',
                area: 309500,
                areaRank: 70,
                coastline: 2092,
                highestPoint: 'Jabal Shams',
                highestElevation: 3009,
                lowestPoint: 'Laut Arab',
                lowestElevation: 0,
                landBorders: ['Arab Saudi', 'UAE', 'Yaman'],
                coordinates: { lat: 21.0, lng: 57.0 },
                timezone: ['Waktu Teluk'],
                utcOffset: ['+4'],
                population: 4500000,
                populationRank: 125,
                populationDensity: 14,
                populationGrowth: 2.0,
                medianAge: 31.0,
                lifeExpectancy: 75.0,
                fertilityRate: 2.2,
                urbanization: 84,
                ethnicGroups: [
                    { name: 'Arab', percentage: 85.0 },
                    { name: 'Baloch', percentage: 10.0 },
                    { name: 'Lainnya', percentage: 5.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 95.0 },
                    { name: 'Kristen', percentage: 2.0 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 30 },
                    { name: 'Baloch', percentage: 10 }
                ],
                literacyRate: 92,
                governmentType: 'Monarki Absolut',
                independenceDay: '1970-07-23',
                nationalHoliday: '18 November',
                legalSystem: 'Hukum Syariah',
                constitution: '1996',
                administrativeDivisions: 11,
                memberships: ['PBB', 'Liga Arab', 'OKI', 'GCC'],
                giniCoefficient: 30.0,
                hdi: 0.813,
                hdiRank: 60,
                corruptionIndex: 54,
                currency: 'Rial Oman',
                currencyCode: 'OMR',
                gdp: 110000000000,
                gdpPerCapita: 24400,
                gdpPpp: 200000000000,
                gdpGrowth: 3.0,
                inflation: 2.5,
                unemployment: 3.0,
                povertyRate: 1.0,
                mainIndustries: ['Minyak', 'Gas', 'Pariwisata', 'Perikanan', 'Logistik'],
                exports: [
                    { item: 'Minyak', value: 30000000000 },
                    { item: 'Gas', value: 10000000000 },
                    { item: 'Tekstil', value: 5000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 15000000000 },
                    { item: 'Elektronik', value: 8000000000 },
                    { item: 'Makanan', value: 5000000000 }
                ],
                tradeBalance: 20000000000,
                naturalResources: ['Minyak', 'Gas', 'Emas', 'Tembaga', 'Garam'],
                economicRanking: 60,
                internetPenetration: 88,
                mobilePenetration: 95,
                electricityAccess: 100,
                roadLength: 60000,
                railwayLength: 0,
                airports: 20,
                seaports: 10,
                healthcareAccess: 85,
                educationIndex: 0.72,
                nationalMotto: 'Allah, Bangsa, Sultan',
                nationalAnthem: 'As-Salam as-Sultani',
                nationalAnimal: 'Kuda Arab',
                nationalFlower: 'Mawar Gurun',
                nationalCuisine: ['Shuwa', 'Mandi', 'Kabsa', 'Halwa', 'Tahini'],
                culturalHeritage: ['Bahla Fort', 'Nizwa', 'Muscat', 'Salalah'],
                publicHolidays: ['Idul Fitri', 'Idul Adha', 'Hari Nasional', 'Tahun Baru Islam'],
                socialRanking: 75,
                climate: 'Gurun',
                averageTemperature: 28,
                averageRainfall: 100,
                forestArea: 1,
                protectedAreas: 10,
                biodiversityRank: 40,
                carbonEmissions: 15.0,
                environmentalIndex: 45,
                riskScore: 25,
                politicalStability: 80,
                crimeIndex: 15,
                militarySpending: 8.0,
                peaceIndex: 30,
                terrorismIndex: 15,
                refugeePopulation: 0,
                opportunityScore: 68,
                easeOfDoingBusiness: 60,
                innovationIndex: 40,
                startupEcosystem: 45,
                investmentScore: 65,
                talentPool: 55,
                marketSize: 60,
                infrastructureQuality: 80,
                internetSpeed: 40,
                digitalAdoption: 75,
                techEcosystem: 50,
                aiReadiness: 40,
                startups: 100,
                phoneCode: '+968',
                tld: '.om',
                isoCode: 'OMN',
                isoCode2: 'OM',
                drivingSide: 'right',
                tags: ['negara', 'asian-barat', 'maritim', 'benteng', 'stabil']
            }
        },
        // ==========================================================
        // 🇦🇪 UNI EMIRAT ARAB
        // ==========================================================
        {
            text: 'Uni Emirat Arab - Negara federasi di Asia Barat dengan ekonomi maju dan Dubai. Ibu kota: Abu Dhabi. Populasi: 9.5 juta jiwa. Mata uang: Dirham UAE (AED). Bahasa: Arab, Inggris. Sistem pemerintahan: Monarki Konstitusional Federal. Pusat keuangan, perdagangan, dan pariwisata global. Burj Khalifa, gedung tertinggi dunia. Inovasi dan diversifikasi ekonomi terbaik di Timur Tengah.',
            metadata: {
                category: 'country',
                region: 'asian-barat',
                name: 'Uni Emirat Arab',
                officialName: 'Uni Emirat Arab',
                shortName: 'UAE',
                capital: 'Abu Dhabi',
                capitalCoordinates: { lat: 24.4539, lng: 54.3773 },
                largestCity: 'Dubai',
                demonym: 'Emirati',
                subregion: 'Western Asia',
                area: 83600,
                areaRank: 114,
                coastline: 1318,
                highestPoint: 'Jabal Hafeet',
                highestElevation: 1249,
                lowestPoint: 'Teluk Persia',
                lowestElevation: 0,
                landBorders: ['Arab Saudi', 'Oman'],
                coordinates: { lat: 24.0, lng: 54.0 },
                timezone: ['Waktu Teluk'],
                utcOffset: ['+4'],
                population: 9500000,
                populationRank: 92,
                populationDensity: 113,
                populationGrowth: 1.5,
                medianAge: 35.0,
                lifeExpectancy: 78.0,
                fertilityRate: 1.4,
                urbanization: 86,
                ethnicGroups: [
                    { name: 'Emirati', percentage: 11.0 },
                    { name: 'Asia Selatan', percentage: 50.0 },
                    { name: 'Ekspatriat', percentage: 39.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 76.0 },
                    { name: 'Kristen', percentage: 12.0 },
                    { name: 'Hindu', percentage: 8.0 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 80 },
                    { name: 'Hindi', percentage: 20 }
                ],
                literacyRate: 93,
                governmentType: 'Monarki Konstitusional Federal',
                independenceDay: '1971-12-02',
                nationalHoliday: '2 Desember',
                legalSystem: 'Hukum Sipil, Syariah',
                constitution: '1971',
                administrativeDivisions: 7,
                memberships: ['PBB', 'Liga Arab', 'GCC', 'OKI', 'OPEC'],
                giniCoefficient: 32.5,
                hdi: 0.890,
                hdiRank: 31,
                corruptionIndex: 71,
                currency: 'Dirham UAE',
                currencyCode: 'AED',
                gdp: 500000000000,
                gdpPerCapita: 52600,
                gdpPpp: 800000000000,
                gdpGrowth: 4.0,
                inflation: 2.0,
                unemployment: 2.5,
                povertyRate: 0.5,
                mainIndustries: ['Minyak', 'Gas', 'Pariwisata', 'Keuangan', 'Perdagangan'],
                exports: [
                    { item: 'Minyak', value: 100000000000 },
                    { item: 'Gas', value: 30000000000 },
                    { item: 'Keuangan', value: 20000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 50000000000 },
                    { item: 'Elektronik', value: 30000000000 },
                    { item: 'Makanan', value: 20000000000 }
                ],
                tradeBalance: 60000000000,
                naturalResources: ['Minyak', 'Gas', 'Garam'],
                economicRanking: 30,
                internetPenetration: 95,
                mobilePenetration: 99,
                electricityAccess: 100,
                roadLength: 4000,
                railwayLength: 0,
                airports: 10,
                seaports: 10,
                healthcareAccess: 95,
                educationIndex: 0.82,
                nationalMotto: 'Allah, Negara, Presiden',
                nationalAnthem: 'Ishy Bilady',
                nationalAnimal: 'Falcon',
                nationalFlower: 'Bunga Gurun',
                nationalCuisine: ['Shawarma', 'Hummus', 'Kabsa', 'Baklava', 'Machboos'],
                culturalHeritage: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain'],
                publicHolidays: ['Idul Fitri', 'Idul Adha', 'Hari Nasional', 'Tahun Baru'],
                socialRanking: 85,
                climate: 'Gurun',
                averageTemperature: 30,
                averageRainfall: 50,
                forestArea: 0.5,
                protectedAreas: 10,
                biodiversityRank: 65,
                carbonEmissions: 25.0,
                environmentalIndex: 50,
                riskScore: 20,
                politicalStability: 85,
                crimeIndex: 15,
                militarySpending: 5.0,
                peaceIndex: 25,
                terrorismIndex: 10,
                refugeePopulation: 0,
                opportunityScore: 85,
                easeOfDoingBusiness: 85,
                innovationIndex: 65,
                startupEcosystem: 75,
                investmentScore: 85,
                talentPool: 80,
                marketSize: 80,
                infrastructureQuality: 95,
                internetSpeed: 50,
                digitalAdoption: 90,
                techEcosystem: 80,
                aiReadiness: 70,
                startups: 3000,
                phoneCode: '+971',
                tld: '.ae',
                isoCode: 'ARE',
                isoCode2: 'AE',
                drivingSide: 'right',
                tags: ['negara', 'asian-barat', 'dubai', 'pusat-keuangan', 'pariwisata']
            }
        },
        // ==========================================================
        // 🇶🇦 QATAR
        // ==========================================================
        {
            text: 'Qatar - Negara di Asia Barat dengan ekonomi terkaya per kapita. Ibu kota: Doha. Populasi: 2.7 juta jiwa. Mata uang: Riyal Qatar (QAR). Bahasa: Arab. Sistem pemerintahan: Monarki Konstitusional. Cadangan gas alam terbesar ketiga dunia. Tuan rumah Piala Dunia FIFA 2022. Pusat media global Al Jazeera. Negara dengan inovasi dan pengaruh global.',
            metadata: {
                category: 'country',
                region: 'asian-barat',
                name: 'Qatar',
                officialName: 'Negara Qatar',
                shortName: 'QAT',
                capital: 'Doha',
                capitalCoordinates: { lat: 25.3548, lng: 51.1839 },
                largestCity: 'Doha',
                demonym: 'Qatar',
                subregion: 'Western Asia',
                area: 11586,
                areaRank: 164,
                coastline: 563,
                highestPoint: 'Qurain Abu al-Bawl',
                highestElevation: 103,
                lowestPoint: 'Teluk Persia',
                lowestElevation: 0,
                landBorders: ['Arab Saudi'],
                coordinates: { lat: 25.5, lng: 51.25 },
                timezone: ['Waktu Arab'],
                utcOffset: ['+3'],
                population: 2700000,
                populationRank: 139,
                populationDensity: 233,
                populationGrowth: 1.5,
                medianAge: 33.0,
                lifeExpectancy: 80.0,
                fertilityRate: 1.8,
                urbanization: 99,
                ethnicGroups: [
                    { name: 'Arab', percentage: 40.0 },
                    { name: 'Asia Selatan', percentage: 36.0 },
                    { name: 'Ekspatriat', percentage: 24.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 67.0 },
                    { name: 'Kristen', percentage: 15.0 },
                    { name: 'Hindu', percentage: 14.0 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 70 },
                    { name: 'Hindi', percentage: 20 }
                ],
                literacyRate: 93,
                governmentType: 'Monarki Konstitusional',
                independenceDay: '1971-09-03',
                nationalHoliday: '18 Desember',
                legalSystem: 'Civil Law, Syariah',
                constitution: '2003',
                administrativeDivisions: 8,
                memberships: ['PBB', 'Liga Arab', 'GCC', 'OKI', 'OPEC'],
                giniCoefficient: 41.0,
                hdi: 0.855,
                hdiRank: 42,
                corruptionIndex: 63,
                currency: 'Riyal Qatar',
                currencyCode: 'QAR',
                gdp: 220000000000,
                gdpPerCapita: 81000,
                gdpPpp: 350000000000,
                gdpGrowth: 3.5,
                inflation: 2.0,
                unemployment: 0.1,
                povertyRate: 0.0,
                mainIndustries: ['Gas', 'Minyak', 'Petrokimia', 'Keuangan', 'Media'],
                exports: [
                    { item: 'Gas', value: 80000000000 },
                    { item: 'Minyak', value: 40000000000 },
                    { item: 'Petrokimia', value: 20000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 30000000000 },
                    { item: 'Elektronik', value: 20000000000 },
                    { item: 'Makanan', value: 10000000000 }
                ],
                tradeBalance: 80000000000,
                naturalResources: ['Gas', 'Minyak'],
                economicRanking: 50,
                internetPenetration: 92,
                mobilePenetration: 98,
                electricityAccess: 100,
                roadLength: 1000,
                railwayLength: 0,
                airports: 5,
                seaports: 3,
                healthcareAccess: 90,
                educationIndex: 0.78,
                nationalMotto: 'Allah, Bangsa, Emir',
                nationalAnthem: 'As-Salam al-Amiri',
                nationalAnimal: 'Falcon',
                nationalFlower: 'Bunga Gurun',
                nationalCuisine: ['Machboos', 'Hummus', 'Shawarma', 'Baklava'],
                culturalHeritage: ['Doha', 'Al Zubarah', 'Katara', 'Souq Waqif'],
                publicHolidays: ['Idul Fitri', 'Idul Adha', 'Hari Nasional', 'Tahun Baru'],
                socialRanking: 82,
                climate: 'Gurun',
                averageTemperature: 30,
                averageRainfall: 75,
                forestArea: 0,
                protectedAreas: 5,
                biodiversityRank: 70,
                carbonEmissions: 35.0,
                environmentalIndex: 42,
                riskScore: 20,
                politicalStability: 85,
                crimeIndex: 10,
                militarySpending: 5.0,
                peaceIndex: 28,
                terrorismIndex: 8,
                refugeePopulation: 0,
                opportunityScore: 80,
                easeOfDoingBusiness: 75,
                innovationIndex: 55,
                startupEcosystem: 60,
                investmentScore: 80,
                talentPool: 70,
                marketSize: 70,
                infrastructureQuality: 90,
                internetSpeed: 55,
                digitalAdoption: 88,
                techEcosystem: 70,
                aiReadiness: 60,
                startups: 400,
                phoneCode: '+974',
                tld: '.qa',
                isoCode: 'QAT',
                isoCode2: 'QA',
                drivingSide: 'right',
                tags: ['negara', 'asian-barat', 'gas-alam', 'piala-dunia', 'media']
            }
        },
        // ==========================================================
        // 🇰🇼 KUWAIT
        // ==========================================================
        {
            text: 'Kuwait - Negara di Asia Barat dengan ekonomi berbasis minyak. Ibu kota: Kuwait City. Populasi: 4.3 juta jiwa. Mata uang: Dinar Kuwait (KWD). Bahasa: Arab. Sistem pemerintahan: Monarki Konstitusional. Mata uang tertinggi di dunia. Parlemen aktif dan kebebasan pers relatif tinggi. Negara dengan demokrasi paling maju di Teluk.',
            metadata: {
                category: 'country',
                region: 'asian-barat',
                name: 'Kuwait',
                officialName: 'Negara Kuwait',
                shortName: 'KWT',
                capital: 'Kuwait City',
                capitalCoordinates: { lat: 29.3759, lng: 47.9774 },
                largestCity: 'Kuwait City',
                demonym: 'Kuwait',
                subregion: 'Western Asia',
                area: 17818,
                areaRank: 152,
                coastline: 499,
                highestPoint: 'Mutla Ridge',
                highestElevation: 306,
                lowestPoint: 'Teluk Persia',
                lowestElevation: 0,
                landBorders: ['Irak', 'Arab Saudi'],
                coordinates: { lat: 29.5, lng: 47.75 },
                timezone: ['Waktu Arab'],
                utcOffset: ['+3'],
                population: 4300000,
                populationRank: 128,
                populationDensity: 240,
                populationGrowth: 1.5,
                medianAge: 34.0,
                lifeExpectancy: 78.5,
                fertilityRate: 2.0,
                urbanization: 100,
                ethnicGroups: [
                    { name: 'Arab', percentage: 70.0 },
                    { name: 'Asia Selatan', percentage: 25.0 },
                    { name: 'Lainnya', percentage: 5.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 76.0 },
                    { name: 'Kristen', percentage: 18.0 },
                    { name: 'Lainnya', percentage: 6.0 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 40 },
                    { name: 'Hindi', percentage: 20 }
                ],
                literacyRate: 94,
                governmentType: 'Monarki Konstitusional',
                independenceDay: '1961-06-19',
                nationalHoliday: '25 Februari',
                legalSystem: 'Civil Law, Syariah',
                constitution: '1962',
                administrativeDivisions: 6,
                memberships: ['PBB', 'Liga Arab', 'GCC', 'OKI', 'OPEC'],
                giniCoefficient: 36.0,
                hdi: 0.806,
                hdiRank: 64,
                corruptionIndex: 42,
                currency: 'Dinar Kuwait',
                currencyCode: 'KWD',
                gdp: 160000000000,
                gdpPerCapita: 37200,
                gdpPpp: 250000000000,
                gdpGrowth: 3.0,
                inflation: 2.0,
                unemployment: 2.0,
                povertyRate: 0.5,
                mainIndustries: ['Minyak', 'Gas', 'Petrokimia', 'Keuangan', 'Konstruksi'],
                exports: [
                    { item: 'Minyak', value: 60000000000 },
                    { item: 'Petrokimia', value: 20000000000 },
                    { item: 'Gas', value: 10000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 20000000000 },
                    { item: 'Elektronik', value: 15000000000 },
                    { item: 'Makanan', value: 10000000000 }
                ],
                tradeBalance: 40000000000,
                naturalResources: ['Minyak', 'Gas', 'Garam'],
                economicRanking: 55,
                internetPenetration: 90,
                mobilePenetration: 96,
                electricityAccess: 100,
                roadLength: 5000,
                railwayLength: 0,
                airports: 5,
                seaports: 3,
                healthcareAccess: 88,
                educationIndex: 0.76,
                nationalMotto: 'Allah, Bangsa, Emir',
                nationalAnthem: 'Al-Nasheed Al-Watani',
                nationalAnimal: 'Falcon',
                nationalFlower: 'Bunga Gurun',
                nationalCuisine: ['Machboos', 'Mutabbaq', 'Jareesh', 'Kebab'],
                culturalHeritage: ['Kuwait City', 'Failaka Island', 'Kuwait Towers'],
                publicHolidays: ['Idul Fitri', 'Idul Adha', 'Hari Nasional', 'Hari Pembebasan'],
                socialRanking: 78,
                climate: 'Gurun',
                averageTemperature: 30,
                averageRainfall: 100,
                forestArea: 0,
                protectedAreas: 5,
                biodiversityRank: 75,
                carbonEmissions: 20.0,
                environmentalIndex: 38,
                riskScore: 30,
                politicalStability: 70,
                crimeIndex: 20,
                militarySpending: 5.0,
                peaceIndex: 35,
                terrorismIndex: 20,
                refugeePopulation: 0,
                opportunityScore: 72,
                easeOfDoingBusiness: 65,
                innovationIndex: 45,
                startupEcosystem: 50,
                investmentScore: 68,
                talentPool: 65,
                marketSize: 65,
                infrastructureQuality: 80,
                internetSpeed: 45,
                digitalAdoption: 78,
                techEcosystem: 55,
                aiReadiness: 45,
                startups: 150,
                phoneCode: '+965',
                tld: '.kw',
                isoCode: 'KWT',
                isoCode2: 'KW',
                drivingSide: 'right',
                tags: ['negara', 'asian-barat', 'minyak', 'demokrasi', 'mata-uang-tertinggi']
            }
        },
        // ==========================================================
        // 🇧🇭 BAHRAIN
        // ==========================================================
        {
            text: 'Bahrain - Negara kepulauan di Asia Barat. Ibu kota: Manama. Populasi: 1.5 juta jiwa. Mata uang: Dinar Bahrain (BHD). Bahasa: Arab. Sistem pemerintahan: Monarki Konstitusional. Pusat keuangan dan perbankan Timur Tengah. Sirkuit Internasional Bahrain tuan rumah F1. Sejarah perdagangan mutiara. Negara dengan ekonomi paling diversifikasi di Teluk.',
            metadata: {
                category: 'country',
                region: 'asian-barat',
                name: 'Bahrain',
                officialName: 'Kerajaan Bahrain',
                shortName: 'BHR',
                capital: 'Manama',
                capitalCoordinates: { lat: 26.2285, lng: 50.5860 },
                largestCity: 'Manama',
                demonym: 'Bahrain',
                subregion: 'Western Asia',
                area: 765,
                areaRank: 172,
                coastline: 161,
                highestPoint: 'Jabal ad-Dukhan',
                highestElevation: 134,
                lowestPoint: 'Teluk Persia',
                lowestElevation: 0,
                landBorders: [],
                coordinates: { lat: 26.0, lng: 50.55 },
                timezone: ['Waktu Arab'],
                utcOffset: ['+3'],
                population: 1500000,
                populationRank: 149,
                populationDensity: 1960,
                populationGrowth: 1.0,
                medianAge: 32.0,
                lifeExpectancy: 77.0,
                fertilityRate: 1.8,
                urbanization: 89,
                ethnicGroups: [
                    { name: 'Bahraini', percentage: 50.0 },
                    { name: 'Asia Selatan', percentage: 30.0 },
                    { name: 'Ekspatriat', percentage: 20.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 70.0 },
                    { name: 'Kristen', percentage: 15.0 },
                    { name: 'Hindu', percentage: 10.0 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 50 },
                    { name: 'Hindi', percentage: 20 }
                ],
                literacyRate: 95,
                governmentType: 'Monarki Konstitusional',
                independenceDay: '1971-08-14',
                nationalHoliday: '16 Desember',
                legalSystem: 'Civil Law, Syariah',
                constitution: '2002',
                administrativeDivisions: 4,
                memberships: ['PBB', 'Liga Arab', 'GCC', 'OKI'],
                giniCoefficient: 35.0,
                hdi: 0.852,
                hdiRank: 43,
                corruptionIndex: 48,
                currency: 'Dinar Bahrain',
                currencyCode: 'BHD',
                gdp: 40000000000,
                gdpPerCapita: 26600,
                gdpPpp: 75000000000,
                gdpGrowth: 4.0,
                inflation: 2.5,
                unemployment: 3.0,
                povertyRate: 0.5,
                mainIndustries: ['Keuangan', 'Minyak', 'Aluminium', 'Pariwisata', 'Perbankan'],
                exports: [
                    { item: 'Minyak', value: 10000000000 },
                    { item: 'Aluminium', value: 5000000000 },
                    { item: 'Keuangan', value: 3000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 8000000000 },
                    { item: 'Elektronik', value: 5000000000 },
                    { item: 'Makanan', value: 3000000000 }
                ],
                tradeBalance: 5000000000,
                naturalResources: ['Minyak', 'Gas', 'Mutiara', 'Garam'],
                economicRanking: 70,
                internetPenetration: 90,
                mobilePenetration: 96,
                electricityAccess: 100,
                roadLength: 4000,
                railwayLength: 0,
                airports: 5,
                seaports: 3,
                healthcareAccess: 88,
                educationIndex: 0.76,
                nationalMotto: 'Allah, Bangsa, Raja',
                nationalAnthem: 'Bahrainona',
                nationalAnimal: 'Falcon',
                nationalFlower: 'Bunga Gurun',
                nationalCuisine: ['Machboos', 'Hummus', 'Shawarma', 'Baklava'],
                culturalHeritage: ['Manama', 'Muharraq', 'Arad Fort'],
                publicHolidays: ['Idul Fitri', 'Idul Adha', 'Hari Nasional', 'Ashura'],
                socialRanking: 76,
                climate: 'Gurun',
                averageTemperature: 30,
                averageRainfall: 75,
                forestArea: 0,
                protectedAreas: 3,
                biodiversityRank: 70,
                carbonEmissions: 25.0,
                environmentalIndex: 40,
                riskScore: 35,
                politicalStability: 55,
                crimeIndex: 25,
                militarySpending: 4.0,
                peaceIndex: 40,
                terrorismIndex: 25,
                refugeePopulation: 0,
                opportunityScore: 70,
                easeOfDoingBusiness: 70,
                innovationIndex: 50,
                startupEcosystem: 55,
                investmentScore: 68,
                talentPool: 65,
                marketSize: 60,
                infrastructureQuality: 82,
                internetSpeed: 40,
                digitalAdoption: 78,
                techEcosystem: 58,
                aiReadiness: 48,
                startups: 150,
                phoneCode: '+973',
                tld: '.bh',
                isoCode: 'BHR',
                isoCode2: 'BH',
                drivingSide: 'right',
                tags: ['negara', 'asian-barat', 'keuangan', 'f1', 'mutiara']
            }
        },
        // ==========================================================
        // 🇯🇴 YORDANIA
        // ==========================================================
        {
            text: 'Yordania - Negara di Asia Barat dengan sejarah dan keramahan terkenal. Ibu kota: Amman. Populasi: 11 juta jiwa. Mata uang: Dinar Yordania (JOD). Bahasa: Arab. Sistem pemerintahan: Monarki Konstitusional. Rumah Petra, salah satu keajaiban dunia baru. Negara stabil dengan pariwisata maju. Destinasi wisata terbaik di Timur Tengah dengan situs sejarah kuno dan Laut Mati.',
            metadata: {
                category: 'country',
                region: 'asian-barat',
                name: 'Yordania',
                officialName: 'Kerajaan Hashemite Yordania',
                shortName: 'JOR',
                capital: 'Amman',
                capitalCoordinates: { lat: 31.9539, lng: 35.9106 },
                largestCity: 'Amman',
                demonym: 'Yordania',
                subregion: 'Western Asia',
                area: 89342,
                areaRank: 110,
                coastline: 26,
                highestPoint: 'Gunung Nebo',
                highestElevation: 1754,
                lowestPoint: 'Laut Mati',
                lowestElevation: -408,
                landBorders: ['Suriah', 'Irak', 'Arab Saudi', 'Israel', 'Palestina'],
                coordinates: { lat: 31.0, lng: 36.0 },
                timezone: ['Waktu Yordania'],
                utcOffset: ['+3'],
                population: 11000000,
                populationRank: 81,
                populationDensity: 123,
                populationGrowth: 2.0,
                medianAge: 23.0,
                lifeExpectancy: 74.0,
                fertilityRate: 2.5,
                urbanization: 91,
                ethnicGroups: [
                    { name: 'Arab', percentage: 95.0 },
                    { name: 'Circassian', percentage: 3.0 },
                    { name: 'Lainnya', percentage: 2.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 94.0 },
                    { name: 'Kristen', percentage: 5.0 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 30 }
                ],
                literacyRate: 96,
                governmentType: 'Monarki Konstitusional',
                independenceDay: '1946-05-25',
                nationalHoliday: '25 Mei',
                legalSystem: 'Civil Law, Syariah',
                constitution: '1952',
                administrativeDivisions: 12,
                memberships: ['PBB', 'Liga Arab', 'OKI'],
                giniCoefficient: 35.4,
                hdi: 0.720,
                hdiRank: 102,
                corruptionIndex: 53,
                currency: 'Dinar Yordania',
                currencyCode: 'JOD',
                gdp: 50000000000,
                gdpPerCapita: 4540,
                gdpPpp: 120000000000,
                gdpGrowth: 3.5,
                inflation: 3.0,
                unemployment: 15.0,
                povertyRate: 15.0,
                mainIndustries: ['Pariwisata', 'Tekstil', 'Fosfat', 'Pertanian', 'Keuangan'],
                exports: [
                    { item: 'Tekstil', value: 5000000000 },
                    { item: 'Fosfat', value: 3000000000 },
                    { item: 'Pariwisata', value: 2000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 8000000000 },
                    { item: 'Elektronik', value: 5000000000 },
                    { item: 'Minyak', value: 4000000000 }
                ],
                tradeBalance: -5000000000,
                naturalResources: ['Fosfat', 'Kalium', 'Batu kapur', 'Gas'],
                economicRanking: 85,
                internetPenetration: 85,
                mobilePenetration: 92,
                electricityAccess: 100,
                roadLength: 8000,
                railwayLength: 500,
                airports: 10,
                seaports: 2,
                healthcareAccess: 85,
                educationIndex: 0.68,
                nationalMotto: 'Allah, Negara, Raja',
                nationalAnthem: 'As-Salam al-Malaki',
                nationalAnimal: 'Kuda Arab',
                nationalFlower: 'Mawar Gurun',
                nationalCuisine: ['Mansaf', 'Hummus', 'Falafel', 'Kunafa', 'Maqluba'],
                culturalHeritage: ['Petra', 'Jerash', 'Amman', 'Laut Mati'],
                publicHolidays: ['Idul Fitri', 'Idul Adha', 'Hari Kemerdekaan', 'Tahun Baru'],
                socialRanking: 65,
                climate: 'Gurun',
                averageTemperature: 25,
                averageRainfall: 100,
                forestArea: 1,
                protectedAreas: 8,
                biodiversityRank: 50,
                carbonEmissions: 3.0,
                environmentalIndex: 45,
                riskScore: 40,
                politicalStability: 65,
                crimeIndex: 30,
                militarySpending: 3.5,
                peaceIndex: 45,
                terrorismIndex: 25,
                refugeePopulation: 700000,
                opportunityScore: 65,
                easeOfDoingBusiness: 62,
                innovationIndex: 40,
                startupEcosystem: 50,
                investmentScore: 58,
                talentPool: 65,
                marketSize: 60,
                infrastructureQuality: 65,
                internetSpeed: 25,
                digitalAdoption: 65,
                techEcosystem: 50,
                aiReadiness: 40,
                startups: 150,
                phoneCode: '+962',
                tld: '.jo',
                isoCode: 'JOR',
                isoCode2: 'JO',
                drivingSide: 'right',
                tags: ['negara', 'asian-barat', 'petra', 'pariwisata', 'sejarah']
            }
        },
        // ==========================================================
        // 🇱🇧 LEBANON
        // ==========================================================
        {
            text: 'Lebanon - Negara di Asia Barat dengan budaya Mediterania dan sejarah kuno. Ibu kota: Beirut. Populasi: 5.5 juta jiwa. Mata uang: Pound Lebanon (LBP). Bahasa: Arab, Prancis. Sistem pemerintahan: Republik Parlementer. Paris-nya Timur Tengah. Keragaman agama dan budaya. Industri perbankan dan pariwisata maju. Rumah bagi reruntuhan Romawi di Baalbek dan pantai Mediterania.',
            metadata: {
                category: 'country',
                region: 'asian-barat',
                name: 'Lebanon',
                officialName: 'Republik Lebanon',
                shortName: 'LBN',
                capital: 'Beirut',
                capitalCoordinates: { lat: 33.8938, lng: 35.5018 },
                largestCity: 'Beirut',
                demonym: 'Lebanon',
                subregion: 'Western Asia',
                area: 10400,
                areaRank: 161,
                coastline: 225,
                highestPoint: 'Qurnat as-Sawda',
                highestElevation: 3088,
                lowestPoint: 'Laut Mediterania',
                lowestElevation: 0,
                landBorders: ['Suriah', 'Israel'],
                coordinates: { lat: 33.8333, lng: 35.8333 },
                timezone: ['Waktu Timur Eropa'],
                utcOffset: ['+2'],
                population: 5500000,
                populationRank: 109,
                populationDensity: 528,
                populationGrowth: 0.5,
                medianAge: 32.0,
                lifeExpectancy: 78.0,
                fertilityRate: 1.7,
                urbanization: 88,
                ethnicGroups: [
                    { name: 'Arab', percentage: 95.0 },
                    { name: 'Armenia', percentage: 4.0 },
                    { name: 'Lainnya', percentage: 1.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 54.0 },
                    { name: 'Kristen', percentage: 40.0 },
                    { name: 'Druze', percentage: 6.0 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Prancis', percentage: 40, official: true },
                    { name: 'Inggris', percentage: 30 }
                ],
                literacyRate: 93,
                governmentType: 'Republik Parlementer',
                independenceDay: '1943-11-22',
                nationalHoliday: '22 November',
                legalSystem: 'Civil Law',
                constitution: '1926',
                administrativeDivisions: 8,
                memberships: ['PBB', 'Liga Arab', 'OKI'],
                giniCoefficient: 31.8,
                hdi: 0.744,
                hdiRank: 92,
                corruptionIndex: 28,
                currency: 'Pound Lebanon',
                currencyCode: 'LBP',
                gdp: 20000000000,
                gdpPerCapita: 3630,
                gdpPpp: 80000000000,
                gdpGrowth: -5.0,
                inflation: 200.0,
                unemployment: 30.0,
                povertyRate: 45.0,
                mainIndustries: ['Keuangan', 'Pariwisata', 'Tekstil', 'Pertanian', 'Perbankan'],
                exports: [
                    { item: 'Keuangan', value: 5000000000 },
                    { item: 'Tekstil', value: 3000000000 },
                    { item: 'Pariwisata', value: 2000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 5000000000 },
                    { item: 'Elektronik', value: 3000000000 },
                    { item: 'Minyak', value: 2000000000 }
                ],
                tradeBalance: -5000000000,
                naturalResources: ['Batu kapur', 'Kayu', 'Air'],
                economicRanking: 90,
                internetPenetration: 80,
                mobilePenetration: 88,
                electricityAccess: 95,
                roadLength: 7000,
                railwayLength: 0,
                airports: 5,
                seaports: 3,
                healthcareAccess: 70,
                educationIndex: 0.62,
                nationalMotto: 'Allah, Bangsa, Presiden',
                nationalAnthem: 'Kulluna lil Watan',
                nationalAnimal: 'Cedar',
                nationalFlower: 'Bunga Cedar',
                nationalCuisine: ['Hummus', 'Falafel', 'Kebab', 'Tabbouleh', 'Baklava'],
                culturalHeritage: ['Beirut', 'Baalbek', 'Byblos', 'Tyre'],
                publicHolidays: ['Idul Fitri', 'Idul Adha', 'Hari Kemerdekaan', 'Christmas'],
                socialRanking: 55,
                climate: 'Mediterania',
                averageTemperature: 20,
                averageRainfall: 800,
                forestArea: 13,
                protectedAreas: 5,
                biodiversityRank: 35,
                carbonEmissions: 4.0,
                environmentalIndex: 42,
                riskScore: 70,
                politicalStability: 25,
                crimeIndex: 40,
                militarySpending: 3.0,
                peaceIndex: 65,
                terrorismIndex: 50,
                refugeePopulation: 1500000,
                opportunityScore: 40,
                easeOfDoingBusiness: 35,
                innovationIndex: 35,
                startupEcosystem: 40,
                investmentScore: 30,
                talentPool: 60,
                marketSize: 55,
                infrastructureQuality: 40,
                internetSpeed: 15,
                digitalAdoption: 55,
                techEcosystem: 40,
                aiReadiness: 30,
                startups: 80,
                phoneCode: '+961',
                tld: '.lb',
                isoCode: 'LBN',
                isoCode2: 'LB',
                drivingSide: 'right',
                tags: ['negara', 'asian-barat', 'mediterania', 'budaya', 'pariwisata']
            }
        },
        // ==========================================================
        // 🇮🇱 ISRAEL
        // ==========================================================
        {
            text: 'Israel - Negara di Asia Barat dengan teknologi maju dan sejarah kuno. Ibu kota: Yerusalem. Populasi: 9.5 juta jiwa. Mata uang: Shekel Baru Israel (ILS). Bahasa: Ibrani, Arab. Sistem pemerintahan: Republik Parlementer. Startup Nation — pusat inovasi teknologi global. Kota suci tiga agama: Yudaisme, Kristen, Islam. Negara dengan 10% populasi dunia insinyur dan ilmuwan. Rumah bagi startup dan Unicorn.',
            metadata: {
                category: 'country',
                region: 'asian-barat',
                name: 'Israel',
                officialName: 'Negara Israel',
                shortName: 'ISR',
                capital: 'Yerusalem',
                capitalCoordinates: { lat: 31.7683, lng: 35.2137 },
                largestCity: 'Yerusalem',
                demonym: 'Israel',
                subregion: 'Western Asia',
                area: 22072,
                areaRank: 148,
                coastline: 273,
                highestPoint: 'Gunung Hermon',
                highestElevation: 2814,
                lowestPoint: 'Laut Mati',
                lowestElevation: -408,
                landBorders: ['Lebanon', 'Suriah', 'Yordania', 'Mesir', 'Palestina'],
                coordinates: { lat: 31.5, lng: 34.75 },
                timezone: ['Waktu Israel'],
                utcOffset: ['+2'],
                population: 9500000,
                populationRank: 93,
                populationDensity: 430,
                populationGrowth: 1.5,
                medianAge: 31.0,
                lifeExpectancy: 83.0,
                fertilityRate: 2.8,
                urbanization: 92,
                ethnicGroups: [
                    { name: 'Yahudi', percentage: 74.0 },
                    { name: 'Arab', percentage: 21.0 },
                    { name: 'Lainnya', percentage: 5.0 }
                ],
                religions: [
                    { name: 'Yahudi', percentage: 74.0 },
                    { name: 'Islam', percentage: 18.0 },
                    { name: 'Kristen', percentage: 2.0 }
                ],
                languages: [
                    { name: 'Ibrani', percentage: 100, official: true },
                    { name: 'Arab', percentage: 20, official: true },
                    { name: 'Inggris', percentage: 60 }
                ],
                literacyRate: 97,
                governmentType: 'Republik Parlementer',
                independenceDay: '1948-05-14',
                nationalHoliday: '5 Iyar',
                legalSystem: 'Mixed Law',
                constitution: 'Basic Law',
                administrativeDivisions: 6,
                memberships: ['PBB', 'OECD', 'WTO'],
                giniCoefficient: 38.6,
                hdi: 0.919,
                hdiRank: 19,
                corruptionIndex: 61,
                currency: 'Shekel Baru Israel',
                currencyCode: 'ILS',
                gdp: 522000000000,
                gdpPerCapita: 54900,
                gdpPpp: 480000000000,
                gdpGrowth: 4.0,
                inflation: 2.0,
                unemployment: 4.0,
                povertyRate: 18.0,
                mainIndustries: ['Teknologi', 'Keuangan', 'Pertanian', 'Pariwisata', 'Keamanan'],
                exports: [
                    { item: 'Elektronik', value: 50000000000 },
                    { item: 'Keamanan', value: 30000000000 },
                    { item: 'Teknologi', value: 20000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 40000000000 },
                    { item: 'Elektronik', value: 30000000000 },
                    { item: 'Minyak', value: 20000000000 }
                ],
                tradeBalance: 10000000000,
                naturalResources: ['Gas', 'Fosfat', 'Garam'],
                economicRanking: 30,
                internetPenetration: 92,
                mobilePenetration: 98,
                electricityAccess: 100,
                roadLength: 20000,
                railwayLength: 1000,
                airports: 15,
                seaports: 3,
                healthcareAccess: 95,
                educationIndex: 0.85,
                nationalMotto: 'Shema Israel',
                nationalAnthem: 'Hatikvah',
                nationalAnimal: 'Gazelle',
                nationalFlower: 'Anemone',
                nationalCuisine: ['Hummus', 'Falafel', 'Shakshuka', 'Sabich', 'Kebab'],
                culturalHeritage: ['Yerusalem', 'Tel Aviv', 'Haifa', 'Galilee'],
                publicHolidays: ['Rosh Hashanah', 'Yom Kippur', 'Paskah', 'Hari Kemerdekaan'],
                socialRanking: 85,
                climate: 'Mediterania',
                averageTemperature: 20,
                averageRainfall: 500,
                forestArea: 8,
                protectedAreas: 15,
                biodiversityRank: 30,
                carbonEmissions: 7.5,
                environmentalIndex: 55,
                riskScore: 50,
                politicalStability: 55,
                crimeIndex: 25,
                militarySpending: 5.0,
                peaceIndex: 55,
                terrorismIndex: 40,
                refugeePopulation: 1000,
                opportunityScore: 88,
                easeOfDoingBusiness: 82,
                innovationIndex: 90,
                startupEcosystem: 95,
                investmentScore: 85,
                talentPool: 92,
                marketSize: 78,
                infrastructureQuality: 85,
                internetSpeed: 45,
                digitalAdoption: 92,
                techEcosystem: 95,
                aiReadiness: 90,
                startups: 6000,
                phoneCode: '+972',
                tld: '.il',
                isoCode: 'ISR',
                isoCode2: 'IL',
                drivingSide: 'right',
                tags: ['negara', 'asian-barat', 'teknologi', 'startup', 'kota-suci']
            }
        },
        // ==========================================================
        // 🇨🇾 SIPRUS
        // ==========================================================
        {
            text: 'Siprus - Negara kepulauan di Asia Barat dengan budaya Yunani dan Turki. Ibu kota: Nikosia. Populasi: 1.2 juta jiwa. Mata uang: Euro (EUR). Bahasa: Yunani, Turki. Sistem pemerintahan: Republik Presidensial. Anggota UE dan PBB. Satu-satunya negara yang terbagi antara Yunani dan Turki. Destinasi wisata dengan pantai indah dan sejarah kuno.',
            metadata: {
                category: 'country',
                region: 'asian-barat',
                name: 'Siprus',
                officialName: 'Republik Siprus',
                shortName: 'CYP',
                capital: 'Nikosia',
                capitalCoordinates: { lat: 35.1856, lng: 33.3823 },
                largestCity: 'Nikosia',
                demonym: 'Siprus',
                subregion: 'Western Asia',
                area: 9251,
                areaRank: 162,
                coastline: 648,
                highestPoint: 'Gunung Olympus',
                highestElevation: 1952,
                lowestPoint: 'Laut Mediterania',
                lowestElevation: 0,
                landBorders: [],
                coordinates: { lat: 35.0, lng: 33.0 },
                timezone: ['Waktu Eropa Timur'],
                utcOffset: ['+2'],
                population: 1200000,
                populationRank: 155,
                populationDensity: 129,
                populationGrowth: 0.5,
                medianAge: 37.0,
                lifeExpectancy: 81.0,
                fertilityRate: 1.3,
                urbanization: 70,
                ethnicGroups: [
                    { name: 'Yunani', percentage: 75.0 },
                    { name: 'Turki', percentage: 20.0 },
                    { name: 'Lainnya', percentage: 5.0 }
                ],
                religions: [
                    { name: 'Kristen', percentage: 75.0 },
                    { name: 'Islam', percentage: 20.0 },
                    { name: 'Lainnya', percentage: 5.0 }
                ],
                languages: [
                    { name: 'Yunani', percentage: 100, official: true },
                    { name: 'Turki', percentage: 20, official: true },
                    { name: 'Inggris', percentage: 30 }
                ],
                literacyRate: 98,
                governmentType: 'Republik Presidensial',
                independenceDay: '1960-08-16',
                nationalHoliday: '1 Oktober',
                legalSystem: 'Common Law',
                constitution: '1960',
                administrativeDivisions: 6,
                memberships: ['PBB', 'UE', 'Commonwealth'],
                giniCoefficient: 31.0,
                hdi: 0.873,
                hdiRank: 32,
                corruptionIndex: 59,
                currency: 'Euro',
                currencyCode: 'EUR',
                gdp: 30000000000,
                gdpPerCapita: 25000,
                gdpPpp: 50000000000,
                gdpGrowth: 3.5,
                inflation: 2.0,
                unemployment: 6.0,
                povertyRate: 10.0,
                mainIndustries: ['Pariwisata', 'Keuangan', 'Perdagangan', 'Pertanian'],
                exports: [
                    { item: 'Keuangan', value: 10000000000 },
                    { item: 'Pariwisata', value: 5000000000 },
                    { item: 'Pertanian', value: 3000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 8000000000 },
                    { item: 'Elektronik', value: 5000000000 },
                    { item: 'Minyak', value: 3000000000 }
                ],
                tradeBalance: 4000000000,
                naturalResources: ['Tembaga', 'Garam', 'Air'],
                economicRanking: 65,
                internetPenetration: 88,
                mobilePenetration: 95,
                electricityAccess: 100,
                roadLength: 12000,
                railwayLength: 0,
                airports: 5,
                seaports: 3,
                healthcareAccess: 88,
                educationIndex: 0.78,
                nationalMotto: 'Kebebasan atau Mati',
                nationalAnthem: 'Imnos eis tin Eleftherian',
                nationalAnimal: 'Domba',
                nationalFlower: 'Bunga Siprus',
                nationalCuisine: ['Kleftiko', 'Halloumi', 'Meze', 'Souvlaki', 'Baklava'],
                culturalHeritage: ['Nikosia', 'Paphos', 'Larnaca', 'Kyrenia'],
                publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Hari Unifikasi'],
                socialRanking: 78,
                climate: 'Mediterania',
                averageTemperature: 22,
                averageRainfall: 500,
                forestArea: 20,
                protectedAreas: 10,
                biodiversityRank: 40,
                carbonEmissions: 6.0,
                environmentalIndex: 52,
                riskScore: 30,
                politicalStability: 60,
                crimeIndex: 20,
                militarySpending: 1.5,
                peaceIndex: 35,
                terrorismIndex: 15,
                refugeePopulation: 0,
                opportunityScore: 68,
                easeOfDoingBusiness: 65,
                innovationIndex: 45,
                startupEcosystem: 50,
                investmentScore: 60,
                talentPool: 60,
                marketSize: 55,
                infrastructureQuality: 78,
                internetSpeed: 35,
                digitalAdoption: 72,
                techEcosystem: 50,
                aiReadiness: 40,
                startups: 150,
                phoneCode: '+357',
                tld: '.cy',
                isoCode: 'CYP',
                isoCode2: 'CY',
                drivingSide: 'left',
                tags: ['negara', 'asian-barat', 'pulau', 'ue', 'mediterania']
            }
        },
        // ==========================================================
        // 🇵🇸 PALESTINA
        // ==========================================================
        {
            text: 'Palestina - Negara di Asia Barat dengan sejarah dan budaya kuno. Ibu kota: Ramallah (de facto). Populasi: 5.5 juta jiwa. Mata uang: Shekel Baru Israel (ILS). Bahasa: Arab. Sistem pemerintahan: Republik Semi-Presidensial. Anggota PBB (observer). Rumah kota suci Yerusalem, Bethlehem, dan Hebron. Kaya akan sejarah dan warisan budaya. Destinasi ziarah dan wisata religi.',
            metadata: {
                category: 'country',
                region: 'asian-barat',
                name: 'Palestina',
                officialName: 'Negara Palestina',
                shortName: 'PSE',
                capital: 'Ramallah',
                capitalCoordinates: { lat: 31.9000, lng: 35.2000 },
                largestCity: 'Ramallah',
                demonym: 'Palestina',
                subregion: 'Western Asia',
                area: 6020,
                areaRank: 163,
                coastline: 0,
                highestPoint: 'Gunung Nabi Yunis',
                highestElevation: 1000,
                lowestPoint: 'Laut Mati',
                lowestElevation: -408,
                landBorders: ['Israel', 'Yordania'],
                coordinates: { lat: 32.0, lng: 35.25 },
                timezone: ['Waktu Timur Eropa'],
                utcOffset: ['+2'],
                population: 5500000,
                populationRank: 110,
                populationDensity: 913,
                populationGrowth: 2.5,
                medianAge: 20.0,
                lifeExpectancy: 74.0,
                fertilityRate: 3.5,
                urbanization: 76,
                ethnicGroups: [
                    { name: 'Arab', percentage: 95.0 },
                    { name: 'Lainnya', percentage: 5.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 85.0 },
                    { name: 'Kristen', percentage: 10.0 },
                    { name: 'Yahudi', percentage: 5.0 }
                ],
                languages: [
                    { name: 'Arab', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 20 },
                    { name: 'Ibrani', percentage: 10 }
                ],
                literacyRate: 96,
                governmentType: 'Republik Semi-Presidensial',
                independenceDay: '1988-11-15',
                nationalHoliday: '15 November',
                legalSystem: 'Civil Law, Syariah',
                constitution: '2003',
                administrativeDivisions: 16,
                memberships: ['PBB', 'Liga Arab', 'OKI'],
                giniCoefficient: 35.0,
                hdi: 0.708,
                hdiRank: 115,
                corruptionIndex: 28,
                currency: 'Shekel Baru Israel',
                currencyCode: 'ILS',
                gdp: 20000000000,
                gdpPerCapita: 3640,
                gdpPpp: 40000000000,
                gdpGrowth: 3.0,
                inflation: 3.5,
                unemployment: 25.0,
                povertyRate: 30.0,
                mainIndustries: ['Pertanian', 'Tekstil', 'Pariwisata', 'Keuangan'],
                exports: [
                    { item: 'Tekstil', value: 3000000000 },
                    { item: 'Pertanian', value: 1000000000 },
                    { item: 'Pariwisata', value: 500000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 5000000000 },
                    { item: 'Elektronik', value: 3000000000 },
                    { item: 'Makanan', value: 2000000000 }
                ],
                tradeBalance: -5000000000,
                naturalResources: ['Batu kapur', 'Air', 'Tanah pertanian'],
                economicRanking: 100,
                internetPenetration: 70,
                mobilePenetration: 85,
                electricityAccess: 95,
                roadLength: 5000,
                railwayLength: 0,
                airports: 2,
                seaports: 1,
                healthcareAccess: 70,
                educationIndex: 0.65,
                nationalMotto: 'Palestina Bebas',
                nationalAnthem: 'Fida\'i',
                nationalAnimal: 'Elang',
                nationalFlower: 'Bunga Gurun',
                nationalCuisine: ['Hummus', 'Falafel', 'Maqluba', 'Kunafa', 'Kebab'],
                culturalHeritage: ['Yerusalem', 'Bethlehem', 'Hebron', 'Jericho'],
                publicHolidays: ['Idul Fitri', 'Idul Adha', 'Hari Kemerdekaan', 'Christmas'],
                socialRanking: 50,
                climate: 'Mediterania',
                averageTemperature: 20,
                averageRainfall: 500,
                forestArea: 2,
                protectedAreas: 5,
                biodiversityRank: 45,
                carbonEmissions: 0.5,
                environmentalIndex: 40,
                riskScore: 70,
                politicalStability: 30,
                crimeIndex: 35,
                militarySpending: 0.5,
                peaceIndex: 70,
                terrorismIndex: 55,
                refugeePopulation: 5000000,
                opportunityScore: 40,
                easeOfDoingBusiness: 35,
                innovationIndex: 30,
                startupEcosystem: 35,
                investmentScore: 30,
                talentPool: 55,
                marketSize: 50,
                infrastructureQuality: 35,
                internetSpeed: 12,
                digitalAdoption: 50,
                techEcosystem: 35,
                aiReadiness: 25,
                startups: 50,
                phoneCode: '+970',
                tld: '.ps',
                isoCode: 'PSE',
                isoCode2: 'PS',
                drivingSide: 'right',
                tags: ['negara', 'asian-barat', 'sejarah', 'budaya', 'kota-suci']
            }
        }
    ];

    // ============================================================
    // PROSES DATA KE REGISTER
    // ============================================================
    for (let i = 0; i < data.length; i++) {
        window.__DATA_REGISTER.push(data[i]);
    }

    // ============================================================
    // LOGGER
    // ============================================================
    if (window.InternalLogger) {
        window.InternalLogger.info('CountryAsianBarat', '✅ Loaded ' + data.length + ' countries (SUPER LENGKAP - 16 NEGARA!)');
    }

})();