/* ============================================================
   📁 dataries/country/asian-selatan.js
   📌 DATA NEGARA ASIA SELATAN
   🔥 8 NEGARA — India, Pakistan, Bangladesh, Sri Lanka, Nepal, Bhutan, Maladewa, Afghanistan
   🔥 DATA SUPER LENGKAP — 100+ FIELD PER NEGARA!
   ============================================================ */

(function() {
    'use strict';
    
    if (window.__CountryAsianSelatanLoaded) return;
    window.__CountryAsianSelatanLoaded = true;
    
    window.__DATA_REGISTER = window.__DATA_REGISTER || [];
    
    const data = [
        // ==========================================================
        // 🇮🇳 INDIA
        // ==========================================================
        {
            text: 'India - Negara terbesar di Asia Selatan dan terpadat kedua di dunia dengan populasi 1.4 miliar jiwa. Ibu kota: New Delhi. Mata uang: Rupee India (INR). Bahasa: Hindi, Inggris. Sistem pemerintahan: Republik Parlementer Federal. Ekonomi terbesar kelima di dunia. Pemimpin global dalam IT, farmasi, dan startup. Rumah bagi Taj Mahal, Himalaya, dan peradaban kuno. Negara dengan 22 bahasa resmi dan budaya yang sangat beragam.',
            metadata: {
                category: 'country',
                region: 'asian-selatan',
                name: 'India',
                officialName: 'Republik India',
                shortName: 'IND',
                capital: 'New Delhi',
                capitalCoordinates: { lat: 28.6139, lng: 77.2090 },
                largestCity: 'Mumbai',
                demonym: 'India',
                subregion: 'Southern Asia',
                area: 3287263,
                areaRank: 7,
                coastline: 7516,
                highestPoint: 'Kangchenjunga',
                highestElevation: 8586,
                lowestPoint: 'Lautan Hindia',
                lowestElevation: 0,
                landBorders: ['Afghanistan', 'Bangladesh', 'Bhutan', 'China', 'Myanmar', 'Nepal', 'Pakistan', 'Sri Lanka'],
                coordinates: { lat: 20.0, lng: 77.0 },
                timezone: ['Waktu India'],
                utcOffset: ['+5.5'],
                population: 1400000000,
                populationRank: 1,
                populationDensity: 425,
                populationGrowth: 0.8,
                medianAge: 28.4,
                lifeExpectancy: 70.1,
                fertilityRate: 2.0,
                urbanization: 35,
                ethnicGroups: [
                    { name: 'Indo-Arya', percentage: 72.0 },
                    { name: 'Dravida', percentage: 25.0 },
                    { name: 'Lainnya', percentage: 3.0 }
                ],
                religions: [
                    { name: 'Hindu', percentage: 79.8 },
                    { name: 'Islam', percentage: 14.2 },
                    { name: 'Kristen', percentage: 2.3 },
                    { name: 'Sikh', percentage: 1.7 }
                ],
                languages: [
                    { name: 'Hindi', percentage: 44, official: true },
                    { name: 'Inggris', percentage: 10, official: true },
                    { name: 'Bengali', percentage: 8 },
                    { name: 'Telugu', percentage: 7 }
                ],
                literacyRate: 74,
                governmentType: 'Republik Parlementer Federal',
                independenceDay: '1947-08-15',
                nationalHoliday: '26 Januari',
                legalSystem: 'Common Law',
                constitution: '1950',
                administrativeDivisions: 28,
                memberships: ['PBB', 'G20', 'BRICS', 'SAARC', 'Commonwealth'],
                giniCoefficient: 35.7,
                hdi: 0.645,
                hdiRank: 131,
                corruptionIndex: 40,
                currency: 'Rupee India',
                currencyCode: 'INR',
                gdp: 3700000000000,
                gdpPerCapita: 2640,
                gdpPpp: 14000000000000,
                gdpGrowth: 6.5,
                inflation: 4.5,
                unemployment: 6.0,
                povertyRate: 21.0,
                mainIndustries: ['IT', 'Farmasi', 'Tekstil', 'Otomotif', 'Pertanian'],
                exports: [
                    { item: 'IT', value: 250000000000 },
                    { item: 'Farmasi', value: 100000000000 },
                    { item: 'Tekstil', value: 80000000000 },
                    { item: 'Otomotif', value: 50000000000 }
                ],
                imports: [
                    { item: 'Minyak', value: 200000000000 },
                    { item: 'Elektronik', value: 150000000000 },
                    { item: 'Mesin', value: 100000000000 },
                    { item: 'Bahan kimia', value: 80000000000 }
                ],
                tradeBalance: -200000000000,
                naturalResources: ['Batu bara', 'Besi', 'Mangan', 'Gas', 'Emas'],
                economicRanking: 5,
                internetPenetration: 60,
                mobilePenetration: 85,
                electricityAccess: 95,
                roadLength: 6200000,
                railwayLength: 68000,
                airports: 400,
                seaports: 200,
                healthcareAccess: 60,
                educationIndex: 0.58,
                nationalMotto: 'Kebenaran saja yang menang',
                nationalAnthem: 'Jana Gana Mana',
                nationalAnimal: 'Harimau Bengal',
                nationalFlower: 'Bunga Lotus',
                nationalCuisine: ['Biryani', 'Tandoori', 'Dosa', 'Butter Chicken', 'Samosa'],
                culturalHeritage: ['Taj Mahal', 'Jaipur', 'Varanasi', 'Kerala'],
                publicHolidays: ['Hari Kemerdekaan', 'Hari Republik', 'Diwali', 'Holi'],
                socialRanking: 55,
                climate: 'Beragam',
                averageTemperature: 25,
                averageRainfall: 1200,
                forestArea: 23,
                protectedAreas: 5,
                biodiversityRank: 4,
                carbonEmissions: 1.8,
                environmentalIndex: 40,
                riskScore: 45,
                politicalStability: 55,
                crimeIndex: 45,
                militarySpending: 2.5,
                peaceIndex: 55,
                terrorismIndex: 45,
                refugeePopulation: 200000,
                opportunityScore: 75,
                easeOfDoingBusiness: 63,
                innovationIndex: 60,
                startupEcosystem: 80,
                investmentScore: 70,
                talentPool: 90,
                marketSize: 100,
                infrastructureQuality: 55,
                internetSpeed: 25,
                digitalAdoption: 65,
                techEcosystem: 80,
                aiReadiness: 65,
                startups: 30000,
                phoneCode: '+91',
                tld: '.in',
                isoCode: 'IND',
                isoCode2: 'IN',
                drivingSide: 'left',
                tags: ['negara', 'asian-selatan', 'it', 'startup', 'populasi']
            }
        },
        // ==========================================================
        // 🇵🇰 PAKISTAN
        // ==========================================================
        {
            text: 'Pakistan - Negara di Asia Selatan dengan populasi 240 juta jiwa. Ibu kota: Islamabad. Mata uang: Rupee Pakistan (PKR). Bahasa: Urdu, Inggris. Sistem pemerintahan: Republik Parlementer Federal. Ekonomi berkembang dengan sektor pertanian kuat. Rumah peradaban Lembah Indus. Pelabuhan strategis Gwadar. Negara dengan pegunungan Karakoram dan K2 (gunung tertinggi kedua dunia).',
            metadata: {
                category: 'country',
                region: 'asian-selatan',
                name: 'Pakistan',
                officialName: 'Republik Islam Pakistan',
                shortName: 'PAK',
                capital: 'Islamabad',
                capitalCoordinates: { lat: 33.6844, lng: 73.0479 },
                largestCity: 'Karachi',
                demonym: 'Pakistan',
                subregion: 'Southern Asia',
                area: 796095,
                areaRank: 33,
                coastline: 1046,
                highestPoint: 'K2',
                highestElevation: 8611,
                lowestPoint: 'Laut Arab',
                lowestElevation: 0,
                landBorders: ['India', 'Afghanistan', 'Iran', 'China'],
                coordinates: { lat: 30.0, lng: 70.0 },
                timezone: ['Waktu Pakistan'],
                utcOffset: ['+5'],
                population: 240000000,
                populationRank: 5,
                populationDensity: 301,
                populationGrowth: 1.8,
                medianAge: 22.0,
                lifeExpectancy: 67.0,
                fertilityRate: 3.5,
                urbanization: 37,
                ethnicGroups: [
                    { name: 'Punjabi', percentage: 44.7 },
                    { name: 'Pashtun', percentage: 15.4 },
                    { name: 'Sindhi', percentage: 14.1 },
                    { name: 'Baloch', percentage: 3.6 }
                ],
                religions: [
                    { name: 'Islam', percentage: 96.0 },
                    { name: 'Kristen', percentage: 2.0 },
                    { name: 'Hindu', percentage: 1.5 }
                ],
                languages: [
                    { name: 'Urdu', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 20, official: true },
                    { name: 'Punjabi', percentage: 40 }
                ],
                literacyRate: 60,
                governmentType: 'Republik Parlementer Federal',
                independenceDay: '1947-08-14',
                nationalHoliday: '23 Maret',
                legalSystem: 'Common Law, Syariah',
                constitution: '1973',
                administrativeDivisions: 4,
                memberships: ['PBB', 'SAARC', 'OKI', 'SCO'],
                giniCoefficient: 29.6,
                hdi: 0.560,
                hdiRank: 154,
                corruptionIndex: 31,
                currency: 'Rupee Pakistan',
                currencyCode: 'PKR',
                gdp: 400000000000,
                gdpPerCapita: 1660,
                gdpPpp: 1500000000000,
                gdpGrowth: 4.0,
                inflation: 8.0,
                unemployment: 6.0,
                povertyRate: 25.0,
                mainIndustries: ['Pertanian', 'Tekstil', 'Manufaktur', 'Tambang'],
                exports: [
                    { item: 'Tekstil', value: 25000000000 },
                    { item: 'Beras', value: 5000000000 },
                    { item: 'Kayu', value: 3000000000 },
                    { item: 'Kulit', value: 2000000000 }
                ],
                imports: [
                    { item: 'Minyak', value: 20000000000 },
                    { item: 'Elektronik', value: 15000000000 },
                    { item: 'Mesin', value: 10000000000 },
                    { item: 'Bahan kimia', value: 8000000000 }
                ],
                tradeBalance: -30000000000,
                naturalResources: ['Gas', 'Batu bara', 'Emas', 'Tembaga', 'Kapur'],
                economicRanking: 45,
                internetPenetration: 45,
                mobilePenetration: 70,
                electricityAccess: 85,
                roadLength: 260000,
                railwayLength: 12000,
                airports: 50,
                seaports: 10,
                healthcareAccess: 55,
                educationIndex: 0.48,
                nationalMotto: 'Iman, Persatuan, Disiplin',
                nationalAnthem: 'Qaumi Taranah',
                nationalAnimal: 'Markhor',
                nationalFlower: 'Jasmine',
                nationalCuisine: ['Biryani', 'Kebab', 'Naan', 'Curry', 'Lassi'],
                culturalHeritage: ['Lahore', 'Karachi', 'Mohenjo-Daro', 'Islamabad'],
                publicHolidays: ['Hari Kemerdekaan', 'Hari Pakistan', 'Idul Fitri', 'Idul Adha'],
                socialRanking: 40,
                climate: 'Beragam',
                averageTemperature: 25,
                averageRainfall: 500,
                forestArea: 5,
                protectedAreas: 10,
                biodiversityRank: 25,
                carbonEmissions: 1.0,
                environmentalIndex: 35,
                riskScore: 60,
                politicalStability: 40,
                crimeIndex: 55,
                militarySpending: 4.0,
                peaceIndex: 65,
                terrorismIndex: 60,
                refugeePopulation: 1400000,
                opportunityScore: 50,
                easeOfDoingBusiness: 50,
                innovationIndex: 35,
                startupEcosystem: 45,
                investmentScore: 45,
                talentPool: 70,
                marketSize: 85,
                infrastructureQuality: 40,
                internetSpeed: 15,
                digitalAdoption: 45,
                techEcosystem: 40,
                aiReadiness: 30,
                startups: 500,
                phoneCode: '+92',
                tld: '.pk',
                isoCode: 'PAK',
                isoCode2: 'PK',
                drivingSide: 'left',
                tags: ['negara', 'asian-selatan', 'pertanian', 'peradaban-kuno']
            }
        },
        // ==========================================================
        // 🇧🇩 BANGLADESH
        // ==========================================================
        {
            text: 'Bangladesh - Negara di Asia Selatan dengan populasi 170 juta jiwa. Ibu kota: Dhaka. Mata uang: Taka (BDT). Bahasa: Bengali. Sistem pemerintahan: Republik Parlementer. Ekonomi berkembang pesat, industri garmen terbesar kedua dunia. Terletak di delta sungai Ganges dan Brahmaputra. Negara dengan kepadatan penduduk tertinggi di dunia. Sektor ekonomi mikro dan fintech yang maju.',
            metadata: {
                category: 'country',
                region: 'asian-selatan',
                name: 'Bangladesh',
                officialName: 'Republik Rakyat Bangladesh',
                shortName: 'BGD',
                capital: 'Dhaka',
                capitalCoordinates: { lat: 23.8103, lng: 90.4125 },
                largestCity: 'Dhaka',
                demonym: 'Bangladesh',
                subregion: 'Southern Asia',
                area: 147570,
                areaRank: 94,
                coastline: 580,
                highestPoint: 'Keokradong',
                highestElevation: 1230,
                lowestPoint: 'Teluk Benggala',
                lowestElevation: 0,
                landBorders: ['India', 'Myanmar'],
                coordinates: { lat: 24.0, lng: 90.0 },
                timezone: ['Waktu Bangladesh'],
                utcOffset: ['+6'],
                population: 170000000,
                populationRank: 8,
                populationDensity: 1152,
                populationGrowth: 1.0,
                medianAge: 27.0,
                lifeExpectancy: 72.0,
                fertilityRate: 2.0,
                urbanization: 38,
                ethnicGroups: [
                    { name: 'Bengali', percentage: 98.0 },
                    { name: 'Lainnya', percentage: 2.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 90.4 },
                    { name: 'Hindu', percentage: 8.5 },
                    { name: 'Kristen', percentage: 0.5 }
                ],
                languages: [
                    { name: 'Bengali', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 15 }
                ],
                literacyRate: 74,
                governmentType: 'Republik Parlementer',
                independenceDay: '1971-03-26',
                nationalHoliday: '26 Maret',
                legalSystem: 'Common Law',
                constitution: '1972',
                administrativeDivisions: 8,
                memberships: ['PBB', 'SAARC', 'Commonwealth'],
                giniCoefficient: 32.4,
                hdi: 0.632,
                hdiRank: 133,
                corruptionIndex: 26,
                currency: 'Taka',
                currencyCode: 'BDT',
                gdp: 460000000000,
                gdpPerCapita: 2700,
                gdpPpp: 1400000000000,
                gdpGrowth: 6.5,
                inflation: 5.0,
                unemployment: 4.5,
                povertyRate: 18.0,
                mainIndustries: ['Garmen', 'Tekstil', 'Pertanian', 'IT', 'Keuangan'],
                exports: [
                    { item: 'Garmen', value: 40000000000 },
                    { item: 'Tekstil', value: 15000000000 },
                    { item: 'Kulit', value: 5000000000 },
                    { item: 'Pertanian', value: 3000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 20000000000 },
                    { item: 'Elektronik', value: 15000000000 },
                    { item: 'Minyak', value: 10000000000 },
                    { item: 'Bahan kimia', value: 8000000000 }
                ],
                tradeBalance: 5000000000,
                naturalResources: ['Gas', 'Batu bara', 'Kayu', 'Air'],
                economicRanking: 35,
                internetPenetration: 55,
                mobilePenetration: 80,
                electricityAccess: 90,
                roadLength: 210000,
                railwayLength: 3000,
                airports: 20,
                seaports: 5,
                healthcareAccess: 60,
                educationIndex: 0.55,
                nationalMotto: 'Bersatu, Berdoa, Berjuang',
                nationalAnthem: 'Amar Sonar Bangla',
                nationalAnimal: 'Harimau Bengal',
                nationalFlower: 'Bunga Teratai',
                nationalCuisine: ['Biryani', 'Hilsa', 'Pitha', 'Curry', 'Misti'],
                culturalHeritage: ['Dhaka', 'Sundarbans', 'Paharpur', 'Sylhet'],
                publicHolidays: ['Hari Kemerdekaan', 'Hari Bahasa', 'Idul Fitri', 'Idul Adha'],
                socialRanking: 50,
                climate: 'Tropis',
                averageTemperature: 28,
                averageRainfall: 2000,
                forestArea: 11,
                protectedAreas: 5,
                biodiversityRank: 15,
                carbonEmissions: 0.5,
                environmentalIndex: 38,
                riskScore: 50,
                politicalStability: 50,
                crimeIndex: 40,
                militarySpending: 1.2,
                peaceIndex: 50,
                terrorismIndex: 35,
                refugeePopulation: 900000,
                opportunityScore: 60,
                easeOfDoingBusiness: 55,
                innovationIndex: 40,
                startupEcosystem: 50,
                investmentScore: 55,
                talentPool: 75,
                marketSize: 80,
                infrastructureQuality: 45,
                internetSpeed: 18,
                digitalAdoption: 55,
                techEcosystem: 50,
                aiReadiness: 35,
                startups: 400,
                phoneCode: '+880',
                tld: '.bd',
                isoCode: 'BGD',
                isoCode2: 'BD',
                drivingSide: 'left',
                tags: ['negara', 'asian-selatan', 'garmen', 'delta', 'ekonomi-berkembang']
            }
        },
        // ==========================================================
        // 🇱🇰 SRI LANKA
        // ==========================================================
        {
            text: 'Sri Lanka - Negara kepulauan di Asia Selatan dengan keindahan alam dan budaya kaya. Ibu kota: Sri Jayawardenepura Kotte. Populasi: 22 juta jiwa. Mata uang: Rupee Sri Lanka (LKR). Bahasa: Sinhala, Tamil, Inggris. Sistem pemerintahan: Republik Presidensial. Terkenal dengan teh Ceylon, rempah-rempah, dan pariwisata. Rumah bagi anjing laut dan paus biru. Destinasi wisata alam dan budaya terkemuka di Asia Selatan.',
            metadata: {
                category: 'country',
                region: 'asian-selatan',
                name: 'Sri Lanka',
                officialName: 'Republik Sosialis Demokratik Sri Lanka',
                shortName: 'LKA',
                capital: 'Sri Jayawardenepura Kotte',
                capitalCoordinates: { lat: 6.9271, lng: 79.8612 },
                largestCity: 'Colombo',
                demonym: 'Sri Lanka',
                subregion: 'Southern Asia',
                area: 65610,
                areaRank: 120,
                coastline: 1340,
                highestPoint: 'Pidurutalagala',
                highestElevation: 2524,
                lowestPoint: 'Samudra Hindia',
                lowestElevation: 0,
                landBorders: ['India'],
                coordinates: { lat: 7.0, lng: 81.0 },
                timezone: ['Waktu Sri Lanka'],
                utcOffset: ['+5.5'],
                population: 22000000,
                populationRank: 57,
                populationDensity: 335,
                populationGrowth: 0.5,
                medianAge: 34.0,
                lifeExpectancy: 76.0,
                fertilityRate: 1.9,
                urbanization: 18,
                ethnicGroups: [
                    { name: 'Sinhala', percentage: 74.9 },
                    { name: 'Tamil', percentage: 11.2 },
                    { name: 'Moor', percentage: 9.2 },
                    { name: 'Lainnya', percentage: 4.7 }
                ],
                religions: [
                    { name: 'Buddha', percentage: 70.2 },
                    { name: 'Hindu', percentage: 12.6 },
                    { name: 'Islam', percentage: 9.7 },
                    { name: 'Kristen', percentage: 7.4 }
                ],
                languages: [
                    { name: 'Sinhala', percentage: 100, official: true },
                    { name: 'Tamil', percentage: 20, official: true },
                    { name: 'Inggris', percentage: 15 }
                ],
                literacyRate: 92,
                governmentType: 'Republik Presidensial',
                independenceDay: '1948-02-04',
                nationalHoliday: '4 Februari',
                legalSystem: 'Common Law',
                constitution: '1978',
                administrativeDivisions: 9,
                memberships: ['PBB', 'SAARC', 'Commonwealth'],
                giniCoefficient: 39.8,
                hdi: 0.782,
                hdiRank: 72,
                corruptionIndex: 38,
                currency: 'Rupee Sri Lanka',
                currencyCode: 'LKR',
                gdp: 85000000000,
                gdpPerCapita: 3860,
                gdpPpp: 350000000000,
                gdpGrowth: 3.0,
                inflation: 10.0,
                unemployment: 5.0,
                povertyRate: 15.0,
                mainIndustries: ['Pariwisata', 'Teh', 'Tekstil', 'Pertanian', 'Keuangan'],
                exports: [
                    { item: 'Teh', value: 15000000000 },
                    { item: 'Tekstil', value: 10000000000 },
                    { item: 'Pariwisata', value: 8000000000 },
                    { item: 'Karet', value: 5000000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 10000000000 },
                    { item: 'Elektronik', value: 8000000000 },
                    { item: 'Minyak', value: 5000000000 },
                    { item: 'Makanan', value: 4000000000 }
                ],
                tradeBalance: -8000000000,
                naturalResources: ['Teh', 'Karet', 'Kayu', 'Permata'],
                economicRanking: 80,
                internetPenetration: 60,
                mobilePenetration: 80,
                electricityAccess: 100,
                roadLength: 12000,
                railwayLength: 1500,
                airports: 10,
                seaports: 5,
                healthcareAccess: 75,
                educationIndex: 0.70,
                nationalMotto: 'Tanah air, Kemakmuran, Kebebasan',
                nationalAnthem: 'Sri Lanka Matha',
                nationalAnimal: 'Gajah',
                nationalFlower: 'Bunga Teratai',
                nationalCuisine: ['Rice and Curry', 'Kottu', 'Hoppers', 'String Hoppers'],
                culturalHeritage: ['Kandy', 'Galle', 'Anuradhapura', 'Polonnaruwa'],
                publicHolidays: ['Hari Kemerdekaan', 'Hari Poya', 'Sinhala Tamil New Year', 'Christmas'],
                socialRanking: 65,
                climate: 'Tropis',
                averageTemperature: 28,
                averageRainfall: 2000,
                forestArea: 28,
                protectedAreas: 15,
                biodiversityRank: 15,
                carbonEmissions: 1.0,
                environmentalIndex: 48,
                riskScore: 55,
                politicalStability: 45,
                crimeIndex: 30,
                militarySpending: 2.0,
                peaceIndex: 50,
                terrorismIndex: 40,
                refugeePopulation: 1000,
                opportunityScore: 55,
                easeOfDoingBusiness: 60,
                innovationIndex: 40,
                startupEcosystem: 45,
                investmentScore: 50,
                talentPool: 65,
                marketSize: 65,
                infrastructureQuality: 55,
                internetSpeed: 20,
                digitalAdoption: 55,
                techEcosystem: 45,
                aiReadiness: 35,
                startups: 100,
                phoneCode: '+94',
                tld: '.lk',
                isoCode: 'LKA',
                isoCode2: 'LK',
                drivingSide: 'left',
                tags: ['negara', 'asian-selatan', 'teh', 'pariwisata', 'rempah']
            }
        },
        // ==========================================================
        // 🇳🇵 NEPAL
        // ==========================================================
        {
            text: 'Nepal - Negara di Asia Selatan dengan Pegunungan Himalaya dan Gunung Everest. Ibu kota: Kathmandu. Populasi: 30 juta jiwa. Mata uang: Rupee Nepal (NPR). Bahasa: Nepal. Sistem pemerintahan: Republik Federal. Destinasi pendakian kelas dunia. Tempat lahir Buddha Gautama. Ekonomi berbasis pariwisata dan pertanian. Rumah bagi 8 dari 10 gunung tertinggi di dunia. Negara dengan keanekaragaman budaya dan alam yang luar biasa.',
            metadata: {
                category: 'country',
                region: 'asian-selatan',
                name: 'Nepal',
                officialName: 'Republik Federal Nepal',
                shortName: 'NPL',
                capital: 'Kathmandu',
                capitalCoordinates: { lat: 27.7172, lng: 85.3240 },
                largestCity: 'Kathmandu',
                demonym: 'Nepal',
                subregion: 'Southern Asia',
                area: 147181,
                areaRank: 93,
                coastline: 0,
                highestPoint: 'Gunung Everest',
                highestElevation: 8848,
                lowestPoint: 'Lembah Kathmandu',
                lowestElevation: 70,
                landBorders: ['China', 'India'],
                coordinates: { lat: 28.0, lng: 84.0 },
                timezone: ['Waktu Nepal'],
                utcOffset: ['+5.75'],
                population: 30000000,
                populationRank: 49,
                populationDensity: 204,
                populationGrowth: 1.1,
                medianAge: 25.0,
                lifeExpectancy: 70.0,
                fertilityRate: 2.0,
                urbanization: 21,
                ethnicGroups: [
                    { name: 'Chhetri', percentage: 16.6 },
                    { name: 'Brahmin', percentage: 12.2 },
                    { name: 'Magar', percentage: 7.1 },
                    { name: 'Tharu', percentage: 6.6 }
                ],
                religions: [
                    { name: 'Hindu', percentage: 81.3 },
                    { name: 'Buddha', percentage: 9.0 },
                    { name: 'Islam', percentage: 4.4 },
                    { name: 'Kristen', percentage: 1.4 }
                ],
                languages: [
                    { name: 'Nepal', percentage: 100, official: true },
                    { name: 'Maithili', percentage: 12 },
                    { name: 'Bhojpuri', percentage: 7 }
                ],
                literacyRate: 68,
                governmentType: 'Republik Federal Parlementer',
                independenceDay: '2008-05-28',
                nationalHoliday: '19 September',
                legalSystem: 'Civil Law',
                constitution: '2015',
                administrativeDivisions: 7,
                memberships: ['PBB', 'SAARC', 'Non-Aligned Movement'],
                giniCoefficient: 32.8,
                hdi: 0.602,
                hdiRank: 142,
                corruptionIndex: 33,
                currency: 'Rupee Nepal',
                currencyCode: 'NPR',
                gdp: 40000000000,
                gdpPerCapita: 1330,
                gdpPpp: 140000000000,
                gdpGrowth: 5.0,
                inflation: 4.0,
                unemployment: 3.0,
                povertyRate: 25.0,
                mainIndustries: ['Pariwisata', 'Pertanian', 'Tekstil', 'Kerajinan'],
                exports: [
                    { item: 'Pariwisata', value: 5000000000 },
                    { item: 'Tekstil', value: 2000000000 },
                    { item: 'Pertanian', value: 1000000000 },
                    { item: 'Kerajinan', value: 500000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 3000000000 },
                    { item: 'Elektronik', value: 2000000000 },
                    { item: 'Minyak', value: 1000000000 },
                    { item: 'Makanan', value: 1000000000 }
                ],
                tradeBalance: -4000000000,
                naturalResources: ['Air', 'Kayu', 'Mineral', 'Batu bara'],
                economicRanking: 100,
                internetPenetration: 40,
                mobilePenetration: 65,
                electricityAccess: 90,
                roadLength: 20000,
                railwayLength: 50,
                airports: 30,
                seaports: 0,
                healthcareAccess: 55,
                educationIndex: 0.50,
                nationalMotto: 'Ibu dan Tanah air lebih besar dari Surga',
                nationalAnthem: 'Sayaun Thunga Phulka',
                nationalAnimal: 'Sapi',
                nationalFlower: 'Rhododendron',
                nationalCuisine: ['Dal Bhat', 'Momo', 'Thukpa', 'Sel Roti', 'Gundruk'],
                culturalHeritage: ['Kathmandu', 'Lumbini', 'Pokhara', 'Chitwan'],
                publicHolidays: ['Hari Kemerdekaan', 'Hari Republik', 'Dasain', 'Tihar'],
                socialRanking: 45,
                climate: 'Beragam',
                averageTemperature: 15,
                averageRainfall: 1500,
                forestArea: 25,
                protectedAreas: 20,
                biodiversityRank: 15,
                carbonEmissions: 0.5,
                environmentalIndex: 50,
                riskScore: 55,
                politicalStability: 50,
                crimeIndex: 30,
                militarySpending: 1.5,
                peaceIndex: 50,
                terrorismIndex: 20,
                refugeePopulation: 1000,
                opportunityScore: 50,
                easeOfDoingBusiness: 50,
                innovationIndex: 35,
                startupEcosystem: 40,
                investmentScore: 45,
                talentPool: 55,
                marketSize: 60,
                infrastructureQuality: 35,
                internetSpeed: 12,
                digitalAdoption: 40,
                techEcosystem: 35,
                aiReadiness: 25,
                startups: 50,
                phoneCode: '+977',
                tld: '.np',
                isoCode: 'NPL',
                isoCode2: 'NP',
                drivingSide: 'left',
                tags: ['negara', 'asian-selatan', 'himalaya', 'everest', 'buddha']
            }
        },
        // ==========================================================
        // 🇧🇹 BHUTAN
        // ==========================================================
        {
            text: 'Bhutan - Negara di Asia Selatan dengan konsep Kebahagiaan Nasional Bruto. Ibu kota: Thimphu. Populasi: 800 ribu jiwa. Mata uang: Ngultrum (BTN). Bahasa: Dzongkha. Sistem pemerintahan: Monarki Konstitusional. Karbon negatif, arsitektur dzong, dan budaya Buddhis. Salah satu negara paling bahagia di dunia. Negara dengan kebijakan lingkungan terbaik di dunia. Destinasi ekowisata terkemuka di Asia.',
            metadata: {
                category: 'country',
                region: 'asian-selatan',
                name: 'Bhutan',
                officialName: 'Kerajaan Bhutan',
                shortName: 'BTN',
                capital: 'Thimphu',
                capitalCoordinates: { lat: 27.4712, lng: 89.6339 },
                largestCity: 'Thimphu',
                demonym: 'Bhutan',
                subregion: 'Southern Asia',
                area: 38394,
                areaRank: 133,
                coastline: 0,
                highestPoint: 'Gangkhar Puensum',
                highestElevation: 7570,
                lowestPoint: 'Lembah Drangme Chhu',
                lowestElevation: 100,
                landBorders: ['China', 'India'],
                coordinates: { lat: 27.5, lng: 90.5 },
                timezone: ['Waktu Bhutan'],
                utcOffset: ['+6'],
                population: 800000,
                populationRank: 165,
                populationDensity: 20,
                populationGrowth: 1.0,
                medianAge: 28.0,
                lifeExpectancy: 71.0,
                fertilityRate: 1.8,
                urbanization: 42,
                ethnicGroups: [
                    { name: 'Bhutanese', percentage: 100.0 }
                ],
                religions: [
                    { name: 'Buddha', percentage: 75.0 },
                    { name: 'Hindu', percentage: 22.0 },
                    { name: 'Kristen', percentage: 2.0 }
                ],
                languages: [
                    { name: 'Dzongkha', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 20 }
                ],
                literacyRate: 64,
                governmentType: 'Monarki Konstitusional',
                independenceDay: '1907-12-17',
                nationalHoliday: '17 Desember',
                legalSystem: 'Civil Law',
                constitution: '2008',
                administrativeDivisions: 20,
                memberships: ['PBB', 'SAARC', 'Non-Aligned Movement'],
                giniCoefficient: 38.0,
                hdi: 0.654,
                hdiRank: 126,
                corruptionIndex: 50,
                currency: 'Ngultrum',
                currencyCode: 'BTN',
                gdp: 5000000000,
                gdpPerCapita: 6250,
                gdpPpp: 10000000000,
                gdpGrowth: 4.0,
                inflation: 3.0,
                unemployment: 3.0,
                povertyRate: 10.0,
                mainIndustries: ['Pariwisata', 'Pertanian', 'Energi', 'Kerajinan'],
                exports: [
                    { item: 'Energi', value: 2000000000 },
                    { item: 'Pariwisata', value: 1000000000 },
                    { item: 'Pertanian', value: 500000000 },
                    { item: 'Kerajinan', value: 200000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 1000000000 },
                    { item: 'Elektronik', value: 800000000 },
                    { item: 'Makanan', value: 500000000 },
                    { item: 'Minyak', value: 300000000 }
                ],
                tradeBalance: -100000000,
                naturalResources: ['Air', 'Kayu', 'Energi', 'Mineral'],
                economicRanking: 130,
                internetPenetration: 50,
                mobilePenetration: 70,
                electricityAccess: 100,
                roadLength: 8000,
                railwayLength: 0,
                airports: 4,
                seaports: 0,
                healthcareAccess: 70,
                educationIndex: 0.55,
                nationalMotto: 'Kebahagiaan Nasional Bruto',
                nationalAnthem: 'Druk Tsendhen',
                nationalAnimal: 'Takir',
                nationalFlower: 'Blue Poppy',
                nationalCuisine: ['Ema Datshi', 'Momos', 'Phaksha Paa', 'Kewa Datshi'],
                culturalHeritage: ['Tigers Nest', 'Thimphu', 'Punakha', 'Paro'],
                publicHolidays: ['Hari Nasional', 'Tahun Baru Bhutan', 'Buddha Birthday', 'Dashain'],
                socialRanking: 70,
                climate: 'Beragam',
                averageTemperature: 15,
                averageRainfall: 1000,
                forestArea: 72,
                protectedAreas: 50,
                biodiversityRank: 10,
                carbonEmissions: 0.0,
                environmentalIndex: 70,
                riskScore: 30,
                politicalStability: 75,
                crimeIndex: 15,
                militarySpending: 1.0,
                peaceIndex: 25,
                terrorismIndex: 5,
                refugeePopulation: 0,
                opportunityScore: 55,
                easeOfDoingBusiness: 50,
                innovationIndex: 35,
                startupEcosystem: 30,
                investmentScore: 45,
                talentPool: 40,
                marketSize: 40,
                infrastructureQuality: 45,
                internetSpeed: 15,
                digitalAdoption: 45,
                techEcosystem: 30,
                aiReadiness: 25,
                startups: 20,
                phoneCode: '+975',
                tld: '.bt',
                isoCode: 'BTN',
                isoCode2: 'BT',
                drivingSide: 'left',
                tags: ['negara', 'asian-selatan', 'kebahagiaan', 'karbon-negatif', 'buddhis']
            }
        },
        // ==========================================================
        // 🇲🇻 MALADEWA
        // ==========================================================
        {
            text: 'Maladewa - Negara kepulauan di Asia Selatan dengan resor mewah dan pantai indah. Ibu kota: Male. Populasi: 500 ribu jiwa. Mata uang: Rufiyaa (MVR). Bahasa: Dhivehi. Sistem pemerintahan: Republik Presidensial. Destinasi wisata kelas dunia. Terancam kenaikan permukaan laut. Ekonomi berbasis pariwisata dan perikanan. Pulau-pulau dengan pantai pasir putih dan laut biru jernih. Surga tropis di Samudra Hindia.',
            metadata: {
                category: 'country',
                region: 'asian-selatan',
                name: 'Maladewa',
                officialName: 'Republik Maladewa',
                shortName: 'MDV',
                capital: 'Male',
                capitalCoordinates: { lat: 4.1755, lng: 73.5093 },
                largestCity: 'Male',
                demonym: 'Maladewa',
                subregion: 'Southern Asia',
                area: 298,
                areaRank: 178,
                coastline: 644,
                highestPoint: 'Villingili',
                highestElevation: 5,
                lowestPoint: 'Samudra Hindia',
                lowestElevation: 0,
                landBorders: ['India'],
                coordinates: { lat: 3.25, lng: 73.0 },
                timezone: ['Waktu Maladewa'],
                utcOffset: ['+5'],
                population: 500000,
                populationRank: 172,
                populationDensity: 1678,
                populationGrowth: 1.0,
                medianAge: 29.0,
                lifeExpectancy: 79.0,
                fertilityRate: 1.7,
                urbanization: 43,
                ethnicGroups: [
                    { name: 'Maladewa', percentage: 100.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 100.0 }
                ],
                languages: [
                    { name: 'Dhivehi', percentage: 100, official: true },
                    { name: 'Inggris', percentage: 20 }
                ],
                literacyRate: 98,
                governmentType: 'Republik Presidensial',
                independenceDay: '1968-07-26',
                nationalHoliday: '26 Juli',
                legalSystem: 'Hukum Syariah',
                constitution: '2008',
                administrativeDivisions: 20,
                memberships: ['PBB', 'SAARC', 'Commonwealth'],
                giniCoefficient: 31.0,
                hdi: 0.740,
                hdiRank: 95,
                corruptionIndex: 43,
                currency: 'Rufiyaa',
                currencyCode: 'MVR',
                gdp: 7000000000,
                gdpPerCapita: 14000,
                gdpPpp: 15000000000,
                gdpGrowth: 5.0,
                inflation: 2.0,
                unemployment: 5.0,
                povertyRate: 8.0,
                mainIndustries: ['Pariwisata', 'Perikanan', 'Keuangan', 'Logistik'],
                exports: [
                    { item: 'Pariwisata', value: 3000000000 },
                    { item: 'Perikanan', value: 500000000 },
                    { item: 'Tekstil', value: 200000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 1000000000 },
                    { item: 'Elektronik', value: 800000000 },
                    { item: 'Makanan', value: 600000000 },
                    { item: 'Minyak', value: 400000000 }
                ],
                tradeBalance: -1000000000,
                naturalResources: ['Perikanan', 'Pariwisata'],
                economicRanking: 120,
                internetPenetration: 80,
                mobilePenetration: 90,
                electricityAccess: 100,
                roadLength: 200,
                railwayLength: 0,
                airports: 10,
                seaports: 5,
                healthcareAccess: 85,
                educationIndex: 0.68,
                nationalMotto: 'Persatuan, Kemajuan, Kejayaan',
                nationalAnthem: 'Qaumee Salaam',
                nationalAnimal: 'Ikan Tuna',
                nationalFlower: 'Bunga Teratai',
                nationalCuisine: ['Fish Curry', 'Roshi', 'Hedhikaa', 'Gulha'],
                culturalHeritage: ['Male', 'Maldives', 'Addu City'],
                publicHolidays: ['Hari Kemerdekaan', 'Hari Republik', 'Idul Fitri', 'Idul Adha'],
                socialRanking: 60,
                climate: 'Tropis',
                averageTemperature: 28,
                averageRainfall: 2000,
                forestArea: 3,
                protectedAreas: 5,
                biodiversityRank: 30,
                carbonEmissions: 0.5,
                environmentalIndex: 45,
                riskScore: 60,
                politicalStability: 55,
                crimeIndex: 20,
                militarySpending: 1.5,
                peaceIndex: 40,
                terrorismIndex: 10,
                refugeePopulation: 0,
                opportunityScore: 60,
                easeOfDoingBusiness: 55,
                innovationIndex: 35,
                startupEcosystem: 40,
                investmentScore: 55,
                talentPool: 45,
                marketSize: 40,
                infrastructureQuality: 55,
                internetSpeed: 20,
                digitalAdoption: 60,
                techEcosystem: 40,
                aiReadiness: 30,
                startups: 30,
                phoneCode: '+960',
                tld: '.mv',
                isoCode: 'MDV',
                isoCode2: 'MV',
                drivingSide: 'right',
                tags: ['negara', 'asian-selatan', 'pariwisata', 'resor', 'perubahan-iklim']
            }
        },
        // ==========================================================
        // 🇦🇫 AFGHANISTAN
        // ==========================================================
        {
            text: 'Afghanistan - Negara di Asia Selatan dengan sejarah Jalur Sutra dan peradaban kuno. Ibu kota: Kabul. Populasi: 38 juta jiwa. Mata uang: Afghani (AFN). Bahasa: Pashto, Dari. Sistem pemerintahan: Republik Islam. Rumah peradaban Baktria dan Gandhara. Kaya akan sumber daya alam seperti litium, tembaga, dan batu bara. Negara dengan sejarah panjang dan budaya yang kaya. Jalan Sutra kuno dan peradaban yang sangat tua.',
            metadata: {
                category: 'country',
                region: 'asian-selatan',
                name: 'Afghanistan',
                officialName: 'Republik Islam Afghanistan',
                shortName: 'AFG',
                capital: 'Kabul',
                capitalCoordinates: { lat: 34.5553, lng: 69.2075 },
                largestCity: 'Kabul',
                demonym: 'Afghanistan',
                subregion: 'Southern Asia',
                area: 652230,
                areaRank: 40,
                coastline: 0,
                highestPoint: 'Noshaq',
                highestElevation: 7492,
                lowestPoint: 'Amu Darya',
                lowestElevation: 258,
                landBorders: ['Pakistan', 'Iran', 'Turkmenistan', 'Uzbekistan', 'Tajikistan', 'China'],
                coordinates: { lat: 33.0, lng: 65.0 },
                timezone: ['Waktu Afghanistan'],
                utcOffset: ['+4.5'],
                population: 38000000,
                populationRank: 37,
                populationDensity: 58,
                populationGrowth: 2.0,
                medianAge: 18.0,
                lifeExpectancy: 64.0,
                fertilityRate: 4.0,
                urbanization: 25,
                ethnicGroups: [
                    { name: 'Pashtun', percentage: 42.0 },
                    { name: 'Tajik', percentage: 27.0 },
                    { name: 'Hazara', percentage: 9.0 },
                    { name: 'Uzbek', percentage: 9.0 }
                ],
                religions: [
                    { name: 'Islam', percentage: 99.0 },
                    { name: 'Kristen', percentage: 0.5 }
                ],
                languages: [
                    { name: 'Pashto', percentage: 50, official: true },
                    { name: 'Dari', percentage: 50, official: true },
                    { name: 'Inggris', percentage: 10 }
                ],
                literacyRate: 38,
                governmentType: 'Republik Islam',
                independenceDay: '1919-08-19',
                nationalHoliday: '19 Agustus',
                legalSystem: 'Hukum Syariah',
                constitution: '2004',
                administrativeDivisions: 34,
                memberships: ['PBB', 'SAARC', 'SCO'],
                giniCoefficient: 29.4,
                hdi: 0.478,
                hdiRank: 175,
                corruptionIndex: 16,
                currency: 'Afghani',
                currencyCode: 'AFN',
                gdp: 15000000000,
                gdpPerCapita: 390,
                gdpPpp: 70000000000,
                gdpGrowth: -5.0,
                inflation: 10.0,
                unemployment: 30.0,
                povertyRate: 50.0,
                mainIndustries: ['Pertanian', 'Tambang', 'Tekstil', 'Kerajinan'],
                exports: [
                    { item: 'Buah', value: 2000000000 },
                    { item: 'Karpet', value: 1000000000 },
                    { item: 'Opium', value: 500000000 },
                    { item: 'Mineral', value: 200000000 }
                ],
                imports: [
                    { item: 'Mesin', value: 3000000000 },
                    { item: 'Elektronik', value: 2000000000 },
                    { item: 'Makanan', value: 1500000000 },
                    { item: 'Minyak', value: 1000000000 }
                ],
                tradeBalance: -5000000000,
                naturalResources: ['Litium', 'Tembaga', 'Batu bara', 'Emas', 'Gas'],
                economicRanking: 140,
                internetPenetration: 20,
                mobilePenetration: 40,
                electricityAccess: 50,
                roadLength: 30000,
                railwayLength: 100,
                airports: 15,
                seaports: 0,
                healthcareAccess: 30,
                educationIndex: 0.35,
                nationalMotto: 'Tidak ada tuhan selain Allah',
                nationalAnthem: 'Milli Surood',
                nationalAnimal: 'Elang Emas',
                nationalFlower: 'Bunga Tulip',
                nationalCuisine: ['Kabuli Palaw', 'Mantu', 'Ashak', 'Kebab', 'Boulani'],
                culturalHeritage: ['Kabul', 'Bamiyan', 'Herat', 'Kandahar'],
                publicHolidays: ['Idul Fitri', 'Idul Adha', 'Hari Kemerdekaan', 'Ashura'],
                socialRanking: 20,
                climate: 'Beragam',
                averageTemperature: 15,
                averageRainfall: 300,
                forestArea: 2,
                protectedAreas: 3,
                biodiversityRank: 35,
                carbonEmissions: 0.5,
                environmentalIndex: 25,
                riskScore: 90,
                politicalStability: 10,
                crimeIndex: 60,
                militarySpending: 5.0,
                peaceIndex: 90,
                terrorismIndex: 80,
                refugeePopulation: 2000000,
                opportunityScore: 20,
                easeOfDoingBusiness: 20,
                innovationIndex: 15,
                startupEcosystem: 10,
                investmentScore: 15,
                talentPool: 35,
                marketSize: 50,
                infrastructureQuality: 15,
                internetSpeed: 5,
                digitalAdoption: 20,
                techEcosystem: 10,
                aiReadiness: 10,
                startups: 10,
                phoneCode: '+93',
                tld: '.af',
                isoCode: 'AFG',
                isoCode2: 'AF',
                drivingSide: 'right',
                tags: ['negara', 'asian-selatan', 'jalur-sutra', 'sejarah', 'mineral']
            }
        }
    ];

    // ============================================================
    // PROSES DATA KE REGISTER
    // ============================================================
    for (let i = 0; i < data.length; i++) {
        window.__DATA_REGISTER.push(data[i]);
    }

    // ============================================================
    // LOGGER
    // ============================================================
    if (window.InternalLogger) {
        window.InternalLogger.info('CountryAsianSelatan', '✅ Loaded ' + data.length + ' countries (SUPER LENGKAP - 8 NEGARA!)');
    }

})();