const data = [
    // ==========================================================
    // 🇳🇴 NORWEGIA
    // ==========================================================
    {
        text: 'Norwegia - Negara di Eropa Utara dengan fjord dan kekayaan minyak. Ibu kota: Oslo. Populasi: 5.4 juta jiwa. Mata uang: Krone (NOK). Bahasa: Norwegia. Sistem pemerintahan: Monarki Konstitusional Parlementer. Negara dengan kualitas hidup tertinggi di dunia. Kaya akan minyak, gas, dan pemandangan alam yang indah. Rumah bagi fjord-fjord megah dan Aurora Borealis. Pemimpin global dalam energi terbarukan dan kesetaraan gender.',
        metadata: {
            category: 'country',
            region: 'eropan-utara',
            name: 'Norwegia',
            officialName: 'Kerajaan Norwegia',
            shortName: 'NOR',
            capital: 'Oslo',
            capitalCoordinates: { lat: 59.9139, lng: 10.7522 },
            largestCity: 'Oslo',
            demonym: 'Norwegia',
            subregion: 'Northern Europe',
            area: 385207,
            areaRank: 67,
            coastline: 25148,
            highestPoint: 'Galdhøpiggen',
            highestElevation: 2469,
            lowestPoint: 'Laut Norwegia',
            lowestElevation: 0,
            landBorders: ['Swedia', 'Finlandia', 'Rusia'],
            coordinates: { lat: 62.0, lng: 10.0 },
            timezone: ['Waktu Eropa Tengah'],
            utcOffset: ['+1'],
            population: 5400000,
            populationRank: 118,
            populationDensity: 14,
            populationGrowth: 0.8,
            medianAge: 40.0,
            lifeExpectancy: 82.5,
            fertilityRate: 1.5,
            urbanization: 83,
            ethnicGroups: [
                { name: 'Norwegia', percentage: 85.0 },
                { name: 'Eropa', percentage: 10.0 },
                { name: 'Lainnya', percentage: 5.0 }
            ],
            religions: [
                { name: 'Kristen Protestan', percentage: 70.0 },
                { name: 'Tidak beragama', percentage: 20.0 },
                { name: 'Islam', percentage: 3.0 },
                { name: 'Lainnya', percentage: 7.0 }
            ],
            languages: [
                { name: 'Norwegia', percentage: 100, official: true },
                { name: 'Inggris', percentage: 90 },
                { name: 'Swedia', percentage: 10 }
            ],
            literacyRate: 100,
            governmentType: 'Monarki Konstitusional Parlementer',
            independenceDay: '1905-06-07',
            nationalHoliday: '17 Mei',
            legalSystem: 'Civil Law',
            constitution: '1814',
            administrativeDivisions: 19,
            memberships: ['PBB', 'NATO', 'OECD', 'WTO'],
            giniCoefficient: 27.0,
            hdi: 0.966,
            hdiRank: 1,
            corruptionIndex: 85,
            currency: 'Krone',
            currencyCode: 'NOK',
            gdp: 550000000000,
            gdpPerCapita: 101800,
            gdpPpp: 450000000000,
            gdpGrowth: 1.5,
            inflation: 2.5,
            unemployment: 4.0,
            povertyRate: 8.0,
            mainIndustries: ['Minyak', 'Gas', 'Perikanan', 'Perkapalan', 'Teknologi'],
            exports: [
                { item: 'Minyak', value: 150000000000 },
                { item: 'Gas', value: 100000000000 },
                { item: 'Perikanan', value: 50000000000 },
                { item: 'Teknologi', value: 30000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 50000000000 },
                { item: 'Elektronik', value: 40000000000 },
                { item: 'Makanan', value: 30000000000 },
                { item: 'Bahan kimia', value: 20000000000 }
            ],
            tradeBalance: 150000000000,
            naturalResources: ['Minyak', 'Gas', 'Perikanan', 'Kayu', 'Air'],
            economicRanking: 30,
            internetPenetration: 98,
            mobilePenetration: 99,
            electricityAccess: 100,
            roadLength: 100000,
            railwayLength: 4000,
            airports: 100,
            seaports: 50,
            healthcareAccess: 98,
            educationIndex: 0.88,
            nationalMotto: 'Semua untuk Norwegia',
            nationalAnthem: 'Ja, vi elsker dette landet',
            nationalAnimal: 'Rusa',
            nationalFlower: 'Bunga Gips',
            nationalCuisine: ['Fårikål', 'Rakfisk', 'Brunost', 'Krumkake', 'Lutefisk'],
            culturalHeritage: ['Oslo', 'Bergen', 'Tromsø', 'Geirangerfjord'],
            publicHolidays: ['Hari Konstitusi', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 95,
            climate: 'Kontinental',
            averageTemperature: 5,
            averageRainfall: 800,
            forestArea: 33,
            protectedAreas: 20,
            biodiversityRank: 25,
            carbonEmissions: 8.0,
            environmentalIndex: 65,
            riskScore: 10,
            politicalStability: 95,
            crimeIndex: 8,
            militarySpending: 1.5,
            peaceIndex: 15,
            terrorismIndex: 3,
            refugeePopulation: 50000,
            opportunityScore: 85,
            easeOfDoingBusiness: 85,
            innovationIndex: 78,
            startupEcosystem: 75,
            investmentScore: 82,
            talentPool: 85,
            marketSize: 78,
            infrastructureQuality: 92,
            internetSpeed: 60,
            digitalAdoption: 95,
            techEcosystem: 82,
            aiReadiness: 75,
            startups: 1000,
            phoneCode: '+47',
            tld: '.no',
            isoCode: 'NOR',
            isoCode2: 'NO',
            drivingSide: 'right',
            tags: ['negara', 'eropan-utara', 'minyak', 'fjord', 'nato']
        }
    },
    // ==========================================================
    // 🇸🇪 SWEDIA
    // ==========================================================
    {
        text: 'Swedia - Negara di Eropa Utara dengan ekonomi maju dan inovasi tinggi. Ibu kota: Stockholm. Populasi: 10.4 juta jiwa. Mata uang: Krona (SEK). Bahasa: Swedia. Sistem pemerintahan: Monarki Konstitusional Parlementer. Negara dengan inovasi, kesetaraan, dan kualitas hidup tertinggi. Rumah bagi Spotify, IKEA, dan Volvo. Pemimpin global dalam teknologi dan hak asasi manusia.',
        metadata: {
            category: 'country',
            region: 'eropan-utara',
            name: 'Swedia',
            officialName: 'Kerajaan Swedia',
            shortName: 'SWE',
            capital: 'Stockholm',
            capitalCoordinates: { lat: 59.3293, lng: 18.0686 },
            largestCity: 'Stockholm',
            demonym: 'Swedia',
            subregion: 'Northern Europe',
            area: 450295,
            areaRank: 55,
            coastline: 3218,
            highestPoint: 'Kebnekaise',
            highestElevation: 2106,
            lowestPoint: 'Laut Baltik',
            lowestElevation: 0,
            landBorders: ['Norwegia', 'Finlandia'],
            coordinates: { lat: 62.0, lng: 15.0 },
            timezone: ['Waktu Eropa Tengah'],
            utcOffset: ['+1'],
            population: 10400000,
            populationRank: 88,
            populationDensity: 23,
            populationGrowth: 0.5,
            medianAge: 41.0,
            lifeExpectancy: 82.0,
            fertilityRate: 1.7,
            urbanization: 88,
            ethnicGroups: [
                { name: 'Swedia', percentage: 80.0 },
                { name: 'Finlandia', percentage: 5.0 },
                { name: 'Arab', percentage: 5.0 },
                { name: 'Lainnya', percentage: 10.0 }
            ],
            religions: [
                { name: 'Kristen Protestan', percentage: 60.0 },
                { name: 'Tidak beragama', percentage: 30.0 },
                { name: 'Islam', percentage: 5.0 },
                { name: 'Lainnya', percentage: 5.0 }
            ],
            languages: [
                { name: 'Swedia', percentage: 100, official: true },
                { name: 'Inggris', percentage: 90 },
                { name: 'Finlandia', percentage: 5 }
            ],
            literacyRate: 99,
            governmentType: 'Monarki Konstitusional Parlementer',
            independenceDay: '1523-06-06',
            nationalHoliday: '6 Juni',
            legalSystem: 'Civil Law',
            constitution: '1974',
            administrativeDivisions: 21,
            memberships: ['PBB', 'UE', 'NATO', 'OECD', 'WTO'],
            giniCoefficient: 28.0,
            hdi: 0.947,
            hdiRank: 7,
            corruptionIndex: 85,
            currency: 'Krona',
            currencyCode: 'SEK',
            gdp: 650000000000,
            gdpPerCapita: 62500,
            gdpPpp: 700000000000,
            gdpGrowth: 2.0,
            inflation: 2.5,
            unemployment: 6.0,
            povertyRate: 12.0,
            mainIndustries: ['Teknologi', 'Manufaktur', 'Otomotif', 'Farmasi', 'Pariwisata'],
            exports: [
                { item: 'Teknologi', value: 150000000000 },
                { item: 'Otomotif', value: 100000000000 },
                { item: 'Farmasi', value: 80000000000 },
                { item: 'Mesin', value: 60000000000 }
            ],
            imports: [
                { item: 'Elektronik', value: 80000000000 },
                { item: 'Mesin', value: 70000000000 },
                { item: 'Minyak', value: 50000000000 },
                { item: 'Makanan', value: 40000000000 }
            ],
            tradeBalance: 10000000000,
            naturalResources: ['Kayu', 'Air', 'Besi', 'Tembaga', 'Emas'],
            economicRanking: 25,
            internetPenetration: 95,
            mobilePenetration: 99,
            electricityAccess: 100,
            roadLength: 200000,
            railwayLength: 14000,
            airports: 200,
            seaports: 50,
            healthcareAccess: 95,
            educationIndex: 0.85,
            nationalMotto: 'Kebebasan, Kesetaraan, Persaudaraan',
            nationalAnthem: 'Du gamla, du fria',
            nationalAnimal: 'Rusa',
            nationalFlower: 'Bunga Jagung',
            nationalCuisine: ['Meatballs', 'Gravlax', 'Smörgåsbord', 'Kanelbulle', 'Surströmming'],
            culturalHeritage: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala'],
            publicHolidays: ['Hari Nasional', 'Midsommar', 'Christmas', 'Tahun Baru'],
            socialRanking: 92,
            climate: 'Kontinental',
            averageTemperature: 6,
            averageRainfall: 600,
            forestArea: 69,
            protectedAreas: 20,
            biodiversityRank: 25,
            carbonEmissions: 4.0,
            environmentalIndex: 62,
            riskScore: 12,
            politicalStability: 90,
            crimeIndex: 15,
            militarySpending: 1.2,
            peaceIndex: 18,
            terrorismIndex: 8,
            refugeePopulation: 100000,
            opportunityScore: 82,
            easeOfDoingBusiness: 82,
            innovationIndex: 82,
            startupEcosystem: 85,
            investmentScore: 80,
            talentPool: 88,
            marketSize: 82,
            infrastructureQuality: 90,
            internetSpeed: 55,
            digitalAdoption: 95,
            techEcosystem: 88,
            aiReadiness: 80,
            startups: 3000,
            phoneCode: '+46',
            tld: '.se',
            isoCode: 'SWE',
            isoCode2: 'SE',
            drivingSide: 'right',
            tags: ['negara', 'eropan-utara', 'inovasi', 'hak-asasi', 'ue']
        }
    },
    // ==========================================================
    // 🇫🇮 FINLANDIA
    // ==========================================================
    {
        text: 'Finlandia - Negara di Eropa Utara dengan pendidikan terbaik dunia. Ibu kota: Helsinki. Populasi: 5.5 juta jiwa. Mata uang: Euro (EUR). Bahasa: Finlandia, Swedia. Sistem pemerintahan: Republik Parlementer. Negara dengan pendidikan dan kualitas hidup terbaik. Rumah bagi sauna, Danau Saimaa, dan Aurora Borealis. Pemimpin global dalam teknologi dan inovasi.',
        metadata: {
            category: 'country',
            region: 'eropan-utara',
            name: 'Finlandia',
            officialName: 'Republik Finlandia',
            shortName: 'FIN',
            capital: 'Helsinki',
            capitalCoordinates: { lat: 60.1699, lng: 24.9384 },
            largestCity: 'Helsinki',
            demonym: 'Finlandia',
            subregion: 'Northern Europe',
            area: 338424,
            areaRank: 64,
            coastline: 1250,
            highestPoint: 'Halti',
            highestElevation: 1324,
            lowestPoint: 'Laut Baltik',
            lowestElevation: 0,
            landBorders: ['Norwegia', 'Swedia', 'Rusia'],
            coordinates: { lat: 64.0, lng: 26.0 },
            timezone: ['Waktu Eropa Timur'],
            utcOffset: ['+2'],
            population: 5500000,
            populationRank: 115,
            populationDensity: 16,
            populationGrowth: 0.1,
            medianAge: 43.0,
            lifeExpectancy: 81.7,
            fertilityRate: 1.4,
            urbanization: 85,
            ethnicGroups: [
                { name: 'Finlandia', percentage: 93.0 },
                { name: 'Swedia', percentage: 5.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            religions: [
                { name: 'Kristen Protestan', percentage: 70.0 },
                { name: 'Tidak beragama', percentage: 25.0 },
                { name: 'Kristen Ortodoks', percentage: 2.0 },
                { name: 'Lainnya', percentage: 3.0 }
            ],
            languages: [
                { name: 'Finlandia', percentage: 100, official: true },
                { name: 'Swedia', percentage: 5, official: true },
                { name: 'Inggris', percentage: 70 }
            ],
            literacyRate: 100,
            governmentType: 'Republik Parlementer',
            independenceDay: '1917-12-06',
            nationalHoliday: '6 Desember',
            legalSystem: 'Civil Law',
            constitution: '1919',
            administrativeDivisions: 19,
            memberships: ['PBB', 'UE', 'NATO', 'OECD', 'WTO'],
            giniCoefficient: 27.0,
            hdi: 0.945,
            hdiRank: 9,
            corruptionIndex: 88,
            currency: 'Euro',
            currencyCode: 'EUR',
            gdp: 350000000000,
            gdpPerCapita: 63600,
            gdpPpp: 400000000000,
            gdpGrowth: 1.5,
            inflation: 2.0,
            unemployment: 6.0,
            povertyRate: 10.0,
            mainIndustries: ['Teknologi', 'Mesin', 'Kimia', 'Pertanian', 'Pariwisata'],
            exports: [
                { item: 'Teknologi', value: 100000000000 },
                { item: 'Mesin', value: 80000000000 },
                { item: 'Kimia', value: 60000000000 },
                { item: 'Kayu', value: 40000000000 }
            ],
            imports: [
                { item: 'Elektronik', value: 60000000000 },
                { item: 'Mesin', value: 50000000000 },
                { item: 'Minyak', value: 40000000000 },
                { item: 'Makanan', value: 30000000000 }
            ],
            tradeBalance: 10000000000,
            naturalResources: ['Kayu', 'Air', 'Mineral', 'Emas'],
            economicRanking: 40,
            internetPenetration: 95,
            mobilePenetration: 99,
            electricityAccess: 100,
            roadLength: 80000,
            railwayLength: 6000,
            airports: 50,
            seaports: 30,
            healthcareAccess: 95,
            educationIndex: 0.88,
            nationalMotto: 'Kebebasan, Keadilan, Kemakmuran',
            nationalAnthem: 'Maamme',
            nationalAnimal: 'Beruang',
            nationalFlower: 'Bunga Lily',
            nationalCuisine: ['Karjalanpiirakka', 'Korvapuusti', 'Kalakeitto', 'Ruisleipä', 'Mämmi'],
            culturalHeritage: ['Helsinki', 'Rovaniemi', 'Sauna', 'Turku'],
            publicHolidays: ['Hari Kemerdekaan', 'Midsommar', 'Christmas', 'Tahun Baru'],
            socialRanking: 92,
            climate: 'Kontinental',
            averageTemperature: 5,
            averageRainfall: 600,
            forestArea: 73,
            protectedAreas: 15,
            biodiversityRank: 30,
            carbonEmissions: 8.0,
            environmentalIndex: 60,
            riskScore: 12,
            politicalStability: 92,
            crimeIndex: 10,
            militarySpending: 1.5,
            peaceIndex: 18,
            terrorismIndex: 5,
            refugeePopulation: 20000,
            opportunityScore: 80,
            easeOfDoingBusiness: 80,
            innovationIndex: 78,
            startupEcosystem: 78,
            investmentScore: 78,
            talentPool: 85,
            marketSize: 78,
            infrastructureQuality: 88,
            internetSpeed: 55,
            digitalAdoption: 92,
            techEcosystem: 82,
            aiReadiness: 75,
            startups: 1500,
            phoneCode: '+358',
            tld: '.fi',
            isoCode: 'FIN',
            isoCode2: 'FI',
            drivingSide: 'right',
            tags: ['negara', 'eropan-utara', 'pendidikan', 'teknologi', 'ue']
        }
    },
    // ==========================================================
    // 🇩🇰 DENMARK
    // ==========================================================
    {
        text: 'Denmark - Negara di Eropa Utara dengan sejarah Viking dan desain. Ibu kota: Kopenhagen. Populasi: 5.9 juta jiwa. Mata uang: Krone (DKK). Bahasa: Denmark. Sistem pemerintahan: Monarki Konstitusional Parlementer. Negara dengan desain, kualitas hidup, dan energi terbarukan. Rumah bagi LEGO, hygge, dan istana-istana megah. Pemimpin global dalam energi angin dan keberlanjutan.',
        metadata: {
            category: 'country',
            region: 'eropan-utara',
            name: 'Denmark',
            officialName: 'Kerajaan Denmark',
            shortName: 'DNK',
            capital: 'Kopenhagen',
            capitalCoordinates: { lat: 55.6761, lng: 12.5683 },
            largestCity: 'Kopenhagen',
            demonym: 'Denmark',
            subregion: 'Northern Europe',
            area: 43094,
            areaRank: 130,
            coastline: 7314,
            highestPoint: 'Møllehøj',
            highestElevation: 170,
            lowestPoint: 'Laut Utara',
            lowestElevation: 0,
            landBorders: ['Jerman'],
            coordinates: { lat: 56.0, lng: 10.0 },
            timezone: ['Waktu Eropa Tengah'],
            utcOffset: ['+1'],
            population: 5900000,
            populationRank: 113,
            populationDensity: 137,
            populationGrowth: 0.3,
            medianAge: 42.0,
            lifeExpectancy: 81.4,
            fertilityRate: 1.7,
            urbanization: 88,
            ethnicGroups: [
                { name: 'Denmark', percentage: 85.0 },
                { name: 'Eropa', percentage: 10.0 },
                { name: 'Lainnya', percentage: 5.0 }
            ],
            religions: [
                { name: 'Kristen Protestan', percentage: 75.0 },
                { name: 'Tidak beragama', percentage: 20.0 },
                { name: 'Islam', percentage: 3.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            languages: [
                { name: 'Denmark', percentage: 100, official: true },
                { name: 'Inggris', percentage: 90 },
                { name: 'Jerman', percentage: 20 }
            ],
            literacyRate: 99,
            governmentType: 'Monarki Konstitusional Parlementer',
            independenceDay: '1849-06-05',
            nationalHoliday: '5 Juni',
            legalSystem: 'Civil Law',
            constitution: '1849',
            administrativeDivisions: 5,
            memberships: ['PBB', 'UE', 'NATO', 'OECD', 'WTO'],
            giniCoefficient: 28.0,
            hdi: 0.948,
            hdiRank: 6,
            corruptionIndex: 88,
            currency: 'Krone',
            currencyCode: 'DKK',
            gdp: 400000000000,
            gdpPerCapita: 67800,
            gdpPpp: 450000000000,
            gdpGrowth: 2.0,
            inflation: 2.5,
            unemployment: 5.0,
            povertyRate: 10.0,
            mainIndustries: ['Manufaktur', 'Pariwisata', 'Keuangan', 'Desain', 'Energi'],
            exports: [
                { item: 'Manufaktur', value: 100000000000 },
                { item: 'Pariwisata', value: 50000000000 },
                { item: 'Keuangan', value: 40000000000 },
                { item: 'Energi', value: 30000000000 }
            ],
            imports: [
                { item: 'Elektronik', value: 60000000000 },
                { item: 'Mesin', value: 50000000000 },
                { item: 'Minyak', value: 40000000000 },
                { item: 'Makanan', value: 30000000000 }
            ],
            tradeBalance: 10000000000,
            naturalResources: ['Gas', 'Air', 'Tanah subur', 'Perikanan'],
            economicRanking: 35,
            internetPenetration: 95,
            mobilePenetration: 99,
            electricityAccess: 100,
            roadLength: 75000,
            railwayLength: 3000,
            airports: 50,
            seaports: 30,
            healthcareAccess: 95,
            educationIndex: 0.85,
            nationalMotto: 'Tuhan membantu Denmark',
            nationalAnthem: 'Der er et yndigt land',
            nationalAnimal: 'Angsa',
            nationalFlower: 'Bunga Daisy',
            nationalCuisine: ['Smørrebrød', 'Frikadeller', 'Æbleskiver', 'Wienerbrød', 'Rødgrød'],
            culturalHeritage: ['Copenhagen', 'Nyhavn', 'Tivoli', 'Legoland'],
            publicHolidays: ['Hari Konstitusi', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 92,
            climate: 'Maritim',
            averageTemperature: 8,
            averageRainfall: 700,
            forestArea: 14,
            protectedAreas: 10,
            biodiversityRank: 30,
            carbonEmissions: 5.0,
            environmentalIndex: 60,
            riskScore: 12,
            politicalStability: 92,
            crimeIndex: 15,
            militarySpending: 1.2,
            peaceIndex: 18,
            terrorismIndex: 5,
            refugeePopulation: 20000,
            opportunityScore: 82,
            easeOfDoingBusiness: 82,
            innovationIndex: 75,
            startupEcosystem: 78,
            investmentScore: 80,
            talentPool: 82,
            marketSize: 78,
            infrastructureQuality: 88,
            internetSpeed: 55,
            digitalAdoption: 92,
            techEcosystem: 78,
            aiReadiness: 72,
            startups: 1500,
            phoneCode: '+45',
            tld: '.dk',
            isoCode: 'DNK',
            isoCode2: 'DK',
            drivingSide: 'right',
            tags: ['negara', 'eropan-utara', 'viking', 'desain', 'energi']
        }
    },
    // ==========================================================
    // 🇮🇸 ISLANDIA
    // ==========================================================
    {
        text: 'Islandia - Negara di Eropa Utara dengan alam vulkanik dan aurora. Ibu kota: Reykjavik. Populasi: 0.38 juta jiwa. Mata uang: Krona (ISK). Bahasa: Islandia. Sistem pemerintahan: Republik Parlementer. Negara dengan energi terbarukan 100%. Rumah bagi gunung berapi, gletser, dan Aurora Borealis. Destinasi wisata alam terbaik di dunia.',
        metadata: {
            category: 'country',
            region: 'eropan-utara',
            name: 'Islandia',
            officialName: 'Republik Islandia',
            shortName: 'ISL',
            capital: 'Reykjavik',
            capitalCoordinates: { lat: 64.1466, lng: -21.9426 },
            largestCity: 'Reykjavik',
            demonym: 'Islandia',
            subregion: 'Northern Europe',
            area: 103000,
            areaRank: 106,
            coastline: 4970,
            highestPoint: 'Hvannadalshnúkur',
            highestElevation: 2110,
            lowestPoint: 'Laut Atlantik',
            lowestElevation: 0,
            landBorders: [],
            coordinates: { lat: 65.0, lng: -18.0 },
            timezone: ['Waktu Greenwich'],
            utcOffset: ['+0'],
            population: 380000,
            populationRank: 172,
            populationDensity: 3,
            populationGrowth: 0.6,
            medianAge: 38.0,
            lifeExpectancy: 82.0,
            fertilityRate: 1.7,
            urbanization: 94,
            ethnicGroups: [
                { name: 'Islandia', percentage: 90.0 },
                { name: 'Eropa', percentage: 8.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            religions: [
                { name: 'Kristen Protestan', percentage: 70.0 },
                { name: 'Tidak beragama', percentage: 20.0 },
                { name: 'Kristen Katolik', percentage: 5.0 },
                { name: 'Lainnya', percentage: 5.0 }
            ],
            languages: [
                { name: 'Islandia', percentage: 100, official: true },
                { name: 'Inggris', percentage: 90 },
                { name: 'Denmark', percentage: 10 }
            ],
            literacyRate: 100,
            governmentType: 'Republik Parlementer',
            independenceDay: '1944-06-17',
            nationalHoliday: '17 Juni',
            legalSystem: 'Civil Law',
            constitution: '1944',
            administrativeDivisions: 8,
            memberships: ['PBB', 'NATO', 'OECD', 'WTO'],
            giniCoefficient: 26.0,
            hdi: 0.959,
            hdiRank: 3,
            corruptionIndex: 89,
            currency: 'Krona',
            currencyCode: 'ISK',
            gdp: 30000000000,
            gdpPerCapita: 78900,
            gdpPpp: 25000000000,
            gdpGrowth: 3.0,
            inflation: 3.0,
            unemployment: 3.0,
            povertyRate: 5.0,
            mainIndustries: ['Pariwisata', 'Perikanan', 'Energi', 'Teknologi', 'Keuangan'],
            exports: [
                { item: 'Perikanan', value: 15000000000 },
                { item: 'Pariwisata', value: 10000000000 },
                { item: 'Energi', value: 5000000000 },
                { item: 'Teknologi', value: 3000000000 }
            ],
            imports: [
                { item: 'Mesin', value: 8000000000 },
                { item: 'Elektronik', value: 6000000000 },
                { item: 'Makanan', value: 5000000000 },
                { item: 'Minyak', value: 4000000000 }
            ],
            tradeBalance: 2000000000,
            naturalResources: ['Perikanan', 'Geotermal', 'Air', 'Kayu'],
            economicRanking: 65,
            internetPenetration: 98,
            mobilePenetration: 99,
            electricityAccess: 100,
            roadLength: 13000,
            railwayLength: 0,
            airports: 20,
            seaports: 10,
            healthcareAccess: 95,
            educationIndex: 0.85,
            nationalMotto: 'Kebebasan, Kesetaraan, Persaudaraan',
            nationalAnthem: 'Lofsöngur',
            nationalAnimal: 'Falcon',
            nationalFlower: 'Mountain Avens',
            nationalCuisine: ['Hákarl', 'Skyr', 'Lamb Soup', 'Rúgbrauð', 'Plokkfiskur'],
            culturalHeritage: ['Reykjavik', 'Golden Circle', 'Vatnajökull', 'Blue Lagoon'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 92,
            climate: 'Subartik',
            averageTemperature: 2,
            averageRainfall: 800,
            forestArea: 1,
            protectedAreas: 20,
            biodiversityRank: 30,
            carbonEmissions: 0.5,
            environmentalIndex: 70,
            riskScore: 15,
            politicalStability: 90,
            crimeIndex: 5,
            militarySpending: 0.5,
            peaceIndex: 15,
            terrorismIndex: 2,
            refugeePopulation: 1000,
            opportunityScore: 75,
            easeOfDoingBusiness: 75,
            innovationIndex: 70,
            startupEcosystem: 65,
            investmentScore: 72,
            talentPool: 70,
            marketSize: 55,
            infrastructureQuality: 82,
            internetSpeed: 60,
            digitalAdoption: 92,
            techEcosystem: 72,
            aiReadiness: 65,
            startups: 150,
            phoneCode: '+354',
            tld: '.is',
            isoCode: 'ISL',
            isoCode2: 'IS',
            drivingSide: 'right',
            tags: ['negara', 'eropan-utara', 'vulkan', 'aurora', 'energi']
        }
    },
    // ==========================================================
    // 🇪🇪 ESTONIA
    // ==========================================================
    {
        text: 'Estonia - Negara Baltik di Eropa Utara dengan digitalisasi terbaik. Ibu kota: Tallinn. Populasi: 1.3 juta jiwa. Mata uang: Euro (EUR). Bahasa: Estonia. Sistem pemerintahan: Republik Parlementer. Negara dengan e-government terbaik di dunia. Pemimpin global dalam digitalisasi dan startup. Rumah bagi Skype dan kota abad pertengahan Tallinn.',
        metadata: {
            category: 'country',
            region: 'eropan-utara',
            name: 'Estonia',
            officialName: 'Republik Estonia',
            shortName: 'EST',
            capital: 'Tallinn',
            capitalCoordinates: { lat: 59.4370, lng: 24.7536 },
            largestCity: 'Tallinn',
            demonym: 'Estonia',
            subregion: 'Northern Europe',
            area: 45228,
            areaRank: 129,
            coastline: 3794,
            highestPoint: 'Suur Munamägi',
            highestElevation: 318,
            lowestPoint: 'Laut Baltik',
            lowestElevation: 0,
            landBorders: ['Latvia', 'Rusia'],
            coordinates: { lat: 59.0, lng: 26.0 },
            timezone: ['Waktu Eropa Timur'],
            utcOffset: ['+2'],
            population: 1300000,
            populationRank: 155,
            populationDensity: 29,
            populationGrowth: 0.0,
            medianAge: 42.0,
            lifeExpectancy: 78.0,
            fertilityRate: 1.6,
            urbanization: 69,
            ethnicGroups: [
                { name: 'Estonia', percentage: 68.0 },
                { name: 'Rusia', percentage: 25.0 },
                { name: 'Lainnya', percentage: 7.0 }
            ],
            religions: [
                { name: 'Tidak beragama', percentage: 55.0 },
                { name: 'Kristen Protestan', percentage: 20.0 },
                { name: 'Kristen Ortodoks', percentage: 15.0 },
                { name: 'Lainnya', percentage: 10.0 }
            ],
            languages: [
                { name: 'Estonia', percentage: 100, official: true },
                { name: 'Rusia', percentage: 25 },
                { name: 'Inggris', percentage: 50 }
            ],
            literacyRate: 99,
            governmentType: 'Republik Parlementer',
            independenceDay: '1918-02-24',
            nationalHoliday: '24 Februari',
            legalSystem: 'Civil Law',
            constitution: '1992',
            administrativeDivisions: 15,
            memberships: ['PBB', 'UE', 'NATO', 'OECD', 'WTO'],
            giniCoefficient: 30.0,
            hdi: 0.892,
            hdiRank: 30,
            corruptionIndex: 74,
            currency: 'Euro',
            currencyCode: 'EUR',
            gdp: 40000000000,
            gdpPerCapita: 30700,
            gdpPpp: 60000000000,
            gdpGrowth: 3.0,
            inflation: 3.0,
            unemployment: 5.0,
            povertyRate: 15.0,
            mainIndustries: ['Digital', 'Teknologi', 'Manufaktur', 'Pariwisata', 'Keuangan'],
            exports: [
                { item: 'Teknologi', value: 15000000000 },
                { item: 'Digital', value: 10000000000 },
                { item: 'Manufaktur', value: 8000000000 },
                { item: 'Pariwisata', value: 5000000000 }
            ],
            imports: [
                { item: 'Elektronik', value: 8000000000 },
                { item: 'Mesin', value: 6000000000 },
                { item: 'Minyak', value: 4000000000 },
                { item: 'Makanan', value: 3000000000 }
            ],
            tradeBalance: 2000000000,
            naturalResources: ['Kayu', 'Air', 'Mineral', 'Garam'],
            economicRanking: 60,
            internetPenetration: 95,
            mobilePenetration: 99,
            electricityAccess: 100,
            roadLength: 60000,
            railwayLength: 1000,
            airports: 20,
            seaports: 10,
            healthcareAccess: 85,
            educationIndex: 0.78,
            nationalMotto: 'Kebebasan, Keadilan, Kemakmuran',
            nationalAnthem: 'Mu isamaa, mu õnn ja rõõm',
            nationalAnimal: 'Burung Layang-layang',
            nationalFlower: 'Bunga Jagung',
            nationalCuisine: ['Verivorst', 'Mulgipuder', 'Kama', 'Kohuke', 'Rye Bread'],
            culturalHeritage: ['Tallinn', 'Tartu', 'Pärnu', 'Saaremaa'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 78,
            climate: 'Kontinental',
            averageTemperature: 6,
            averageRainfall: 500,
            forestArea: 50,
            protectedAreas: 15,
            biodiversityRank: 30,
            carbonEmissions: 10.0,
            environmentalIndex: 55,
            riskScore: 20,
            politicalStability: 80,
            crimeIndex: 20,
            militarySpending: 2.0,
            peaceIndex: 25,
            terrorismIndex: 5,
            refugeePopulation: 5000,
            opportunityScore: 75,
            easeOfDoingBusiness: 78,
            innovationIndex: 70,
            startupEcosystem: 75,
            investmentScore: 72,
            talentPool: 72,
            marketSize: 65,
            infrastructureQuality: 78,
            internetSpeed: 50,
            digitalAdoption: 95,
            techEcosystem: 80,
            aiReadiness: 72,
            startups: 500,
            phoneCode: '+372',
            tld: '.ee',
            isoCode: 'EST',
            isoCode2: 'EE',
            drivingSide: 'right',
            tags: ['negara', 'eropan-utara', 'digital', 'egov', 'ue']
        }
    },
    // ==========================================================
    // 🇱🇻 LATVIA
    // ==========================================================
    {
        text: 'Latvia - Negara Baltik di Eropa Utara dengan sejarah dan budaya. Ibu kota: Riga. Populasi: 1.8 juta jiwa. Mata uang: Euro (EUR). Bahasa: Latvia. Sistem pemerintahan: Republik Parlementer. Negara dengan arsitektur Art Nouveau dan budaya Baltik. Riga salah satu kota terindah di Eropa. Pemimpin global dalam inovasi dan startup.',
        metadata: {
            category: 'country',
            region: 'eropan-utara',
            name: 'Latvia',
            officialName: 'Republik Latvia',
            shortName: 'LVA',
            capital: 'Riga',
            capitalCoordinates: { lat: 56.9496, lng: 24.1052 },
            largestCity: 'Riga',
            demonym: 'Latvia',
            subregion: 'Northern Europe',
            area: 64589,
            areaRank: 122,
            coastline: 498,
            highestPoint: 'Gaiziņkalns',
            highestElevation: 311,
            lowestPoint: 'Laut Baltik',
            lowestElevation: 0,
            landBorders: ['Estonia', 'Lithuania', 'Belarus', 'Rusia'],
            coordinates: { lat: 57.0, lng: 25.0 },
            timezone: ['Waktu Eropa Timur'],
            utcOffset: ['+2'],
            population: 1800000,
            populationRank: 149,
            populationDensity: 28,
            populationGrowth: -0.1,
            medianAge: 43.0,
            lifeExpectancy: 75.0,
            fertilityRate: 1.5,
            urbanization: 68,
            ethnicGroups: [
                { name: 'Latvia', percentage: 62.0 },
                { name: 'Rusia', percentage: 25.0 },
                { name: 'Lainnya', percentage: 13.0 }
            ],
            religions: [
                { name: 'Kristen Protestan', percentage: 35.0 },
                { name: 'Kristen Katolik', percentage: 25.0 },
                { name: 'Tidak beragama', percentage: 30.0 },
                { name: 'Kristen Ortodoks', percentage: 10.0 }
            ],
            languages: [
                { name: 'Latvia', percentage: 100, official: true },
                { name: 'Rusia', percentage: 25 },
                { name: 'Inggris', percentage: 40 }
            ],
            literacyRate: 99,
            governmentType: 'Republik Parlementer',
            independenceDay: '1918-11-18',
            nationalHoliday: '18 November',
            legalSystem: 'Civil Law',
            constitution: '1922',
            administrativeDivisions: 10,
            memberships: ['PBB', 'UE', 'NATO', 'OECD', 'WTO'],
            giniCoefficient: 35.0,
            hdi: 0.866,
            hdiRank: 33,
            corruptionIndex: 58,
            currency: 'Euro',
            currencyCode: 'EUR',
            gdp: 50000000000,
            gdpPerCapita: 27700,
            gdpPpp: 70000000000,
            gdpGrowth: 3.0,
            inflation: 3.0,
            unemployment: 6.0,
            povertyRate: 20.0,
            mainIndustries: ['Manufaktur', 'Pariwisata', 'Keuangan', 'Teknologi', 'Pertanian'],
            exports: [
                { item: 'Manufaktur', value: 15000000000 },
                { item: 'Pariwisata', value: 10000000000 },
                { item: 'Teknologi', value: 8000000000 },
                { item: 'Pertanian', value: 5000000000 }
            ],
            imports: [
                { item: 'Elektronik', value: 8000000000 },
                { item: 'Mesin', value: 6000000000 },
                { item: 'Minyak', value: 4000000000 },
                { item: 'Makanan', value: 3000000000 }
            ],
            tradeBalance: -2000000000,
            naturalResources: ['Kayu', 'Air', 'Mineral', 'Garam'],
            economicRanking: 70,
            internetPenetration: 88,
            mobilePenetration: 94,
            electricityAccess: 100,
            roadLength: 60000,
            railwayLength: 2000,
            airports: 20,
            seaports: 10,
            healthcareAccess: 80,
            educationIndex: 0.76,
            nationalMotto: 'Kebebasan, Kesetaraan, Persaudaraan',
            nationalAnthem: 'Dievs, svētī Latviju!',
            nationalAnimal: 'Kumbang',
            nationalFlower: 'Bunga Daisy',
            nationalCuisine: ['Rupjmaize', 'Pīrāgi', 'Sklandrausis', 'Kartupeļu pankūkas', 'Pelēkie zirņi'],
            culturalHeritage: ['Riga', 'Jūrmala', 'Sigulda', 'Ventspils'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 72,
            climate: 'Kontinental',
            averageTemperature: 6,
            averageRainfall: 600,
            forestArea: 54,
            protectedAreas: 10,
            biodiversityRank: 30,
            carbonEmissions: 4.0,
            environmentalIndex: 52,
            riskScore: 25,
            politicalStability: 70,
            crimeIndex: 25,
            militarySpending: 1.5,
            peaceIndex: 30,
            terrorismIndex: 8,
            refugeePopulation: 5000,
            opportunityScore: 68,
            easeOfDoingBusiness: 70,
            innovationIndex: 60,
            startupEcosystem: 65,
            investmentScore: 65,
            talentPool: 68,
            marketSize: 62,
            infrastructureQuality: 72,
            internetSpeed: 45,
            digitalAdoption: 78,
            techEcosystem: 68,
            aiReadiness: 58,
            startups: 200,
            phoneCode: '+371',
            tld: '.lv',
            isoCode: 'LVA',
            isoCode2: 'LV',
            drivingSide: 'right',
            tags: ['negara', 'eropan-utara', 'baltik', 'ue', 'nato']
        }
    },
    // ==========================================================
    // 🇱🇹 LITHUANIA
    // ==========================================================
    {
        text: 'Lithuania - Negara Baltik di Eropa Utara dengan ekonomi maju. Ibu kota: Vilnius. Populasi: 2.7 juta jiwa. Mata uang: Euro (EUR). Bahasa: Lithuania. Sistem pemerintahan: Republik Semi-Presidensial. Negara dengan sejarah panjang dan budaya Baltik. Vilnius salah satu kota terindah di Eropa. Pemimpin global dalam fintech dan teknologi.',
        metadata: {
            category: 'country',
            region: 'eropan-utara',
            name: 'Lithuania',
            officialName: 'Republik Lithuania',
            shortName: 'LTU',
            capital: 'Vilnius',
            capitalCoordinates: { lat: 54.6872, lng: 25.2797 },
            largestCity: 'Vilnius',
            demonym: 'Lithuania',
            subregion: 'Northern Europe',
            area: 65300,
            areaRank: 121,
            coastline: 90,
            highestPoint: 'Aukštojas',
            highestElevation: 294,
            lowestPoint: 'Laut Baltik',
            lowestElevation: 0,
            landBorders: ['Latvia', 'Belarus', 'Polandia', 'Rusia'],
            coordinates: { lat: 56.0, lng: 24.0 },
            timezone: ['Waktu Eropa Timur'],
            utcOffset: ['+2'],
            population: 2700000,
            populationRank: 137,
            populationDensity: 41,
            populationGrowth: 0.0,
            medianAge: 44.0,
            lifeExpectancy: 76.0,
            fertilityRate: 1.5,
            urbanization: 67,
            ethnicGroups: [
                { name: 'Lithuania', percentage: 84.0 },
                { name: 'Polandia', percentage: 6.0 },
                { name: 'Rusia', percentage: 5.0 },
                { name: 'Lainnya', percentage: 5.0 }
            ],
            religions: [
                { name: 'Kristen Katolik', percentage: 80.0 },
                { name: 'Kristen Ortodoks', percentage: 5.0 },
                { name: 'Tidak beragama', percentage: 10.0 },
                { name: 'Lainnya', percentage: 5.0 }
            ],
            languages: [
                { name: 'Lithuania', percentage: 100, official: true },
                { name: 'Rusia', percentage: 20 },
                { name: 'Inggris', percentage: 40 }
            ],
            literacyRate: 99,
            governmentType: 'Republik Semi-Presidensial',
            independenceDay: '1918-02-16',
            nationalHoliday: '16 Februari',
            legalSystem: 'Civil Law',
            constitution: '1992',
            administrativeDivisions: 10,
            memberships: ['PBB', 'UE', 'NATO', 'OECD', 'WTO'],
            giniCoefficient: 35.0,
            hdi: 0.882,
            hdiRank: 33,
            corruptionIndex: 58,
            currency: 'Euro',
            currencyCode: 'EUR',
            gdp: 80000000000,
            gdpPerCapita: 29600,
            gdpPpp: 120000000000,
            gdpGrowth: 3.5,
            inflation: 3.0,
            unemployment: 5.0,
            povertyRate: 15.0,
            mainIndustries: ['Manufaktur', 'Keuangan', 'Teknologi', 'Pariwisata', 'Pertanian'],
            exports: [
                { item: 'Manufaktur', value: 20000000000 },
                { item: 'Keuangan', value: 15000000000 },
                { item: 'Teknologi', value: 10000000000 },
                { item: 'Pariwisata', value: 5000000000 }
            ],
            imports: [
                { item: 'Elektronik', value: 10000000000 },
                { item: 'Mesin', value: 8000000000 },
                { item: 'Minyak', value: 6000000000 },
                { item: 'Makanan', value: 4000000000 }
            ],
            tradeBalance: -2000000000,
            naturalResources: ['Kayu', 'Air', 'Mineral', 'Garam'],
            economicRanking: 55,
            internetPenetration: 90,
            mobilePenetration: 96,
            electricityAccess: 100,
            roadLength: 80000,
            railwayLength: 2000,
            airports: 20,
            seaports: 5,
            healthcareAccess: 82,
            educationIndex: 0.78,
            nationalMotto: 'Kebebasan, Kemakmuran, Persatuan',
            nationalAnthem: 'Lietuvos himnas',
            nationalAnimal: 'Kuda',
            nationalFlower: 'Bunga Daisy',
            nationalCuisine: ['Cepelinai', 'Kugelis', 'Šaltibarščiai', 'Kvass', 'Rupjmaize'],
            culturalHeritage: ['Vilnius', 'Kaunas', 'Klaipėda', 'Trakai'],
            publicHolidays: ['Hari Kemerdekaan', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 75,
            climate: 'Kontinental',
            averageTemperature: 7,
            averageRainfall: 500,
            forestArea: 34,
            protectedAreas: 10,
            biodiversityRank: 30,
            carbonEmissions: 4.0,
            environmentalIndex: 55,
            riskScore: 20,
            politicalStability: 75,
            crimeIndex: 20,
            militarySpending: 1.5,
            peaceIndex: 25,
            terrorismIndex: 5,
            refugeePopulation: 5000,
            opportunityScore: 72,
            easeOfDoingBusiness: 72,
            innovationIndex: 65,
            startupEcosystem: 68,
            investmentScore: 70,
            talentPool: 72,
            marketSize: 68,
            infrastructureQuality: 75,
            internetSpeed: 48,
            digitalAdoption: 80,
            techEcosystem: 72,
            aiReadiness: 62,
            startups: 300,
            phoneCode: '+370',
            tld: '.lt',
            isoCode: 'LTU',
            isoCode2: 'LT',
            drivingSide: 'right',
            tags: ['negara', 'eropan-utara', 'baltik', 'ue', 'nato']
        }
    },
    // ==========================================================
    // 🇫🇴 KEPULAUAN FAROE
    // ==========================================================
    {
        text: 'Kepulauan Faroe - Wilayah otonom Denmark di Eropa Utara dengan budaya Viking. Ibu kota: Tórshavn. Populasi: 50 ribu jiwa. Mata uang: Krone (DKK). Bahasa: Faroe, Denmark. Sistem pemerintahan: Wilayah Otonom. Pemandangan fjord dan tebing curam. Ekonomi berbasis perikanan. Destinasi wisata alam yang eksotis dan budaya Viking yang kuat.',
        metadata: {
            category: 'country',
            region: 'eropan-utara',
            name: 'Kepulauan Faroe',
            officialName: 'Kepulauan Faroe',
            shortName: 'FRO',
            capital: 'Tórshavn',
            capitalCoordinates: { lat: 62.0079, lng: -6.7902 },
            largestCity: 'Tórshavn',
            demonym: 'Faroe',
            subregion: 'Northern Europe',
            area: 1393,
            areaRank: 177,
            coastline: 1117,
            highestPoint: 'Slættaratindur',
            highestElevation: 882,
            lowestPoint: 'Laut Atlantik',
            lowestElevation: 0,
            landBorders: [],
            coordinates: { lat: 62.0, lng: -6.8 },
            timezone: ['Waktu Greenwich'],
            utcOffset: ['+0'],
            population: 50000,
            populationRank: 178,
            populationDensity: 35,
            populationGrowth: 0.5,
            medianAge: 38.0,
            lifeExpectancy: 80.0,
            fertilityRate: 1.8,
            urbanization: 40,
            ethnicGroups: [
                { name: 'Faroe', percentage: 90.0 },
                { name: 'Denmark', percentage: 8.0 },
                { name: 'Lainnya', percentage: 2.0 }
            ],
            religions: [
                { name: 'Kristen Protestan', percentage: 85.0 },
                { name: 'Lainnya', percentage: 15.0 }
            ],
            languages: [
                { name: 'Faroe', percentage: 100, official: true },
                { name: 'Denmark', percentage: 50, official: true },
                { name: 'Inggris', percentage: 30 }
            ],
            literacyRate: 99,
            governmentType: 'Wilayah Otonom',
            independenceDay: '1948-03-30',
            nationalHoliday: '29 Juli',
            legalSystem: 'Civil Law',
            constitution: '1948',
            administrativeDivisions: 30,
            memberships: ['NATO', 'OECD'],
            giniCoefficient: 28.0,
            hdi: 0.900,
            hdiRank: 26,
            corruptionIndex: 80,
            currency: 'Krone',
            currencyCode: 'DKK',
            gdp: 3000000000,
            gdpPerCapita: 60000,
            gdpPpp: 3000000000,
            gdpGrowth: 3.0,
            inflation: 2.0,
            unemployment: 2.0,
            povertyRate: 5.0,
            mainIndustries: ['Perikanan', 'Pariwisata', 'Perkapalan'],
            exports: [
                { item: 'Perikanan', value: 2000000000 },
                { item: 'Pariwisata', value: 500000000 },
                { item: 'Perkapalan', value: 300000000 }
            ],
            imports: [
                { item: 'Mesin', value: 500000000 },
                { item: 'Elektronik', value: 300000000 },
                { item: 'Makanan', value: 200000000 },
                { item: 'Minyak', value: 100000000 }
            ],
            tradeBalance: 500000000,
            naturalResources: ['Perikanan', 'Energi', 'Air'],
            economicRanking: 100,
            internetPenetration: 95,
            mobilePenetration: 98,
            electricityAccess: 100,
            roadLength: 1000,
            railwayLength: 0,
            airports: 1,
            seaports: 5,
            healthcareAccess: 92,
            educationIndex: 0.80,
            nationalMotto: 'Kebebasan, Kesetaraan, Persaudaraan',
            nationalAnthem: 'Tú alfagra land mítt',
            nationalAnimal: 'Domba',
            nationalFlower: 'Bunga Gunung',
            nationalCuisine: ['Kjöttsúpa', 'Ræst kjøt', 'Ræst fiskur', 'Garnatálg', 'Skerpikjøt'],
            culturalHeritage: ['Tórshavn', 'Klakkur', 'Gjógv', 'Vestmanna'],
            publicHolidays: ['Hari Nasional', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 85,
            climate: 'Subartik',
            averageTemperature: 5,
            averageRainfall: 1000,
            forestArea: 1,
            protectedAreas: 10,
            biodiversityRank: 35,
            carbonEmissions: 2.0,
            environmentalIndex: 60,
            riskScore: 20,
            politicalStability: 90,
            crimeIndex: 10,
            militarySpending: 0.5,
            peaceIndex: 20,
            terrorismIndex: 2,
            refugeePopulation: 0,
            opportunityScore: 60,
            easeOfDoingBusiness: 65,
            innovationIndex: 50,
            startupEcosystem: 40,
            investmentScore: 55,
            talentPool: 50,
            marketSize: 30,
            infrastructureQuality: 70,
            internetSpeed: 45,
            digitalAdoption: 75,
            techEcosystem: 50,
            aiReadiness: 40,
            startups: 10,
            phoneCode: '+298',
            tld: '.fo',
            isoCode: 'FRO',
            isoCode2: 'FO',
            drivingSide: 'right',
            tags: ['negara', 'eropan-utara', 'viking', 'fjord', 'perikanan']
        }
    },
    // ==========================================================
    // 🇸🇯 SVALBARD
    // ==========================================================
    {
        text: 'Svalbard - Wilayah Norwegia di Eropa Utara dengan beruang kutub dan aurora. Ibu kota: Longyearbyen. Populasi: 2.5 ribu jiwa. Mata uang: Krone (NOK). Bahasa: Norwegia. Sistem pemerintahan: Wilayah Khusus. Satu-satunya tempat di dunia yang bebas visa. Gudang benih global. Destinasi wisata Arktik yang eksotis. Rumah bagi beruang kutub dan pemandangan aurora yang spektakuler.',
        metadata: {
            category: 'country',
            region: 'eropan-utara',
            name: 'Svalbard',
            officialName: 'Svalbard',
            shortName: 'SJM',
            capital: 'Longyearbyen',
            capitalCoordinates: { lat: 78.2232, lng: 15.6267 },
            largestCity: 'Longyearbyen',
            demonym: 'Svalbard',
            subregion: 'Northern Europe',
            area: 61022,
            areaRank: 123,
            coastline: 3587,
            highestPoint: 'Newtontoppen',
            highestElevation: 1717,
            lowestPoint: 'Laut Arktik',
            lowestElevation: 0,
            landBorders: [],
            coordinates: { lat: 78.0, lng: 20.0 },
            timezone: ['Waktu Eropa Tengah'],
            utcOffset: ['+1'],
            population: 2500,
            populationRank: 180,
            populationDensity: 0,
            populationGrowth: 0.5,
            medianAge: 35.0,
            lifeExpectancy: 78.0,
            fertilityRate: 1.5,
            urbanization: 100,
            ethnicGroups: [
                { name: 'Norwegia', percentage: 70.0 },
                { name: 'Rusia', percentage: 25.0 },
                { name: 'Lainnya', percentage: 5.0 }
            ],
            religions: [
                { name: 'Kristen Protestan', percentage: 70.0 },
                { name: 'Lainnya', percentage: 30.0 }
            ],
            languages: [
                { name: 'Norwegia', percentage: 100, official: true },
                { name: 'Rusia', percentage: 25 },
                { name: 'Inggris', percentage: 50 }
            ],
            literacyRate: 100,
            governmentType: 'Wilayah Khusus',
            independenceDay: '1920-02-09',
            nationalHoliday: '9 Februari',
            legalSystem: 'Civil Law',
            constitution: '1920',
            administrativeDivisions: 1,
            memberships: ['PBB', 'NATO'],
            giniCoefficient: 25.0,
            hdi: 0.950,
            hdiRank: 6,
            corruptionIndex: 90,
            currency: 'Krone',
            currencyCode: 'NOK',
            gdp: 500000000,
            gdpPerCapita: 200000,
            gdpPpp: 500000000,
            gdpGrowth: 2.0,
            inflation: 2.0,
            unemployment: 1.0,
            povertyRate: 0,
            mainIndustries: ['Pariwisata', 'Tambang', 'Penelitian', 'Energi'],
            exports: [
                { item: 'Pariwisata', value: 200000000 },
                { item: 'Tambang', value: 100000000 },
                { item: 'Penelitian', value: 100000000 }
            ],
            imports: [
                { item: 'Makanan', value: 100000000 },
                { item: 'Mesin', value: 80000000 },
                { item: 'Elektronik', value: 50000000 },
                { item: 'Minyak', value: 40000000 }
            ],
            tradeBalance: 100000000,
            naturalResources: ['Batu bara', 'Gas', 'Perikanan'],
            economicRanking: 100,
            internetPenetration: 95,
            mobilePenetration: 98,
            electricityAccess: 100,
            roadLength: 50,
            railwayLength: 0,
            airports: 1,
            seaports: 1,
            healthcareAccess: 90,
            educationIndex: 0.85,
            nationalMotto: 'Kebebasan, Kesetaraan, Persaudaraan',
            nationalAnthem: 'Ja, vi elsker dette landet',
            nationalAnimal: 'Beruang Kutub',
            nationalFlower: 'Bunga Arktik',
            nationalCuisine: ['Arktik Cuisine', 'Seafood', 'Reindeer', 'Whale'],
            culturalHeritage: ['Longyearbyen', 'Isfjorden', 'Ny-Ålesund', 'Barentsburg'],
            publicHolidays: ['Hari Nasional', 'Paskah', 'Christmas', 'Tahun Baru'],
            socialRanking: 90,
            climate: 'Arktik',
            averageTemperature: -10,
            averageRainfall: 100,
            forestArea: 0,
            protectedAreas: 60,
            biodiversityRank: 20,
            carbonEmissions: 0.5,
            environmentalIndex: 75,
            riskScore: 10,
            politicalStability: 95,
            crimeIndex: 2,
            militarySpending: 0.5,
            peaceIndex: 10,
            terrorismIndex: 1,
            refugeePopulation: 0,
            opportunityScore: 50,
            easeOfDoingBusiness: 60,
            innovationIndex: 45,
            startupEcosystem: 20,
            investmentScore: 40,
            talentPool: 35,
            marketSize: 10,
            infrastructureQuality: 65,
            internetSpeed: 40,
            digitalAdoption: 80,
            techEcosystem: 30,
            aiReadiness: 25,
            startups: 2,
            phoneCode: '+47',
            tld: '.sj',
            isoCode: 'SJM',
            isoCode2: 'SJ',
            drivingSide: 'right',
            tags: ['negara', 'eropan-utara', 'arktik', 'aurora', 'beruang-kutub']
        }
    }
];

export const DATA = data;

// ============================================================
// LOGGER
// ============================================================
if (window.InternalLogger) {
    window.InternalLogger.info('CountryEropanUtara', '✅ Loaded ' + data.length + ' countries (SUPER LENGKAP - 10 NEGARA!)');
}
